动态装备系统: DynamicTroopEquipmentReupload.EveryoneCampaignBehavior Class Reference
DynamicTroopEquipmentReupload.EveryoneCampaignBehavior Class Reference
Classes
class Data
Public Member Functions
override void RegisterEvents ()
override void SyncData (IDataStore dataStore)
Static Public Member Functions
static void AddItemToPartyArmory (MBGUID partyId, ItemObject item, int count)
static ? Dictionary< ItemObject, int > SanitizePartyArmory (MBGUID partyId)
向指定部队的装备库中添加物品。
Static Public Attributes
static readonly Dictionary< ItemObject.ItemTypeEnum, Func< int, int > > EquipmentAndThresholds
static readonly Dictionary< ItemObject.ItemTypeEnum, List< ItemObject > > ItemListByType = new()
static readonly Dictionary< MBGUID, Dictionary< ItemObject, int > > PartyArmories = new()
Private Member Functions
void AllocateRandomEquipmentToPartyArmory (MobileParty mobileParty)
Dictionary< uint, Dictionary< string, int > > CreateSerializedPartyArmories ()
void DailyTickParty (MobileParty mobileParty)
void DistributeLootRandomly (MapEventParty[] winnerParties, float totalWinnerStrength, IEnumerable< MapEventParty > loserParties)
根据战斗结果，随机分配战败方部队的战利品给胜利方的各个部队。
MapEventParty[] FilterValidParties (IEnumerable< MapEventParty > parties)
void GarbageCollectEquipments (MobileParty mobileParty)
bool GarbageCollectParties (MobileParty mobileParty)
void MoveRosterToArmory (MobileParty mobileParty)
void OnGameLoaded (CampaignGameStarter starter)
void OnMapEventEnded (MapEvent mapEvent)
void OnMobilePartyCreated (MobileParty mobileParty)
void OnMobilePartyDestroyed (MobileParty mobileParty, PartyBase partyBase)
void OnNewGameCreated (CampaignGameStarter starter)
void RestoreReadyPartyArmories ()
void WeeklyTick ()
Static Private Member Functions
static float CalculateTotalStrength (IEnumerable< MapEventParty > parties)
static ? MobileParty ChoosePartyRandomly (IEnumerable< MapEventParty > parties, float totalStrength, Random random)
从一系列部队中根据其总力量随机选择一个部队。
static ? MobileParty FindActiveParty (MBGUID partyId)
static Dictionary< ItemObject, int > GetAllLootItems (IEnumerable< MapEventParty > parties)
static void InitializeItemListByType ()
static bool IsMapEventPartyValid (MapEventParty? party)
static void LogParties (IEnumerable< MapEventParty > parties, string label)
static void OnTroopRecruited (Hero? recruiterHero, Settlement recruitmentSettlement, Hero recruitmentSource, CharacterObject troop, int amount)
当兵种被招募时的处理逻辑。
static bool ShouldPersistParty (MobileParty? mobileParty)
Private Attributes
Data _data = new()
readonly Dictionary< uint, Dictionary< string, int > > _unresolvedPartyArmories = new()
Detailed Description
Definition at line 27 of file EveryoneCampaignBehavior.cs.
Member Function Documentation
AddItemToPartyArmory()
static void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.AddItemToPartyArmory (MBGUID partyId, ItemObject item, int count) static
Definition at line 538 of file EveryoneCampaignBehavior.cs.
{
        if (count <= 0 || !ArmyArmory.TryResolveArmoryItem(item, out var resolvedItem) || !ItemBlackList.Test(resolvedItem))
            return;
        if (!PartyArmories.TryGetValue(partyId, out var inventory)) {
            inventory = new Dictionary<ItemObject, int>();
            PartyArmories[partyId] = inventory;
        }
        inventory[resolvedItem] = inventory.TryGetValue(resolvedItem, out var currentCount)
            ? currentCount + count
            : count;
    }
References PartyArmories, DynamicTroopEquipmentReupload.ItemBlackList.Test(), and DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem().
Referenced by AllocateRandomEquipmentToPartyArmory(), DistributeLootRandomly(), MoveRosterToArmory(), OnMobilePartyCreated(), OnTroopRecruited(), and DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ReturnItem().
AllocateRandomEquipmentToPartyArmory()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.AllocateRandomEquipmentToPartyArmory (MobileParty mobileParty) private
Definition at line 255 of file EveryoneCampaignBehavior.cs.
{
        if (mobileParty.MemberRoster                  == null ||
            mobileParty.MemberRoster.GetTroopRoster() == null ||
            mobileParty.MemberRoster.GetTroopRoster().IsEmpty())
            return;
        var settings = SubModule.Settings;
        var writeDebugLog = settings is { DebugMode: true } &&
            (settings.MinimumLogLevel == Level.All || Level.Debug >= settings.MinimumLogLevel);
        var randomEquipmentElementsFromTroop = mobileParty.GetRandomEquipmentsFromTroop();
        foreach (var equipmentElement in randomEquipmentElementsFromTroop) {
            AddItemToPartyArmory(mobileParty.Id, equipmentElement.Item, 1);
            if (writeDebugLog)
                Global.Debug($"random equipment (troop) {equipmentElement.Item.Name} added to {mobileParty.Name}");
        }
        var randomItemsFromFiefs = mobileParty.GetDailyEquipmentFromFiefs();
        foreach (var item in randomItemsFromFiefs) {
            AddItemToPartyArmory(mobileParty.Id, item, 1);
            if (writeDebugLog)
                Global.Debug($"random equipment (fief) {item.Name} added to {mobileParty.Name}");
        }
        var randomItemsFromClan = mobileParty.GetRandomEquipmentsFromClan();
        foreach (var item in randomItemsFromClan) {
            AddItemToPartyArmory(mobileParty.Id, item, 1);
            if (writeDebugLog)
                Global.Debug($"random equipment (clan) {item.Name} added to {mobileParty.Name}");
        }
    }
References AddItemToPartyArmory(), DynamicTroopEquipmentReupload.Global.Debug(), and DynamicTroopEquipmentReupload.SubModule.Settings.
Referenced by DailyTickParty().
CalculateTotalStrength()
static float DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.CalculateTotalStrength (IEnumerable< MapEventParty > parties) static private
Definition at line 356 of file EveryoneCampaignBehavior.cs.
{
        return parties.SumQ(party => party.Party.EstimatedStrength);
    }
Referenced by OnMapEventEnded().
ChoosePartyRandomly()
static ? MobileParty DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.ChoosePartyRandomly (IEnumerable< MapEventParty > parties, float totalStrength, Random random) static private
从一系列部队中根据其总力量随机选择一个部队。
Parameters
parties 参与选择的部队集合。
totalStrength 所有部队的总力量。
random 用于生成随机数的Random实例。
Returns
根据力量加权随机选中的移动部队，如果没有选中则返回null。
Definition at line 453 of file EveryoneCampaignBehavior.cs.
{
        var randomValue        = random.NextDouble() * totalStrength;
        var cumulativeStrength = 0f;
        foreach (var party in parties) {
            cumulativeStrength += party.Party.EstimatedStrength;
            if (cumulativeStrength >= randomValue) return party.Party.MobileParty;
        }
        return null;
    }
Referenced by DistributeLootRandomly().
CreateSerializedPartyArmories()
Dictionary< uint, Dictionary< string, int > > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.CreateSerializedPartyArmories () private
Definition at line 556 of file EveryoneCampaignBehavior.cs.
{
        var serializedArmories = new Dictionary<uint, Dictionary<string, int>>();
        foreach (var pendingParty in _unresolvedPartyArmories) {
            var party = FindActiveParty(new MBGUID(pendingParty.Key));
            if (!ShouldPersistParty(party))
                continue;
            serializedArmories[pendingParty.Key] = new Dictionary<string, int>(pendingParty.Value);
        }
        foreach (var partyEntry in PartyArmories) {
            var party = FindActiveParty(partyEntry.Key);
            if (!ShouldPersistParty(party))
                continue;
            var serializedItems = serializedArmories.TryGetValue(partyEntry.Key.InternalValue, out var existingItems)
                ? existingItems
                : new Dictionary<string, int>();
            foreach (var itemEntry in partyEntry.Value) {
                if (itemEntry.Value <= 0 || !ArmyArmory.TryResolveArmoryItem(itemEntry.Key, out var item))
                    continue;
                serializedItems[item.StringId] = serializedItems.TryGetValue(item.StringId, out var currentCount)
                    ? currentCount + itemEntry.Value
                    : itemEntry.Value;
            }
            if (serializedItems.Count > 0)
                serializedArmories[partyEntry.Key.InternalValue] = serializedItems;
        }
        return serializedArmories;
    }
References _unresolvedPartyArmories, FindActiveParty(), PartyArmories, ShouldPersistParty(), and DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem().
Referenced by SyncData().
DailyTickParty()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.DailyTickParty (MobileParty mobileParty) private
Definition at line 198 of file EveryoneCampaignBehavior.cs.
{
        if (!mobileParty.IsValid()) return;
        if (!GarbageCollectParties(mobileParty))
            AllocateRandomEquipmentToPartyArmory(mobileParty);
        else
            Global.Debug($"garbage collect party {mobileParty.Name}");
        if (CampaignTime.Now.GetDayOfWeek != mobileParty.Id.InternalValue % 7) return;
        GarbageCollectEquipments(mobileParty);
        //ReplenishBasicTroopEquipments(mobileParty);
        MoveRosterToArmory(mobileParty);
    }
References AllocateRandomEquipmentToPartyArmory(), DynamicTroopEquipmentReupload.Global.Debug(), GarbageCollectEquipments(), GarbageCollectParties(), and MoveRosterToArmory().
Referenced by RegisterEvents().
DistributeLootRandomly()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.DistributeLootRandomly (MapEventParty[] winnerParties, float totalWinnerStrength, IEnumerable< MapEventParty > loserParties) private
根据战斗结果，随机分配战败方部队的战利品给胜利方的各个部队。
Parameters
winnerParties 胜利方的部队数组。
totalWinnerStrength 胜利方部队的总力量。
loserParties 战败方的部队集合。
Definition at line 366 of file EveryoneCampaignBehavior.cs.
{
        var lootItemsWithCount = GetAllLootItems(loserParties);
        if (winnerParties.Length == 1) {
            var winnerParty = winnerParties[0].Party.MobileParty;
            var totalLootCount = 0;
            foreach (var lootItem in lootItemsWithCount) {
                AddItemToPartyArmory(winnerParty.Id, lootItem.Key, lootItem.Value);
                totalLootCount += lootItem.Value;
            }
            if (totalLootCount > 0)
                Global.Debug($"Party {winnerParty.Id} looted {totalLootCount} items");
            return;
        }
        Random random = new();
        Dictionary<MBGUID, int> partyLootCount = new();
        Dictionary<MBGUID, int> currentItemDistribution = new();
        foreach (var lootItem in lootItemsWithCount) {
            var item      = lootItem.Key;
            var itemCount = lootItem.Value;
            var selectionFailed = false;
            currentItemDistribution.Clear();
            for (var i = 0; i < itemCount; i++) {
                var chosenParty = ChoosePartyRandomly(winnerParties, totalWinnerStrength, random);
                if (chosenParty == null) {
                    selectionFailed = true;
                    break;
                }
                currentItemDistribution[chosenParty.Id] =
                    currentItemDistribution.TryGetValue(chosenParty.Id, out var currentItemCount)
                        ? currentItemCount + 1
                        : 1;
                partyLootCount[chosenParty.Id] =
                    partyLootCount.TryGetValue(chosenParty.Id, out var currentPartyCount)
                        ? currentPartyCount + 1
                        : 1;
            }
            foreach (var partyItemCount in currentItemDistribution)
                AddItemToPartyArmory(partyItemCount.Key, item, partyItemCount.Value);
            if (selectionFailed)
                return;
        }
        // 记录每个party获得的物品总数
        foreach (var partyCount in partyLootCount)
            Global.Debug($"Party {partyCount.Key} looted {partyCount.Value} items");
    }
References AddItemToPartyArmory(), ChoosePartyRandomly(), DynamicTroopEquipmentReupload.Global.Debug(), and GetAllLootItems().
Referenced by OnMapEventEnded().
FilterValidParties()
MapEventParty[] DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.FilterValidParties (IEnumerable< MapEventParty > parties) private
Definition at line 342 of file EveryoneCampaignBehavior.cs.
{
        return parties.WhereQ(IsMapEventPartyValid).ToArrayQ();
    }
References IsMapEventPartyValid().
Referenced by OnMapEventEnded().
FindActiveParty()
static ? MobileParty DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.FindActiveParty (MBGUID partyId) static private
Definition at line 641 of file EveryoneCampaignBehavior.cs.
{
        return Campaign.Current?.MobileParties?.FirstOrDefault(party => party.Id == partyId && party.IsActive);
    }
Referenced by CreateSerializedPartyArmories(), and RestoreReadyPartyArmories().
GarbageCollectEquipments()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.GarbageCollectEquipments (MobileParty mobileParty) private
Definition at line 163 of file EveryoneCampaignBehavior.cs.
{
        if (!mobileParty.IsValid() || mobileParty.MemberRoster?.GetTroopRoster() == null) return;
        var memberCnt = mobileParty.MemberRoster.GetTroopRoster()
                                   .WhereQ(element => element.Character is { IsHero: false })
                                   .SumQ(element => element.Number);
        foreach (var equipmentAndThreshold in EquipmentAndThresholds) {
            var partyArmory = PartyArmories.GetValueSafe(mobileParty.Id);
            if (partyArmory == null || partyArmory.IsEmpty()) return;
            var armorTotalCount = partyArmory.WhereQ(kv => kv.Key.ItemType == equipmentAndThreshold.Key)
                                             .SumQ(kv => kv.Value);
            var surplusCount = armorTotalCount - memberCnt;
            if (surplusCount <= 0) continue;
            var surplusCountCpy = surplusCount;
            // 创建优先级队列
            ItemPriorityQueue armorQueue = new(new EquipmentEffectivenessComparer());
            foreach (var kv in partyArmory.WhereQ(kv => kv.Key.ItemType == equipmentAndThreshold.Key))
                armorQueue.Enqueue(kv.Key, ((int)kv.Key.Tier, kv.Key.Value));
            // 移除多余的装备
            while (surplusCount > 0 && armorQueue.Count > 0) {
                var lowestArmor   = armorQueue.Dequeue();
                var countToRemove = Math.Min(partyArmory[lowestArmor.Key], surplusCount);
                partyArmory[lowestArmor.Key] -= countToRemove;
                surplusCount                 -= countToRemove;
                if (partyArmory[lowestArmor.Key] == 0) _ = partyArmory.Remove(lowestArmor.Key);
            }
            Global.Debug($"Garbage collected {surplusCountCpy - surplusCount}x{equipmentAndThreshold.Key} armors from party {mobileParty.Name}");
        }
    }
References DynamicTroopEquipmentReupload.Global.Debug(), EquipmentAndThresholds, and PartyArmories.
Referenced by DailyTickParty().
GarbageCollectParties()
bool DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.GarbageCollectParties (MobileParty mobileParty) private
Definition at line 214 of file EveryoneCampaignBehavior.cs.
{
        if (mobileParty is not {
                                   LeaderHero: {
                                                   CharacterObject       : { IsHero: true, IsPlayerCharacter: false },
                                                   IsHumanPlayerCharacter: false,
                                                   IsPartyLeader         : true,
                                                   IsAlive               : true,
                                                   IsActive              : true
                                               },
                                   Owner: {
                                              CharacterObject       : { IsHero: true, IsPlayerCharacter: false },
                                              IsHumanPlayerCharacter: false,
                                              IsActive              : true,
                                              IsAlive               : true
                                          },
                                   MemberRoster: { TotalHeroes: > 0, TotalManCount: > 0 },
                                   IsDisbanding: false
                               })
            return PartyArmories.Remove(mobileParty.Id);
        return false;
    }
References PartyArmories.
Referenced by DailyTickParty().
GetAllLootItems()
static Dictionary< ItemObject, int > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.GetAllLootItems (IEnumerable< MapEventParty > parties) static private
Definition at line 425 of file EveryoneCampaignBehavior.cs.
{
        Dictionary<ItemObject, int> itemsWithCount = new();
        foreach (var party in parties) {
            var partyId = party.Party.MobileParty.Id;
            var inventory = SanitizePartyArmory(partyId);
            if (inventory == null)
                continue;
            foreach (var item in inventory) {
                if (item.Value <= 0 || !ItemBlackList.Test(item.Key))
                    continue;
                itemsWithCount[item.Key] = itemsWithCount.TryGetValue(item.Key, out var currentCount)
                    ? currentCount + item.Value
                    : item.Value;
            }
        }
        return itemsWithCount;
    }
References SanitizePartyArmory(), and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by DistributeLootRandomly().
InitializeItemListByType()
static void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.InitializeItemListByType () static private
Definition at line 54 of file EveryoneCampaignBehavior.cs.
{
        ItemListByType.Clear();
        Cache.Clear();
        ItemBlackList.ResetCache();
        foreach (var itemType in Global.ItemTypes)
            ItemListByType[itemType] = new List<ItemObject>();
        var allItems = MBObjectManager.Instance.GetObjectTypeList<ItemObject>();
        if (allItems != null) {
            foreach (var item in allItems) {
                if (ItemListByType.TryGetValue(item.ItemType, out var items) &&
                    ArmyArmory.TryResolveArmoryItem(item, out _))
                    items.Add(item);
            }
        }
        foreach (var itemType in Global.ItemTypes)
        {
            ItemListByType[itemType] = ItemListByType[itemType]
                .OrderBy(item => item.Tier)
                .ThenBy(item => item.Value)
                .ToList();
        }
    }
References DynamicTroopEquipmentReupload.Cache.Clear(), ItemListByType, DynamicTroopEquipmentReupload.Global.ItemTypes, DynamicTroopEquipmentReupload.ItemBlackList.ResetCache(), and DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem().
Referenced by OnGameLoaded(), and OnNewGameCreated().
IsMapEventPartyValid()
static bool DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.IsMapEventPartyValid (MapEventParty? party) static private
Definition at line 552 of file EveryoneCampaignBehavior.cs.
{
        return party is { Party.MobileParty: var mobileParty } && mobileParty.IsValid();
    }
Referenced by FilterValidParties().
LogParties()
static void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.LogParties (IEnumerable< MapEventParty > parties, string label) static private
Definition at line 346 of file EveryoneCampaignBehavior.cs.
{
        var settings = SubModule.Settings;
        if (settings is not { DebugMode: true } ||
            (settings.MinimumLogLevel != Level.All && Level.Debug < settings.MinimumLogLevel))
            return;
        foreach (var party in parties)
            Global.Log($"{label} party: {party.Party.Name}#{party.Party.MobileParty.Id}", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.SubModule.Settings.
Referenced by OnMapEventEnded().
MoveRosterToArmory()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.MoveRosterToArmory (MobileParty mobileParty) private
Definition at line 236 of file EveryoneCampaignBehavior.cs.
{
        var settings = SubModule.Settings;
        var writeDebugLog = settings is { DebugMode: true } &&
            (settings.MinimumLogLevel == Level.All || Level.Debug >= settings.MinimumLogLevel);
        var elements = mobileParty.ItemRoster.WhereQ(element =>
                                                         (element.EquipmentElement.Item?.HasArmorComponent  ?? false) ||
                                                         (element.EquipmentElement.Item?.HasWeaponComponent ?? false))
                                 .ToArrayQ();
        foreach (var element in elements)
            if (element.Amount > 0 && ArmyArmory.TryResolveArmoryItem(element.EquipmentElement.Item, out var item)) {
                AddItemToPartyArmory(mobileParty.Id, item, element.Amount);
                if (writeDebugLog)
                    Global.Debug($"equipment {item.Name}x{element.Amount} moved to armory from {mobileParty.Name}");
                mobileParty.ItemRoster.Remove(element);
                var hero                    = mobileParty.LeaderHero ?? mobileParty.Owner;
                if (hero != null) hero.Gold += item.Value * element.Amount;
            }
    }
References AddItemToPartyArmory(), DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.SubModule.Settings, and DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem().
Referenced by DailyTickParty().
OnGameLoaded()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnGameLoaded (CampaignGameStarter starter) private
Definition at line 103 of file EveryoneCampaignBehavior.cs.
{
        Global.Debug("OnGameLoaded() called");
        InitializeItemListByType();
        RestoreReadyPartyArmories();
        IEnumerable<MobileParty>? validParties = Campaign.Current?.MobileParties?.WhereQ(party => party.IsValid());
        if (validParties != null) {
            foreach (var validParty in validParties) {
                if (!PartyArmories.ContainsKey(validParty.Id))
                    OnMobilePartyCreated(validParty);
                else
                    SanitizePartyArmory(validParty.Id);
            }
        }
        CharacterObjectExtension.Init();
    }
References DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.Init(), InitializeItemListByType(), OnMobilePartyCreated(), PartyArmories, RestoreReadyPartyArmories(), and SanitizePartyArmory().
Referenced by RegisterEvents().
OnMapEventEnded()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMapEventEnded (MapEvent mapEvent) private
Definition at line 324 of file EveryoneCampaignBehavior.cs.
{
        Global.Log($"Map Event ended with state {mapEvent.BattleState}", Colors.Green, Level.Debug);
        if (mapEvent.BattleState is not BattleState.AttackerVictory and not BattleState.DefenderVictory) return;
        var validWinnerParties = FilterValidParties(mapEvent.BattleState == BattleState.AttackerVictory
                                                        ? mapEvent.AttackerSide.Parties
                                                        : mapEvent.DefenderSide.Parties);
        var validLoserParties = FilterValidParties(mapEvent.BattleState == BattleState.AttackerVictory
                                                       ? mapEvent.DefenderSide.Parties
                                                       : mapEvent.AttackerSide.Parties);
        LogParties(validWinnerParties, "Winning");
        LogParties(validLoserParties,  "Defeated");
        var totalWinnerStrength = CalculateTotalStrength(validWinnerParties);
        DistributeLootRandomly(validWinnerParties, totalWinnerStrength, validLoserParties);
    }
References CalculateTotalStrength(), DistributeLootRandomly(), FilterValidParties(), DynamicTroopEquipmentReupload.Global.Log(), and LogParties().
Referenced by RegisterEvents().
OnMobilePartyCreated()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMobilePartyCreated (MobileParty mobileParty) private
Definition at line 287 of file EveryoneCampaignBehavior.cs.
{
        if (!mobileParty.IsValid()) return;
        if (!PartyArmories.ContainsKey(mobileParty.Id))
            PartyArmories[mobileParty.Id] = new Dictionary<ItemObject, int>();
        var startingEquipmentCount = 0;
        foreach (var rosterElement in mobileParty.MemberRoster.GetTroopRoster()) {
            if (rosterElement.Character is not { IsHero: false } character || rosterElement.Number <= 0)
                continue;
            var startingEquipment = RecruitmentPatch.GetRecruitEquipments(character);
            foreach (var equipmentElement in startingEquipment) {
                if (equipmentElement.Item == null)
                    continue;
                AddItemToPartyArmory(mobileParty.Id, equipmentElement.Item, rosterElement.Number);
                startingEquipmentCount += rosterElement.Number;
            }
        }
        Global.Log($"Mobile party {mobileParty.Name} created, {startingEquipmentCount} start equipment added",
                   Colors.Green,
                   Level.Debug);
    }
References AddItemToPartyArmory(), DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRecruitEquipments(), DynamicTroopEquipmentReupload.Global.Log(), and PartyArmories.
Referenced by OnGameLoaded(), and RegisterEvents().
OnMobilePartyDestroyed()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMobilePartyDestroyed (MobileParty mobileParty, PartyBase partyBase) private
Definition at line 313 of file EveryoneCampaignBehavior.cs.
{
        if (mobileParty?.Id != null) _ = PartyArmories.Remove(mobileParty.Id);
        if (!mobileParty.IsValid()) return;
        if (mobileParty is { Name: not null } && partyBase is { Name: not null })
            Global.Log($"Mobile party {mobileParty.Name} destroyed, partyBase = {partyBase.Name}",
                       Colors.Green,
                       Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log(), and PartyArmories.
Referenced by RegisterEvents().
OnNewGameCreated()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnNewGameCreated (CampaignGameStarter starter) private
Definition at line 93 of file EveryoneCampaignBehavior.cs.
{
        Global.Debug("OnNewGameCreated() called");
        _unresolvedPartyArmories.Clear();
        PartyArmories.Clear();
        InitializeItemListByType();
        CharacterObjectExtension.Init();
    }
References _unresolvedPartyArmories, DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.Init(), InitializeItemListByType(), and PartyArmories.
Referenced by RegisterEvents().
OnTroopRecruited()
static void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnTroopRecruited (Hero? recruiterHero, Settlement recruitmentSettlement, Hero recruitmentSource, CharacterObject troop, int amount) static private
当兵种被招募时的处理逻辑。
Parameters
recruiterHero 进行招募的英雄。
recruitmentSettlement 招募发生的定居点。
recruitmentSource 提供招募的英雄。
troop 被招募的兵种。
amount 招募数量。
Definition at line 475 of file EveryoneCampaignBehavior.cs.
{
        if (recruiterHero == null) return;
        var party = recruiterHero.PartyBelongedTo;
        if (!party.IsValid()) return;
        var list = RecruitmentPatch.GetRecruitEquipments(troop);
        foreach (var element in list) {
            if (element.Item != null)
                AddItemToPartyArmory(party.Id, element.Item, amount);
        }
        Global.Log($"troop {troop.Name}x{amount} recruited by recruiterHero={recruiterHero.Name} in party {party.Name}, {list.Count * amount} start equipment added",
                   Colors.Green,
                   Level.Debug);
    }
References AddItemToPartyArmory(), DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRecruitEquipments(), and DynamicTroopEquipmentReupload.Global.Log().
Referenced by RegisterEvents().
RegisterEvents()
override void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.RegisterEvents ()
Definition at line 80 of file EveryoneCampaignBehavior.cs.
{
        CampaignEvents.MobilePartyCreated.AddNonSerializedListener(this, OnMobilePartyCreated);
        CampaignEvents.MobilePartyDestroyed.AddNonSerializedListener(this, OnMobilePartyDestroyed);
        CampaignEvents.MapEventEnded.AddNonSerializedListener(this, OnMapEventEnded);
        CampaignEvents.OnTroopRecruitedEvent.AddNonSerializedListener(this, OnTroopRecruited);
        CampaignEvents.DailyTickPartyEvent.AddNonSerializedListener(this, DailyTickParty);
        CampaignEvents.WeeklyTickEvent.AddNonSerializedListener(this, WeeklyTick);
        CampaignEvents.OnGameLoadedEvent.AddNonSerializedListener(this, OnGameLoaded);
        CampaignEvents.OnNewGameCreatedEvent.AddNonSerializedListener(this, OnNewGameCreated);
        //Global.InitializeCraftingTemplatesByItemType();
    }
References DailyTickParty(), OnGameLoaded(), OnMapEventEnded(), OnMobilePartyCreated(), OnMobilePartyDestroyed(), OnNewGameCreated(), OnTroopRecruited(), and WeeklyTick().
RestoreReadyPartyArmories()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.RestoreReadyPartyArmories () private
Definition at line 592 of file EveryoneCampaignBehavior.cs.
{
        foreach (var pendingParty in new Dictionary<uint, Dictionary<string, int>>(_unresolvedPartyArmories)) {
            var partyId = new MBGUID(pendingParty.Key);
            if (FindActiveParty(partyId) == null)
                continue;
            if (!PartyArmories.TryGetValue(partyId, out var armory)) {
                armory = new Dictionary<ItemObject, int>();
                PartyArmories[partyId] = armory;
            }
            foreach (var pendingItem in new Dictionary<string, int>(pendingParty.Value)) {
                var item = ArmyArmory.ResolveArmoryItem(pendingItem.Key);
                if (item == null)
                    continue;
                armory[item] = armory.TryGetValue(item, out var currentCount)
                    ? currentCount + pendingItem.Value
                    : pendingItem.Value;
                pendingParty.Value.Remove(pendingItem.Key);
            }
            if (pendingParty.Value.Count == 0)
                _unresolvedPartyArmories.Remove(pendingParty.Key);
            else
                _unresolvedPartyArmories[pendingParty.Key] = pendingParty.Value;
        }
    }
References _unresolvedPartyArmories, FindActiveParty(), PartyArmories, and DynamicTroopEquipmentReupload.ArmyArmory.ResolveArmoryItem().
Referenced by OnGameLoaded().
SanitizePartyArmory()
static ? Dictionary< ItemObject, int > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.SanitizePartyArmory (MBGUID partyId) static
向指定部队的装备库中添加物品。
Parameters
partyId 部队的唯一标识符。
item 要添加的物品。
count 添加的物品数量。
Definition at line 502 of file EveryoneCampaignBehavior.cs.
{
        if (!PartyArmories.TryGetValue(partyId, out var armory))
            return null;
        var requiresRebuild = false;
        var normalizedItems = new HashSet<ItemObject>();
        foreach (var entry in armory) {
            if (entry.Value <= 0 ||
                !ArmyArmory.TryResolveArmoryItem(entry.Key, out var item) ||
                !ReferenceEquals(item, entry.Key) ||
                !normalizedItems.Add(item)) {
                requiresRebuild = true;
                break;
            }
        }
        if (!requiresRebuild)
            return armory;
        var sanitizedItems = new Dictionary<ItemObject, int>();
        foreach (var entry in armory) {
            if (entry.Value <= 0 || !ArmyArmory.TryResolveArmoryItem(entry.Key, out var item))
                continue;
            sanitizedItems[item] = sanitizedItems.TryGetValue(item, out var currentCount)
                ? currentCount + entry.Value
                : entry.Value;
        }
        armory.Clear();
        foreach (var entry in sanitizedItems)
            armory[entry.Key] = entry.Value;
        return armory;
    }
References PartyArmories, and DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem().
Referenced by GetAllLootItems(), OnGameLoaded(), DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.Prefix(), and DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.TryInitializeDistributors().
ShouldPersistParty()
static bool DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.ShouldPersistParty (MobileParty? mobileParty) static private
Definition at line 621 of file EveryoneCampaignBehavior.cs.
{
        return mobileParty is {
            LeaderHero: {
                CharacterObject       : { IsHero: true, IsPlayerCharacter: false },
                IsHumanPlayerCharacter: false,
                IsPartyLeader         : true,
                IsAlive               : true,
                IsActive              : true
            },
            Owner: {
                CharacterObject       : { IsHero: true, IsPlayerCharacter: false },
                IsHumanPlayerCharacter: false,
                IsActive              : true,
                IsAlive               : true
            },
            MemberRoster: { TotalHeroes: > 0, TotalManCount: > 0 },
            IsDisbanding: false
        };
    }
Referenced by CreateSerializedPartyArmories().
SyncData()
override void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.SyncData (IDataStore dataStore)
Definition at line 121 of file EveryoneCampaignBehavior.cs.
{
        if (dataStore.IsSaving) {
            _data.PartyArmories = CreateSerializedPartyArmories();
            var tempData = _data;
            if (dataStore.SyncDataAsJson("DynamicTroopPartyArmories", ref tempData) && tempData != null) {
                _data = tempData;
                Global.Debug($"saved {PartyArmories.Count} entries");
            }
            else
                Global.Error("Save Error");
        }
        else if (dataStore.IsLoading) {
            PartyArmories.Clear();
            _unresolvedPartyArmories.Clear();
            var tempData = new Data();
            if (dataStore.SyncDataAsJson("DynamicTroopPartyArmories", ref tempData) && tempData != null) {
                _data = tempData;
                _data.PartyArmories ??= new Dictionary<uint, Dictionary<string, int>>();
                foreach (var partyEntry in _data.PartyArmories) {
                    if (partyEntry.Value == null)
                        continue;
                    var itemCounts = new Dictionary<string, int>();
                    foreach (var itemEntry in partyEntry.Value) {
                        if (!string.IsNullOrEmpty(itemEntry.Key) && itemEntry.Value > 0)
                            itemCounts[itemEntry.Key] = itemEntry.Value;
                    }
                    if (itemCounts.Count > 0)
                        _unresolvedPartyArmories[partyEntry.Key] = itemCounts;
                }
            }
            else
                Global.Error("Load Error");
        }
    }
References _data, _unresolvedPartyArmories, CreateSerializedPartyArmories(), DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Global.Error(), and PartyArmories.
WeeklyTick()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.WeeklyTick () private
Definition at line 158 of file EveryoneCampaignBehavior.cs.
{
        //GarbageCollectParties();
        //GarbageCollectEquipments();
    }
Referenced by RegisterEvents().
Member Data Documentation
_data
Data DynamicTroopEquipmentReupload.EveryoneCampaignBehavior._data = new() private
Definition at line 31 of file EveryoneCampaignBehavior.cs.
Referenced by SyncData().
_unresolvedPartyArmories
readonly Dictionary<uint, Dictionary<string, int> > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior._unresolvedPartyArmories = new() private
Definition at line 30 of file EveryoneCampaignBehavior.cs.
Referenced by CreateSerializedPartyArmories(), OnNewGameCreated(), RestoreReadyPartyArmories(), and SyncData().
EquipmentAndThresholds
readonly Dictionary<ItemObject.ItemTypeEnum, Func<int, int> > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.EquipmentAndThresholds static
Initial value:
=
        new() {
                  { ItemObject.ItemTypeEnum.BodyArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.LegArmor, memberCnt => Math.Max(2     * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HeadArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HandArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Cape, memberCnt => Math.Max(2         * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Shield, memberCnt => Math.Max(2       * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Horse, memberCnt => Math.Max(2        * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HorseHarness, memberCnt => Math.Max(2 * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Bow, memberCnt => Math.Max(2          * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Crossbow, memberCnt => Math.Max(2     * memberCnt, memberCnt + 100) }, {
                                                                                                                       ItemObject.ItemTypeEnum.OneHandedWeapon, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400)
                                                                                                                   }, {
                                                                                                                          ItemObject.ItemTypeEnum.TwoHandedWeapon, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400)
                                                                                                                      },
                  { ItemObject.ItemTypeEnum.Polearm, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400) }
              }
Definition at line 33 of file EveryoneCampaignBehavior.cs.
              {
                  { ItemObject.ItemTypeEnum.BodyArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.LegArmor, memberCnt => Math.Max(2     * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HeadArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HandArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Cape, memberCnt => Math.Max(2         * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Shield, memberCnt => Math.Max(2       * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Horse, memberCnt => Math.Max(2        * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HorseHarness, memberCnt => Math.Max(2 * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Bow, memberCnt => Math.Max(2          * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Crossbow, memberCnt => Math.Max(2     * memberCnt, memberCnt + 100) }, {
                                                                                                                       ItemObject.ItemTypeEnum.OneHandedWeapon, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400)
                                                                                                                   }, {
                                                                                                                          ItemObject.ItemTypeEnum.TwoHandedWeapon, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400)
                                                                                                                      },
                  { ItemObject.ItemTypeEnum.Polearm, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400) }
              };
Referenced by GarbageCollectEquipments(), and DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipment().
ItemListByType
readonly Dictionary<ItemObject.ItemTypeEnum, List<ItemObject> > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.ItemListByType = new() static
Definition at line 52 of file EveryoneCampaignBehavior.cs.
Referenced by DynamicTroopEquipmentReupload.Cache.GetItemsByTypeTierAndCulture(), and InitializeItemListByType().
PartyArmories
readonly Dictionary<MBGUID, Dictionary<ItemObject, int> > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.PartyArmories = new() static
Definition at line 28 of file EveryoneCampaignBehavior.cs.
Referenced by AddItemToPartyArmory(), CreateSerializedPartyArmories(), GarbageCollectEquipments(), GarbageCollectParties(), DynamicTroopEquipmentReupload.Extensions.MobilePartyExtension.IsValid(), OnGameLoaded(), OnMobilePartyCreated(), OnMobilePartyDestroyed(), OnNewGameCreated(), RestoreReadyPartyArmories(), SanitizePartyArmory(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Spawn(), SyncData(), and DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.TransferCargoToTargetStash().
The documentation for this class was generated from the following file:
CSharpSourceCode/EveryoneCampaignBehavior.cs