动态装备系统: PartyBattleRecord Class Reference
PartyBattleRecord Class Reference
Public Member Functions
void AddItemToRecover (ItemObject item)
void AddItemToRecover (ItemObject item, int count)
void AddLootedItem (ItemObject item)
void AddLootedItem (ItemObject item, int count)
Public Attributes
readonly Dictionary< ItemObject, int > ItemsToRecover = new()
readonly Dictionary< ItemObject, int > LootedItems = new()
Properties
int ItemsToRecoverCount [get]
int LootedItemsCount [get]
Static Private Member Functions
static void AddItemToDictionary (IDictionary< ItemObject, int > dictionary, ItemObject? item, int count)
Detailed Description
Definition at line 11 of file PartyBattleRecord.cs.
Member Function Documentation
AddItemToDictionary()
static void PartyBattleRecord.AddItemToDictionary (IDictionary< ItemObject, int > dictionary, ItemObject? item, int count) static private
Definition at line 30 of file PartyBattleRecord.cs.
{
        if (item == null || !ItemBlackList.Test(item)) return;
        dictionary[item] = dictionary.TryGetValue(item, out var existingCount) ? existingCount + count : count;
    }
References ItemBlackList.Test().
Referenced by AddItemToRecover(), and AddLootedItem().
AddItemToRecover() [1/2]
void PartyBattleRecord.AddItemToRecover (ItemObject item)
Definition at line 20 of file PartyBattleRecord.cs.
{
        AddItemToDictionary(ItemsToRecover, item, 1);
    }
References AddItemToDictionary(), and ItemsToRecover.
AddItemToRecover() [2/2]
void PartyBattleRecord.AddItemToRecover (ItemObject item, int count)
Definition at line 24 of file PartyBattleRecord.cs.
{ AddItemToDictionary(ItemsToRecover, item, count); }
References AddItemToDictionary(), and ItemsToRecover.
AddLootedItem() [1/2]
void PartyBattleRecord.AddLootedItem (ItemObject item)
Definition at line 26 of file PartyBattleRecord.cs.
{ AddItemToDictionary(LootedItems, item, 1); }
References AddItemToDictionary(), and LootedItems.
AddLootedItem() [2/2]
void PartyBattleRecord.AddLootedItem (ItemObject item, int count)
Definition at line 28 of file PartyBattleRecord.cs.
{ AddItemToDictionary(LootedItems, item, count); }
References AddItemToDictionary(), and LootedItems.
Member Data Documentation
ItemsToRecover
readonly Dictionary<ItemObject, int> PartyBattleRecord.ItemsToRecover = new()
Definition at line 12 of file PartyBattleRecord.cs.
Referenced by AddItemToRecover().
LootedItems
readonly Dictionary<ItemObject, int> PartyBattleRecord.LootedItems = new()
Definition at line 14 of file PartyBattleRecord.cs.
Referenced by AddLootedItem().
Property Documentation
ItemsToRecoverCount
int PartyBattleRecord.ItemsToRecoverCount get
Definition at line 16 of file PartyBattleRecord.cs.
LootedItemsCount
int PartyBattleRecord.LootedItemsCount get
Definition at line 18 of file PartyBattleRecord.cs.
The documentation for this class was generated from the following file:
PartyBattleRecord.cs