动态装备系统: DynamicTroopEquipmentReupload.DynamicTroopMissionLogic Class Reference
DynamicTroopEquipmentReupload.DynamicTroopMissionLogic Class Reference
Public Member Functions
override void AfterStart ()
override void EarlyStart ()
override void OnAgentRemoved (Agent affectedAgent, Agent affectorAgent, AgentState agentState, KillingBlow blow)
当士兵在战斗中被移除（如被杀或被击晕）时触发的处理。
override void OnBattleEnded ()
override void OnBehaviorInitialize ()
override void OnCreated ()
override InquiryData OnEndMissionRequest (out bool canLeave)
override void OnMissionResultReady (MissionResult missionResult)
override void OnRetreatMission ()
override void OnSurrenderMission ()
void RegisterSpawnedAgentAssignment (Agent agent, Assignment assignment)
override void ShowBattleResults ()
void TryInitializeDistributors ()
Public Attributes
readonly Dictionary< MBGUID, PartyEquipmentDistributor > Distributors = new()
readonly Dictionary< MBGUID, BattleSideEnum > PartyBattleSides = new()
Protected Member Functions
override void OnEndMission ()
Private Member Functions
void DistributeNavalCasualtyLoot (BattleSideEnum winningSide)
void FinalizeMission (MissionResult? missionResult)
void HandlePartyItems (MBGUID partyId, bool isPlayerParty, bool isVictorious, bool isDefeated)
处理部队战后的物品管理。
MobileParty? NavalCasualtyLootOwner (MBReadOnlyList< KeyValuePair< MapEventParty, float > > lootChances, BattleSideEnum winningSide)
void ProcessAgentEquipmentRespectingTemporarySlots (Agent agent, Action< ItemObject > processEquipmentItem)
void ReturnEquipmentFromAgents (MBGUID partyId, IEnumerable< Agent > agents, MBGUID playerPartyId)
从参与战斗的士兵那里回收装备。
void ReturnItemsToDestination (MBGUID partyId, ConcurrentDictionary< ItemObject, int > items, bool isPlayerParty)
将物品返回到指定部队。
Static Private Member Functions
static void ProcessAssignmentEquipmentFallback (Assignment assignment, Action< ItemObject > processEquipmentItem)
Private Attributes
bool _areDistributorsInitialized
readonly Dictionary< Agent, Assignment > _assignmentByAgent = new()
bool _isMissionEnded
readonly ConcurrentDictionary< MBGUID, PartyBattleRecord > _partyBattleRecords = new()
readonly HashSet< Agent > _processedAgents = new()
readonly Random _random = new()
readonly Dictionary< MBGUID, BattleSideEnum > _sideByInvolvedParty = new()
readonly ConcurrentDictionary< MBGUID, ConcurrentDictionary< ItemObject, int > > _unclaimedNavalCasualtyLoot = new()
Detailed Description
Definition at line 17 of file DynamicTroopMissionLogic.cs.
Member Function Documentation
AfterStart()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.AfterStart ()
Definition at line 99 of file DynamicTroopMissionLogic.cs.
{
        base.AfterStart();
        Global.Log("AfterStart", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log().
DistributeNavalCasualtyLoot()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.DistributeNavalCasualtyLoot (BattleSideEnum winningSide) private
Definition at line 355 of file DynamicTroopMissionLogic.cs.
{
        if (_unclaimedNavalCasualtyLoot.IsEmpty)
            return;
        var mapEvent = MapEvent.PlayerMapEvent;
        if (mapEvent == null)
            return;
        var defeatedSide = winningSide == BattleSideEnum.Attacker
            ? BattleSideEnum.Defender
            : BattleSideEnum.Attacker;
        var winnerParties = mapEvent.PartiesOnSide(winningSide);
        var defeatedParties = mapEvent.PartiesOnSide(defeatedSide);
        foreach (var defeatedPartyLoot in _unclaimedNavalCasualtyLoot)
        {
            MapEventParty? defeatedParty = null;
            foreach (var candidate in defeatedParties)
            {
                if (candidate.Party.MobileParty?.Id != defeatedPartyLoot.Key)
                    continue;
                defeatedParty = candidate;
                break;
            }
            if (defeatedParty == null)
                continue;
            var lootChances = Campaign.Current.Models.BattleRewardModel
                .GetLootCasualtyChances(winnerParties, defeatedParty.Party);
            foreach (var item in defeatedPartyLoot.Value)
            {
                for (var itemIndex = 0; itemIndex < item.Value; itemIndex++)
                {
                    var recipientParty = NavalCasualtyLootOwner(lootChances, winningSide);
                    if (recipientParty == null)
                        continue;
                    var battleRecord = _partyBattleRecords.GetOrAdd(
                        recipientParty.Id,
                        _ => new PartyBattleRecord());
                    battleRecord.AddLootedItem(item.Key);
                }
            }
        }
    }
References _partyBattleRecords, _unclaimedNavalCasualtyLoot, and NavalCasualtyLootOwner().
Referenced by FinalizeMission().
EarlyStart()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.EarlyStart ()
Definition at line 93 of file DynamicTroopMissionLogic.cs.
{
        base.EarlyStart();
        Global.Log("EarlyStart", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log().
FinalizeMission()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.FinalizeMission (MissionResult? missionResult) private
Definition at line 302 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("FinalizeMission() called", Colors.Green, Level.Debug);
        if (_isMissionEnded) return;
        if (!_areDistributorsInitialized) {
            _isMissionEnded = true;
            return;
        }
        var mainParty = Campaign.Current?.MainParty;
        var playerTeam = Mission.PlayerTeam;
        if (mainParty == null || playerTeam == null) return;
        _isMissionEnded = true;
        var playerVictory = missionResult?.PlayerVictory ?? false;
        var playerDefeat = missionResult?.PlayerDefeated ?? false;
        var unresolvedBattle = missionResult == null || !missionResult.BattleResolved;
        var playerPartyId = mainParty.Id;
        var playerSide = playerTeam.Side;
        var winningSide = missionResult?.BattleState switch {
            BattleState.AttackerVictory => BattleSideEnum.Attacker,
            BattleState.DefenderVictory => BattleSideEnum.Defender,
            _ => BattleSideEnum.None
        };
        if (winningSide != BattleSideEnum.None &&
            (Mission.IsNavalBattle || Mission.IsNavalRaidBattle))
            DistributeNavalCasualtyLoot(winningSide);
        foreach (var partyBattleSide in PartyBattleSides)
        {
            var isPlayerParty = partyBattleSide.Key == playerPartyId;
            var isVictorious = !unresolvedBattle &&
                (playerVictory && partyBattleSide.Value == playerSide ||
                 playerDefeat && partyBattleSide.Value != playerSide);
            var isDefeated = !unresolvedBattle &&
                (playerDefeat && partyBattleSide.Value == playerSide ||
                 playerVictory && partyBattleSide.Value != playerSide);
            HandlePartyItems(partyBattleSide.Key, isPlayerParty, isVictorious, isDefeated);
        }
        foreach (var partyBattleSide in PartyBattleSides) {
            IEnumerable<Agent> partyAgents = Mission.Agents.WhereQ(agent =>
                agent.IsValid() &&
                agent.IsActive() &&
                !agent.IsHero &&
                !_processedAgents.Contains(agent) &&
                Global.GetAgentParty(agent.Origin)?.Id == partyBattleSide.Key);
            ReturnEquipmentFromAgents(partyBattleSide.Key, partyAgents, playerPartyId);
        }
    }
References _areDistributorsInitialized, _isMissionEnded, _processedAgents, DistributeNavalCasualtyLoot(), DynamicTroopEquipmentReupload.Global.GetAgentParty(), HandlePartyItems(), DynamicTroopEquipmentReupload.Global.Log(), PartyBattleSides, and ReturnEquipmentFromAgents().
Referenced by OnBattleEnded(), OnEndMission(), OnMissionResultReady(), OnRetreatMission(), OnSurrenderMission(), and ShowBattleResults().
HandlePartyItems()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.HandlePartyItems (MBGUID partyId, bool isPlayerParty, bool isVictorious, bool isDefeated) private
处理部队战后的物品管理。
Parameters
partyId 部队的唯一标识符。
isPlayerParty 是否为玩家的部队。
isVictorious 部队是否胜利。
isDefeated 部队是否被击败。
Definition at line 450 of file DynamicTroopMissionLogic.cs.
{
        // 检查是否存在对应的battleRecord
        if (!_partyBattleRecords.TryGetValue(partyId, out var battleRecord)) {
            Global.Warn($"No battle record found for party {partyId}");
            return;
        }
        if (isVictorious) {
            ReturnItemsToDestination(partyId, battleRecord.ItemsToRecover, isPlayerParty);
            ReturnItemsToDestination(partyId, battleRecord.LootedItems,    isPlayerParty);
            if (isPlayerParty) {
                MessageDisplayService.EnqueueMessage(new InformationMessage(LocalizedTexts.GetLootAddedMessage(battleRecord.LootedItemsCount),                   Colors.Green));
                MessageDisplayService.EnqueueMessage(new InformationMessage(LocalizedTexts.GetItemsRecoveredFromFallenMessage(battleRecord.ItemsToRecoverCount), Colors.Green));
            }
        }
        else if (!isDefeated) { ReturnItemsToDestination(partyId, battleRecord.ItemsToRecover, isPlayerParty); }
        // 被击败的一方不获取任何物品
    }
References _partyBattleRecords, MessageDisplayService.EnqueueMessage(), DynamicTroopEquipmentReupload.LocalizedTexts.GetItemsRecoveredFromFallenMessage(), DynamicTroopEquipmentReupload.LocalizedTexts.GetLootAddedMessage(), ReturnItemsToDestination(), and DynamicTroopEquipmentReupload.Global.Warn().
Referenced by FinalizeMission().
NavalCasualtyLootOwner()
MobileParty? DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.NavalCasualtyLootOwner (MBReadOnlyList< KeyValuePair< MapEventParty, float > > lootChances, BattleSideEnum winningSide) private
Definition at line 404 of file DynamicTroopMissionLogic.cs.
{
        var totalChance = 0f;
        foreach (var lootChance in lootChances)
        {
            var mobileParty = lootChance.Key.Party.MobileParty;
            if (mobileParty != null &&
                lootChance.Value > 0f &&
                PartyBattleSides.TryGetValue(mobileParty.Id, out var partySide) &&
                partySide == winningSide)
                totalChance += lootChance.Value;
        }
        if (totalChance <= 0f)
            return null;
        var roll = _random.NextDouble() * totalChance;
        var accumulatedChance = 0f;
        MobileParty? lastEligibleParty = null;
        foreach (var lootChance in lootChances)
        {
            var mobileParty = lootChance.Key.Party.MobileParty;
            if (mobileParty == null ||
                lootChance.Value <= 0f ||
                !PartyBattleSides.TryGetValue(mobileParty.Id, out var partySide) ||
                partySide != winningSide)
                continue;
            lastEligibleParty = mobileParty;
            accumulatedChance += lootChance.Value;
            if (roll < accumulatedChance)
                return mobileParty;
        }
        return lastEligibleParty;
    }
References _random, and PartyBattleSides.
Referenced by DistributeNavalCasualtyLoot().
OnAgentRemoved()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnAgentRemoved (Agent affectedAgent, Agent affectorAgent, AgentState agentState, KillingBlow blow)
当士兵在战斗中被移除（如被杀或被击晕）时触发的处理。
Parameters
affectedAgent 被移除的士兵。
affectorAgent 造成移除的士兵。
agentState 被移除的士兵的状态（如被杀、失去意识等）。
blow 造成移除的攻击详情。
Definition at line 112 of file DynamicTroopMissionLogic.cs.
{
        if (Mission is not { PlayerTeam.IsValid: true }) {
            base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
            return;
        }
        if (!affectedAgent.IsValid() || affectedAgent.Character is not { IsHero: false }) {
            base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
            return;
        }
        if (_processedAgents.Contains(affectedAgent)) {
            base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
            return;
        }
        // potential loot for the opposing side.
        if (agentState is AgentState.Killed or AgentState.Unconscious) {
            _ = _processedAgents.Add(affectedAgent);
            var affectedPartyId = Global.GetAgentParty(affectedAgent.Origin)?.Id;
            if (!affectedPartyId.HasValue) {
                base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
                return;
            }
            if (!_partyBattleRecords.ContainsKey(affectedPartyId.Value))
                _partyBattleRecords.TryAdd(affectedPartyId.Value, new PartyBattleRecord());
            var affectedBattleRecord = _partyBattleRecords[affectedPartyId.Value];
            var hasAffectedSide = _sideByInvolvedParty.TryGetValue(affectedPartyId.Value, out var affectedSide);
            var affectorPartyId = affectorAgent.IsValid() ? Global.GetAgentParty(affectorAgent.Origin)?.Id : null;
            PartyBattleRecord? affectorBattleRecord = null;
            if (hasAffectedSide &&
                affectorPartyId.HasValue &&
                _sideByInvolvedParty.TryGetValue(affectorPartyId.Value, out var affectorSide) &&
                affectorSide != affectedSide)
                affectorBattleRecord = _partyBattleRecords.GetOrAdd(
                    affectorPartyId.Value,
                    _ => new PartyBattleRecord());
            var hitBodyPart = blow.VictimBodyPart;
            var armors      = affectedAgent.GetAgentArmors();
            var hitArmor    = ArmorSelector.GetRandomArmorByBodyPart(armors, hitBodyPart);
            // Extra armor break: ONLY for enemy casualties, tierbased.
            // This is an addition to the existing hitArmor destruction logic.
            ItemObject? extraBrokenArmor = null;
            var isEnemyCasualty = hasAffectedSide && affectedSide != Mission.PlayerTeam.Side;
            if (isEnemyCasualty)
            {
                var troopTier = 0;
                if (affectedAgent.Character is CharacterObject characterObject)
                    troopTier = characterObject.Tier;
                var extraBreakChance = troopTier switch {
                    3 => 0.25f,
                    4 => 0.35f,
                    5 => 0.45f,
                    _ => troopTier >= 6 ? 0.60f : 0f
                };
                if (extraBreakChance > 0f && _random.NextFloat() <= extraBreakChance)
                {
                    // Pick an additional armor piece to destroy (excluding hitArmor)
                    var candidates = new List<ItemObject>();
                    foreach (var armor in armors)
                    {
                        if (armor == null)
                            continue;
                        if (hitArmor != null && armor.StringId == hitArmor.StringId)
                            continue;
                        if (armor.ItemType == ItemObject.ItemTypeEnum.HorseHarness)
                            continue;
                        candidates.Add(armor);
                    }
                    if (candidates.Count > 0)
                        extraBrokenArmor = candidates[_random.Next(candidates.Count)];
                }
            }
            ProcessAgentEquipmentRespectingTemporarySlots(
                affectedAgent,
                item => {
                    if (item == null || !ItemBlackList.Test(item))
                        return;
                    if (hitArmor != null && item.StringId == hitArmor.StringId)
                        return;
                    if (extraBrokenArmor != null && item.StringId == extraBrokenArmor.StringId)
                        return;
                    var dropRate = SubModule.Settings?.DropRate ?? 1f;
                    affectedBattleRecord.AddItemToRecover(item);
                    if (_random.NextFloat() > dropRate)
                        return;
                    if (affectorBattleRecord != null)
                    {
                        affectorBattleRecord.AddLootedItem(item);
                        Global.Log($"{item.StringId} looted", Colors.Green, Level.Debug);
                        return;
                    }
                    if (!Mission.IsNavalBattle && !Mission.IsNavalRaidBattle)
                        return;
                    var casualtyLoot = _unclaimedNavalCasualtyLoot.GetOrAdd(
                        affectedPartyId.Value,
                        _ => new ConcurrentDictionary<ItemObject, int>());
                    casualtyLoot.AddOrUpdate(item, 1, (_, currentCount) => currentCount + 1);
                    Global.Log($"{item.StringId} queued for naval casualty loot", Colors.Green, Level.Debug);
                });
        }
        //Routed (alive, removed mid-battle), make sure their equipment is still returned to their own armory
        else if (!_isMissionEnded && agentState is AgentState.Routed or AgentState.Deleted) {
            _ = _processedAgents.Add(affectedAgent);
            var affectedPartyId = Global.GetAgentParty(affectedAgent.Origin)?.Id;
            if (!affectedPartyId.HasValue) {
                base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
                return;
            }
            if (!_partyBattleRecords.ContainsKey(affectedPartyId.Value))
                _partyBattleRecords.TryAdd(affectedPartyId.Value, new PartyBattleRecord());
            var affectedBattleRecord = _partyBattleRecords[affectedPartyId.Value];
            ProcessAgentEquipmentRespectingTemporarySlots(affectedAgent, item => { affectedBattleRecord.AddItemToRecover(item); });
            Global.Log(
                $"[DTES] Routed/deleted equipment recorded for {affectedAgent.Character?.Name} | party={affectedPartyId.Value} | recordRecoverNow={affectedBattleRecord.ItemsToRecoverCount}",
                Colors.Green,
                Level.Debug);
        }
        base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
    }
References _isMissionEnded, _partyBattleRecords, _processedAgents, _random, _sideByInvolvedParty, _unclaimedNavalCasualtyLoot, DynamicTroopEquipmentReupload.PartyBattleRecord.AddLootedItem(), DynamicTroopEquipmentReupload.ModSettings.DropRate, DynamicTroopEquipmentReupload.Global.GetAgentParty(), DynamicTroopEquipmentReupload.ArmorSelector.GetRandomArmorByBodyPart(), DynamicTroopEquipmentReupload.Global.Log(), ProcessAgentEquipmentRespectingTemporarySlots(), DynamicTroopEquipmentReupload.SubModule.Settings, and DynamicTroopEquipmentReupload.ItemBlackList.Test().
OnBattleEnded()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnBattleEnded ()
Definition at line 294 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnBattleEnded() called", Colors.Green, Level.Debug);
        var missionResult = Mission.MissionResult;
        if (missionResult != null)
            FinalizeMission(missionResult);
        base.OnBattleEnded();
    }
References FinalizeMission(), and DynamicTroopEquipmentReupload.Global.Log().
OnBehaviorInitialize()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnBehaviorInitialize ()
Definition at line 39 of file DynamicTroopMissionLogic.cs.
{
        base.OnBehaviorInitialize();
        Global.Log("OnBehaviorInitialize", Colors.Green, Level.Debug);
        _processedAgents.Clear();
        _sideByInvolvedParty.Clear();
        _partyBattleRecords.Clear();
        _unclaimedNavalCasualtyLoot.Clear();
        Distributors.Clear();
        PartyBattleSides.Clear();
        _assignmentByAgent.Clear();
        _isMissionEnded = false;
        _areDistributorsInitialized = false;
        TryInitializeDistributors();
    }
References _areDistributorsInitialized, _assignmentByAgent, _isMissionEnded, _partyBattleRecords, _processedAgents, _sideByInvolvedParty, _unclaimedNavalCasualtyLoot, Distributors, DynamicTroopEquipmentReupload.Global.Log(), PartyBattleSides, and TryInitializeDistributors().
OnCreated()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnCreated ()
Definition at line 35 of file DynamicTroopMissionLogic.cs.
{
        base.OnCreated();
    }
OnEndMission()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnEndMission () protected
Definition at line 575 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnEndMission() called", Colors.Green, Level.Debug);
        FinalizeMission(Mission.MissionResult);
        base.OnEndMission();
    }
References FinalizeMission(), and DynamicTroopEquipmentReupload.Global.Log().
OnEndMissionRequest()
override InquiryData DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnEndMissionRequest (out bool canLeave)
Definition at line 282 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnEndMissionRequest() called", Colors.Green, Level.Debug);
        return base.OnEndMissionRequest(out canLeave);
    }
References DynamicTroopEquipmentReupload.Global.Log().
OnMissionResultReady()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnMissionResultReady (MissionResult missionResult)
Definition at line 276 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnMissionResultReady() called", Colors.Green, Level.Debug);
        FinalizeMission(missionResult);
        base.OnMissionResultReady(missionResult);
    }
References FinalizeMission(), and DynamicTroopEquipmentReupload.Global.Log().
OnRetreatMission()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnRetreatMission ()
Definition at line 264 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnRetreatMission() called", Colors.Green, Level.Debug);
        FinalizeMission(Mission.MissionResult);
        base.OnRetreatMission();
    }
References FinalizeMission(), and DynamicTroopEquipmentReupload.Global.Log().
OnSurrenderMission()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnSurrenderMission ()
Definition at line 270 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnSurrenderMission() called", Colors.Green, Level.Debug);
        FinalizeMission(Mission.MissionResult);
        base.OnSurrenderMission();
    }
References FinalizeMission(), and DynamicTroopEquipmentReupload.Global.Log().
ProcessAgentEquipmentRespectingTemporarySlots()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ProcessAgentEquipmentRespectingTemporarySlots (Agent agent, Action< ItemObject > processEquipmentItem) private
Definition at line 528 of file DynamicTroopMissionLogic.cs.
{
        if (_assignmentByAgent.TryGetValue(agent, out var assignment)) {
            var processedItemCount = 0;
            Global.ProcessAgentEquipment(
                agent,
                item => {
                    processedItemCount++;
                    processEquipmentItem(item);
                },
                (slot, missionWeapon, spawnElement) => !assignment.IsTemporarySlot(slot, spawnElement.Item));
            if (processedItemCount == 0) {
                Global.Log($"[DTES] Agent equipment returned 0 items. Fallback to Assignment. Agent={agent.Character?.Name}", Colors.Yellow, Level.Debug);
                ProcessAssignmentEquipmentFallback(assignment, processEquipmentItem);
            }
            return;
        }
        Global.ProcessAgentEquipment(agent, processEquipmentItem);
    }
References _assignmentByAgent, DynamicTroopEquipmentReupload.Global.Log(), DynamicTroopEquipmentReupload.Global.ProcessAgentEquipment(), and ProcessAssignmentEquipmentFallback().
Referenced by OnAgentRemoved(), and ReturnEquipmentFromAgents().
ProcessAssignmentEquipmentFallback()
static void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ProcessAssignmentEquipmentFallback (Assignment assignment, Action< ItemObject > processEquipmentItem) static private
Definition at line 551 of file DynamicTroopMissionLogic.cs.
{
        foreach (var slot in Global.EquipmentSlots) {
            if (!assignment.CanUseMountEquipment && (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness))
                continue;
            var element = assignment.Equipment[slot];
            if (element.IsEmpty || element.Item is null)
                continue;
            if (element.Item.IsBannerItem || element.Item.ItemType == ItemObject.ItemTypeEnum.Banner)
                continue;
            if (assignment.IsTemporarySlot(slot, element.Item))
                continue;
            if (element.Item.ItemType is ItemObject.ItemTypeEnum.Arrows
                                         or ItemObject.ItemTypeEnum.Bolts
                                         or ItemObject.ItemTypeEnum.Thrown) { continue; }
            processEquipmentItem(element.Item);
        }
    }
References DynamicTroopEquipmentReupload.Global.EquipmentSlots.
Referenced by ProcessAgentEquipmentRespectingTemporarySlots().
RegisterSpawnedAgentAssignment()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.RegisterSpawnedAgentAssignment (Agent agent, Assignment assignment)
Definition at line 523 of file DynamicTroopMissionLogic.cs.
{
        _assignmentByAgent[agent] = assignment;
    }
References _assignmentByAgent.
Referenced by DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix().
ReturnEquipmentFromAgents()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnEquipmentFromAgents (MBGUID partyId, IEnumerable< Agent > agents, MBGUID playerPartyId) private
从参与战斗的士兵那里回收装备。
Parameters
partyId 部队的唯一标识符。
agents 参与战斗的士兵集合。
Definition at line 501 of file DynamicTroopMissionLogic.cs.
{
        var isPlayerParty  = partyId == playerPartyId;
        var totalItemCount = 0;
        foreach (var agent in agents)
            ProcessAgentEquipmentRespectingTemporarySlots(agent,
                                                          item => {
                                                              if (item is null || !ItemBlackList.Test(item)) return;
                                                              totalItemCount++;
                                                              if (isPlayerParty)
                                                                  ArmyArmory.AddItemToArmory(item);
                                                              else if (Distributors.TryGetValue(partyId, out var distributor))
                                                                  distributor.ReturnItem(item, 1);
                                                          });
        if (totalItemCount <= 0) return;
        var partyType = isPlayerParty ? "Player party" : "Party";
        Global.Log($"{partyType} {partyId} reclaimed {totalItemCount} items from agents", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory(), Distributors, DynamicTroopEquipmentReupload.Global.Log(), ProcessAgentEquipmentRespectingTemporarySlots(), and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by FinalizeMission().
ReturnItemsToDestination()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnItemsToDestination (MBGUID partyId, ConcurrentDictionary< ItemObject, int > items, bool isPlayerParty) private
将物品返回到指定部队。
Parameters
partyId 部队的唯一标识符。
items 要返回的物品及其数量。
isPlayerParty 是否为玩家的部队。
Definition at line 476 of file DynamicTroopMissionLogic.cs.
{
        var totalItemCount = 0; // 用于累计物品总数
        foreach (var item in items) {
            if (item.Key == null || item.Value <= 0 || !ItemBlackList.Test(item.Key)) continue;
            totalItemCount += item.Value;
            if (isPlayerParty)
                ArmyArmory.AddItemToArmory(item.Key, item.Value);
            else if (Distributors.TryGetValue(partyId, out var distributor))
                distributor.ReturnItem(item.Key, item.Value);
        }
        if (totalItemCount <= 0) return;
        var partyType = isPlayerParty ? "Player party" : "Party";
        Global.Log($"{partyType} {partyId} processed a total of {totalItemCount} items", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory(), Distributors, DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by HandlePartyItems().
ShowBattleResults()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ShowBattleResults ()
Definition at line 287 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("ShowBattleResults() called", Colors.Green, Level.Debug);
        if (Mission.MissionResult?.BattleResolved == true)
            FinalizeMission(Mission.MissionResult);
        base.ShowBattleResults();
    }
References FinalizeMission(), and DynamicTroopEquipmentReupload.Global.Log().
TryInitializeDistributors()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.TryInitializeDistributors ()
Definition at line 57 of file DynamicTroopMissionLogic.cs.
{
        if (_areDistributorsInitialized || _isMissionEnded) { return; }
        var mapEvent = MapEvent.PlayerMapEvent;
        var mainParty = Campaign.Current?.MainParty;
        if (mapEvent == null || mainParty == null) { return; }
        ArmyArmory.SanitizeInPlace();
        var mainPartyDistributor = new PartyEquipmentDistributor(Mission, mainParty, ArmyArmory.Armory);
        mainPartyDistributor.RunAsync();
        Distributors[mainParty.Id] = mainPartyDistributor;
        _sideByInvolvedParty[mainParty.Id] = mainParty.Party.Side;
        PartyBattleSides[mainParty.Id] = mainParty.Party.Side;
        foreach (var partyBase in mapEvent.InvolvedParties) {
            var party = partyBase.MobileParty;
            if (party == null || party == mainParty) { continue; }
            _sideByInvolvedParty[party.Id] = partyBase.Side;
            if (!party.IsValid() || party.LeaderHero == null) { continue; }
            var partyArmory = EveryoneCampaignBehavior.SanitizePartyArmory(party.Id);
            if (partyArmory == null) { continue; }
            var distributor = new PartyEquipmentDistributor(Mission, party, partyArmory);
            distributor.RunAsync();
            Distributors[party.Id] = distributor;
            PartyBattleSides[party.Id] = partyBase.Side;
        }
        _areDistributorsInitialized = true;
    }
References _areDistributorsInitialized, _isMissionEnded, _sideByInvolvedParty, DynamicTroopEquipmentReupload.ArmyArmory.Armory, Distributors, PartyBattleSides, DynamicTroopEquipmentReupload.ArmyArmory.SanitizeInPlace(), and DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.SanitizePartyArmory().
Referenced by OnBehaviorInitialize().
Member Data Documentation
_areDistributorsInitialized
bool DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._areDistributorsInitialized private
Definition at line 31 of file DynamicTroopMissionLogic.cs.
Referenced by FinalizeMission(), OnBehaviorInitialize(), and TryInitializeDistributors().
_assignmentByAgent
readonly Dictionary<Agent, Assignment> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._assignmentByAgent = new() private
Definition at line 18 of file DynamicTroopMissionLogic.cs.
Referenced by OnBehaviorInitialize(), ProcessAgentEquipmentRespectingTemporarySlots(), and RegisterSpawnedAgentAssignment().
_isMissionEnded
bool DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._isMissionEnded private
Definition at line 33 of file DynamicTroopMissionLogic.cs.
Referenced by FinalizeMission(), OnAgentRemoved(), OnBehaviorInitialize(), and TryInitializeDistributors().
_partyBattleRecords
readonly ConcurrentDictionary<MBGUID, PartyBattleRecord> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._partyBattleRecords = new() private
Definition at line 20 of file DynamicTroopMissionLogic.cs.
Referenced by DistributeNavalCasualtyLoot(), HandlePartyItems(), OnAgentRemoved(), and OnBehaviorInitialize().
_processedAgents
readonly HashSet<Agent> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._processedAgents = new() private
Definition at line 24 of file DynamicTroopMissionLogic.cs.
Referenced by FinalizeMission(), OnAgentRemoved(), and OnBehaviorInitialize().
_random
readonly Random DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._random = new() private
Definition at line 26 of file DynamicTroopMissionLogic.cs.
Referenced by NavalCasualtyLootOwner(), and OnAgentRemoved().
_sideByInvolvedParty
readonly Dictionary<MBGUID, BattleSideEnum> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._sideByInvolvedParty = new() private
Definition at line 19 of file DynamicTroopMissionLogic.cs.
Referenced by OnAgentRemoved(), OnBehaviorInitialize(), and TryInitializeDistributors().
_unclaimedNavalCasualtyLoot
readonly ConcurrentDictionary<MBGUID, ConcurrentDictionary<ItemObject, int> > DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._unclaimedNavalCasualtyLoot = new() private
Definition at line 22 of file DynamicTroopMissionLogic.cs.
Referenced by DistributeNavalCasualtyLoot(), OnAgentRemoved(), and OnBehaviorInitialize().
Distributors
readonly Dictionary<MBGUID, PartyEquipmentDistributor> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.Distributors = new()
Definition at line 28 of file DynamicTroopMissionLogic.cs.
Referenced by OnBehaviorInitialize(), ReturnEquipmentFromAgents(), ReturnItemsToDestination(), and TryInitializeDistributors().
PartyBattleSides
readonly Dictionary<MBGUID, BattleSideEnum> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.PartyBattleSides = new()
Definition at line 30 of file DynamicTroopMissionLogic.cs.
Referenced by FinalizeMission(), NavalCasualtyLootOwner(), OnBehaviorInitialize(), and TryInitializeDistributors().
The documentation for this class was generated from the following file:
CSharpSourceCode/DynamicTroopMissionLogic.cs