动态装备系统: SpawnAgentPatch Class Reference
SpawnAgentPatch Class Reference
Static Private Member Functions
static void AssignOrSpawnEquipment (AgentBuildData agentBuildData, Assignment assignment, DynamicTroopMissionLogic missionLogic, MBObjectBase party)
分配士兵的装备。
static void EnsureDistributorExists (DynamicTroopMissionLogic missionLogic, MobileParty party)
确保给定部队的装备分配器存在。
static ? Assignment GetAssignmentForCharacter (DynamicTroopMissionLogic missionLogic, MBObjectBase party, string characterStringId)
根据给定的部队和角色ID获取分配的装备。
static bool IsCombatMissionWithValidData (Mission mission, AgentBuildData agentBuildData)
判断当前任务是否为有效的战斗任务，并且士兵生成数据是否有效。
static bool IsPartyValidForProcessing (MobileParty? party)
static void Prefix (Mission __instance, ref AgentBuildData agentBuildData)
在生成士兵之前执行的逻辑。
static void ProcessAgentSpawn (AgentBuildData agentBuildData, MobileParty party, DynamicTroopMissionLogic missionLogic)
处理士兵生成的逻辑。
static void UpdateBattleSides (DynamicTroopMissionLogic missionLogic, MBObjectBase party, BattleSideEnum side)
更新任务逻辑中的部队战斗方面信息。
Detailed Description
Definition at line 15 of file SpawnAgentPatch.cs.
Member Function Documentation
AssignOrSpawnEquipment()
static void SpawnAgentPatch.AssignOrSpawnEquipment (AgentBuildData agentBuildData, Assignment assignment, DynamicTroopMissionLogic missionLogic, MBObjectBase party) static private
分配士兵的装备。
Parameters
agentBuildData 士兵生成数据。
assignment 分配任务。
missionLogic 任务逻辑。
party 部队对象。
Definition at line 131 of file SpawnAgentPatch.cs.
{
        if (Global.IsInPlayerParty(agentBuildData.AgentOrigin))
            ArmyArmory.AssignEquipment(assignment.Equipment);
        else
            missionLogic.Distributors[party.Id].Spawn(assignment.Equipment);
    }
References ArmyArmory.AssignEquipment(), DynamicTroopMissionLogic.Distributors, and Assignment.Equipment.
Referenced by ProcessAgentSpawn().
EnsureDistributorExists()
static void SpawnAgentPatch.EnsureDistributorExists (DynamicTroopMissionLogic missionLogic, MobileParty party) static private
确保给定部队的装备分配器存在。
Parameters
missionLogic 任务逻辑。
party 部队。
Definition at line 99 of file SpawnAgentPatch.cs.
{
        if (missionLogic.Distributors.ContainsKey(party.Id)) return;
        var partyArmory = EveryoneCampaignBehavior.PartyArmories.TryGetValue(party.Id, out var armory)
                              ? armory
                              : new Dictionary<ItemObject, int>();
        missionLogic.Distributors.Add(party.Id, new PartyEquipmentDistributor(Mission.Current, party, partyArmory));
        Global.Debug($"Party {party.Name} involved");
    }
References DynamicTroopMissionLogic.Distributors, and EveryoneCampaignBehavior.PartyArmories.
Referenced by ProcessAgentSpawn().
GetAssignmentForCharacter()
static ? Assignment SpawnAgentPatch.GetAssignmentForCharacter (DynamicTroopMissionLogic missionLogic, MBObjectBase party, string characterStringId) static private
根据给定的部队和角色ID获取分配的装备。
Parameters
missionLogic 任务逻辑。
party 部队对象。
characterStringId 角色ID。
Returns
找到的分配任务，如果没有则返回null。
Definition at line 116 of file SpawnAgentPatch.cs.
{
        return missionLogic.Distributors[party.Id]
                           .Assignments
                           .FirstOrDefaultQ(a => !a.IsAssigned && a.Character.StringId == characterStringId);
    }
References DynamicTroopMissionLogic.Distributors.
Referenced by ProcessAgentSpawn().
IsCombatMissionWithValidData()
static bool SpawnAgentPatch.IsCombatMissionWithValidData (Mission mission, AgentBuildData agentBuildData) static private
判断当前任务是否为有效的战斗任务，并且士兵生成数据是否有效。
Parameters
mission 当前任务。
agentBuildData 士兵生成数据。
Returns
如果是有效的战斗任务并且数据有效，则返回true。
Definition at line 52 of file SpawnAgentPatch.cs.
{
        return mission is { CombatType: Mission.MissionCombatType.Combat, PlayerTeam: not null } &&
               !mission.HasMissionBehavior<TournamentBehavior>()                                 &&
               !mission.HasMissionBehavior<CustomBattleAgentLogic>()                             &&
               mission.HasMissionBehavior<DynamicTroopMissionLogic>()                            &&
               agentBuildData is {
                                     AgentCharacter   : not null,
                                     AgentFormation   : not null,
                                     AgentTeam.IsValid: true,
                                     AgentOrigin      : not null
                                 } &&
               Global.GetAgentParty(agentBuildData.AgentOrigin) != null;
    }
Referenced by Prefix().
IsPartyValidForProcessing()
static bool SpawnAgentPatch.IsPartyValidForProcessing (MobileParty? party) static private
Definition at line 66 of file SpawnAgentPatch.cs.
{
        return party != null && (party.IsValid() || party == MobileParty.MainParty);
    }
Referenced by Prefix().
Prefix()
static void SpawnAgentPatch.Prefix (Mission __instance, ref AgentBuildData agentBuildData) static private
在生成士兵之前执行的逻辑。
Parameters
__instance 当前Mission的实例。
agentBuildData 士兵生成数据。
Definition at line 21 of file SpawnAgentPatch.cs.
{
        if (!IsCombatMissionWithValidData(__instance, agentBuildData)) return;
        var party = Global.GetAgentParty(agentBuildData.AgentOrigin);
        if (!IsPartyValidForProcessing(party)) {
            if ((ModSettings.Instance?.RandomizeNonHeroLedAiPartiesArmor ?? false) &&
                agentBuildData.AgentCharacter is CharacterObject character) {
                Assignment assignment = new(character);
                assignment.FillEmptySlots();
                agentBuildData = agentBuildData.Equipment(assignment.Equipment);
            }
            return;
        }
        var missionLogic = __instance.GetMissionBehavior<DynamicTroopMissionLogic>();
        if (missionLogic == null) {
            Global.Error("missionLogic is null");
            return;
        }
        ProcessAgentSpawn(agentBuildData, party, missionLogic);
        UpdateBattleSides(missionLogic, party, agentBuildData.AgentTeam.Side);
    }
References Assignment.Equipment, Assignment.FillEmptySlots(), IsCombatMissionWithValidData(), IsPartyValidForProcessing(), ProcessAgentSpawn(), ModSettings.RandomizeNonHeroLedAiPartiesArmor, and UpdateBattleSides().
ProcessAgentSpawn()
static void SpawnAgentPatch.ProcessAgentSpawn (AgentBuildData agentBuildData, MobileParty party, DynamicTroopMissionLogic missionLogic) static private
处理士兵生成的逻辑。
Parameters
agentBuildData 士兵生成数据。
party 相关联的部队。
missionLogic 任务逻辑。
Definition at line 76 of file SpawnAgentPatch.cs.
{
        if (agentBuildData.AgentCharacter.IsHero) return;
        EnsureDistributorExists(missionLogic, party);
        var assignment = GetAssignmentForCharacter(missionLogic, party, agentBuildData.AgentCharacter.StringId);
        if (assignment != null) {
            if (!Global.IsInPlayerParty(agentBuildData.AgentOrigin)) assignment.FillEmptySlots();
            agentBuildData = agentBuildData.Equipment(assignment.Equipment);
            AssignOrSpawnEquipment(agentBuildData, assignment, missionLogic, party);
            assignment.IsAssigned = true;
        }
        else { Global.Error($"Assignment not found for {agentBuildData.AgentCharacter.StringId}"); }
    }
References AssignOrSpawnEquipment(), EnsureDistributorExists(), and GetAssignmentForCharacter().
Referenced by Prefix().
UpdateBattleSides()
static void SpawnAgentPatch.UpdateBattleSides (DynamicTroopMissionLogic missionLogic, MBObjectBase party, BattleSideEnum side) static private
更新任务逻辑中的部队战斗方面信息。
Parameters
missionLogic 任务逻辑。
party 部队对象。
side 战斗中的一方。
Definition at line 147 of file SpawnAgentPatch.cs.
{
        if (!missionLogic.PartyBattleSides.ContainsKey(party.Id)) missionLogic.PartyBattleSides.Add(party.Id, side);
    }
References DynamicTroopMissionLogic.PartyBattleSides.
Referenced by Prefix().
The documentation for this class was generated from the following file:
Patches/SpawnAgentPatch.cs