动态装备系统: DynamicTroopEquipmentReupload.ItemBlackList Class Reference
DynamicTroopEquipmentReupload.ItemBlackList Class Reference
Provides functionality to test if an item should be blacklisted.
Classes
class BlackList
Utility class for managing item blacklist for dynamic troops.
Static Public Member Functions
static void ResetCache ()
Determines if an item passes the blacklisting conditions.
static bool Test (ItemObject? item)
Static Private Member Functions
static ItemBlackList ()
Initializes the ItemBlackList.
static void EnsureBlackListExists (string filePath, string modDirectory)
Ensures that the black list exists by checking if the black list file exists on the given file path. If the file does not exist, it will be created using a provided example file.
static void LoadBlackList (string filePath)
Loads the blacklist from a JSON file and populates the internal blacklists.
Static Private Attributes
static readonly ConcurrentDictionary< ItemObject, bool > Cache = new()
static readonly HashSet< Regex > NamePatterns = new()
Contains the patterns used for filtering item names.
static readonly HashSet< string > Names = new()
Represents a collection of string names used for blacklisting items.
static readonly HashSet< Regex > StringIdPatterns = new()
The set of string ID patterns used for blacklisting items.
static readonly HashSet< string > StringIds = new()
Represents a collection of string IDs used for blacklisting items.
Detailed Description
Provides functionality to test if an item should be blacklisted.
Definition at line 16 of file ItemBlackList.cs.
Constructor & Destructor Documentation
ItemBlackList()
static DynamicTroopEquipmentReupload.ItemBlackList.ItemBlackList () static private
Initializes the ItemBlackList.
Definition at line 54 of file ItemBlackList.cs.
{
        try {
            Global.Debug("initializing black list");
            var modDirectory  = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var blackListFile = Path.Combine(modDirectory, "../../blacklist.json");
            EnsureBlackListExists(blackListFile, modDirectory);
            LoadBlackList(blackListFile);
        }
        catch (Exception e) { Global.Error(e.Message); }
    }
References DynamicTroopEquipmentReupload.Global.Debug(), EnsureBlackListExists(), DynamicTroopEquipmentReupload.Global.Error(), and LoadBlackList().
Member Function Documentation
EnsureBlackListExists()
static void DynamicTroopEquipmentReupload.ItemBlackList.EnsureBlackListExists (string filePath, string modDirectory) static private
Ensures that the black list exists by checking if the black list file exists on the given file path. If the file does not exist, it will be created using a provided example file.
Parameters
filePath The file path of the black list file.
modDirectory The directory where the mod is located.
Definition at line 71 of file ItemBlackList.cs.
{
        if (!File.Exists(filePath)) {
            Global.Warn("blacklist.json not found");
            var exampleFile = Path.Combine(modDirectory, "../../blacklist-example.json");
            if (File.Exists(exampleFile))
                File.Copy(exampleFile, filePath);
            else
                Global.Error("blacklist-example.json not found");
        }
    }
References DynamicTroopEquipmentReupload.Global.Error(), and DynamicTroopEquipmentReupload.Global.Warn().
Referenced by ItemBlackList().
LoadBlackList()
static void DynamicTroopEquipmentReupload.ItemBlackList.LoadBlackList (string filePath) static private
Loads the blacklist from a JSON file and populates the internal blacklists.
Parameters
filePath The path to the JSON file containing the blacklist.
Definition at line 86 of file ItemBlackList.cs.
{
        var content = File.ReadAllText(filePath);
        Global.Debug($"read black list file: {content}");
        var blackList = JsonConvert.DeserializeObject<BlackList>(content);
        if (blackList != null) {
            StringIds.UnionWith(blackList.string_id ?? Enumerable.Empty<string>());
            Names.UnionWith(blackList.name          ?? Enumerable.Empty<string>());
            foreach (var pattern in blackList.string_id_regex ?? new List<string>()) {
                if (pattern == null) continue;
                try { StringIdPatterns.Add(new Regex(pattern, RegexOptions.Compiled)); }
                catch (Exception e) { Global.Error(e.Message); }
            }
            foreach (var pattern in blackList.name_regex ?? Enumerable.Empty<string>()) {
                if (pattern == null) continue;
                try { NamePatterns.Add(new Regex(pattern, RegexOptions.Compiled)); }
                catch (Exception e) { Global.Error(e.Message); }
            }
            foreach (var id in StringIds) { Global.Debug($"string id {id} added to blacklist"); }
            foreach (var name in Names) { Global.Debug($"name {name} added to blacklist"); }
            foreach (var pattern in StringIdPatterns) { Global.Debug($"string id regex pattern {pattern} added to blacklist"); }
            foreach (var pattern in NamePatterns) { Global.Debug($"name regex pattern {pattern} added to blacklist"); }
        }
    }
References DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Global.Error(), NamePatterns, Names, StringIdPatterns, and StringIds.
Referenced by ItemBlackList().
ResetCache()
static void DynamicTroopEquipmentReupload.ItemBlackList.ResetCache () static
Determines if an item passes the blacklisting conditions.
Parameters
item The item to test.
Returns
True if the item passes the blacklisting conditions, false otherwise.
Definition at line 121 of file ItemBlackList.cs.
{
        Cache.Clear();
    }
References Cache.
Referenced by DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.InitializeItemListByType().
Test()
static bool DynamicTroopEquipmentReupload.ItemBlackList.Test (ItemObject? item) static
Definition at line 124 of file ItemBlackList.cs.
{
        try {
            if (item == null || !ArmyArmory.TryResolveArmoryItem(item, out var resolvedItem))
                return false;
            if (Cache.TryGetValue(resolvedItem, out var cachedResult))
                return cachedResult;
            var stringId = resolvedItem.StringId;
            var name     = resolvedItem.Name.ToString();
            var isAllowed =
                !StringIds.Contains(stringId)                               &&
                !Names.Contains(name)                                       &&
                !StringIdPatterns.Any(pattern => pattern.IsMatch(stringId)) &&
                !NamePatterns.Any(pattern => pattern.IsMatch(name));
            Cache[resolvedItem] = isAllowed;
            return isAllowed;
        }
        catch (Exception e) {
            Global.Error(e.Message);
            return false;
        }
    }
References Cache, DynamicTroopEquipmentReupload.Global.Error(), NamePatterns, Names, StringIdPatterns, StringIds, and DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem().
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AddEquipmentToAssign(), DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory(), DynamicTroopEquipmentReupload.PartyBattleRecord.AddItemToDictionary(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.AddItemToPartyArmory(), DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.AddRandomGearItems(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ApplyEmergencyLoadout(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.GetAllLootItems(), DynamicTroopEquipmentReupload.Cache.GetItemsByTierAndCulture(), DynamicTroopEquipmentReupload.Cache.GetItemsByTypeTierAndCulture(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnAgentRemoved(), DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.Prefix(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnEquipmentFromAgents(), and DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnItemsToDestination().
Member Data Documentation
Cache
readonly ConcurrentDictionary<ItemObject, bool> DynamicTroopEquipmentReupload.ItemBlackList.Cache = new() static private
Definition at line 17 of file ItemBlackList.cs.
Referenced by ResetCache(), and Test().
NamePatterns
readonly HashSet<Regex> DynamicTroopEquipmentReupload.ItemBlackList.NamePatterns = new() static private
Contains the patterns used for filtering item names.
This set is populated by reading and parsing a blacklist file.
Definition at line 49 of file ItemBlackList.cs.
Referenced by LoadBlackList(), and Test().
Names
readonly HashSet<string> DynamicTroopEquipmentReupload.ItemBlackList.Names = new() static private
Represents a collection of string names used for blacklisting items.
This set is populated by reading and parsing a blacklist file.
Definition at line 33 of file ItemBlackList.cs.
Referenced by LoadBlackList(), and Test().
StringIdPatterns
readonly HashSet<Regex> DynamicTroopEquipmentReupload.ItemBlackList.StringIdPatterns = new() static private
The set of string ID patterns used for blacklisting items.
This set is populated by reading and parsing a blacklist file.
Definition at line 41 of file ItemBlackList.cs.
Referenced by LoadBlackList(), and Test().
StringIds
readonly HashSet<string> DynamicTroopEquipmentReupload.ItemBlackList.StringIds = new() static private
Represents a collection of string IDs used for blacklisting items.
This set is populated by reading and parsing a blacklist file.
Definition at line 25 of file ItemBlackList.cs.
Referenced by LoadBlackList(), and Test().
The documentation for this class was generated from the following file:
ItemBlackList.cs