动态装备系统: DynamicTroopEquipmentReupload.Assignment Class Reference
DynamicTroopEquipmentReupload.Assignment Class Reference
Public Member Functions
Assignment (CharacterObject character)
int CompareTo (object? obj)
Equipment CreateEquipmentForArmoryConsumption ()
void FillEmptySlots ()
EquipmentElement GetEquipmentFromSlot (EquipmentIndex slot)
bool IsTemporarySlot (EquipmentIndex slot, ItemObject? item)
void MarkSlotAsTemporary (EquipmentIndex slot, ItemObject item)
void SetEquipment (EquipmentIndex slot, EquipmentElement equipment)
Public Attributes
readonly Equipment Equipment
Static Public Attributes
static readonly EquipmentIndex[] WeaponSlots
Properties
bool CanBeShielded [get]
CharacterObject Character [get]
EquipmentIndex? EmptyWeaponSlot [get]
bool HasTemporarySlots [get]
bool HaveThrown [get]
bool HaveTwoHandedWeaponOrPolearms [get]
int Index [get]
bool IsArcher [get]
bool IsAssigned [get, set]
bool IsCrossBowMan [get]
bool IsMounted [get]
bool IsShielded [get]
bool IsUnarmed [get]
bool IsUnderEquipped [get, set]
Equipment ReferenceEquipment [get]
float UnderEquippedMoralePenalty [get, set]
Static Private Member Functions
static Equipment CreateEmptyEquipment ()
Private Attributes
readonly ReaderWriterLockSlim _eqLock = new()
bool _isAssigned
readonly ReaderWriterLockSlim _lock = new()
readonly Dictionary< EquipmentIndex, string > _temporaryItemIdBySlot = new()
Static Private Attributes
static int _counter
Detailed Description
Definition at line 14 of file Assignment.cs.
Constructor & Destructor Documentation
Assignment()
DynamicTroopEquipmentReupload.Assignment.Assignment (CharacterObject character)
Definition at line 33 of file Assignment.cs.
{
        _lock.EnterWriteLock();
        try { Index = Interlocked.Increment(ref _counter); }
        finally { _lock.ExitWriteLock(); }
        Character          = character;
        Equipment          = CreateEmptyEquipment();
        ReferenceEquipment = character.RandomBattleEquipment.Clone();
    }
References _counter, _lock, Character, CreateEmptyEquipment(), Equipment, Index, and ReferenceEquipment.
Referenced by CompareTo().
Member Function Documentation
CompareTo()
int DynamicTroopEquipmentReupload.Assignment.CompareTo (object? obj)
Definition at line 128 of file Assignment.cs.
{
        if (obj == null) return 1;
        if (obj is not Assignment other) throw new ArgumentException("Object is not an Assignment");
        var tierComparison = Character.Tier.CompareTo(other.Character.Tier);
        if (tierComparison != 0) return tierComparison;
        // TroopType 比较，小的放在前面
        var thisTroopType       = Character.GetTroopType();
        var otherTroopType      = other.Character.GetTroopType();
        var troopTypeComparison = thisTroopType.CompareTo(otherTroopType);
        if (troopTypeComparison != 0) return troopTypeComparison;
        // 按 IsRanged 比较，IsRanged 排在 !IsRanged 前面
        if (!Character.IsRanged && other.Character.IsRanged) return 1;
        if (Character.IsRanged && !other.Character.IsRanged) return -1;
        // 按 IsMounted 比较，!IsMounted 排在 IsMounted 前面
        if (Character.IsMounted && !other.Character.IsMounted) return 1;
        if (!Character.IsMounted && other.Character.IsMounted) return -1;
        var skillValueComparison = Character.SkillValue().CompareTo(other.Character.SkillValue());
        if (skillValueComparison != 0) return skillValueComparison;
        var equipmentValueComparison = Character.EquipmentValue().CompareTo(other.Character.EquipmentValue());
        if (equipmentValueComparison != 0) return equipmentValueComparison;
        var levelComparison = Character.Level.CompareTo(other.Character.Level);
        if (levelComparison != 0) return levelComparison;
        return 0; // 如果所有条件都相等，则认为两者相等
    }
References Assignment(), and Character.
CreateEmptyEquipment()
static Equipment DynamicTroopEquipmentReupload.Assignment.CreateEmptyEquipment () static private
Definition at line 196 of file Assignment.cs.
{
        Equipment emptyEquipment = new();
        foreach (var slot in Global.EquipmentSlots)
            emptyEquipment.AddEquipmentToSlotWithoutAgent(slot, new EquipmentElement());
        return emptyEquipment;
    }
References Equipment, and DynamicTroopEquipmentReupload.Global.EquipmentSlots.
Referenced by Assignment().
CreateEquipmentForArmoryConsumption()
Equipment DynamicTroopEquipmentReupload.Assignment.CreateEquipmentForArmoryConsumption ()
Definition at line 172 of file Assignment.cs.
{
        if (_temporaryItemIdBySlot.Count == 0)
            return Equipment;
        var equipmentClone = Equipment.Clone();
        foreach (var temporarySlot in _temporaryItemIdBySlot.Keys)
            equipmentClone.AddEquipmentToSlotWithoutAgent(temporarySlot, new EquipmentElement());
        return equipmentClone;
    }
References _temporaryItemIdBySlot, and Equipment.
Referenced by DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix().
FillEmptySlots()
void DynamicTroopEquipmentReupload.Assignment.FillEmptySlots ()
Definition at line 204 of file Assignment.cs.
{
        var isHideoutBattle = Mission.Current?.HasMissionBehavior<HideoutMissionController>() ?? false;
        foreach (var slot in Global.ArmourSlots) {
            var referenceEquipment = ReferenceEquipment.GetEquipmentFromSlot(slot);
            if (GetEquipmentFromSlot(slot) is not { IsEmpty: false, Item: not null }) {
                var itemType = Helper.EquipmentIndexToItemEnumType(slot);
                if (!itemType.HasValue) continue;
                ItemObject? item;
                if (referenceEquipment is { IsEmpty: false, Item: not null }) {
                    List<ItemObject> itemList         = new() { referenceEquipment.Item };
                    var              itemsByCharacter = Cache.GetItemsByTypeTierAndCulture(itemType.Value, Character.Tier, Character.Culture);
                    if (itemsByCharacter != null) itemList.AddRange(itemsByCharacter);
                    if (referenceEquipment.Item.Culture is CultureObject cultureObject) {
                        var itemsByReference = Cache.GetItemsByTypeTierAndCulture(itemType.Value, (int)referenceEquipment.Item.Tier, cultureObject);
                        if (itemsByReference != null) itemList.AddRange(itemsByReference);
                    }
                    item = WeightedRandomSelector.SelectItem(itemList, referenceEquipment.Item.Effectiveness);
                }
                else {
                    item = Cache.GetItemsByTypeTierAndCulture(itemType.Value, Character.Tier, Character.Culture)?.GetRandomElement();
                    if (item == null) continue;
                }
                SetEquipment(slot, new EquipmentElement(item));
            }
        }
        foreach (var slot in Global.EquipmentSlots) {
            // hideout harness fix
            if (isHideoutBattle && (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness)) continue;
            if (GetEquipmentFromSlot(slot) is not { IsEmpty: false, Item: not null })
                SetEquipment(slot, ReferenceEquipment.GetEquipmentFromSlot(slot));
        }
    }
References DynamicTroopEquipmentReupload.Global.ArmourSlots, Character, DynamicTroopEquipmentReupload.Helper.EquipmentIndexToItemEnumType(), DynamicTroopEquipmentReupload.Global.EquipmentSlots, GetEquipmentFromSlot(), DynamicTroopEquipmentReupload.Cache.GetItemsByTypeTierAndCulture(), ReferenceEquipment, DynamicTroopEquipmentReupload.WeightedRandomSelector.SelectItem(), and SetEquipment().
GetEquipmentFromSlot()
EquipmentElement DynamicTroopEquipmentReupload.Assignment.GetEquipmentFromSlot (EquipmentIndex slot)
Definition at line 184 of file Assignment.cs.
{
        _eqLock.EnterReadLock();
        try { return Equipment.GetEquipmentFromSlot(slot); }
        finally { _eqLock.ExitReadLock(); }
    }
References _eqLock, and Equipment.
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumTypeBySlot(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClassBySlot(), and FillEmptySlots().
IsTemporarySlot()
bool DynamicTroopEquipmentReupload.Assignment.IsTemporarySlot (EquipmentIndex slot, ItemObject? item)
Definition at line 168 of file Assignment.cs.
{
        return item != null && _temporaryItemIdBySlot.TryGetValue(slot, out var itemId) && item.StringId == itemId;
    }
References _temporaryItemIdBySlot.
MarkSlotAsTemporary()
void DynamicTroopEquipmentReupload.Assignment.MarkSlotAsTemporary (EquipmentIndex slot, ItemObject item)
Definition at line 164 of file Assignment.cs.
{
        _temporaryItemIdBySlot[slot] = item.StringId;
    }
References _temporaryItemIdBySlot.
SetEquipment()
void DynamicTroopEquipmentReupload.Assignment.SetEquipment (EquipmentIndex slot, EquipmentElement equipment)
Definition at line 190 of file Assignment.cs.
{
        _eqLock.EnterWriteLock();
        try { Equipment.AddEquipmentToSlotWithoutAgent(slot, equipment); }
        finally { _eqLock.ExitWriteLock(); }
    }
References _eqLock, and Equipment.
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumTypeBySlot(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClassBySlot(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponIfAvailable(), and FillEmptySlots().
Member Data Documentation
_counter
int DynamicTroopEquipmentReupload.Assignment._counter static private
Definition at line 22 of file Assignment.cs.
Referenced by Assignment().
_eqLock
readonly ReaderWriterLockSlim DynamicTroopEquipmentReupload.Assignment._eqLock = new() private
Definition at line 23 of file Assignment.cs.
Referenced by GetEquipmentFromSlot(), and SetEquipment().
_isAssigned
bool DynamicTroopEquipmentReupload.Assignment._isAssigned private
Definition at line 31 of file Assignment.cs.
_lock
readonly ReaderWriterLockSlim DynamicTroopEquipmentReupload.Assignment._lock = new() private
Definition at line 24 of file Assignment.cs.
Referenced by Assignment().
_temporaryItemIdBySlot
readonly Dictionary<EquipmentIndex, string> DynamicTroopEquipmentReupload.Assignment._temporaryItemIdBySlot = new() private
Definition at line 27 of file Assignment.cs.
Referenced by CreateEquipmentForArmoryConsumption(), IsTemporarySlot(), and MarkSlotAsTemporary().
Equipment
readonly Equipment DynamicTroopEquipmentReupload.Assignment.Equipment
Definition at line 29 of file Assignment.cs.
Referenced by Assignment(), CreateEmptyEquipment(), CreateEquipmentForArmoryConsumption(), GetEquipmentFromSlot(), and SetEquipment().
WeaponSlots
readonly EquipmentIndex [] DynamicTroopEquipmentReupload.Assignment.WeaponSlots static
Initial value:
= {
                                                              EquipmentIndex.Weapon0,
                                                              EquipmentIndex.Weapon1,
                                                              EquipmentIndex.Weapon2,
                                                              EquipmentIndex.Weapon3
                                                          }
Definition at line 15 of file Assignment.cs.
{
                                                              EquipmentIndex.Weapon0,
                                                              EquipmentIndex.Weapon1,
                                                              EquipmentIndex.Weapon2,
                                                              EquipmentIndex.Weapon3
                                                          };
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ApplyEmergencyLoadout(), DynamicTroopEquipmentReupload.Global.CountCharacterEquipmentItemTypes(), and DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRecruitEquipments().
Property Documentation
CanBeShielded
bool DynamicTroopEquipmentReupload.Assignment.CanBeShielded get
Definition at line 80 of file Assignment.cs.
Character
CharacterObject DynamicTroopEquipmentReupload.Assignment.Character get
Definition at line 63 of file Assignment.cs.
{ get; }
Referenced by Assignment(), CompareTo(), FillEmptySlots(), and DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsWeaponSuitable().
EmptyWeaponSlot
EquipmentIndex? DynamicTroopEquipmentReupload.Assignment.EmptyWeaponSlot get
Definition at line 101 of file Assignment.cs.
    {
        get
        {
            foreach (var slot in WeaponSlots)
                if (GetEquipmentFromSlot(slot).IsEmpty || GetEquipmentFromSlot(slot).Item == null)
                    return slot;
            return null;
        }
    }
HasTemporarySlots
bool DynamicTroopEquipmentReupload.Assignment.HasTemporarySlots get
Definition at line 71 of file Assignment.cs.
HaveThrown
bool DynamicTroopEquipmentReupload.Assignment.HaveThrown get
Definition at line 95 of file Assignment.cs.
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraThrownWeapon().
HaveTwoHandedWeaponOrPolearms
bool DynamicTroopEquipmentReupload.Assignment.HaveTwoHandedWeaponOrPolearms get
Definition at line 98 of file Assignment.cs.
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraTwoHandedWeaponOrPolearms().
Index
int DynamicTroopEquipmentReupload.Assignment.Index get
Definition at line 43 of file Assignment.cs.
{ get; }
Referenced by Assignment().
IsArcher
bool DynamicTroopEquipmentReupload.Assignment.IsArcher get
Definition at line 89 of file Assignment.cs.
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraArrows().
IsAssigned
bool DynamicTroopEquipmentReupload.Assignment.IsAssigned get set
Definition at line 45 of file Assignment.cs.
    {
        get
        {
            //return _isAssigned;
            _lock.EnterReadLock();
            try { return _isAssigned; }
            finally { _lock.ExitReadLock(); }
        }
        set
        {
            //_isAssigned = value;
            _lock.EnterWriteLock();
            try { _isAssigned = value; }
            finally { _lock.ExitWriteLock(); }
        }
    }
IsCrossBowMan
bool DynamicTroopEquipmentReupload.Assignment.IsCrossBowMan get
Definition at line 92 of file Assignment.cs.
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraBolts().
IsMounted
bool DynamicTroopEquipmentReupload.Assignment.IsMounted get
Definition at line 113 of file Assignment.cs.
    {
        get
        {
            var horse = ReferenceEquipment.GetEquipmentFromSlot(EquipmentIndex.Horse);
            return horse is { IsEmpty: false, Item: not null };
        }
    }
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsWeaponSuitable().
IsShielded
bool DynamicTroopEquipmentReupload.Assignment.IsShielded get
Definition at line 74 of file Assignment.cs.
IsUnarmed
bool DynamicTroopEquipmentReupload.Assignment.IsUnarmed get
Definition at line 122 of file Assignment.cs.
IsUnderEquipped
bool DynamicTroopEquipmentReupload.Assignment.IsUnderEquipped get set
Definition at line 67 of file Assignment.cs.
{ get; set; }
ReferenceEquipment
Equipment DynamicTroopEquipmentReupload.Assignment.ReferenceEquipment get
Definition at line 65 of file Assignment.cs.
{ get; }
Referenced by Assignment(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumTypeBySlot(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClassBySlot(), and FillEmptySlots().
UnderEquippedMoralePenalty
float DynamicTroopEquipmentReupload.Assignment.UnderEquippedMoralePenalty get set
Definition at line 69 of file Assignment.cs.
{ get; set; }
Referenced by DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix().
The documentation for this class was generated from the following file:
Assignment.cs