动态装备系统: ArmorSelector Class Reference
ArmorSelector Class Reference
Static Public Member Functions
static ? ItemObject GetRandomArmorByBodyPart (List< ItemObject > armors, BoneBodyPartType? bodyPart)
根据身体部位从装甲列表中随机选择一件装甲。
Static Private Member Functions
static ? ItemObject SelectArmorBasedOnWeight ((ItemObject Armor, int Weight)[] weightedArmors)
基于权重从装甲列表中选择一件装甲。
Static Private Attributes
static readonly Random Random = new()
Detailed Description
Definition at line 9 of file ArmorSelector.cs.
Member Function Documentation
GetRandomArmorByBodyPart()
static ? ItemObject ArmorSelector.GetRandomArmorByBodyPart (List< ItemObject > armors, BoneBodyPartType? bodyPart) static
根据身体部位从装甲列表中随机选择一件装甲。
Parameters
armors 装甲列表。
bodyPart 要保护的身体部位。
Returns
选中的装甲物品，如果没有合适的装甲则返回null。
Definition at line 18 of file ArmorSelector.cs.
{
        if (!bodyPart.HasValue) return null;
        var weightedArmors = armors.WhereQ(armor => armor.HasArmorComponent)
                                   .SelectQ(armor => new { Armor = armor, armor.ArmorComponent })
                                   .WhereQ(ac => ac.ArmorComponent != null)
                                   .SelectQ(ac => new {
                                                          ac.Armor,
                                                          Weight =
                                                              Helper.GetArmorValueForBodyPart(ac.ArmorComponent,
                                                                  bodyPart.Value)
                                                      })
                                   .WhereQ(aw => aw.Weight > 0)
                                   .ToArrayQ();
        return SelectArmorBasedOnWeight(weightedArmors.SelectQ(aw => (aw.Armor, aw.Weight)).ToArrayQ());
    }
References Helper.GetArmorValueForBodyPart(), and SelectArmorBasedOnWeight().
Referenced by DynamicTroopMissionLogic.OnAgentRemoved().
SelectArmorBasedOnWeight()
static ? ItemObject ArmorSelector.SelectArmorBasedOnWeight ((ItemObject Armor, int Weight)[] weightedArmors) static private
基于权重从装甲列表中选择一件装甲。
Parameters
weightedArmors 包含装甲及其权重的数组。
Returns
根据权重选中的装甲物品，如果没有选中任何装甲则返回null。
Definition at line 41 of file ArmorSelector.cs.
{
        var totalWeight = weightedArmors.SumQ(a => a.Weight);
        var choice      = Random.Next(totalWeight);
        var sum         = 0;
        foreach ((var armor, var weight) in weightedArmors) {
            sum += weight;
            if (choice < sum) return armor;
        }
        return null;
    }
References Random.
Referenced by GetRandomArmorByBodyPart().
Member Data Documentation
Random
readonly Random ArmorSelector.Random = new() static private
Definition at line 10 of file ArmorSelector.cs.
Referenced by SelectArmorBasedOnWeight().
The documentation for this class was generated from the following file:
ArmorSelector.cs