动态装备系统: DynamicTroopEquipmentReupload.EveryoneCampaignBehavior Class Reference
DynamicTroopEquipmentReupload.EveryoneCampaignBehavior Class Reference
Classes
class Data
Public Member Functions
override void RegisterEvents ()
override void SyncData (IDataStore dataStore)
Static Public Attributes
static readonly Dictionary< ItemObject.ItemTypeEnum, Func< int, int > > EquipmentAndThresholds
static readonly Dictionary< ItemObject.ItemTypeEnum, List< ItemObject > > ItemListByType = new()
static Dictionary< MBGUID, Dictionary< ItemObject, int > > PartyArmories = new()
Private Member Functions
void AllocateRandomEquipmentToPartyArmory (MobileParty mobileParty)
void DailyTickParty (MobileParty mobileParty)
void DistributeLootRandomly (MapEventParty[] winnerParties, float totalWinnerStrength, IEnumerable< MapEventParty > loserParties)
根据战斗结果，随机分配战败方部队的战利品给胜利方的各个部队。
MapEventParty[] FilterValidParties (IEnumerable< MapEventParty > parties)
void GarbageCollectEquipments (MobileParty mobileParty)
bool GarbageCollectParties (MobileParty mobileParty)
void MoveRosterToArmory (MobileParty mobileParty)
void OnGameLoaded (CampaignGameStarter starter)
void OnMapEventEnded (MapEvent mapEvent)
void OnMobilePartyCreated (MobileParty mobileParty)
void OnMobilePartyDestroyed (MobileParty mobileParty, PartyBase partyBase)
void OnNewGameCreated (CampaignGameStarter starter)
void WeeklyTick ()
Static Private Member Functions
static void AddItemToPartyArmory (MBGUID partyId, ItemObject item, int count)
向指定部队的装备库中添加物品。
static float CalculateTotalStrength (IEnumerable< MapEventParty > parties)
static ? MobileParty ChoosePartyRandomly (IEnumerable< MapEventParty > parties, float totalStrength, Random random)
从一系列部队中根据其总力量随机选择一个部队。
static Dictionary< MBGUID, Dictionary< ItemObject, int > > ConvertToGuidDict (Dictionary< uint, Dictionary< string, int > > uintDict)
将使用uint键和字符串ID的字典转换为包含MBGUID键和物品字典的字典。
static Dictionary< uint, Dictionary< string, int > > ConvertToUIntGuidDict (Dictionary< MBGUID, Dictionary< ItemObject, int > > guidDict)
将包含MBGUID键和物品字典的字典转换为使用uint键和字符串ID的字典。
static Dictionary< ItemObject, int > GetAllLootItems (IEnumerable< MapEventParty > parties)
static void InitializeItemListByType ()
static bool IsMapEventPartyValid (MapEventParty? party)
static void LogParties (IEnumerable< MapEventParty > parties, string label)
static void OnTroopRecruited (Hero? recruiterHero, Settlement recruitmentSettlement, Hero recruitmentSource, CharacterObject troop, int amount)
当兵种被招募时的处理逻辑。
Static Private Attributes
static Data _data = new()
Detailed Description
Definition at line 27 of file EveryoneCampaignBehavior.cs.
Member Function Documentation
AddItemToPartyArmory()
static void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.AddItemToPartyArmory (MBGUID partyId, ItemObject item, int count) static private
向指定部队的装备库中添加物品。
Parameters
partyId 部队的唯一标识符。
item 要添加的物品。
count 添加的物品数量。
Definition at line 418 of file EveryoneCampaignBehavior.cs.
{
        if (!PartyArmories.TryGetValue(partyId, out var inventory)) {
            inventory              = new Dictionary<ItemObject, int>();
            PartyArmories[partyId] = inventory;
        }
        if (!inventory.TryGetValue(item, out var currentCount)) currentCount = 0;
        inventory[item] = currentCount + count;
    }
References PartyArmories.
Referenced by AllocateRandomEquipmentToPartyArmory(), DistributeLootRandomly(), and MoveRosterToArmory().
AllocateRandomEquipmentToPartyArmory()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.AllocateRandomEquipmentToPartyArmory (MobileParty mobileParty) private
Definition at line 215 of file EveryoneCampaignBehavior.cs.
{
        if (mobileParty.MemberRoster                  == null ||
            mobileParty.MemberRoster.GetTroopRoster() == null ||
            mobileParty.MemberRoster.GetTroopRoster().IsEmpty())
            return;
        var randomEquipmentElementsFromTroop = mobileParty.GetRandomEquipmentsFromTroop();
        foreach (var equipmentElement in randomEquipmentElementsFromTroop) {
            AddItemToPartyArmory(mobileParty.Id, equipmentElement.Item, 1);
            Global.Debug($"random equipment (troop) {equipmentElement.Item.Name} added to {mobileParty.Name}");
        }
        var randomItemsFromFiefs = mobileParty.GetDailyEquipmentFromFiefs();
        foreach (var item in randomItemsFromFiefs) {
            AddItemToPartyArmory(mobileParty.Id, item, 1);
            Global.Debug($"random equipment (fief) {item.Name} added to {mobileParty.Name}");
        }
        var randomItemsFromClan = mobileParty.GetRandomEquipmentsFromClan();
        foreach (var item in randomItemsFromClan) {
            AddItemToPartyArmory(mobileParty.Id, item, 1);
            Global.Debug($"random equipment (clan) {item.Name} added to {mobileParty.Name}");
        }
    }
References AddItemToPartyArmory(), and DynamicTroopEquipmentReupload.Global.Debug().
Referenced by DailyTickParty().
CalculateTotalStrength()
static float DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.CalculateTotalStrength (IEnumerable< MapEventParty > parties) static private
Definition at line 299 of file EveryoneCampaignBehavior.cs.
{
        return parties.SumQ(party => party.Party.EstimatedStrength);
    }
Referenced by OnMapEventEnded().
ChoosePartyRandomly()
static ? MobileParty DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.ChoosePartyRandomly (IEnumerable< MapEventParty > parties, float totalStrength, Random random) static private
从一系列部队中根据其总力量随机选择一个部队。
Parameters
parties 参与选择的部队集合。
totalStrength 所有部队的总力量。
random 用于生成随机数的Random实例。
Returns
根据力量加权随机选中的移动部队，如果没有选中则返回null。
Definition at line 361 of file EveryoneCampaignBehavior.cs.
{
        var randomValue        = random.NextDouble() * totalStrength;
        var cumulativeStrength = 0f;
        foreach (var party in parties) {
            cumulativeStrength += party.Party.EstimatedStrength;
            if (cumulativeStrength >= randomValue) return party.Party.MobileParty;
        }
        return null;
    }
Referenced by DistributeLootRandomly().
ConvertToGuidDict()
static Dictionary< MBGUID, Dictionary< ItemObject, int > > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.ConvertToGuidDict (Dictionary< uint, Dictionary< string, int > > uintDict) static private
将使用uint键和字符串ID的字典转换为包含MBGUID键和物品字典的字典。
Parameters
uintDict 以uint为键，以物品字符串ID和数量的字典为值的字典。
Returns
转换后的字典，其中键为MBGUID类型，值为以物品对象和数量构成的字典。
Definition at line 482 of file EveryoneCampaignBehavior.cs.
{
        Dictionary<MBGUID, Dictionary<ItemObject, int>> guidDict = new();
        foreach (var pair in uintDict) {
            if (!guidDict.TryGetValue(new MBGUID(pair.Key), out var innerDict)) {
                innerDict = new Dictionary<ItemObject, int>();
                guidDict.Add(new MBGUID(pair.Key), innerDict);
            }
            foreach (var innerPair in pair.Value) {
                var itemObject = MBObjectManager.Instance.GetObject<ItemObject>(innerPair.Key) ??
                                 ItemObject.GetCraftedItemObjectFromHashedCode(innerPair.Key);
                if (itemObject != null && innerPair.Value > 0) {
                    if (innerDict.ContainsKey(itemObject))
                        innerDict[itemObject] += innerPair.Value;
                    else
                        innerDict.Add(itemObject, innerPair.Value);
                }
                else { Global.Warn($"cannot get object {innerPair.Key}"); }
            }
        }
        return guidDict;
    }
References DynamicTroopEquipmentReupload.Global.Warn().
Referenced by SyncData().
ConvertToUIntGuidDict()
static Dictionary< uint, Dictionary< string, int > > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.ConvertToUIntGuidDict (Dictionary< MBGUID, Dictionary< ItemObject, int > > guidDict) static private
将包含MBGUID键和物品字典的字典转换为使用uint键和字符串ID的字典。
Parameters
guidDict 以MBGUID为键，以物品和数量的字典为值的字典。
Returns
转换后的字典，其中键为uint类型，值为以物品字符串ID和数量构成的字典。
Definition at line 438 of file EveryoneCampaignBehavior.cs.
{
        Dictionary<uint, Dictionary<string, int>> uintDict = new();
        foreach (var pair in guidDict) {
            var party = Campaign.Current.MobileParties.FirstOrDefault(party => party.Id == pair.Key);
            if (party is not {
                                 LeaderHero: {
                                                 CharacterObject       : { IsHero: true, IsPlayerCharacter: false },
                                                 IsHumanPlayerCharacter: false,
                                                 IsPartyLeader         : true,
                                                 IsAlive               : true,
                                                 IsActive              : true
                                             },
                                 Owner: {
                                            CharacterObject       : { IsHero: true, IsPlayerCharacter: false },
                                            IsHumanPlayerCharacter: false,
                                            IsActive              : true,
                                            IsAlive               : true
                                        },
                                 MemberRoster: { TotalHeroes: > 0, TotalManCount: > 0 },
                                 IsDisbanding: false
                             }) continue;
            if (!uintDict.TryGetValue(pair.Key.InternalValue, out var innerDict)) {
                innerDict = new Dictionary<string, int>();
                uintDict.Add(pair.Key.InternalValue, innerDict);
            }
            foreach (var innerPair in pair.Value)
                if (innerPair is { Key: not null, Value: > 0 }) {
                    if (innerDict.ContainsKey(innerPair.Key.StringId))
                        innerDict[innerPair.Key.StringId] += innerPair.Value;
                    else
                        innerDict.Add(innerPair.Key.StringId, innerPair.Value);
                }
        }
        return uintDict;
    }
Referenced by SyncData().
DailyTickParty()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.DailyTickParty (MobileParty mobileParty) private
Definition at line 163 of file EveryoneCampaignBehavior.cs.
{
        if (!mobileParty.IsValid()) return;
        if (!GarbageCollectParties(mobileParty))
            AllocateRandomEquipmentToPartyArmory(mobileParty);
        else
            Global.Debug($"garbage collect party {mobileParty.Name}");
        if (CampaignTime.Now.GetDayOfWeek != mobileParty.Id.InternalValue % 7) return;
        GarbageCollectEquipments(mobileParty);
        //ReplenishBasicTroopEquipments(mobileParty);
        MoveRosterToArmory(mobileParty);
    }
References AllocateRandomEquipmentToPartyArmory(), DynamicTroopEquipmentReupload.Global.Debug(), GarbageCollectEquipments(), GarbageCollectParties(), and MoveRosterToArmory().
Referenced by RegisterEvents().
DistributeLootRandomly()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.DistributeLootRandomly (MapEventParty[] winnerParties, float totalWinnerStrength, IEnumerable< MapEventParty > loserParties) private
根据战斗结果，随机分配战败方部队的战利品给胜利方的各个部队。
Parameters
winnerParties 胜利方的部队数组。
totalWinnerStrength 胜利方部队的总力量。
loserParties 战败方的部队集合。
Definition at line 309 of file EveryoneCampaignBehavior.cs.
{
        Random                  random             = new();
        var                     lootItemsWithCount = GetAllLootItems(loserParties);
        Dictionary<MBGUID, int> partyLootCount     = new();
        foreach (var lootItem in lootItemsWithCount) {
            var item      = lootItem.Key;
            var itemCount = lootItem.Value;
            for (var i = 0; i < itemCount; i++) {
                var chosenParty = ChoosePartyRandomly(winnerParties, totalWinnerStrength, random);
                if (chosenParty == null) return;
                AddItemToPartyArmory(chosenParty.Id, item, 1);
                // 更新统计信息
                if (partyLootCount.ContainsKey(chosenParty.Id))
                    partyLootCount[chosenParty.Id]++;
                else
                    partyLootCount[chosenParty.Id] = 1;
            }
        }
        // 记录每个party获得的物品总数
        foreach (var partyCount in partyLootCount)
            Global.Debug($"Party {partyCount.Key} looted {partyCount.Value} items");
    }
References AddItemToPartyArmory(), ChoosePartyRandomly(), DynamicTroopEquipmentReupload.Global.Debug(), and GetAllLootItems().
Referenced by OnMapEventEnded().
FilterValidParties()
MapEventParty[] DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.FilterValidParties (IEnumerable< MapEventParty > parties) private
Definition at line 290 of file EveryoneCampaignBehavior.cs.
{
        return parties.WhereQ(IsMapEventPartyValid).ToArrayQ();
    }
References IsMapEventPartyValid().
Referenced by OnMapEventEnded().
GarbageCollectEquipments()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.GarbageCollectEquipments (MobileParty mobileParty) private
Definition at line 128 of file EveryoneCampaignBehavior.cs.
{
        if (!mobileParty.IsValid() || mobileParty.MemberRoster?.GetTroopRoster() == null) return;
        var memberCnt = mobileParty.MemberRoster.GetTroopRoster()
                                   .WhereQ(element => element.Character is { IsHero: false })
                                   .SumQ(element => element.Number);
        foreach (var equipmentAndThreshold in EquipmentAndThresholds) {
            var partyArmory = PartyArmories.GetValueSafe(mobileParty.Id);
            if (partyArmory == null || partyArmory.IsEmpty()) return;
            var armorTotalCount = partyArmory.WhereQ(kv => kv.Key.ItemType == equipmentAndThreshold.Key)
                                             .SumQ(kv => kv.Value);
            var surplusCount = armorTotalCount - memberCnt;
            if (surplusCount <= 0) continue;
            var surplusCountCpy = surplusCount;
            // 创建优先级队列
            ItemPriorityQueue armorQueue = new(new EquipmentEffectivenessComparer());
            foreach (var kv in partyArmory.WhereQ(kv => kv.Key.ItemType == equipmentAndThreshold.Key))
                armorQueue.Enqueue(kv.Key, ((int)kv.Key.Tier, kv.Key.Value));
            // 移除多余的装备
            while (surplusCount > 0 && armorQueue.Count > 0) {
                var lowestArmor   = armorQueue.Dequeue();
                var countToRemove = Math.Min(partyArmory[lowestArmor.Key], surplusCount);
                partyArmory[lowestArmor.Key] -= countToRemove;
                surplusCount                 -= countToRemove;
                if (partyArmory[lowestArmor.Key] == 0) _ = partyArmory.Remove(lowestArmor.Key);
            }
            Global.Debug($"Garbage collected {surplusCountCpy - surplusCount}x{equipmentAndThreshold.Key} armors from party {mobileParty.Name}");
        }
    }
References DynamicTroopEquipmentReupload.Global.Debug(), EquipmentAndThresholds, and PartyArmories.
Referenced by DailyTickParty().
GarbageCollectParties()
bool DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.GarbageCollectParties (MobileParty mobileParty) private
Definition at line 179 of file EveryoneCampaignBehavior.cs.
{
        if (mobileParty is not {
                                   LeaderHero: {
                                                   CharacterObject       : { IsHero: true, IsPlayerCharacter: false },
                                                   IsHumanPlayerCharacter: false,
                                                   IsPartyLeader         : true,
                                                   IsAlive               : true,
                                                   IsActive              : true
                                               },
                                   Owner: {
                                              CharacterObject       : { IsHero: true, IsPlayerCharacter: false },
                                              IsHumanPlayerCharacter: false,
                                              IsActive              : true,
                                              IsAlive               : true
                                          },
                                   MemberRoster: { TotalHeroes: > 0, TotalManCount: > 0 },
                                   IsDisbanding: false
                               })
            return PartyArmories.Remove(mobileParty.Id);
        return false;
    }
References PartyArmories.
Referenced by DailyTickParty().
GetAllLootItems()
static Dictionary< ItemObject, int > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.GetAllLootItems (IEnumerable< MapEventParty > parties) static private
Definition at line 339 of file EveryoneCampaignBehavior.cs.
{
        Dictionary<ItemObject, int> itemsWithCount = new();
        foreach (var party in parties)
            if (PartyArmories.TryGetValue(party.Party.MobileParty.Id, out var inventory))
                foreach (var item in inventory) {
                    if (!ItemBlackList.Test(item.Key)) continue;
                    if (itemsWithCount.ContainsKey(item.Key))
                        itemsWithCount[item.Key] += item.Value;
                    else
                        itemsWithCount.Add(item.Key, item.Value);
                }
        return itemsWithCount;
    }
References PartyArmories, and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by DistributeLootRandomly().
InitializeItemListByType()
static void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.InitializeItemListByType () static private
Definition at line 53 of file EveryoneCampaignBehavior.cs.
{
        foreach (var itemType in Global.ItemTypes) {
            var items = MBObjectManager.Instance.GetObjectTypeList<ItemObject>()
                                       ?.WhereQ(item => item != null && item.ItemType == itemType)
                                       ?.OrderByQ(item => item.Tier)
                                       ?.ThenBy(item => item.Value)
                                       .ToListQ();
            ItemListByType[itemType] = items ?? new List<ItemObject>();
        }
    }
References ItemListByType, and DynamicTroopEquipmentReupload.Global.ItemTypes.
Referenced by RegisterEvents().
IsMapEventPartyValid()
static bool DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.IsMapEventPartyValid (MapEventParty? party) static private
Definition at line 429 of file EveryoneCampaignBehavior.cs.
{
        return party is { Party.MobileParty: var mobileParty } && mobileParty.IsValid();
    }
Referenced by FilterValidParties().
LogParties()
static void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.LogParties (IEnumerable< MapEventParty > parties, string label) static private
Definition at line 294 of file EveryoneCampaignBehavior.cs.
{
        foreach (var party in parties)
            Global.Log($"{label} party: {party.Party.Name}#{party.Party.MobileParty.Id}", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log().
Referenced by OnMapEventEnded().
MoveRosterToArmory()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.MoveRosterToArmory (MobileParty mobileParty) private
Definition at line 201 of file EveryoneCampaignBehavior.cs.
{
        var elements = mobileParty.ItemRoster.WhereQ(element =>
                                                         (element.EquipmentElement.Item?.HasArmorComponent  ?? false) ||
                                                         (element.EquipmentElement.Item?.HasWeaponComponent ?? false));
        foreach (var element in elements)
            if (element.EquipmentElement.Item != null) {
                AddItemToPartyArmory(mobileParty.Id, element.EquipmentElement.Item, element.Amount);
                Global.Debug($"equipment {element.EquipmentElement.Item.Name}x{element.Amount} moved to armory from {mobileParty.Name}");
                mobileParty.ItemRoster.Remove(element);
                var hero                    = mobileParty.LeaderHero ?? mobileParty.Owner;
                if (hero != null) hero.Gold += element.EquipmentElement.Item.Value * element.Amount;
            }
    }
References AddItemToPartyArmory(), and DynamicTroopEquipmentReupload.Global.Debug().
Referenced by DailyTickParty().
OnGameLoaded()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnGameLoaded (CampaignGameStarter starter) private
Definition at line 87 of file EveryoneCampaignBehavior.cs.
{
        Global.Debug("OnGameLoaded() called");
        IEnumerable<MobileParty>? validParties = Campaign.Current?.MobileParties?.WhereQ(party => party.IsValid());
        if (validParties == null) return;
        foreach (var validParty in validParties)
            if (!PartyArmories.ContainsKey(validParty.Id))
                OnMobilePartyCreated(validParty);
        CharacterObjectExtension.Init();
    }
References DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.Init(), OnMobilePartyCreated(), and PartyArmories.
Referenced by RegisterEvents().
OnMapEventEnded()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMapEventEnded (MapEvent mapEvent) private
Definition at line 271 of file EveryoneCampaignBehavior.cs.
{
        Global.Log($"Map Event ended with state {mapEvent.BattleState}", Colors.Green, Level.Debug);
        if (mapEvent.BattleState is not BattleState.AttackerVictory and not BattleState.DefenderVictory) return;
        var validWinnerParties = FilterValidParties(mapEvent.BattleState == BattleState.AttackerVictory
                                                        ? mapEvent.AttackerSide.Parties
                                                        : mapEvent.DefenderSide.Parties)
            .ToArrayQ();
        var validLoserParties = FilterValidParties(mapEvent.BattleState == BattleState.AttackerVictory
                                                       ? mapEvent.DefenderSide.Parties
                                                       : mapEvent.AttackerSide.Parties);
        LogParties(validWinnerParties, "Winning");
        LogParties(validLoserParties,  "Defeated");
        var totalWinnerStrength = CalculateTotalStrength(validWinnerParties);
        DistributeLootRandomly(validWinnerParties, totalWinnerStrength, validLoserParties);
    }
References CalculateTotalStrength(), DistributeLootRandomly(), FilterValidParties(), DynamicTroopEquipmentReupload.Global.Log(), and LogParties().
Referenced by RegisterEvents().
OnMobilePartyCreated()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMobilePartyCreated (MobileParty mobileParty) private
Definition at line 240 of file EveryoneCampaignBehavior.cs.
{
        if (!mobileParty.IsValid()) return;
        if (!PartyArmories.TryGetValue(mobileParty.Id, out var itemDict)) {
            itemDict                      = new Dictionary<ItemObject, int>();
            PartyArmories[mobileParty.Id] = itemDict;
        }
        var list = mobileParty.GetItems();
        foreach (var element in list) {
            if (!itemDict.TryGetValue(element.Item, out var count)) count = 0;
            itemDict[element.Item] = count + 1;
        }
        Global.Log($"Mobile party {mobileParty.Name} created, {list.Count} start equipment added",
                   Colors.Green,
                   Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log(), and PartyArmories.
Referenced by OnGameLoaded(), and RegisterEvents().
OnMobilePartyDestroyed()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMobilePartyDestroyed (MobileParty mobileParty, PartyBase partyBase) private
Definition at line 260 of file EveryoneCampaignBehavior.cs.
{
        if (mobileParty?.Id != null) _ = PartyArmories.Remove(mobileParty.Id);
        if (!mobileParty.IsValid()) return;
        if (mobileParty is { Name: not null } && partyBase is { Name: not null })
            Global.Log($"Mobile party {mobileParty.Name} destroyed, partyBase = {partyBase.Name}",
                       Colors.Green,
                       Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log(), and PartyArmories.
Referenced by RegisterEvents().
OnNewGameCreated()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnNewGameCreated (CampaignGameStarter starter) private
Definition at line 79 of file EveryoneCampaignBehavior.cs.
{
        Global.Debug("OnNewGameCreated() called");
        PartyArmories.Clear();
        CharacterObjectExtension.Init();
    }
References DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.Init(), and PartyArmories.
Referenced by RegisterEvents().
OnTroopRecruited()
static void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnTroopRecruited (Hero? recruiterHero, Settlement recruitmentSettlement, Hero recruitmentSource, CharacterObject troop, int amount) static private
当兵种被招募时的处理逻辑。
Parameters
recruiterHero 进行招募的英雄。
recruitmentSettlement 招募发生的定居点。
recruitmentSource 提供招募的英雄。
troop 被招募的兵种。
amount 招募数量。
Definition at line 383 of file EveryoneCampaignBehavior.cs.
{
        if (recruiterHero == null) return;
        var party = recruiterHero.PartyBelongedTo;
        if (!party.IsValid()) return;
        // 确保PartyArmories包含party.Id键
        if (!PartyArmories.TryGetValue(party.Id, out var partyInventory)) {
            partyInventory          = new Dictionary<ItemObject, int>();
            PartyArmories[party.Id] = partyInventory;
        }
        var list = RecruitmentPatch.GetRecruitEquipments(troop);
        foreach (var element in list) {
            // 确保partyInventory包含element.Item键
            if (!partyInventory.TryGetValue(element.Item, out var count)) count = 0;
            partyInventory[element.Item] = count + amount;
        }
        Global.Log($"troop {troop.Name}x{amount} recruited by recruiterHero={recruiterHero.Name} in party {party.Name}, {list.Count * amount} start equipment added",
                   Colors.Green,
                   Level.Debug);
    }
References DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRecruitEquipments(), DynamicTroopEquipmentReupload.Global.Log(), and PartyArmories.
Referenced by RegisterEvents().
RegisterEvents()
override void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.RegisterEvents ()
Definition at line 65 of file EveryoneCampaignBehavior.cs.
{
        CampaignEvents.MobilePartyCreated.AddNonSerializedListener(this, OnMobilePartyCreated);
        CampaignEvents.MobilePartyDestroyed.AddNonSerializedListener(this, OnMobilePartyDestroyed);
        CampaignEvents.MapEventEnded.AddNonSerializedListener(this, OnMapEventEnded);
        CampaignEvents.OnTroopRecruitedEvent.AddNonSerializedListener(this, OnTroopRecruited);
        CampaignEvents.DailyTickPartyEvent.AddNonSerializedListener(this, DailyTickParty);
        CampaignEvents.WeeklyTickEvent.AddNonSerializedListener(this, WeeklyTick);
        CampaignEvents.OnGameLoadedEvent.AddNonSerializedListener(this, OnGameLoaded);
        CampaignEvents.OnNewGameCreatedEvent.AddNonSerializedListener(this, OnNewGameCreated);
        InitializeItemListByType();
        //Global.InitializeCraftingTemplatesByItemType();
    }
References DailyTickParty(), InitializeItemListByType(), OnGameLoaded(), OnMapEventEnded(), OnMobilePartyCreated(), OnMobilePartyDestroyed(), OnNewGameCreated(), OnTroopRecruited(), and WeeklyTick().
SyncData()
override void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.SyncData (IDataStore dataStore)
Definition at line 99 of file EveryoneCampaignBehavior.cs.
{
        if (dataStore.IsSaving) {
            _data.PartyArmories = ConvertToUIntGuidDict(PartyArmories);
            var tempData = _data;
            if (dataStore.SyncDataAsJson("DynamicTroopPartyArmories", ref tempData) && tempData != null) {
                _data = tempData;
                Global.Debug($"saved {PartyArmories.Count} entries");
                _data.PartyArmories.Clear();
            }
            else { Global.Error("Save Error"); }
        }
        else if (dataStore.IsLoading) {
            _data.PartyArmories.Clear();
            var tempData = _data;
            if (dataStore.SyncDataAsJson("DynamicTroopPartyArmories", ref tempData) && tempData != null) {
                _data         = tempData;
                PartyArmories = ConvertToGuidDict(_data.PartyArmories);
                _data.PartyArmories.Clear();
                Global.Debug($"loaded {PartyArmories.Count} entries");
            }
            else { Global.Error("Load Error"); }
        }
    }
References _data, ConvertToGuidDict(), ConvertToUIntGuidDict(), DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Global.Error(), and PartyArmories.
WeeklyTick()
void DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.WeeklyTick () private
Definition at line 123 of file EveryoneCampaignBehavior.cs.
{
        //GarbageCollectParties();
        //GarbageCollectEquipments();
    }
Referenced by RegisterEvents().
Member Data Documentation
_data
Data DynamicTroopEquipmentReupload.EveryoneCampaignBehavior._data = new() static private
Definition at line 30 of file EveryoneCampaignBehavior.cs.
Referenced by SyncData().
EquipmentAndThresholds
readonly Dictionary<ItemObject.ItemTypeEnum, Func<int, int> > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.EquipmentAndThresholds static
Initial value:
=
        new() {
                  { ItemObject.ItemTypeEnum.BodyArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.LegArmor, memberCnt => Math.Max(2     * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HeadArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HandArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Cape, memberCnt => Math.Max(2         * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Shield, memberCnt => Math.Max(2       * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Horse, memberCnt => Math.Max(2        * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HorseHarness, memberCnt => Math.Max(2 * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Bow, memberCnt => Math.Max(2          * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Crossbow, memberCnt => Math.Max(2     * memberCnt, memberCnt + 100) }, {
                                                                                                                       ItemObject.ItemTypeEnum.OneHandedWeapon, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400)
                                                                                                                   }, {
                                                                                                                          ItemObject.ItemTypeEnum.TwoHandedWeapon, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400)
                                                                                                                      },
                  { ItemObject.ItemTypeEnum.Polearm, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400) }
              }
Definition at line 32 of file EveryoneCampaignBehavior.cs.
              {
                  { ItemObject.ItemTypeEnum.BodyArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.LegArmor, memberCnt => Math.Max(2     * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HeadArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HandArmor, memberCnt => Math.Max(2    * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Cape, memberCnt => Math.Max(2         * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Shield, memberCnt => Math.Max(2       * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Horse, memberCnt => Math.Max(2        * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.HorseHarness, memberCnt => Math.Max(2 * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Bow, memberCnt => Math.Max(2          * memberCnt, memberCnt + 100) },
                  { ItemObject.ItemTypeEnum.Crossbow, memberCnt => Math.Max(2     * memberCnt, memberCnt + 100) }, {
                                                                                                                       ItemObject.ItemTypeEnum.OneHandedWeapon, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400)
                                                                                                                   }, {
                                                                                                                          ItemObject.ItemTypeEnum.TwoHandedWeapon, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400)
                                                                                                                      },
                  { ItemObject.ItemTypeEnum.Polearm, memberCnt => Math.Max(8 * memberCnt, 4 * memberCnt + 400) }
              };
Referenced by GarbageCollectEquipments(), and DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipment().
ItemListByType
readonly Dictionary<ItemObject.ItemTypeEnum, List<ItemObject> > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.ItemListByType = new() static
Definition at line 51 of file EveryoneCampaignBehavior.cs.
Referenced by DynamicTroopEquipmentReupload.Cache.GetItemsByTypeTierAndCulture(), and InitializeItemListByType().
PartyArmories
Dictionary<MBGUID, Dictionary<ItemObject, int> > DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.PartyArmories = new() static
Definition at line 28 of file EveryoneCampaignBehavior.cs.
Referenced by AddItemToPartyArmory(), GarbageCollectEquipments(), GarbageCollectParties(), GetAllLootItems(), DynamicTroopEquipmentReupload.Extensions.MobilePartyExtension.IsValid(), OnGameLoaded(), OnMobilePartyCreated(), OnMobilePartyDestroyed(), OnNewGameCreated(), OnTroopRecruited(), DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.Postfix(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ReturnItem(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Spawn(), SyncData(), DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.TransferCargoToTargetStash(), and DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.TryInitializeDistributors().
The documentation for this class was generated from the following file:
EveryoneCampaignBehavior.cs