动态装备系统: DynamicTroopEquipmentReupload.Patches.RecruitmentPatch Class Reference
DynamicTroopEquipmentReupload.Patches.RecruitmentPatch Class Reference
Classes
class EquipmentElementComparer
Static Public Member Functions
static List< EquipmentElement > GetRandomizedRecruitEquipments (CharacterObject? character)
static List< EquipmentElement > GetRecruitEquipments (CharacterObject? character)
static void Prefix (RecruitmentVM __instance)
Detailed Description
Definition at line 14 of file RecruitmentPatch.cs.
Member Function Documentation
GetRandomizedRecruitEquipments()
static List< EquipmentElement > DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRandomizedRecruitEquipments (CharacterObject? character) static
Definition at line 85 of file RecruitmentPatch.cs.
{
        List<EquipmentElement> list = new();
        if (character?.BattleEquipments?.IsEmpty() ?? true) return list;
        foreach (var equipment in character.BattleEquipments)
            if (!equipment.IsEmpty())
                foreach (var slot in Global.EquipmentSlots) {
                    var item = equipment.GetEquipmentFromSlot(slot);
                    if (item is { IsEmpty: false, Item: not null }) list.Add(item);
                }
        return list;
    }
References DynamicTroopEquipmentReupload.Global.EquipmentSlots.
GetRecruitEquipments()
static List< EquipmentElement > DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRecruitEquipments (CharacterObject? character) static
Definition at line 28 of file RecruitmentPatch.cs.
{
        if (character?.BattleEquipments?.IsEmpty() ?? true) return new List<EquipmentElement>();
        var                       armorAndHorse     = character.RandomBattleEquipment;
        List<EquipmentElement>    equipmentElements = new();
        List<EquipmentElement>    weaponList        = new();
        HashSet<EquipmentElement> weaponSet         = new(new EquipmentElementComparer());
        foreach (var slot in Global.ArmourSlots) {
            var equipmentElement = armorAndHorse.GetEquipmentFromSlot(slot);
            if (equipmentElement is { IsEmpty: false, Item: not null }) {
                if (ModSettings.Instance?.RandomizeStartingEquipment ?? false) {
                    List<ItemObject> items  = new();
                    ItemObject[]?    items1 = { };
                    if (equipmentElement.Item.Culture is CultureObject cultureObject)
                        items1 = Cache.GetItemsByTypeTierAndCulture(equipmentElement.Item.ItemType,
                                                                    (int)equipmentElement.Item.Tier,
                                                                    cultureObject);
                    var items2 =
                        Cache.GetItemsByTypeTierAndCulture(equipmentElement.Item.ItemType,
                                                           character.Tier,
                                                           character.Culture);
                    if (items1 != null) items.AddRange(items1);
                    if (items2 != null) items.AddRange(items2);
                    items.Add(equipmentElement.Item);
                    items = items.Distinct().ToList();
                    equipmentElements.Add(new EquipmentElement(WeightedRandomSelector.SelectItem(items,
                                                                                                 equipmentElement.Item.Effectiveness)));
                }
                else { equipmentElements.Add(equipmentElement); }
            }
        }
        foreach (var slot in new[] { EquipmentIndex.Horse, EquipmentIndex.HorseHarness }) {
            var equipmentElement = armorAndHorse.GetEquipmentFromSlot(slot);
            if (equipmentElement is { IsEmpty: false, Item: not null }) equipmentElements.Add(equipmentElement);
        }
        foreach (var equipment in character.BattleEquipments)
            if (!equipment.IsEmpty())
                foreach (var slot in Assignment.WeaponSlots) {
                    var item = equipment.GetEquipmentFromSlot(slot);
                    if (item is not { IsEmpty: false, Item: not null } || !item.Item.HasWeaponComponent) continue;
                    if (item.Item.IsConsumable())
                        equipmentElements.Add(item); // 直接添加消耗品类型武器
                    else
                        weaponList.Add(item); // 非消耗品类型武器添加到列表
                }
        weaponList.Shuffle();
        var newWeapons                       = weaponList.Except(weaponSet);
        foreach (var weapon in newWeapons) _ = weaponSet.Add(weapon);
        equipmentElements.AddRange(weaponSet);
        return equipmentElements;
    }
References DynamicTroopEquipmentReupload.Global.ArmourSlots, DynamicTroopEquipmentReupload.Cache.GetItemsByTypeTierAndCulture(), DynamicTroopEquipmentReupload.ModSettings.RandomizeStartingEquipment, DynamicTroopEquipmentReupload.WeightedRandomSelector.SelectItem(), and DynamicTroopEquipmentReupload.Assignment.WeaponSlots.
Referenced by DynamicTroopEquipmentReupload.Extensions.MobilePartyExtension.GetItems(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnTroopRecruited(), DynamicTroopEquipmentReupload.Patches.BuyMercenariesPatch.Prefix(), and Prefix().
Prefix()
static void DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.Prefix (RecruitmentVM __instance) static
Definition at line 15 of file RecruitmentPatch.cs.
{
        foreach (var troop in __instance.TroopsInCart)
            // 在这里实现将士兵基础装备添加到军火库的逻辑
            if (!troop.IsTroopEmpty && troop.Character != null) {
                Global.Log($"recruiting {troop.Character.StringId}", Colors.Green, Level.Debug);
                var equipments = GetRecruitEquipments(troop.Character);
                Global.Debug($"{equipments.Count} starting equipments added");
                foreach (var equipment in equipments)
                    if (equipment is { IsEmpty: false, Item: not null })
                        ArmyArmory.AddItemToArmory(equipment.Item);
            }
    }
References DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory(), DynamicTroopEquipmentReupload.Global.Debug(), GetRecruitEquipments(), and DynamicTroopEquipmentReupload.Global.Log().
The documentation for this class was generated from the following file:
Patches/RecruitmentPatch.cs