动态装备系统: DynamicTroopEquipmentReupload.Helper Class Reference
DynamicTroopEquipmentReupload.Helper Class Reference
Static Public Member Functions
static ItemObject.? ItemTypeEnum EquipmentIndexToItemEnumType (EquipmentIndex index)
static int GetArmorValueForBodyPart (ArmorComponent armorComponent, BoneBodyPartType bodyPart)
static ? EquipmentIndex ItemEnumTypeToEquipmentIndex (ItemObject.ItemTypeEnum itemType)
Detailed Description
Definition at line 6 of file Helper.cs.
Member Function Documentation
EquipmentIndexToItemEnumType()
static ItemObject.? ItemTypeEnum DynamicTroopEquipmentReupload.Helper.EquipmentIndexToItemEnumType (EquipmentIndex index) static
Definition at line 20 of file Helper.cs.
{
        return index switch {
                   EquipmentIndex.Head         => ItemObject.ItemTypeEnum.HeadArmor,
                   EquipmentIndex.Gloves       => ItemObject.ItemTypeEnum.HandArmor,
                   EquipmentIndex.Body         => ItemObject.ItemTypeEnum.BodyArmor,
                   EquipmentIndex.Leg          => ItemObject.ItemTypeEnum.LegArmor,
                   EquipmentIndex.Cape         => ItemObject.ItemTypeEnum.Cape,
                   EquipmentIndex.Horse        => ItemObject.ItemTypeEnum.Horse,
                   EquipmentIndex.HorseHarness => ItemObject.ItemTypeEnum.HorseHarness,
                   _                           => null
               };
    }
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ApplyEmergencyLoadout(), and DynamicTroopEquipmentReupload.Assignment.FillEmptySlots().
GetArmorValueForBodyPart()
static int DynamicTroopEquipmentReupload.Helper.GetArmorValueForBodyPart (ArmorComponent armorComponent, BoneBodyPartType bodyPart) static
Definition at line 33 of file Helper.cs.
{
        return bodyPart switch {
                   BoneBodyPartType.Head          => armorComponent.HeadArmor,
                   BoneBodyPartType.Neck          => armorComponent.HeadArmor,
                   BoneBodyPartType.Chest         => armorComponent.BodyArmor,
                   BoneBodyPartType.Abdomen       => armorComponent.BodyArmor,
                   BoneBodyPartType.ShoulderLeft  => armorComponent.BodyArmor,
                   BoneBodyPartType.ShoulderRight => armorComponent.BodyArmor,
                   BoneBodyPartType.ArmLeft       => armorComponent.ArmArmor,
                   BoneBodyPartType.ArmRight      => armorComponent.ArmArmor,
                   BoneBodyPartType.Legs          => armorComponent.LegArmor,
                   _                              => 0
               };
    }
Referenced by DynamicTroopEquipmentReupload.ArmorSelector.GetRandomArmorByBodyPart().
ItemEnumTypeToEquipmentIndex()
static ? EquipmentIndex DynamicTroopEquipmentReupload.Helper.ItemEnumTypeToEquipmentIndex (ItemObject.ItemTypeEnum itemType) static
Definition at line 7 of file Helper.cs.
{
        return itemType switch {
                   ItemObject.ItemTypeEnum.HeadArmor    => EquipmentIndex.Head,
                   ItemObject.ItemTypeEnum.HandArmor    => EquipmentIndex.Gloves,
                   ItemObject.ItemTypeEnum.BodyArmor    => EquipmentIndex.Body,
                   ItemObject.ItemTypeEnum.LegArmor     => EquipmentIndex.Leg,
                   ItemObject.ItemTypeEnum.Cape         => EquipmentIndex.Cape,
                   ItemObject.ItemTypeEnum.Horse        => EquipmentIndex.Horse,
                   ItemObject.ItemTypeEnum.HorseHarness => EquipmentIndex.HorseHarness,
                   _                                    => null
               };
    }
The documentation for this class was generated from the following file:
Helper.cs