动态装备系统: DynamicTroopEquipmentReupload.ArmyArmory Class Reference
DynamicTroopEquipmentReupload.ArmyArmory Class Reference
Static Public Member Functions
static void AddItemToArmory (ItemObject item, int count=1)
static void AssignEquipment (Equipment equipment)
static void DebugClearEmptyItem ()
static void DebugRemovePlayerCraftedItems ()
static void Export ()
static void Import ()
static void RebuildArmory ()
static void ReturnEquipmentToArmoryFromAgents (IEnumerable< Agent > agents)
static void SellExcessEquipmentForThrowingWeapons ()
Static Public Attributes
static ItemRoster Armory = new()
Static Private Member Functions
static int SellExcessEquipment ()
Static Private Attributes
static ? ItemObject[] _cachedArrows
static ? ItemObject[] _cachedBolts
static ? ItemObject[] _cachedThrownWeapons
Detailed Description
Definition at line 25 of file ArmyArmory.cs.
Member Function Documentation
AddItemToArmory()
static void DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory (ItemObject item, int count = 1) static
Definition at line 33 of file ArmyArmory.cs.
{
        if (!ItemBlackList.Test(item)) return;
        _ = Armory.AddToCounts(item, count);
    }
References Armory, and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by DynamicTroopEquipmentReupload.Patches.BuyMercenariesPatch.Prefix(), DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.Prefix(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnEquipmentFromAgents(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnItemsToDestination(), and SellExcessEquipmentForThrowingWeapons().
AssignEquipment()
static void DynamicTroopEquipmentReupload.ArmyArmory.AssignEquipment (Equipment equipment) static
Definition at line 58 of file ArmyArmory.cs.
{
        foreach (var slot in Global.EquipmentSlots) {
            if ((Mission.Current?.HasMissionBehavior<HideoutMissionController>() == true ||
                 Mission.Current?.HasMissionBehavior<MissionSiegeEnginesLogic>() == true) &&
                (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness))
                continue;
            var element = equipment.GetEquipmentFromSlot(slot);
            // 使用模式匹配来检查条件，并反转if语句来减少嵌套
            if (element.IsEmpty || element.Item is null) continue;
            var itemToAssign =
                Armory.FirstOrDefaultQ(a => !a.IsEmpty                                                &&
                                            a.EquipmentElement.Item.StringId == element.Item.StringId &&
                                            a.Amount                         > 0);
            if (!itemToAssign.IsEmpty)
                _ = Armory.AddToCounts(itemToAssign.EquipmentElement, -1);
            else
                Global.Log($"Assigning Empty item {element.Item.StringId}", Colors.Red, Level.Warn);
        }
    }
References Armory, DynamicTroopEquipmentReupload.Global.EquipmentSlots, and DynamicTroopEquipmentReupload.Global.Log().
Referenced by DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix().
DebugClearEmptyItem()
static void DynamicTroopEquipmentReupload.ArmyArmory.DebugClearEmptyItem () static
Definition at line 306 of file ArmyArmory.cs.
{
        var toRemove = Armory
                       .WhereQ(kv => kv is not {
                                                   IsEmpty         : false,
                                                   EquipmentElement: { IsEmpty: false, Item: not null },
                                                   Amount          : > 0
                                               }                                                          ||
                                     kv.EquipmentElement.Item.ItemType == ItemObject.ItemTypeEnum.Invalid ||
                                     kv.EquipmentElement.Item.StringId == null                            ||
                                     kv.EquipmentElement.Item.StringId.IsEmpty())
                       .ToArrayQ();
        if (toRemove == null) return;
        foreach (var item in toRemove) Armory.Remove(item);
        Global.Debug($"Removed {toRemove.Length} empty entries from player's armory");
    }
References Armory, and DynamicTroopEquipmentReupload.Global.Debug().
DebugRemovePlayerCraftedItems()
static void DynamicTroopEquipmentReupload.ArmyArmory.DebugRemovePlayerCraftedItems () static
Definition at line 339 of file ArmyArmory.cs.
{
        var toRemove = Armory
                       .WhereQ(kv => kv is not {
                                                   IsEmpty         : false,
                                                   EquipmentElement: { IsEmpty: false, Item.IsCraftedByPlayer: true }
                                               })
                       .ToArrayQ();
        if (toRemove == null) return;
        foreach (var item in toRemove) Armory.Remove(item);
        Global.Debug($"Removed {toRemove.Length} player crafted entries from player's armory");
    }
References Armory, and DynamicTroopEquipmentReupload.Global.Debug().
Export()
static void DynamicTroopEquipmentReupload.ArmyArmory.Export () static
Definition at line 375 of file ArmyArmory.cs.
{
        try {
            Dictionary<string, int> dict = new();
            foreach (var rosterElement in Armory) {
                var stringId = rosterElement.EquipmentElement.Item?.StringId;
                var cnt      = rosterElement.Amount;
                if (stringId == null || cnt <= 0) continue;
                if (dict.ContainsKey(stringId)) { dict[stringId] += cnt; }
                else { dict.Add(stringId, cnt); }
            }
            // 使用 Newtonsoft.Json 的 JsonSerializer 进行序列化
            var json = JsonConvert.SerializeObject(dict, Formatting.Indented);
            // 写入到 armory.json 文件
            var filename = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "../../armory.json");
            File.WriteAllText(filename, json);
            Global.Debug($"Successfully export armory to {filename}");
        }
        catch (Exception e) { Global.Error(e.Message); }
    }
References Armory, DynamicTroopEquipmentReupload.Global.Debug(), and DynamicTroopEquipmentReupload.Global.Error().
Import()
static void DynamicTroopEquipmentReupload.ArmyArmory.Import () static
Definition at line 353 of file ArmyArmory.cs.
{
        try {
            // 获取 armory.json 文件的完整路径
            var filePath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "../../armory.json");
            // 读取文件内容
            var json = File.ReadAllText(filePath);
            // 使用 Newtonsoft.Json 的 JsonSerializer 进行反序列化
            var dict = JsonConvert.DeserializeObject<Dictionary<string, int>>(json);
            Armory.Clear();
            foreach (var kpv in dict) {
                var item = MBObjectManager.Instance.GetObject<ItemObject>(kpv.Key);
                if (item != null) { _ = Armory.AddToCounts(item, kpv.Value); }
                else { Global.Warn($"cannot get object {kpv.Key}"); }
            }
            Global.Debug($"Successfully export armory from {filePath}");
        }
        catch (Exception e) { Global.Error(e.Message); }
    }
References Armory, DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Global.Error(), and DynamicTroopEquipmentReupload.Global.Warn().
RebuildArmory()
static void DynamicTroopEquipmentReupload.ArmyArmory.RebuildArmory () static
Definition at line 324 of file ArmyArmory.cs.
{
        var toAdd = Armory
                    .WhereQ(kv => kv is {
                                            IsEmpty         : false,
                                            EquipmentElement: { IsEmpty: false, Item: not null },
                                            Amount          : > 0
                                        })
                    .ToArrayQ();
        Armory = new ItemRoster();
        if (toAdd == null) return;
        Armory.Add(toAdd);
        Global.Debug($"Armory has been rebuilt with {toAdd.Length} entries");
    }
References Armory, and DynamicTroopEquipmentReupload.Global.Debug().
Referenced by SellExcessEquipment().
ReturnEquipmentToArmoryFromAgents()
static void DynamicTroopEquipmentReupload.ArmyArmory.ReturnEquipmentToArmoryFromAgents (IEnumerable< Agent > agents) static
Definition at line 38 of file ArmyArmory.cs.
{
        Global.Log("ReturnEquipmentToArmoryFromAgents", Colors.Green, Level.Debug);
        var count = 0;
        foreach (var agent in agents)
            if (agent.IsValid()) {
                Global.Log($"Returning equipment of agent {agent.Character.StringId}", Colors.Green, Level.Debug);
                Global.ProcessAgentEquipment(agent,
                                             item => {
                                                 _ = Armory.AddToCounts(item, 1);
                                                 Global.Log($"equipment {item.StringId} returned",
                                                            Colors.Green,
                                                            Level.Debug);
                                                 count++;
                                             });
            }
        Global.Log($"{count} equipment reclaimed", Colors.Green, Level.Debug);
    }
References Armory, DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.Global.ProcessAgentEquipment().
SellExcessEquipment()
static int DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipment () static private
Definition at line 263 of file ArmyArmory.cs.
{
        RebuildArmory();
        var excessValue = 0;
        var playerParty = MobileParty.MainParty;
        if (playerParty?.MemberRoster?.GetTroopRoster() == null) return 0;
        var memberCnt = playerParty.MemberRoster.GetTroopRoster()
                                   .WhereQ(element => element.Character is { IsHero: false })
                                   .SumQ(element => element.Number);
        foreach (var equipmentAndThreshold in EveryoneCampaignBehavior.EquipmentAndThresholds) {
            var armorTotalCount = Armory.WhereQ(kv => kv.EquipmentElement.Item?.ItemType == equipmentAndThreshold.Key)
                                        .SumQ(kv => kv.Amount);
            var surplusCount = armorTotalCount - equipmentAndThreshold.Value(memberCnt);
            if (surplusCount <= 0) continue;
            var surplusCountCpy = surplusCount;
            // 创建优先级队列
            ItemPriorityQueue armorQueue = new(new ArmorElementComparer());
            foreach (var kv in Armory.WhereQ(kv => kv.EquipmentElement.Item?.ItemType == equipmentAndThreshold.Key))
                armorQueue.Enqueue(kv.EquipmentElement, kv.EquipmentElement.ItemValue);
            // 移除多余的装备
            while (surplusCount > 0 && !armorQueue.IsEmpty) {
                var lowestArmor = armorQueue.Dequeue();
                var countToRemove = Math.Min(Armory.GetElementNumber(Armory.FindIndexOfElement(lowestArmor.Key)),
                                             surplusCount);
                //Global.Debug($"countToRemove={countToRemove}, lowestArmorNumber={Armory.GetItemNumber(lowestArmor.Key)}");
                _            =  Armory.AddToCounts(lowestArmor.Key, -countToRemove); // 减少数量
                surplusCount -= countToRemove;
                excessValue  += countToRemove * lowestArmor.Key.ItemValue;
                Global.Debug($"Sold {countToRemove}x{lowestArmor.Key.ItemValue} from player's armory");
            }
            Global.Debug($"Sold {surplusCountCpy - surplusCount}x{equipmentAndThreshold.Key} items from player's armory");
        }
        Global.Debug($"Sold {excessValue} denars worth of equipment from player's armory");
        return excessValue;
    }
References Armory, DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.EquipmentAndThresholds, and RebuildArmory().
Referenced by SellExcessEquipmentForThrowingWeapons().
SellExcessEquipmentForThrowingWeapons()
static void DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipmentForThrowingWeapons () static
Definition at line 81 of file ArmyArmory.cs.
{
        var soldValue = SellExcessEquipment();
        if (soldValue <= 0)
        {
            MessageDisplayService.EnqueueMessage(new InformationMessage(
                LocalizedTexts.GetSoldExcessEquipmentForThrowingWeapons(0, 0, 0),
                Colors.Green));
            return;
        }
        _cachedThrownWeapons ??= MBObjectManager.Instance
            .GetObjectTypeList<ItemObject>()
            ?.WhereQ(item => item.IsThrowingWeaponCanBeAcquired())
            .ToArrayQ() ?? Array.Empty<ItemObject>();
        _cachedArrows ??= MBObjectManager.Instance
            .GetObjectTypeList<ItemObject>()
            ?.WhereQ(item => item.IsArrow() && item.Value > 0)
            .ToArrayQ() ?? Array.Empty<ItemObject>();
        _cachedBolts ??= MBObjectManager.Instance
            .GetObjectTypeList<ItemObject>()
            ?.WhereQ(item => item.IsBolt() && item.Value > 0)
            .ToArrayQ() ?? Array.Empty<ItemObject>();
        var playerParty = MobileParty.MainParty;
        var troopRoster = playerParty?.MemberRoster?.GetTroopRoster();
        if (troopRoster == null) return;
        // (cavalry + infantry) = X, (horse archer + archers) = Y, X+Y=100
        var infantryAndCavalryCount = 0;
        var archerAndHorseArcherCount = 0;
        // split
        var bowUserCount = 0;
        var crossbowUserCount = 0;
        // weighting for type of ranged ammo / throwing weapon
        var preferredThrowingWeights = new Dictionary<ItemObject, int>();
        var preferredArrowWeights = new Dictionary<ItemObject, int>();
        var preferredBoltWeights = new Dictionary<ItemObject, int>();
        foreach (var troop in troopRoster)
        {
            if (troop.Character is not { IsHero: false } character) continue;
            var troopCount = troop.Number;
            if (troopCount <= 0) continue;
            var isRanged = character.IsRanged;
            if (isRanged)
                archerAndHorseArcherCount += troopCount;
            else
                infantryAndCavalryCount += troopCount;
            var referenceEquipment = character.RandomBattleEquipment;
            var usesBow = false;
            var usesCrossbow = false;
            ItemObject? preferredThrowing = null;
            ItemObject? preferredArrows = null;
            ItemObject? preferredBolts = null;
            foreach (var slot in Assignment.WeaponSlots)
            {
                var equipmentElement = referenceEquipment.GetEquipmentFromSlot(slot);
                if (equipmentElement is not { IsEmpty: false, Item: { } item }) continue;
                if (!usesBow && item.IsBow())
                    usesBow = true;
                if (!usesCrossbow && item.IsCrossBow())
                    usesCrossbow = true;
                if (preferredThrowing == null && item.IsThrowingWeaponCanBeAcquired())
                    preferredThrowing = item;
                if (preferredArrows == null && item.IsArrow())
                    preferredArrows = item;
                if (preferredBolts == null && item.IsBolt())
                    preferredBolts = item;
            }
            if (isRanged)
            {
                if (usesCrossbow)
                {
                    crossbowUserCount += troopCount;
                    if (preferredBolts != null)
                        preferredBoltWeights[preferredBolts] = preferredBoltWeights.TryGetValue(preferredBolts, out var count)
                            ? count + troopCount
                            : troopCount;
                }
                else if (usesBow)
                {
                    bowUserCount += troopCount;
                    if (preferredArrows != null)
                        preferredArrowWeights[preferredArrows] = preferredArrowWeights.TryGetValue(preferredArrows, out var count)
                            ? count + troopCount
                            : troopCount;
                }
            }
            else if (preferredThrowing != null)
            {
                preferredThrowingWeights[preferredThrowing] = preferredThrowingWeights.TryGetValue(preferredThrowing, out var count)
                    ? count + troopCount
                    : troopCount;
            }
        }
        static ItemObject? GetWeightedRandomItem(Dictionary<ItemObject, int> weightByItem) {
            if (weightByItem.Count == 0) return null;
            var totalWeight = 0;
            foreach (var kv in weightByItem)
                totalWeight += kv.Value;
            if (totalWeight <= 0) return null;
            var roll = MBRandom.RandomInt(totalWeight);
            foreach (var kv in weightByItem)
            {
                roll -= kv.Value;
                if (roll < 0)
                    return kv.Key;
            }
            return null;
        }
        var totalTroopCount = infantryAndCavalryCount + archerAndHorseArcherCount;
        var throwingBudget = totalTroopCount > 0
            ? (int)Math.Round(soldValue * (double)infantryAndCavalryCount / totalTroopCount)
            : soldValue;
        var ammoBudget = soldValue - throwingBudget;
        var totalRangedWeaponUsers = bowUserCount + crossbowUserCount;
        var arrowBudget = totalRangedWeaponUsers > 0
            ? (int)Math.Round(ammoBudget * (double)bowUserCount / totalRangedWeaponUsers)
            : ammoBudget;
        var boltBudget = ammoBudget - arrowBudget;
        var throwingCount = 0;
        var ammoCount = 0;
        var remainingThrowingBudget = throwingBudget;
        while (remainingThrowingBudget > 0)
        {
            var item = GetWeightedRandomItem(preferredThrowingWeights) ?? _cachedThrownWeapons.GetRandomElement();
            if (item == null) break;
            AddItemToArmory(item);
            remainingThrowingBudget -= item.Value;
            throwingCount++;
        }
        var remainingArrowBudget = arrowBudget;
        while (remainingArrowBudget > 0)
        {
            var item = GetWeightedRandomItem(preferredArrowWeights) ?? _cachedArrows.GetRandomElement();
            if (item == null) break;
            AddItemToArmory(item);
            remainingArrowBudget -= item.Value;
            ammoCount++;
        }
        var remainingBoltBudget = boltBudget;
        while (remainingBoltBudget > 0)
        {
            var item = GetWeightedRandomItem(preferredBoltWeights) ?? _cachedBolts.GetRandomElement();
            if (item == null) break;
            AddItemToArmory(item);
            remainingBoltBudget -= item.Value;
            ammoCount++;
        }
        MessageDisplayService.EnqueueMessage(new InformationMessage(
            LocalizedTexts.GetSoldExcessEquipmentForThrowingWeapons(soldValue, throwingCount, ammoCount),
            Colors.Green));
    }
References _cachedArrows, _cachedBolts, _cachedThrownWeapons, AddItemToArmory(), MessageDisplayService.EnqueueMessage(), DynamicTroopEquipmentReupload.LocalizedTexts.GetSoldExcessEquipmentForThrowingWeapons(), SellExcessEquipment(), and DynamicTroopEquipmentReupload.Assignment.WeaponSlots.
Member Data Documentation
_cachedArrows
? ItemObject [] DynamicTroopEquipmentReupload.ArmyArmory._cachedArrows static private
Definition at line 29 of file ArmyArmory.cs.
Referenced by SellExcessEquipmentForThrowingWeapons().
_cachedBolts
? ItemObject [] DynamicTroopEquipmentReupload.ArmyArmory._cachedBolts static private
Definition at line 31 of file ArmyArmory.cs.
Referenced by SellExcessEquipmentForThrowingWeapons().
_cachedThrownWeapons
? ItemObject [] DynamicTroopEquipmentReupload.ArmyArmory._cachedThrownWeapons static private
Definition at line 28 of file ArmyArmory.cs.
Referenced by SellExcessEquipmentForThrowingWeapons().
Armory
ItemRoster DynamicTroopEquipmentReupload.ArmyArmory.Armory = new() static
Definition at line 26 of file ArmyArmory.cs.
Referenced by AddItemToArmory(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.ApplyCapturedArmoryLoss(), AssignEquipment(), DebugClearEmptyItem(), DebugRemovePlayerCraftedItems(), Export(), Import(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.Load(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnNewGameCreated(), DynamicTroopEquipmentReupload.Patches.InventoryLogic_TransferItem_CommandersGreedPatch.Prefix(), RebuildArmory(), ReturnEquipmentToArmoryFromAgents(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.Save(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.ScrapArmyArmoryByCategory(), SellExcessEquipment(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.SyncData(), and DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.TryInitializeDistributors().
The documentation for this class was generated from the following file:
ArmyArmory.cs