动态装备系统: DynamicTroopEquipmentReupload.CutTheirSupplyBehavior Class Reference
DynamicTroopEquipmentReupload.CutTheirSupplyBehavior Class Reference sealed
Classes
class Data
Public Member Functions
override void RegisterEvents ()
override void SyncData (IDataStore dataStore)
Static Public Member Functions
static bool IsReinforcementCaravanParty (MobileParty? mobileParty)
Private Member Functions
void CleanupCaravan (MobileParty caravanParty)
void OnDailyTickTown (Town town)
void OnMobilePartyDestroyed (MobileParty mobileParty, PartyBase destroyerParty)
void OnTick (float dt)
void SpawnReinforcementCaravan (Town sourceTown, Clan ownerClan, MobileParty targetParty)
Static Private Member Functions
static void AddExtraCultureTroops (MobileParty caravanParty, BasicCultureObject culture, int count)
static void AddRandomGearItems (List< ItemObject > results, BasicCultureObject culture, int tier, int cap, float chance)
static void AddReinforcementSupplies (MobileParty caravanParty)
static ? Clan FindClanById (MBGUID clanId)
static ? MobileParty FindMobilePartyById (MBGUID partyId)
static ? Settlement FindSettlementById (MBGUID settlementId)
static ? MobileParty FindTargetLordParty (Clan clan)
static ? MobileParty FindTargetLordParty (Clan clan, MBGUID excludedPartyId)
static float GetDailySpawnChance (float prosperity)
static List< ItemObject > GetRandomGearItems (BasicCultureObject culture)
static CampaignVec2 GetWaitPointNear (MobileParty caravanParty, MobileParty movementTargetParty)
static bool HasArrived (MobileParty caravan, MobileParty target)
static bool ReinforcementCaravanBuyProductsDisabledOnClickableCondition (out TextObject explanation)
static bool ReinforcementCaravanBuyProductsDisabledOnCondition ()
static void RemoveMobileParty (MobileParty mobileParty)
static void TransferCargoToTargetStash (MobileParty caravanParty, MobileParty targetParty)
static bool TryRunAwayFromNearbyThreat (MobileParty caravanParty)
Private Attributes
readonly Dictionary< MBGUID, MBGUID > _activeCaravanBySourceSettlementId = new()
Data _data = new()
float _escortRefreshTimer
readonly Dictionary< MBGUID, MBGUID > _ownerClanByCaravanId = new()
readonly HashSet< MBGUID > _returningCaravanIds = new()
readonly Dictionary< MBGUID, MBGUID > _sourceSettlementByCaravanId = new()
readonly Dictionary< MBGUID, MBGUID > _targetByCaravanId = new()
Static Private Attributes
const float ARRIVAL_DISTANCE_SQUARED = 4f
const float BASE_CHANCE_AT_MIN_PROSPERITY = 0.01f
const float CHANCE_PER_PROSPERITY_POINT = 0.000001f
const float ESCORT_REFRESH_SECONDS = 0.25f
const int EXTRA_TROOP_COUNT = 25
const float FLEE_IF_ENEMY_STRENGTH_MULTIPLIER = 1.20f
const float FLEE_POINT_DISTANCE = 8f
const int FOOD_PER_TYPE_COUNT = 17
const int GEAR_COUNT = 26
const int GEAR_TIER_1_CAP = 4
const float GEAR_TIER_1_CHANCE = 0.85f
const int GEAR_TIER_2_CAP = 5
const float GEAR_TIER_2_CHANCE = 0.75f
const int GEAR_TIER_3_CAP = 8
const float GEAR_TIER_3_CHANCE = 0.55f
const int GEAR_TIER_4_CAP = 4
const float GEAR_TIER_4_CHANCE = 0.45f
const int GEAR_TIER_5_CAP = 2
const float GEAR_TIER_5_CHANCE = 0.35f
const int GEAR_TIER_6_CAP = 1
const float GEAR_TIER_6_CHANCE = 0.25f
const float MAX_DAILY_CHANCE = 0.125f
const float MIN_PROSPERITY = 2000f
static readonly HashSet< MBGUID > ReinforcementCaravanIds = new()
static readonly? MethodInfo RemovePartyMethod
const int SUMPTER_HORSE_COUNT = 17
const string SUMPTER_HORSE_ITEM_ID = "sumpter_horse"
const int TARGET_PARTY_SIZE = 100
const float THREAT_SCAN_RADIUS = 10f
const float THREAT_SCAN_RADIUS_SQUARED = THREAT_SCAN_RADIUS * THREAT_SCAN_RADIUS
const float WAIT_DISTANCE = 2f
const float WAIT_DISTANCE_SQUARED = WAIT_DISTANCE * WAIT_DISTANCE
Detailed Description
Definition at line 23 of file CutTheirSupplyBehavior.cs.
Member Function Documentation
AddExtraCultureTroops()
static void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.AddExtraCultureTroops (MobileParty caravanParty, BasicCultureObject culture, int count) static private
Definition at line 499 of file CutTheirSupplyBehavior.cs.
{
        var cultureTroops = CharacterObject.All
                                           .Where(t =>
                                                      t != null && !t.IsHero && t.Culture == culture && t.Occupation == Occupation.Soldier && t.Tier >= 1 && t.Tier <= 6)
                                           .ToList();
        if (cultureTroops.Count == 0)
            return;
        var troopsByTier = cultureTroops
                           .GroupBy(t => t.Tier)
                           .ToDictionary(g => g.Key, g => g.ToList());
        for (var i = 0; i < count; i++) {
            var randomTier = MBRandom.RandomInt(1, 7); // 1..6
            if (!troopsByTier.TryGetValue(randomTier, out var tierPool) || tierPool.Count == 0)
                tierPool = cultureTroops;
            var troop = tierPool.GetRandomElement();
            caravanParty.MemberRoster.AddToCounts(troop, 1);
        }
    }
Referenced by SpawnReinforcementCaravan().
AddRandomGearItems()
static void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.AddRandomGearItems (List< ItemObject > results, BasicCultureObject culture, int tier, int cap, float chance) static private
Definition at line 607 of file CutTheirSupplyBehavior.cs.
{
        var tierCandidates = Cache.GetItemsByTierAndCulture(tier, culture)
                                  .Where(i => i != null && ItemBlackList.Test(i) && (int)i.Tier == tier)
                                  .ToList();
        if (tierCandidates.Count == 0) {
            tierCandidates = Cache.GetItemsByTierAndCulture(tier, culture)
                                  .Where(i => i != null && ItemBlackList.Test(i))
                                  .ToList();
        }
        if (tierCandidates.Count == 0) { return; }
        for (var attemptIndex = 0; attemptIndex < cap && results.Count < GEAR_COUNT; attemptIndex++) {
            if (MBRandom.RandomFloat > chance) {
                break; // stop upon fail
            }
            results.Add(tierCandidates.GetRandomElement());
        }
    }
References GEAR_COUNT, DynamicTroopEquipmentReupload.Cache.GetItemsByTierAndCulture(), and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by GetRandomGearItems().
AddReinforcementSupplies()
static void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.AddReinforcementSupplies (MobileParty caravanParty) static private
Definition at line 522 of file CutTheirSupplyBehavior.cs.
{
        var allItems = MBObjectManager.Instance.GetObjectTypeList<ItemObject>();
        foreach (var item in allItems) {
            if (item != null && item.IsFood) { caravanParty.ItemRoster.AddToCounts(item, FOOD_PER_TYPE_COUNT); }
        }
        var sumpterHorse = MBObjectManager.Instance.GetObject<ItemObject>(SUMPTER_HORSE_ITEM_ID);
        if (sumpterHorse != null) { caravanParty.ItemRoster.AddToCounts(sumpterHorse, SUMPTER_HORSE_COUNT); }
    }
References FOOD_PER_TYPE_COUNT, SUMPTER_HORSE_COUNT, and SUMPTER_HORSE_ITEM_ID.
Referenced by SpawnReinforcementCaravan().
CleanupCaravan()
void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.CleanupCaravan (MobileParty caravanParty) private
Definition at line 656 of file CutTheirSupplyBehavior.cs.
{
        ReinforcementCaravanIds.Remove(caravanParty.Id);
        _targetByCaravanId.Remove(caravanParty.Id);
        _returningCaravanIds.Remove(caravanParty.Id);
        if (_sourceSettlementByCaravanId.TryGetValue(caravanParty.Id, out var sourceSettlementId)) {
            _sourceSettlementByCaravanId.Remove(caravanParty.Id);
            if (_activeCaravanBySourceSettlementId.TryGetValue(sourceSettlementId, out var activeCaravanId) && activeCaravanId == caravanParty.Id) { _activeCaravanBySourceSettlementId.Remove(sourceSettlementId); }
        }
        _ownerClanByCaravanId.Remove(caravanParty.Id);
        RemoveMobileParty(caravanParty);
    }
References _activeCaravanBySourceSettlementId, _ownerClanByCaravanId, _returningCaravanIds, _sourceSettlementByCaravanId, _targetByCaravanId, ReinforcementCaravanIds, and RemoveMobileParty().
Referenced by OnTick().
FindClanById()
static ? Clan DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.FindClanById (MBGUID clanId) static private
Definition at line 382 of file CutTheirSupplyBehavior.cs.
{
        foreach (var clan in Campaign.Current.Clans) {
            if (clan.Id == clanId)
                return clan;
        }
        return null;
    }
Referenced by OnTick().
FindMobilePartyById()
static ? MobileParty DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.FindMobilePartyById (MBGUID partyId) static private
Definition at line 368 of file CutTheirSupplyBehavior.cs.
{
        var campaign = Campaign.Current;
        if (campaign == null)
            return null;
        foreach (var party in campaign.MobileParties) {
            if (party.Id == partyId)
                return party;
        }
        return null;
    }
Referenced by OnDailyTickTown(), and OnTick().
FindSettlementById()
static ? Settlement DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.FindSettlementById (MBGUID settlementId) static private
Definition at line 391 of file CutTheirSupplyBehavior.cs.
{
        foreach (var settlement in Settlement.All) {
            if (settlement.Id == settlementId)
                return settlement;
        }
        return null;
    }
Referenced by OnTick().
FindTargetLordParty() [1/2]
static ? MobileParty DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.FindTargetLordParty (Clan clan) static private
Definition at line 339 of file CutTheirSupplyBehavior.cs.
{
        MobileParty? bestParty    = null;
        var          bestDistance = int.MaxValue;
        foreach (var party in Campaign.Current.MobileParties) {
            if (party == null || !party.IsActive)
                continue;
            var leaderHero = party.LeaderHero;
            if (leaderHero == null || leaderHero.Clan != clan)
                continue;
            // lords
            if (party.IsCaravan || party.IsVillager || party.IsMilitia || party.IsBandit)
                continue;
            var partySize = party.MemberRoster.TotalManCount;
            var distance  = Math.Abs(partySize - TARGET_PARTY_SIZE);
            if (distance < bestDistance) {
                bestDistance = distance;
                bestParty    = party;
            }
        }
        return bestParty;
    }
References TARGET_PARTY_SIZE.
Referenced by OnDailyTickTown(), and OnTick().
FindTargetLordParty() [2/2]
static ? MobileParty DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.FindTargetLordParty (Clan clan, MBGUID excludedPartyId) static private
Definition at line 400 of file CutTheirSupplyBehavior.cs.
{
        MobileParty? bestParty    = null;
        var          bestDistance = int.MaxValue;
        foreach (var party in Campaign.Current.MobileParties) {
            if (party == null || !party.IsActive || party.Id == excludedPartyId)
                continue;
            var leaderHero = party.LeaderHero;
            if (leaderHero == null || leaderHero.Clan != clan)
                continue;
            if (party.IsCaravan || party.IsVillager || party.IsMilitia || party.IsBandit)
                continue;
            var partySize = party.MemberRoster.TotalManCount;
            var distance  = Math.Abs(partySize - TARGET_PARTY_SIZE);
            if (distance < bestDistance) {
                bestDistance = distance;
                bestParty    = party;
            }
        }
        return bestParty;
    }
References TARGET_PARTY_SIZE.
GetDailySpawnChance()
static float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GetDailySpawnChance (float prosperity) static private
Definition at line 333 of file CutTheirSupplyBehavior.cs.
{
        var extraProsperity = prosperity                    - MIN_PROSPERITY;
        var chance          = BASE_CHANCE_AT_MIN_PROSPERITY + extraProsperity * CHANCE_PER_PROSPERITY_POINT;
        return Math.Min(chance, MAX_DAILY_CHANCE);
    }
References BASE_CHANCE_AT_MIN_PROSPERITY, CHANCE_PER_PROSPERITY_POINT, MAX_DAILY_CHANCE, and MIN_PROSPERITY.
Referenced by OnDailyTickTown().
GetRandomGearItems()
static List< ItemObject > DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GetRandomGearItems (BasicCultureObject culture) static private
Definition at line 594 of file CutTheirSupplyBehavior.cs.
{
        var results = new List<ItemObject>(GEAR_COUNT);
        AddRandomGearItems(results, culture, 1, GEAR_TIER_1_CAP, GEAR_TIER_1_CHANCE);
        AddRandomGearItems(results, culture, 2, GEAR_TIER_2_CAP, GEAR_TIER_2_CHANCE);
        AddRandomGearItems(results, culture, 3, GEAR_TIER_3_CAP, GEAR_TIER_3_CHANCE);
        AddRandomGearItems(results, culture, 4, GEAR_TIER_4_CAP, GEAR_TIER_4_CHANCE);
        AddRandomGearItems(results, culture, 5, GEAR_TIER_5_CAP, GEAR_TIER_5_CHANCE);
        AddRandomGearItems(results, culture, 6, GEAR_TIER_6_CAP, GEAR_TIER_6_CHANCE);
        return results;
    }
References AddRandomGearItems(), GEAR_COUNT, GEAR_TIER_1_CAP, GEAR_TIER_1_CHANCE, GEAR_TIER_2_CAP, GEAR_TIER_2_CHANCE, GEAR_TIER_3_CAP, GEAR_TIER_3_CHANCE, GEAR_TIER_4_CAP, GEAR_TIER_4_CHANCE, GEAR_TIER_5_CAP, GEAR_TIER_5_CHANCE, GEAR_TIER_6_CAP, and GEAR_TIER_6_CHANCE.
Referenced by SpawnReinforcementCaravan().
GetWaitPointNear()
static CampaignVec2 DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GetWaitPointNear (MobileParty caravanParty, MobileParty movementTargetParty) static private
Definition at line 436 of file CutTheirSupplyBehavior.cs.
{
        var targetPos  = movementTargetParty.Position.ToVec2();
        var caravanPos = caravanParty.Position.ToVec2();
        var away = caravanPos - targetPos;
        if (away.LengthSquared < 0.0001f) { away = new Vec2(1f, 0f); }
        else { away                              = away.Normalized(); }
        var waitPos = targetPos + away * WAIT_DISTANCE;
        return new CampaignVec2(waitPos, movementTargetParty.Position.IsOnLand);
    }
References WAIT_DISTANCE.
Referenced by OnTick().
HasArrived()
static bool DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.HasArrived (MobileParty caravan, MobileParty target) static private
Definition at line 427 of file CutTheirSupplyBehavior.cs.
{
        if (caravan.CurrentSettlement != null && caravan.CurrentSettlement == target.CurrentSettlement)
            return true;
        var delta = caravan.GetPosition2D - target.GetPosition2D;
        return delta.LengthSquared <= ARRIVAL_DISTANCE_SQUARED;
    }
References ARRIVAL_DISTANCE_SQUARED.
Referenced by OnTick().
IsReinforcementCaravanParty()
static bool DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.IsReinforcementCaravanParty (MobileParty? mobileParty) static
Definition at line 90 of file CutTheirSupplyBehavior.cs.
{
        return mobileParty != null && ReinforcementCaravanIds.Contains(mobileParty.Id);
    }
References ReinforcementCaravanIds.
Referenced by DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.CaravanBuyProductsOnConditionPrefix(), DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.IsSurrenderFeasiblePrefix(), ReinforcementCaravanBuyProductsDisabledOnCondition(), and DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.ReinforcementTradeLineOnCondition().
OnDailyTickTown()
void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.OnDailyTickTown (Town town) private
Definition at line 156 of file CutTheirSupplyBehavior.cs.
{
        var ownerClan = town.OwnerClan;
        var sourceSettlement = town.Settlement;
        if (sourceSettlement == null)
            return;
        if (_activeCaravanBySourceSettlementId.TryGetValue(sourceSettlement.Id, out var existingCaravanId)) {
            var existingCaravan = FindMobilePartyById(existingCaravanId);
            if (existingCaravan != null && existingCaravan.IsActive)
                return;
            // Keep it clean
            _activeCaravanBySourceSettlementId.Remove(sourceSettlement.Id);
        }
        if (ownerClan == null || ownerClan == Clan.PlayerClan)
            return;
        var prosperity = town.Prosperity;
        if (prosperity < MIN_PROSPERITY)
            return;
        var chance = GetDailySpawnChance(prosperity);
        if (MBRandom.RandomFloat > chance)
            return;
        var targetParty = FindTargetLordParty(ownerClan);
        if (targetParty == null)
            return;
        SpawnReinforcementCaravan(town, ownerClan, targetParty);
    }
References _activeCaravanBySourceSettlementId, FindMobilePartyById(), FindTargetLordParty(), GetDailySpawnChance(), MIN_PROSPERITY, and SpawnReinforcementCaravan().
Referenced by RegisterEvents().
OnMobilePartyDestroyed()
void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.OnMobilePartyDestroyed (MobileParty mobileParty, PartyBase destroyerParty) private
Definition at line 318 of file CutTheirSupplyBehavior.cs.
{
        ReinforcementCaravanIds.Remove(mobileParty.Id);
        _targetByCaravanId.Remove(mobileParty.Id);
        _returningCaravanIds.Remove(mobileParty.Id);
        if (_sourceSettlementByCaravanId.TryGetValue(mobileParty.Id, out var sourceSettlementId)) {
            _sourceSettlementByCaravanId.Remove(mobileParty.Id);
            if (_activeCaravanBySourceSettlementId.TryGetValue(sourceSettlementId, out var activeCaravanId) && activeCaravanId == mobileParty.Id) { _activeCaravanBySourceSettlementId.Remove(sourceSettlementId); }
        }
        _ownerClanByCaravanId.Remove(mobileParty.Id);
    }
References _activeCaravanBySourceSettlementId, _ownerClanByCaravanId, _returningCaravanIds, _sourceSettlementByCaravanId, _targetByCaravanId, and ReinforcementCaravanIds.
Referenced by RegisterEvents().
OnTick()
void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.OnTick (float dt) private
Definition at line 195 of file CutTheirSupplyBehavior.cs.
{
        _escortRefreshTimer += dt;
        if (_escortRefreshTimer < ESCORT_REFRESH_SECONDS) { return; }
        _escortRefreshTimer = 0f;
        // take a snapshot to avoid modifying the dictionary during iteration
        foreach (var pair in _targetByCaravanId.ToList()) {
            var caravanParty = FindMobilePartyById(pair.Key);
            if (caravanParty == null || !caravanParty.IsActive) {
                _targetByCaravanId.Remove(pair.Key);
                ReinforcementCaravanIds.Remove(pair.Key);
                continue;
            }
            if (TryRunAwayFromNearbyThreat(caravanParty)) { continue; }
            var targetParty = FindMobilePartyById(pair.Value);
            // guarantee target
            if (targetParty == null || !targetParty.IsActive) {
                if (_ownerClanByCaravanId.TryGetValue(caravanParty.Id, out var ownerClanId)) {
                    var ownerClan = FindClanById(ownerClanId);
                    if (ownerClan != null) {
                        var newTarget = FindTargetLordParty(ownerClan, pair.Value);
                        if (newTarget != null) {
                            _targetByCaravanId[caravanParty.Id] = newTarget.Id;
                            targetParty                         = newTarget;
                        }
                        else { _returningCaravanIds.Add(caravanParty.Id); }
                    }
                    else { _returningCaravanIds.Add(caravanParty.Id); }
                }
                else { _returningCaravanIds.Add(caravanParty.Id); }
            }
            // return and despawn
            if (_returningCaravanIds.Contains(caravanParty.Id)) {
                if (_sourceSettlementByCaravanId.TryGetValue(caravanParty.Id, out var sourceSettlementId)) {
                    var sourceSettlement = FindSettlementById(sourceSettlementId);
                    if (sourceSettlement != null) {
                        // check twice
                        if (caravanParty.CurrentSettlement != null && caravanParty.CurrentSettlement != sourceSettlement) { LeaveSettlementAction.ApplyForParty(caravanParty); }
                        caravanParty.Ai.SetDoNotMakeNewDecisions(true);
                        caravanParty.SetMoveGoToSettlement(sourceSettlement, MobileParty.NavigationType.All, false);
                        caravanParty.RecalculateShortTermBehavior();
                        if (caravanParty.CurrentSettlement == sourceSettlement) { CleanupCaravan(caravanParty); }
                    }
                    else { CleanupCaravan(caravanParty); }
                }
                else { CleanupCaravan(caravanParty); }
                continue;
            }
            // when targetparty is ensured
            if (targetParty == null) {
                _returningCaravanIds.Add(caravanParty.Id);
                continue;
            }
            var stashReceiverParty = targetParty;
            var movementTargetParty = targetParty;
            if (movementTargetParty.Army != null && movementTargetParty.Army.LeaderParty != null) { movementTargetParty = movementTargetParty.Army.LeaderParty; }
            // if they're inside a settlement
            var targetSettlement = movementTargetParty.CurrentSettlement;
            if (targetSettlement != null) {
                if (caravanParty.CurrentSettlement != null && caravanParty.CurrentSettlement != targetSettlement) { LeaveSettlementAction.ApplyForParty(caravanParty); }
                caravanParty.Ai.SetDoNotMakeNewDecisions(true);
                caravanParty.SetMoveGoToSettlement(targetSettlement, MobileParty.NavigationType.All, false);
                caravanParty.RecalculateShortTermBehavior();
                if (caravanParty.CurrentSettlement == targetSettlement) {
                    TransferCargoToTargetStash(caravanParty, stashReceiverParty);
                    CleanupCaravan(caravanParty);
                }
                continue;
            }
            // for sieges/battles, keep the distance
            if (movementTargetParty.MapEvent != null || movementTargetParty.SiegeEvent != null) {
                if (caravanParty.CurrentSettlement != null) { LeaveSettlementAction.ApplyForParty(caravanParty); }
                caravanParty.Ai.SetDoNotMakeNewDecisions(true);
                var delta = caravanParty.GetPosition2D - movementTargetParty.GetPosition2D;
                if (delta.LengthSquared <= WAIT_DISTANCE_SQUARED) { caravanParty.SetMoveModeHold(); }
                else {
                    var waitPoint = GetWaitPointNear(caravanParty, movementTargetParty);
                    caravanParty.SetMoveGoToPoint(waitPoint, MobileParty.NavigationType.Default);
                }
                caravanParty.RecalculateShortTermBehavior();
                continue;
            }
            // regularly
            if (caravanParty.CurrentSettlement != null) { LeaveSettlementAction.ApplyForParty(caravanParty); }
            caravanParty.Ai.SetDoNotMakeNewDecisions(true);
            var destination = new CampaignVec2(movementTargetParty.Position.ToVec2(), movementTargetParty.Position.IsOnLand);
            caravanParty.SetMoveGoToPoint(destination, MobileParty.NavigationType.Default);
            caravanParty.RecalculateShortTermBehavior();
            if (HasArrived(caravanParty, movementTargetParty)) {
                TransferCargoToTargetStash(caravanParty, stashReceiverParty);
                CleanupCaravan(caravanParty);
            }
        }
    }
References _escortRefreshTimer, _ownerClanByCaravanId, _returningCaravanIds, _sourceSettlementByCaravanId, _targetByCaravanId, CleanupCaravan(), ESCORT_REFRESH_SECONDS, FindClanById(), FindMobilePartyById(), FindSettlementById(), FindTargetLordParty(), GetWaitPointNear(), HasArrived(), ReinforcementCaravanIds, TransferCargoToTargetStash(), TryRunAwayFromNearbyThreat(), and WAIT_DISTANCE_SQUARED.
Referenced by RegisterEvents().
RegisterEvents()
override void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.RegisterEvents ()
Definition at line 94 of file CutTheirSupplyBehavior.cs.
{
        CampaignEvents.DailyTickTownEvent.AddNonSerializedListener(this, OnDailyTickTown);
        CampaignEvents.TickEvent.AddNonSerializedListener(this, OnTick);
        CampaignEvents.MobilePartyDestroyed.AddNonSerializedListener(this, OnMobilePartyDestroyed);
    }
References OnDailyTickTown(), OnMobilePartyDestroyed(), and OnTick().
ReinforcementCaravanBuyProductsDisabledOnClickableCondition()
static bool DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.ReinforcementCaravanBuyProductsDisabledOnClickableCondition (out TextObject explanation) static private
Definition at line 150 of file CutTheirSupplyBehavior.cs.
{
        explanation = LocalizedTexts.ReinforcementCaravanTradeDisabled;
        return false;
    }
References DynamicTroopEquipmentReupload.LocalizedTexts.ReinforcementCaravanTradeDisabled.
ReinforcementCaravanBuyProductsDisabledOnCondition()
static bool DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.ReinforcementCaravanBuyProductsDisabledOnCondition () static private
Definition at line 146 of file CutTheirSupplyBehavior.cs.
{
        return IsReinforcementCaravanParty(MobileParty.ConversationParty);
    }
References IsReinforcementCaravanParty().
RemoveMobileParty()
static void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.RemoveMobileParty (MobileParty mobileParty) static private
Definition at line 672 of file CutTheirSupplyBehavior.cs.
{
        if (RemovePartyMethod != null) {
            RemovePartyMethod.Invoke(mobileParty, null);
            return;
        }
        DestroyPartyAction.Apply(null, mobileParty);
    }
References RemovePartyMethod.
Referenced by CleanupCaravan().
SpawnReinforcementCaravan()
void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.SpawnReinforcementCaravan (Town sourceTown, Clan ownerClan, MobileParty targetParty) private
Definition at line 534 of file CutTheirSupplyBehavior.cs.
{
        var caravanOwner = ownerClan.Leader;
        if (caravanOwner == null)
            return;
        var spawnSettlement = sourceTown.Settlement;
        if (spawnSettlement == null)
            return;
        var culture = spawnSettlement.Culture;
        if (culture == null)
            return;
        var templateId     = "caravan_template_" + culture.StringId;
        var templateObject = MBObjectManager.Instance.GetObject<PartyTemplateObject>(templateId);
        if (templateObject == null)
            return;
        var caravanParty = CaravanPartyComponent.CreateCaravanParty(caravanOwner, spawnSettlement, templateObject);
        if (caravanParty == null)
            return;
        caravanParty.Party.SetCustomName(LocalizedTexts.ReinforcementCaravan);
        ReinforcementCaravanIds.Add(caravanParty.Id);
        caravanParty.Ai.SetDoNotMakeNewDecisions(true);
        // fix jitter
        LeaveSettlementAction.ApplyForParty(caravanParty);
        if (caravanParty == null)
            return;
        _sourceSettlementByCaravanId[caravanParty.Id]          = spawnSettlement.Id;
        _ownerClanByCaravanId[caravanParty.Id]                 = ownerClan.Id;
        _activeCaravanBySourceSettlementId[spawnSettlement.Id] = caravanParty.Id;
        var destination = new CampaignVec2(targetParty.Position.ToVec2(), targetParty.Position.IsOnLand);
        caravanParty.SetMoveGoToPoint(destination, MobileParty.NavigationType.Default);
        caravanParty.RecalculateShortTermBehavior();
        // +20 culture troop tree troop:
        AddExtraCultureTroops(caravanParty, culture, EXTRA_TROOP_COUNT);
        AddReinforcementSupplies(caravanParty);
        // +27 (?) gear:
        var gearItems = GetRandomGearItems(culture);
        foreach (var item in gearItems) {
            if (item != null)
                caravanParty.ItemRoster.AddToCounts(item, 1);
        }
        _targetByCaravanId[caravanParty.Id] = targetParty.Id;
    }
References _activeCaravanBySourceSettlementId, _ownerClanByCaravanId, _sourceSettlementByCaravanId, _targetByCaravanId, AddExtraCultureTroops(), AddReinforcementSupplies(), EXTRA_TROOP_COUNT, GetRandomGearItems(), DynamicTroopEquipmentReupload.LocalizedTexts.ReinforcementCaravan, and ReinforcementCaravanIds.
Referenced by OnDailyTickTown().
SyncData()
override void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.SyncData (IDataStore dataStore)
Definition at line 100 of file CutTheirSupplyBehavior.cs.
{
        if (dataStore.IsSaving) {
            _data.CaravanTargets.Clear();
            _data.CaravanSources.Clear();
            _data.CaravanOwnerClans.Clear();
            _data.ReturningCaravans.Clear();
            foreach (var entry in _targetByCaravanId) { _data.CaravanTargets[entry.Key.InternalValue] = entry.Value.InternalValue; }
            foreach (var entry in _sourceSettlementByCaravanId) { _data.CaravanSources[entry.Key.InternalValue] = entry.Value.InternalValue; }
            foreach (var entry in _ownerClanByCaravanId) { _data.CaravanOwnerClans[entry.Key.InternalValue] = entry.Value.InternalValue; }
            foreach (var caravanId in _returningCaravanIds) { _data.ReturningCaravans.Add(caravanId.InternalValue); }
            var tempData = _data;
            dataStore.SyncDataAsJson("DynamicTroopCutTheirSupply", ref tempData);
        }
        else if (dataStore.IsLoading) {
            var tempData = _data;
            if (dataStore.SyncDataAsJson("DynamicTroopCutTheirSupply", ref tempData) && tempData != null) {
                _data = tempData;
                _targetByCaravanId.Clear();
                foreach (var entry in _data.CaravanTargets) { _targetByCaravanId[new MBGUID(entry.Key)] = new MBGUID(entry.Value); }
                _sourceSettlementByCaravanId.Clear();
                foreach (var entry in _data.CaravanSources) { _sourceSettlementByCaravanId[new MBGUID(entry.Key)] = new MBGUID(entry.Value); }
                _ownerClanByCaravanId.Clear();
                foreach (var entry in _data.CaravanOwnerClans) { _ownerClanByCaravanId[new MBGUID(entry.Key)] = new MBGUID(entry.Value); }
                _returningCaravanIds.Clear();
                foreach (var caravanInternalId in _data.ReturningCaravans) { _returningCaravanIds.Add(new MBGUID(caravanInternalId)); }
                _activeCaravanBySourceSettlementId.Clear();
                ReinforcementCaravanIds.Clear();
                foreach (var caravanId in _targetByCaravanId.Keys) { ReinforcementCaravanIds.Add(caravanId); }
                foreach (var entry in _sourceSettlementByCaravanId) { _activeCaravanBySourceSettlementId[entry.Value] = entry.Key; }
            }
        }
    }
References _activeCaravanBySourceSettlementId, _data, _ownerClanByCaravanId, _returningCaravanIds, _sourceSettlementByCaravanId, _targetByCaravanId, and ReinforcementCaravanIds.
TransferCargoToTargetStash()
static void DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.TransferCargoToTargetStash (MobileParty caravanParty, MobileParty targetParty) static private
Definition at line 630 of file CutTheirSupplyBehavior.cs.
{
        if (!EveryoneCampaignBehavior.PartyArmories.TryGetValue(targetParty.Id, out var targetArmory)) {
            targetArmory = new Dictionary<ItemObject, int>();
            EveryoneCampaignBehavior.PartyArmories.Add(targetParty.Id, targetArmory);
        }
        var roster     = caravanParty.ItemRoster;
        var enumerator = roster.GetEnumerator();
        while (enumerator.MoveNext()) {
            var element = enumerator.Current;
            if (element is not { IsEmpty: false, EquipmentElement: { IsEmpty: false, Item: not null }, Amount: > 0 })
                continue;
            var item = element.EquipmentElement.Item;
            if (!targetArmory.TryGetValue(item, out var currentAmount))
                targetArmory.Add(item, element.Amount);
            else
                targetArmory[item] = currentAmount + element.Amount;
        }
        enumerator.Dispose();
    }
References DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.PartyArmories.
Referenced by OnTick().
TryRunAwayFromNearbyThreat()
static bool DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.TryRunAwayFromNearbyThreat (MobileParty caravanParty) static private
Definition at line 450 of file CutTheirSupplyBehavior.cs.
{
        MobileParty? nearestThreat                = null;
        var          nearestThreatDistanceSquared = float.MaxValue;
        foreach (var otherParty in Campaign.Current.MobileParties) {
            if (otherParty == null || !otherParty.IsActive)
                continue;
            if (otherParty == caravanParty)
                continue;
            if (!caravanParty.MapFaction.IsAtWarWith(otherParty.MapFaction))
                continue;
            var delta           = caravanParty.GetPosition2D - otherParty.GetPosition2D;
            var distanceSquared = delta.LengthSquared;
            if (distanceSquared > THREAT_SCAN_RADIUS_SQUARED)
                continue;
            if (distanceSquared < nearestThreatDistanceSquared) {
                nearestThreatDistanceSquared = distanceSquared;
                nearestThreat                = otherParty;
            }
        }
        if (nearestThreat == null)
            return false;
        var caravanManCount = caravanParty.MemberRoster.TotalManCount;
        var enemyManCount   = nearestThreat.MemberRoster.TotalManCount;
        if (enemyManCount <= caravanManCount * FLEE_IF_ENEMY_STRENGTH_MULTIPLIER)
            return false;
        var away = caravanParty.GetPosition2D - nearestThreat.GetPosition2D;
        if (away.LengthSquared < 0.0001f)
            away = new Vec2(1f, 0f);
        else
            away = away.Normalized();
        var fleePos = caravanParty.GetPosition2D + away * FLEE_POINT_DISTANCE;
        caravanParty.SetMoveGoToPoint(new CampaignVec2(fleePos, caravanParty.Position.IsOnLand), MobileParty.NavigationType.Default);
        caravanParty.RecalculateShortTermBehavior();
        return true;
    }
References FLEE_IF_ENEMY_STRENGTH_MULTIPLIER, FLEE_POINT_DISTANCE, and THREAT_SCAN_RADIUS_SQUARED.
Referenced by OnTick().
Member Data Documentation
_activeCaravanBySourceSettlementId
readonly Dictionary<MBGUID, MBGUID> DynamicTroopEquipmentReupload.CutTheirSupplyBehavior._activeCaravanBySourceSettlementId = new() private
Definition at line 75 of file CutTheirSupplyBehavior.cs.
Referenced by CleanupCaravan(), OnDailyTickTown(), OnMobilePartyDestroyed(), SpawnReinforcementCaravan(), and SyncData().
_data
Data DynamicTroopEquipmentReupload.CutTheirSupplyBehavior._data = new() private
Definition at line 87 of file CutTheirSupplyBehavior.cs.
Referenced by SyncData().
_escortRefreshTimer
float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior._escortRefreshTimer private
Definition at line 88 of file CutTheirSupplyBehavior.cs.
Referenced by OnTick().
_ownerClanByCaravanId
readonly Dictionary<MBGUID, MBGUID> DynamicTroopEquipmentReupload.CutTheirSupplyBehavior._ownerClanByCaravanId = new() private
Definition at line 76 of file CutTheirSupplyBehavior.cs.
Referenced by CleanupCaravan(), OnMobilePartyDestroyed(), OnTick(), SpawnReinforcementCaravan(), and SyncData().
_returningCaravanIds
readonly HashSet<MBGUID> DynamicTroopEquipmentReupload.CutTheirSupplyBehavior._returningCaravanIds = new() private
Definition at line 80 of file CutTheirSupplyBehavior.cs.
Referenced by CleanupCaravan(), OnMobilePartyDestroyed(), OnTick(), and SyncData().
_sourceSettlementByCaravanId
readonly Dictionary<MBGUID, MBGUID> DynamicTroopEquipmentReupload.CutTheirSupplyBehavior._sourceSettlementByCaravanId = new() private
Definition at line 82 of file CutTheirSupplyBehavior.cs.
Referenced by CleanupCaravan(), OnMobilePartyDestroyed(), OnTick(), SpawnReinforcementCaravan(), and SyncData().
_targetByCaravanId
readonly Dictionary<MBGUID, MBGUID> DynamicTroopEquipmentReupload.CutTheirSupplyBehavior._targetByCaravanId = new() private
Definition at line 84 of file CutTheirSupplyBehavior.cs.
Referenced by CleanupCaravan(), OnMobilePartyDestroyed(), OnTick(), SpawnReinforcementCaravan(), and SyncData().
ARRIVAL_DISTANCE_SQUARED
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.ARRIVAL_DISTANCE_SQUARED = 4f static private
Definition at line 60 of file CutTheirSupplyBehavior.cs.
Referenced by HasArrived().
BASE_CHANCE_AT_MIN_PROSPERITY
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.BASE_CHANCE_AT_MIN_PROSPERITY = 0.01f static private
Definition at line 27 of file CutTheirSupplyBehavior.cs.
Referenced by GetDailySpawnChance().
CHANCE_PER_PROSPERITY_POINT
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.CHANCE_PER_PROSPERITY_POINT = 0.000001f static private
Definition at line 28 of file CutTheirSupplyBehavior.cs.
Referenced by GetDailySpawnChance().
ESCORT_REFRESH_SECONDS
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.ESCORT_REFRESH_SECONDS = 0.25f static private
Definition at line 58 of file CutTheirSupplyBehavior.cs.
Referenced by OnTick().
EXTRA_TROOP_COUNT
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.EXTRA_TROOP_COUNT = 25 static private
Definition at line 53 of file CutTheirSupplyBehavior.cs.
Referenced by SpawnReinforcementCaravan().
FLEE_IF_ENEMY_STRENGTH_MULTIPLIER
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.FLEE_IF_ENEMY_STRENGTH_MULTIPLIER = 1.20f static private
Definition at line 67 of file CutTheirSupplyBehavior.cs.
Referenced by TryRunAwayFromNearbyThreat().
FLEE_POINT_DISTANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.FLEE_POINT_DISTANCE = 8f static private
Definition at line 66 of file CutTheirSupplyBehavior.cs.
Referenced by TryRunAwayFromNearbyThreat().
FOOD_PER_TYPE_COUNT
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.FOOD_PER_TYPE_COUNT = 17 static private
Definition at line 54 of file CutTheirSupplyBehavior.cs.
Referenced by AddReinforcementSupplies().
GEAR_COUNT
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_COUNT = 26 static private
Definition at line 32 of file CutTheirSupplyBehavior.cs.
Referenced by AddRandomGearItems(), and GetRandomGearItems().
GEAR_TIER_1_CAP
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_1_CAP = 4 static private
Definition at line 34 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_1_CHANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_1_CHANCE = 0.85f static private
Definition at line 35 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_2_CAP
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_2_CAP = 5 static private
Definition at line 37 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_2_CHANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_2_CHANCE = 0.75f static private
Definition at line 38 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_3_CAP
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_3_CAP = 8 static private
Definition at line 40 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_3_CHANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_3_CHANCE = 0.55f static private
Definition at line 41 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_4_CAP
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_4_CAP = 4 static private
Definition at line 43 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_4_CHANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_4_CHANCE = 0.45f static private
Definition at line 44 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_5_CAP
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_5_CAP = 2 static private
Definition at line 46 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_5_CHANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_5_CHANCE = 0.35f static private
Definition at line 47 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_6_CAP
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_6_CAP = 1 static private
Definition at line 49 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
GEAR_TIER_6_CHANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.GEAR_TIER_6_CHANCE = 0.25f static private
Definition at line 50 of file CutTheirSupplyBehavior.cs.
Referenced by GetRandomGearItems().
MAX_DAILY_CHANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.MAX_DAILY_CHANCE = 0.125f static private
Definition at line 29 of file CutTheirSupplyBehavior.cs.
Referenced by GetDailySpawnChance().
MIN_PROSPERITY
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.MIN_PROSPERITY = 2000f static private
Definition at line 26 of file CutTheirSupplyBehavior.cs.
Referenced by GetDailySpawnChance(), and OnDailyTickTown().
ReinforcementCaravanIds
readonly HashSet<MBGUID> DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.ReinforcementCaravanIds = new() static private
Definition at line 72 of file CutTheirSupplyBehavior.cs.
Referenced by CleanupCaravan(), IsReinforcementCaravanParty(), OnMobilePartyDestroyed(), OnTick(), SpawnReinforcementCaravan(), and SyncData().
RemovePartyMethod
readonly? MethodInfo DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.RemovePartyMethod static private
Initial value:
=
        typeof(MobileParty).GetMethod("RemoveParty", BindingFlags.Instance | BindingFlags.NonPublic)
Definition at line 69 of file CutTheirSupplyBehavior.cs.
Referenced by RemoveMobileParty().
SUMPTER_HORSE_COUNT
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.SUMPTER_HORSE_COUNT = 17 static private
Definition at line 55 of file CutTheirSupplyBehavior.cs.
Referenced by AddReinforcementSupplies().
SUMPTER_HORSE_ITEM_ID
const string DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.SUMPTER_HORSE_ITEM_ID = "sumpter_horse" static private
Definition at line 56 of file CutTheirSupplyBehavior.cs.
Referenced by AddReinforcementSupplies().
TARGET_PARTY_SIZE
const int DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.TARGET_PARTY_SIZE = 100 static private
Definition at line 31 of file CutTheirSupplyBehavior.cs.
Referenced by FindTargetLordParty(), and FindTargetLordParty().
THREAT_SCAN_RADIUS
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.THREAT_SCAN_RADIUS = 10f static private
Definition at line 64 of file CutTheirSupplyBehavior.cs.
THREAT_SCAN_RADIUS_SQUARED
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.THREAT_SCAN_RADIUS_SQUARED = THREAT_SCAN_RADIUS * THREAT_SCAN_RADIUS static private
Definition at line 65 of file CutTheirSupplyBehavior.cs.
Referenced by TryRunAwayFromNearbyThreat().
WAIT_DISTANCE
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.WAIT_DISTANCE = 2f static private
Definition at line 61 of file CutTheirSupplyBehavior.cs.
Referenced by GetWaitPointNear().
WAIT_DISTANCE_SQUARED
const float DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.WAIT_DISTANCE_SQUARED = WAIT_DISTANCE * WAIT_DISTANCE static private
Definition at line 62 of file CutTheirSupplyBehavior.cs.
Referenced by OnTick().
The documentation for this class was generated from the following file:
CutTheirSupplyBehavior.cs