动态装备系统: MessageDisplayService Class Reference
MessageDisplayService Class Reference
消息显示服务，用于在游戏中显示消息。
Static Public Member Functions
static void EnqueueMessage (InformationMessage message)
将消息加入队列，并通知消息处理任务。
static void StopService ()
停止消息处理任务。
Static Private Member Functions
static MessageDisplayService ()
静态构造函数，初始化并启动消息处理任务。
static void ProcessMessages ()
消息处理任务的主函数，循环检查消息队列并显示消息。
Static Private Attributes
static readonly CancellationTokenSource CancellationTokenSource = new()
static readonly AutoResetEvent MessageAvailable = new(false)
static readonly ConcurrentQueue< InformationMessage > MessageQueue = new()
Detailed Description
消息显示服务，用于在游戏中显示消息。
Definition at line 14 of file MessageDisplayService.cs.
Constructor & Destructor Documentation
MessageDisplayService()
static MessageDisplayService.MessageDisplayService () static private
静态构造函数，初始化并启动消息处理任务。
Definition at line 22 of file MessageDisplayService.cs.
{
        Task.Factory.StartNew(ProcessMessages,
                              CancellationTokenSource.Token,
                              TaskCreationOptions.LongRunning,
                              TaskScheduler.Default);
    }
References CancellationTokenSource, and ProcessMessages().
Member Function Documentation
EnqueueMessage()
static void MessageDisplayService.EnqueueMessage (InformationMessage message) static
将消息加入队列，并通知消息处理任务。
Parameters
message 要显示的消息。
Definition at line 33 of file MessageDisplayService.cs.
{
        MessageQueue.Enqueue(message);
        MessageAvailable.Set(); // 通知有新消息
    }
References MessageAvailable, and MessageQueue.
Referenced by DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.HandlePartyItems(), DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipmentForThrowingWeapons().
ProcessMessages()
static void MessageDisplayService.ProcessMessages () static private
消息处理任务的主函数，循环检查消息队列并显示消息。
Definition at line 41 of file MessageDisplayService.cs.
{
        while (!CancellationTokenSource.IsCancellationRequested) {
            MessageAvailable.WaitOne(); // 等待新消息通知
            while (MessageQueue.TryDequeue(out var message)) {
                try {
                    // 显示消息
                    InformationManager.DisplayMessage(message);
                }
                catch (Exception) {
                    // 异常处理，可以根据需要记录日志或忽略
                }
            }
        }
    }
References CancellationTokenSource, MessageAvailable, and MessageQueue.
Referenced by MessageDisplayService().
StopService()
static void MessageDisplayService.StopService () static
停止消息处理任务。
Definition at line 59 of file MessageDisplayService.cs.
{
        CancellationTokenSource.Cancel();
        MessageAvailable.Set(); // 确保如果任务正在等待，则能够退出等待状态
    }
References CancellationTokenSource, and MessageAvailable.
Member Data Documentation
CancellationTokenSource
readonly CancellationTokenSource MessageDisplayService.CancellationTokenSource = new() static private
Definition at line 17 of file MessageDisplayService.cs.
Referenced by MessageDisplayService(), ProcessMessages(), and StopService().
MessageAvailable
readonly AutoResetEvent MessageDisplayService.MessageAvailable = new(false) static private
Definition at line 16 of file MessageDisplayService.cs.
Referenced by EnqueueMessage(), ProcessMessages(), and StopService().
MessageQueue
readonly ConcurrentQueue<InformationMessage> MessageDisplayService.MessageQueue = new() static private
Definition at line 15 of file MessageDisplayService.cs.
Referenced by EnqueueMessage(), and ProcessMessages().
The documentation for this class was generated from the following file:
MessageDisplayService.cs