动态装备系统: DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch Class Reference
DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch Class Reference
Classes
class SpawnAgentState
Static Private Member Functions
static void ApplyMoralePenalty (Agent agent, float penalty)
static bool IsPartyValidForProcessing (IAgentOriginBase agentOrigin)
static void Postfix (Agent __result, SpawnAgentState? __state)
static void Prefix (Mission __instance, ref AgentBuildData agentBuildData, ref SpawnAgentState? __state)
Detailed Description
Definition at line 17 of file SpawnAgentPatch.cs.
Member Function Documentation
ApplyMoralePenalty()
static void DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.ApplyMoralePenalty (Agent agent, float penalty) static private
Definition at line 86 of file SpawnAgentPatch.cs.
{
        var currentMorale = agent.GetMorale();
        if (currentMorale < 0f)
            return;
        agent.SetMorale(Math.Max(0f, currentMorale - penalty));
    }
Referenced by Postfix().
IsPartyValidForProcessing()
static bool DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.IsPartyValidForProcessing (IAgentOriginBase agentOrigin) static private
Definition at line 96 of file SpawnAgentPatch.cs.
{
        var party = agentOrigin switch {
                        PartyAgentOrigin partyAgentOrigin           => partyAgentOrigin.Party,
                        PartyGroupAgentOrigin partyGroupAgentOrigin => partyGroupAgentOrigin.Party,
                        SimpleAgentOrigin simpleAgentOrigin         => simpleAgentOrigin.Party,
                        _                                           => null
                    };
        if (party is not { IsValid: true, MobileParty: not null }) { return false; }
        var mobileParty = party.MobileParty;
        if (mobileParty.IsCaravan || mobileParty.IsVillager || mobileParty.IsMilitia || mobileParty.IsBandit) { return false; }
        return true;
    }
Referenced by Prefix().
Postfix()
static void DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix (Agent __result, SpawnAgentState? __state) static private
Definition at line 68 of file SpawnAgentPatch.cs.
{
        if (__result == null || __state == null) { return; }
        var equipmentToConsume = __state.Assignment.CreateEquipmentForArmoryConsumption();
        if (__state.IsMainParty) { ArmyArmory.AssignEquipment(equipmentToConsume); }
        else { __state.Distributor.Spawn(equipmentToConsume); }
        // Underequipped morale penalty (player party only)
        if (__state.IsInPlayerParty && (ModSettings.Instance?.Underequipped ?? true)) {
            var penalty = __state.Assignment.UnderEquippedMoralePenalty;
            if (penalty > 0f) { ApplyMoralePenalty(__result, penalty); }
        }
        var dynamicTroopMissionLogic = Mission.Current.GetMissionBehavior<DynamicTroopMissionLogic>();
        dynamicTroopMissionLogic?.RegisterSpawnedAgentAssignment(__result, __state.Assignment);
    }
References ApplyMoralePenalty(), DynamicTroopEquipmentReupload.ArmyArmory.AssignEquipment(), DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.SpawnAgentState.Assignment, DynamicTroopEquipmentReupload.Assignment.CreateEquipmentForArmoryConsumption(), DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.SpawnAgentState.Distributor, DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.SpawnAgentState.IsInPlayerParty, DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.SpawnAgentState.IsMainParty, DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.RegisterSpawnedAgentAssignment(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Spawn(), DynamicTroopEquipmentReupload.ModSettings.Underequipped, and DynamicTroopEquipmentReupload.Assignment.UnderEquippedMoralePenalty.
Prefix()
static void DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Prefix (Mission __instance, ref AgentBuildData agentBuildData, ref SpawnAgentState? __state) static private
Definition at line 18 of file SpawnAgentPatch.cs.
{
        if (__instance.GetMissionBehavior<MissionAgentSpawnLogic>() == null) { return; }
        if (agentBuildData.AgentOrigin == null) { return; }
        // party not valid
        if (!IsPartyValidForProcessing(agentBuildData.AgentOrigin)) {
            if (ModSettings.Instance?.RandomizeNonHeroLedAiPartiesArmor ?? false) {
                if (agentBuildData.AgentOrigin.Troop is CharacterObject troopCharacterObject && !troopCharacterObject.IsHero) {
                    var assignment = new Assignment(troopCharacterObject);
                    assignment.FillEmptySlots();
                    agentBuildData = agentBuildData.Equipment(assignment.Equipment);
                }
            }
            return;
        }
        var dynamicTroopMissionLogic = __instance.GetMissionBehavior<DynamicTroopMissionLogic>();
        if (dynamicTroopMissionLogic == null) { return; }
        var party = Global.GetAgentParty(agentBuildData.AgentOrigin);
        if (party == null) { return; }
        var isMainParty = party == Campaign.Current.MainParty;
        if (!isMainParty && !party.IsValid()) { return; }
        dynamicTroopMissionLogic.TryInitializeDistributors();
        if (!dynamicTroopMissionLogic.Distributors.TryGetValue(party.Id, out var distributor) || distributor == null) { return; }
        var troopCharacter = agentBuildData.AgentOrigin.Troop as CharacterObject;
        if (troopCharacter == null || troopCharacter.IsHero) { return; }
        var assignmentOrNull = distributor.Assignments.FirstOrDefault(x => x.Character == troopCharacter && !x.IsAssigned);
        if (assignmentOrNull == null) { return; }
        assignmentOrNull.IsAssigned = true;
        var isInPlayerParty = agentBuildData.AgentOrigin.IsUnderPlayersCommand;
        if (!isInPlayerParty) { assignmentOrNull.FillEmptySlots(); }
        agentBuildData = agentBuildData.Equipment(assignmentOrNull.Equipment);
        __state        = new SpawnAgentState(assignmentOrNull, isInPlayerParty, isMainParty, distributor);
    }
References DynamicTroopEquipmentReupload.Global.GetAgentParty(), IsPartyValidForProcessing(), and DynamicTroopEquipmentReupload.ModSettings.RandomizeNonHeroLedAiPartiesArmor.
The documentation for this class was generated from the following file:
Patches/SpawnAgentPatch.cs