动态装备系统: DynamicTroopMissionLogic Class Reference
DynamicTroopMissionLogic Class Reference
Public Member Functions
override async void AfterStart ()
override void OnAgentRemoved (Agent affectedAgent, Agent affectorAgent, AgentState agentState, KillingBlow blow)
当士兵在战斗中被移除（如被杀或被击晕）时触发的处理。
override void OnBattleEnded ()
override InquiryData OnEndMissionRequest (out bool canLeave)
override void OnMissionResultReady (MissionResult missionResult)
override void OnRetreatMission ()
override void OnSurrenderMission ()
override void ShowBattleResults ()
Public Attributes
readonly Dictionary< MBGUID, PartyEquipmentDistributor > Distributors = new()
readonly Dictionary< MBGUID, BattleSideEnum > PartyBattleSides = new()
Protected Member Functions
override void OnEndMission ()
Private Member Functions
void HandlePartyItems (MBGUID partyId, bool isPlayerParty, bool isVictorious, bool isDefeated)
处理部队战后的物品管理。
void OnMissionEnded (MissionResult? missionResult)
void ReturnEquipmentFromAgents (MBGUID partyId, IEnumerable< Agent > agents)
从参与战斗的士兵那里回收装备。
void ReturnItemsToDestination (MBGUID partyId, Dictionary< ItemObject, int > items, bool isPlayerParty)
将物品返回到指定部队。
Private Attributes
bool _isMissionEnded
readonly Dictionary< MBGUID, PartyBattleRecord > _partyBattleRecords = new()
readonly HashSet< Agent > _processedAgents = new()
readonly Random _random = new()
Detailed Description
Definition at line 21 of file DynamicTroopMissionLogic.cs.
Member Function Documentation
AfterStart()
override async void DynamicTroopMissionLogic.AfterStart ()
Definition at line 34 of file DynamicTroopMissionLogic.cs.
{
        base.AfterStart();
        Global.Log("AfterStart", Colors.Green, Level.Debug);
        if (!Mission.DoesMissionRequireCivilianEquipment && Mission.CombatType == Mission.MissionCombatType.Combat) {
            var tasks = new List<Task>();
            Distributors.Add(Campaign.Current.MainParty.Id, new PartyEquipmentDistributor(Mission, Campaign.Current.MainParty, ArmyArmory.Armory));
            foreach (var party in MapEvent.PlayerMapEvent.InvolvedParties) {
                var mobileParty = party.MobileParty;
                if (mobileParty != null && mobileParty != Campaign.Current.MainParty && mobileParty.IsValid()) {
                    var partyArmory = EveryoneCampaignBehavior.PartyArmories.TryGetValue(mobileParty.Id, out var armory)
                                          ? armory
                                          : new Dictionary<ItemObject, int>();
                    Distributors.Add(mobileParty.Id, new PartyEquipmentDistributor(Mission.Current, mobileParty, partyArmory));
                }
            }
            foreach (var distributor in Distributors) {
                tasks.Add(Task.Run(() => distributor.Value.Run()));
            }
            await Task.WhenAll(tasks);
        }
    }
References ArmyArmory.Armory, Distributors, and EveryoneCampaignBehavior.PartyArmories.
HandlePartyItems()
void DynamicTroopMissionLogic.HandlePartyItems (MBGUID partyId, bool isPlayerParty, bool isVictorious, bool isDefeated) private
处理部队战后的物品管理。
Parameters
partyId 部队的唯一标识符。
isPlayerParty 是否为玩家的部队。
isVictorious 部队是否胜利。
isDefeated 部队是否被击败。
Definition at line 194 of file DynamicTroopMissionLogic.cs.
{
        // 检查是否存在对应的battleRecord
        if (!_partyBattleRecords.TryGetValue(partyId, out var battleRecord)) {
            Global.Warn($"No battle record found for party {partyId}");
            return;
        }
        if (isVictorious) {
            ReturnItemsToDestination(partyId, battleRecord.ItemsToRecover, isPlayerParty);
            ReturnItemsToDestination(partyId, battleRecord.LootedItems,    isPlayerParty);
            if (isPlayerParty) {
                InformationManager.DisplayMessage(new InformationMessage(LocalizedTexts.GetLootAddedMessage(battleRecord
                                                                                                                .LootedItemsCount),
                                                                         Colors.Green));
                InformationManager.DisplayMessage(new InformationMessage(LocalizedTexts
                                                                             .GetItemsRecoveredFromFallenMessage(battleRecord
                                                                                                                     .ItemsToRecoverCount),
                                                                         Colors.Green));
            }
        }
        else if (!isDefeated) { ReturnItemsToDestination(partyId, battleRecord.ItemsToRecover, isPlayerParty); }
        // 被击败的一方不获取任何物品
    }
References _partyBattleRecords, LocalizedTexts.GetLootAddedMessage(), and ReturnItemsToDestination().
Referenced by OnMissionEnded().
OnAgentRemoved()
override void DynamicTroopMissionLogic.OnAgentRemoved (Agent affectedAgent, Agent affectorAgent, AgentState agentState, KillingBlow blow)
当士兵在战斗中被移除（如被杀或被击晕）时触发的处理。
Parameters
affectedAgent 被移除的士兵。
affectorAgent 造成移除的士兵。
agentState 被移除的士兵的状态（如被杀、失去意识等）。
blow 造成移除的攻击详情。
Definition at line 64 of file DynamicTroopMissionLogic.cs.
{
        if (Mission is { CombatType: Mission.MissionCombatType.Combat, PlayerTeam.IsValid: true } &&
            agentState is AgentState.Killed or AgentState.Unconscious                             &&
            affectedAgent.IsValid()                                                               &&
            affectorAgent.IsValid()                                                               &&
            !_processedAgents.Contains(affectedAgent)                                             &&
            affectedAgent.Character is { IsHero: false }) {
            Global.Log($"agent {affectedAgent.Character.Name}#{affectedAgent.Index} removed",
                       Colors.Green,
                       Level.Debug);
            _ = _processedAgents.Add(affectedAgent);
            var affectedPartyId = Global.GetAgentParty(affectedAgent.Origin)?.Id;
            var affectorPartyId = Global.GetAgentParty(affectorAgent.Origin)?.Id;
            if (!affectedPartyId.HasValue || !affectorPartyId.HasValue) return;
            if (!_partyBattleRecords.ContainsKey(affectedPartyId.Value))
                _partyBattleRecords.Add(affectedPartyId.Value, new PartyBattleRecord());
            if (!_partyBattleRecords.ContainsKey(affectorPartyId.Value))
                _partyBattleRecords.Add(affectorPartyId.Value, new PartyBattleRecord());
            var affectedBattleRecord = _partyBattleRecords[affectedPartyId.Value];
            var affectorBattleRecord = _partyBattleRecords[affectorPartyId.Value];
            // 获取受击部位
            var hitBodyPart = blow.VictimBodyPart;
            // 获取受击部位的护甲
            var armors   = affectedAgent.GetAgentArmors();
            var hitArmor = ArmorSelector.GetRandomArmorByBodyPart(armors, hitBodyPart);
            Global.ProcessAgentEquipment(affectedAgent,
                                         item => {
                                             if (hitArmor == null || item.StringId != hitArmor.StringId) {
                                                 affectedBattleRecord.AddItemToRecover(item);
                                                 var dropChance = _random.NextFloat(); // 生成一个0到1之间的随机数
                                                 if (dropChance > (SubModule.Settings?.DropRate ?? 1f)) return;
                                                 affectorBattleRecord.AddLootedItem(item);
                                                 Global.Log($"{item.StringId} looted", Colors.Green, Level.Debug);
                                             }
                                             else if (item.StringId == hitArmor.StringId) { Global.Log($"{item.StringId} damaged", Colors.Red, Level.Debug); }
                                         });
        }
        base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
    }
References _partyBattleRecords, _processedAgents, and ArmorSelector.GetRandomArmorByBodyPart().
OnBattleEnded()
override void DynamicTroopMissionLogic.OnBattleEnded ()
Definition at line 145 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnBattleEnded() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.OnBattleEnded();
    }
References OnMissionEnded().
OnEndMission()
override void DynamicTroopMissionLogic.OnEndMission () protected
Definition at line 272 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnEndMission() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.OnEndMission();
    }
References OnMissionEnded().
OnEndMissionRequest()
override InquiryData DynamicTroopMissionLogic.OnEndMissionRequest (out bool canLeave)
Definition at line 133 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnEndMissionRequest() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        return base.OnEndMissionRequest(out canLeave);
    }
References OnMissionEnded().
OnMissionEnded()
void DynamicTroopMissionLogic.OnMissionEnded (MissionResult? missionResult) private
Definition at line 151 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnMissionEnded() called", Colors.Green, Level.Debug);
        if (_isMissionEnded) return;
        _isMissionEnded = true;
        var playerVictory    = missionResult?.PlayerVictory  ?? false;
        var playerDefeat     = missionResult?.PlayerDefeated ?? false;
        var unresolvedBattle = missionResult == null || !missionResult.BattleResolved;
        // 确定玩家方
        var playerPartyId = Campaign.Current.MainParty.Id;
        foreach (var kvPartyBattleSides in PartyBattleSides) {
            var isPlayerParty = kvPartyBattleSides.Key == playerPartyId;
            var isVictorious = !unresolvedBattle &&
                               (playerVictory && kvPartyBattleSides.Value == Mission.PlayerTeam.Side ||
                                playerDefeat  && kvPartyBattleSides.Value != Mission.PlayerTeam.Side);
            var isDefeated = !unresolvedBattle &&
                             (playerDefeat  && kvPartyBattleSides.Value == Mission.PlayerTeam.Side ||
                              playerVictory && kvPartyBattleSides.Value != Mission.PlayerTeam.Side);
            HandlePartyItems(kvPartyBattleSides.Key, isPlayerParty, isVictorious, isDefeated);
        }
        // 回收场上士兵的装备
        foreach (var kvPartyBattleSides in PartyBattleSides) {
            IEnumerable<Agent> partyAgents =
                Mission.Agents.WhereQ(agent => agent.IsValid()  &&
                                               agent.IsActive() &&
                                               !agent.IsHero    &&
                                               Global.GetAgentParty(agent.Origin)?.Id == kvPartyBattleSides.Key);
            ReturnEquipmentFromAgents(kvPartyBattleSides.Key, partyAgents);
        }
    }
References _isMissionEnded, HandlePartyItems(), PartyBattleSides, and ReturnEquipmentFromAgents().
Referenced by OnBattleEnded(), OnEndMission(), OnEndMissionRequest(), OnMissionResultReady(), OnRetreatMission(), OnSurrenderMission(), and ShowBattleResults().
OnMissionResultReady()
override void DynamicTroopMissionLogic.OnMissionResultReady (MissionResult missionResult)
Definition at line 127 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnMissionResultReady() called", Colors.Green, Level.Debug);
        OnMissionEnded(missionResult);
        base.OnMissionResultReady(missionResult);
    }
References OnMissionEnded().
OnRetreatMission()
override void DynamicTroopMissionLogic.OnRetreatMission ()
Definition at line 115 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnRetreatMission() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.OnRetreatMission();
    }
References OnMissionEnded().
OnSurrenderMission()
override void DynamicTroopMissionLogic.OnSurrenderMission ()
Definition at line 121 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnSurrenderMission() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.OnSurrenderMission();
    }
References OnMissionEnded().
ReturnEquipmentFromAgents()
void DynamicTroopMissionLogic.ReturnEquipmentFromAgents (MBGUID partyId, IEnumerable< Agent > agents) private
从参与战斗的士兵那里回收装备。
Parameters
partyId 部队的唯一标识符。
agents 参与战斗的士兵集合。
Definition at line 250 of file DynamicTroopMissionLogic.cs.
{
        var isPlayerParty  = partyId == Campaign.Current.MainParty.Id;
        var totalItemCount = 0;
        foreach (var agent in agents)
            Global.ProcessAgentEquipment(agent,
                                         item => {
                                             if (item is null || !ItemBlackList.Test(item)) return;
                                             totalItemCount++;
                                             if (isPlayerParty)
                                                 ArmyArmory.AddItemToArmory(item);
                                             else if (Distributors.TryGetValue(partyId, out var distributor))
                                                 distributor.ReturnItem(item, 1);
                                         });
        if (totalItemCount <= 0) return;
        var partyType = isPlayerParty ? "Player party" : "Party";
        Global.Log($"{partyType} {partyId} reclaimed {totalItemCount} items from agents", Colors.Green, Level.Debug);
    }
References ArmyArmory.AddItemToArmory(), Distributors, and ItemBlackList.Test().
Referenced by OnMissionEnded().
ReturnItemsToDestination()
void DynamicTroopMissionLogic.ReturnItemsToDestination (MBGUID partyId, Dictionary< ItemObject, int > items, bool isPlayerParty) private
将物品返回到指定部队。
Parameters
partyId 部队的唯一标识符。
items 要返回的物品及其数量。
isPlayerParty 是否为玩家的部队。
Definition at line 225 of file DynamicTroopMissionLogic.cs.
{
        var totalItemCount = 0; // 用于累计物品总数
        foreach (var item in items) {
            if (item.Key == null || item.Value <= 0 || !ItemBlackList.Test(item.Key)) continue;
            totalItemCount += item.Value;
            if (isPlayerParty)
                ArmyArmory.AddItemToArmory(item.Key, item.Value);
            else if (Distributors.TryGetValue(partyId, out var distributor))
                distributor.ReturnItem(item.Key, item.Value);
        }
        if (totalItemCount <= 0) return;
        var partyType = isPlayerParty ? "Player party" : "Party";
        Global.Log($"{partyType} {partyId} processed a total of {totalItemCount} items", Colors.Green, Level.Debug);
    }
References ArmyArmory.AddItemToArmory(), Distributors, and ItemBlackList.Test().
Referenced by HandlePartyItems().
ShowBattleResults()
override void DynamicTroopMissionLogic.ShowBattleResults ()
Definition at line 139 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("ShowBattleResults() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.ShowBattleResults();
    }
References OnMissionEnded().
Member Data Documentation
_isMissionEnded
bool DynamicTroopMissionLogic._isMissionEnded private
Definition at line 32 of file DynamicTroopMissionLogic.cs.
Referenced by OnMissionEnded().
_partyBattleRecords
readonly Dictionary<MBGUID, PartyBattleRecord> DynamicTroopMissionLogic._partyBattleRecords = new() private
Definition at line 22 of file DynamicTroopMissionLogic.cs.
Referenced by HandlePartyItems(), and OnAgentRemoved().
_processedAgents
readonly HashSet<Agent> DynamicTroopMissionLogic._processedAgents = new() private
Definition at line 24 of file DynamicTroopMissionLogic.cs.
Referenced by OnAgentRemoved().
_random
readonly Random DynamicTroopMissionLogic._random = new() private
Definition at line 26 of file DynamicTroopMissionLogic.cs.
Distributors
readonly Dictionary<MBGUID, PartyEquipmentDistributor> DynamicTroopMissionLogic.Distributors = new()
Definition at line 28 of file DynamicTroopMissionLogic.cs.
Referenced by AfterStart(), SpawnAgentPatch.AssignOrSpawnEquipment(), SpawnAgentPatch.EnsureDistributorExists(), SpawnAgentPatch.GetAssignmentForCharacter(), ReturnEquipmentFromAgents(), and ReturnItemsToDestination().
PartyBattleSides
readonly Dictionary<MBGUID, BattleSideEnum> DynamicTroopMissionLogic.PartyBattleSides = new()
Definition at line 30 of file DynamicTroopMissionLogic.cs.
Referenced by OnMissionEnded(), and SpawnAgentPatch.UpdateBattleSides().
The documentation for this class was generated from the following file:
DynamicTroopMissionLogic.cs