动态装备系统: DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches Class Reference
DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches Class Reference
Static Private Member Functions
static void AddDialogsPostfix (CampaignGameStarter starter)
static bool CaravanBuyProductsOnConditionPrefix (ref bool __result)
static bool IsSurrenderFeasiblePrefix (ref bool __result)
static bool ReinforcementTradeLineOnClickableCondition (out TextObject explanation)
static bool ReinforcementTradeLineOnCondition ()
Static Private Attributes
const bool DISABLE_TRADE_BLOCK_FOR_TEST = false
Detailed Description
Definition at line 10 of file ReinforcementCaravanConversationPatches.cs.
Member Function Documentation
AddDialogsPostfix()
static void DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.AddDialogsPostfix (CampaignGameStarter starter) static private
Definition at line 29 of file ReinforcementCaravanConversationPatches.cs.
{
        starter.AddPlayerLine(
            "caravan_buy_products",
            "caravan_talk",
            "caravan_player_trade",
            "{=t0UGXPV4}I'm interested in trading. What kind of products do you have?",
            ReinforcementTradeLineOnCondition,
            null,
            100,
            ReinforcementTradeLineOnClickableCondition);
    }
References ReinforcementTradeLineOnClickableCondition(), and ReinforcementTradeLineOnCondition().
CaravanBuyProductsOnConditionPrefix()
static bool DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.CaravanBuyProductsOnConditionPrefix (ref bool __result) static private
Definition at line 16 of file ReinforcementCaravanConversationPatches.cs.
{
        if (DISABLE_TRADE_BLOCK_FOR_TEST) { return true; }
        if (CutTheirSupplyBehavior.IsReinforcementCaravanParty(MobileParty.ConversationParty)) {
            __result = false;
            return false;
        }
        return true;
    }
References DISABLE_TRADE_BLOCK_FOR_TEST, and DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.IsReinforcementCaravanParty().
IsSurrenderFeasiblePrefix()
static bool DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.IsSurrenderFeasiblePrefix (ref bool __result) static private
Definition at line 54 of file ReinforcementCaravanConversationPatches.cs.
{
        if (CutTheirSupplyBehavior.IsReinforcementCaravanParty(MobileParty.ConversationParty)) {
            __result = false;
            return false;
        }
        return true;
    }
References DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.IsReinforcementCaravanParty().
ReinforcementTradeLineOnClickableCondition()
static bool DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.ReinforcementTradeLineOnClickableCondition (out TextObject explanation) static private
Definition at line 47 of file ReinforcementCaravanConversationPatches.cs.
{
        explanation = LocalizedTexts.ReinforcementCaravanTradeDisabled;
        return false;
    }
References DynamicTroopEquipmentReupload.LocalizedTexts.ReinforcementCaravanTradeDisabled.
Referenced by AddDialogsPostfix().
ReinforcementTradeLineOnCondition()
static bool DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.ReinforcementTradeLineOnCondition () static private
Definition at line 41 of file ReinforcementCaravanConversationPatches.cs.
{
        if (DISABLE_TRADE_BLOCK_FOR_TEST) { return false; }
        return CutTheirSupplyBehavior.IsReinforcementCaravanParty(MobileParty.ConversationParty);
    }
References DISABLE_TRADE_BLOCK_FOR_TEST, and DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.IsReinforcementCaravanParty().
Referenced by AddDialogsPostfix().
Member Data Documentation
DISABLE_TRADE_BLOCK_FOR_TEST
const bool DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.DISABLE_TRADE_BLOCK_FOR_TEST = false static private
Definition at line 11 of file ReinforcementCaravanConversationPatches.cs.
Referenced by CaravanBuyProductsOnConditionPrefix(), and ReinforcementTradeLineOnCondition().
The documentation for this class was generated from the following file:
Patches/ReinforcementCaravanConversationPatches.cs