动态装备系统: Global Class Reference
Global Class Reference
Static Public Member Functions
static int CountCharacterEquipmentItemTypes (CharacterObject? character, ItemObject.ItemTypeEnum? itemType)
static List< ItemObject > CreateRandomCraftedItemsByItemType (ItemObject.ItemTypeEnum? type, BasicCultureObject? culture, int num=0)
static void Debug (string message)
static void Error (string message)
static void Fatal (string message)
static bool FullySameWeaponClass (ItemObject weapon1, ItemObject weapon2)
static ? MobileParty GetAgentParty (IAgentOriginBase? origin)
static List< WeaponClass > GetWeaponClass (ItemObject item)
static bool HaveSameWeaponClass (List< WeaponClass > list1, List< WeaponClass > list2)
static void Info (string message)
static void InitializeCraftingTemplatesByItemType ()
static bool IsInPlayerParty (IAgentOriginBase? agentOrigin)
static void Log (string message, Color color, Level level, int skipFrames=1)
static void ProcessAgentEquipment (Agent agent, Action< ItemObject > processEquipmentItem)
static void Warn (string message)
Static Public Attributes
static readonly EquipmentIndex[] ArmourAndHorsesSlots
static EquipmentIndex[] ArmourSlots
static readonly EquipmentIndex[] EquipmentSlots
static WeaponClass[] InvalidWeaponClasses
static ItemObject.ItemTypeEnum[] ItemTypes
Static Private Member Functions
static bool IsAmmoAndEmpty (MissionWeapon? mw)
static bool IsPartyInPlayerCommand (PartyBase? party)
Static Private Attributes
static readonly Dictionary< ItemObject.ItemTypeEnum, CraftingTemplate[]> CraftingTemplatesByItemType = new()
Detailed Description
Definition at line 21 of file Global.cs.
Member Function Documentation
CountCharacterEquipmentItemTypes()
static int Global.CountCharacterEquipmentItemTypes (CharacterObject? character, ItemObject.ItemTypeEnum? itemType) static
Definition at line 252 of file Global.cs.
{
        return character == null || itemType == null || character.BattleEquipments == null
                   ? 0
                   : character.BattleEquipments.MaxQ(equipment =>
                                                         Assignment.WeaponSlots.CountQ(slot =>
                                                             equipment.GetEquipmentFromSlot(slot)
                                                                      .Item?.ItemType ==
                                                             itemType));
    }
References Assignment.WeaponSlots.
CreateRandomCraftedItemsByItemType()
static List< ItemObject > Global.CreateRandomCraftedItemsByItemType (ItemObject.ItemTypeEnum? type, BasicCultureObject? culture, int num = 0) static
Definition at line 262 of file Global.cs.
{
        List<ItemObject> items  = new();
        Random           random = new();
        if (type == null || culture == null) return items;
        var templates = CraftingTemplatesByItemType[type.Value];
        for (var i = 0; i < num; i++) {
            var        randomElement = templates[random.Next() % templates.Length];
            TextObject textObject    = new("{=uZhHh7pm}Crafted {CURR_TEMPLATE_NAME}");
            _ = textObject.SetTextVariable("CURR_TEMPLATE_NAME", randomElement.TemplateName);
            Crafting crafting = new(randomElement, culture, textObject);
            crafting.Init();
            crafting.Randomize();
            var hashedCode = crafting.CurrentWeaponDesign.HashedCode;
            crafting.GetCurrentCraftedItemObject().StringId = hashedCode;
            var itemObject = MBObjectManager.Instance.GetObject<ItemObject>(hashedCode);
            if (itemObject == null) {
                itemObject = MBObjectManager.Instance.RegisterObject(crafting.GetCurrentCraftedItemObject());
                items.Add(itemObject);
            }
        }
        return items;
    }
References CraftingTemplatesByItemType.
Debug()
static void Global.Debug (string message) static
Definition at line 141 of file Global.cs.
{ Log(message, Colors.Green, Level.Debug, 2); }
References Log().
Error()
static void Global.Error (string message) static
Definition at line 147 of file Global.cs.
{ Log(message, Colors.Red, Level.Error, 2); }
References Log().
Fatal()
static void Global.Fatal (string message) static
Definition at line 149 of file Global.cs.
{ Log(message, Colors.Magenta, Level.Fatal, 2); }
References Log().
FullySameWeaponClass()
static bool Global.FullySameWeaponClass (ItemObject weapon1, ItemObject weapon2) static
Definition at line 171 of file Global.cs.
{
        //var list1 = GetWeaponClass(weapon1);
        //var list2 = GetWeaponClass(weapon2);
        //if (list1.Count != list2.Count) return false;
        if (weapon1.Weapons == null   ||
            weapon2.Weapons == null   ||
            weapon1.Weapons.IsEmpty() ||
            weapon2.Weapons.IsEmpty() ||
            weapon1.Weapons.Count != weapon2.Weapons.Count)
            return false;
        weapon1.Weapons.Sort((x, y) => x.WeaponClass - y.WeaponClass);
        weapon2.Weapons.Sort((x, y) => x.WeaponClass - y.WeaponClass);
        return !Enumerable.Range(0, weapon1.Weapons.Count)
                          .AnyQ(i => weapon1.Weapons[i].WeaponClass      != weapon2.Weapons[i].WeaponClass     ||
                                     weapon1.Weapons[i].SwingDamageType  != weapon2.Weapons[i].SwingDamageType ||
                                     weapon1.Weapons[i].ThrustDamageType != weapon2.Weapons[i].ThrustDamageType);
    }
GetAgentParty()
static ? MobileParty Global.GetAgentParty (IAgentOriginBase? origin) static
Definition at line 238 of file Global.cs.
{
        return origin switch {
                   null                                        => null,
                   PartyAgentOrigin partyAgentOrigin           => partyAgentOrigin.Party?.MobileParty,
                   PartyGroupAgentOrigin partyGroupAgentOrigin => partyGroupAgentOrigin.Party?.MobileParty,
                   SimpleAgentOrigin simpleAgentOrigin         => simpleAgentOrigin.Party?.MobileParty,
                   _                                           => null
               };
    }
GetWeaponClass()
static List< WeaponClass > Global.GetWeaponClass (ItemObject item) static
Definition at line 96 of file Global.cs.
{
        return item is { HasWeaponComponent: true }
                   ? item.WeaponComponent.Weapons.SelectQ(weapon => weapon.WeaponClass)
                         .Distinct()
                         .OrderByQ(weaponClass => weaponClass)
                         .ToListQ()
                   : new List<WeaponClass>();
    }
HaveSameWeaponClass()
static bool Global.HaveSameWeaponClass (List< WeaponClass > list1, List< WeaponClass > list2) static
Definition at line 151 of file Global.cs.
{
        var thrown1 = list1.WhereQ(weaponClass =>
                                       weaponClass is WeaponClass.ThrowingKnife
                                                      or WeaponClass.ThrowingAxe
                                                      or WeaponClass.Stone
                                                      or WeaponClass.Javelin)
                           .ToArrayQ();
        if (!thrown1.IsEmpty()) return list2.AnyQ(weaponClass => thrown1.Contains(weaponClass));
        var thrown2 = list2.WhereQ(weaponClass =>
                                       weaponClass is WeaponClass.ThrowingKnife
                                                      or WeaponClass.ThrowingAxe
                                                      or WeaponClass.Stone
                                                      or WeaponClass.Javelin)
                           .ToArrayQ();
        // 直接返回判断条件的结果
        return !thrown2.IsEmpty() && list1.AnyQ(weaponClass => thrown2.Contains(weaponClass));
    }
Info()
static void Global.Info (string message) static
Definition at line 143 of file Global.cs.
{ Log(message, Colors.Blue, Level.Info, 2); }
References Log().
InitializeCraftingTemplatesByItemType()
static void Global.InitializeCraftingTemplatesByItemType () static
Definition at line 81 of file Global.cs.
{
        ItemObject.ItemTypeEnum[] itemTypes = {
                                                  ItemObject.ItemTypeEnum.OneHandedWeapon,
                                                  ItemObject.ItemTypeEnum.TwoHandedWeapon,
                                                  ItemObject.ItemTypeEnum.Polearm
                                              };
        foreach (var itemType in itemTypes) {
            CraftingTemplate[] templates = CraftingTemplate
                                           .All.WhereQ(template => template.ItemType == itemType)
                                           .ToArrayQ();
            CraftingTemplatesByItemType[itemType] = templates;
        }
    }
References CraftingTemplatesByItemType.
IsAmmoAndEmpty()
static bool Global.IsAmmoAndEmpty (MissionWeapon? mw) static private
Definition at line 220 of file Global.cs.
{
        return mw is { IsEmpty: false, Item.HasWeaponComponent: true, Amount: 0 } &&
               (mw.Value.IsAnyAmmo() || mw.Value.Item.IsThrowing());
    }
Referenced by ProcessAgentEquipment().
IsInPlayerParty()
static bool Global.IsInPlayerParty (IAgentOriginBase? agentOrigin) static
Definition at line 225 of file Global.cs.
{
        if (agentOrigin == null) return false;
        var party = agentOrigin switch {
                        PartyAgentOrigin partyAgentOrigin           => partyAgentOrigin.Party,
                        PartyGroupAgentOrigin partyGroupAgentOrigin => partyGroupAgentOrigin.Party,
                        SimpleAgentOrigin simpleAgentOrigin         => simpleAgentOrigin.Party,
                        _                                           => null
                    };
        return party != null ? IsPartyInPlayerCommand(party) : agentOrigin.IsUnderPlayersCommand;
    }
References IsPartyInPlayerCommand().
IsPartyInPlayerCommand()
static bool Global.IsPartyInPlayerCommand (PartyBase? party) static private
Definition at line 248 of file Global.cs.
{
        return party != null && party == PartyBase.MainParty;
    }
Referenced by IsInPlayerParty().
Log()
static void Global.Log (string message, Color color, Level level, int skipFrames = 1) static
Definition at line 105 of file Global.cs.
{
        if (SubModule.Settings is { DebugMode: true } &&
            (SubModule.Settings.LogLevel.SelectedValue == Level.All ||
             level                                     >= SubModule.Settings.LogLevel.SelectedValue)) {
            // 显示信息
            InformationManager.DisplayMessage(new InformationMessage(message, color));
            // 使用 log4net 记录日志
            StackFrame frame  = new(skipFrames, true); // 创建 StackFrame 对象，参数 1 表示上一个栈帧
            var        method = frame.GetMethod();     // 获取方法信息
            // 获取文件名而不是完整路径
            var fileName = Path.GetFileName(frame.GetFileName());
            var lineNumber = frame.GetFileLineNumber(); // 获取行号
            // 构造日志消息
            var logMessage = $"[{method.DeclaringType?.FullName}.{method.Name}] [{fileName}:{lineNumber}] {message}";
            // 获取 log4net 日志实例
            //LogManager.GetLogger(method.DeclaringType);
            var log = LogManager.GetLogger("dtes");
            // 根据指定的日志级别记录日志
            if (level == Level.Debug)
                log.Debug(logMessage);
            else if (level == Level.Info)
                log.Info(logMessage);
            else if (level == Level.Warn)
                log.Warn(logMessage);
            else if (level == Level.Error)
                log.Error(logMessage);
            else if (level == Level.Fatal) log.Fatal(logMessage);
        }
    }
References ModSettings.LogLevel, and SubModule.Settings.
Referenced by Debug(), Error(), Fatal(), Info(), ProcessAgentEquipment(), and Warn().
ProcessAgentEquipment()
static void Global.ProcessAgentEquipment (Agent agent, Action< ItemObject > processEquipmentItem) static
Definition at line 190 of file Global.cs.
{
        if (!agent.IsValid()) return;
        var missionEquipment = agent.Equipment;
        var spawnEquipment   = agent.SpawnEquipment;
        if (missionEquipment == null || spawnEquipment == null) return;
        // 处理武器槽装备
        foreach (var slot in Assignment.WeaponSlots) {
            var element = missionEquipment[slot];
            if (element.IsEmpty || element.Item == null) continue;
            if (IsAmmoAndEmpty(element)) {
                Log($"Empty Ammo {element.Item.StringId}", Colors.Green, Level.Debug);
                continue;
            }
            processEquipmentItem(element.Item);
        }
        // 处理装甲和马匹槽装备
        foreach (var slot in ArmourAndHorsesSlots) {
            var element = spawnEquipment[slot];
            if (element.IsEmpty || element.Item == null) continue;
            processEquipmentItem(element.Item);
        }
    }
References ArmourAndHorsesSlots, IsAmmoAndEmpty(), Log(), and Assignment.WeaponSlots.
Warn()
static void Global.Warn (string message) static
Definition at line 145 of file Global.cs.
{ Log(message, Colors.Yellow, Level.Warn, 2); }
References Log().
Member Data Documentation
ArmourAndHorsesSlots
readonly EquipmentIndex [] Global.ArmourAndHorsesSlots static
Initial value:
= {
                                                                       EquipmentIndex.Head,
                                                                       EquipmentIndex.Body,
                                                                       EquipmentIndex.Leg,
                                                                       EquipmentIndex.Gloves,
                                                                       EquipmentIndex.Cape,
                                                                       EquipmentIndex.Horse,
                                                                       EquipmentIndex.HorseHarness
                                                                   }
Definition at line 36 of file Global.cs.
Referenced by ProcessAgentEquipment().
ArmourSlots
EquipmentIndex [] Global.ArmourSlots static
Initial value:
= {
                                                     EquipmentIndex.Head,
                                                     EquipmentIndex.Body,
                                                     EquipmentIndex.Leg,
                                                     EquipmentIndex.Gloves,
                                                     EquipmentIndex.Cape
                                                 }
Definition at line 46 of file Global.cs.
CraftingTemplatesByItemType
readonly Dictionary<ItemObject.ItemTypeEnum, CraftingTemplate[]> Global.CraftingTemplatesByItemType = new() static private
Definition at line 79 of file Global.cs.
Referenced by CreateRandomCraftedItemsByItemType(), and InitializeCraftingTemplatesByItemType().
EquipmentSlots
readonly EquipmentIndex [] Global.EquipmentSlots static
Initial value:
= {
                                                                 EquipmentIndex.Weapon0,
                                                                 EquipmentIndex.Weapon1,
                                                                 EquipmentIndex.Weapon2,
                                                                 EquipmentIndex.Weapon3,
                                                                 EquipmentIndex.Head,
                                                                 EquipmentIndex.Body,
                                                                 EquipmentIndex.Leg,
                                                                 EquipmentIndex.Gloves,
                                                                 EquipmentIndex.Cape,
                                                                 EquipmentIndex.Horse,
                                                                 EquipmentIndex.HorseHarness
                                                             }
Definition at line 22 of file Global.cs.
InvalidWeaponClasses
WeaponClass [] Global.InvalidWeaponClasses static
Initial value:
= {
                                                           WeaponClass.Undefined,
                                                           WeaponClass.Boulder,
                                                           WeaponClass.Banner,
                                                           WeaponClass.Stone
                                                       }
Definition at line 72 of file Global.cs.
ItemTypes
ItemObject.ItemTypeEnum [] Global.ItemTypes static
Initial value:
= {
                                                            ItemObject.ItemTypeEnum.BodyArmor,
                                                            ItemObject.ItemTypeEnum.LegArmor,
                                                            ItemObject.ItemTypeEnum.HeadArmor,
                                                            ItemObject.ItemTypeEnum.HandArmor,
                                                            ItemObject.ItemTypeEnum.Cape,
                                                            ItemObject.ItemTypeEnum.Horse,
                                                            ItemObject.ItemTypeEnum.HorseHarness,
                                                            ItemObject.ItemTypeEnum.Bow,
                                                            ItemObject.ItemTypeEnum.Crossbow,
                                                            ItemObject.ItemTypeEnum.OneHandedWeapon,
                                                            ItemObject.ItemTypeEnum.TwoHandedWeapon,
                                                            ItemObject.ItemTypeEnum.Polearm,
                                                            ItemObject.ItemTypeEnum.Arrows,
                                                            ItemObject.ItemTypeEnum.Bolts,
                                                            ItemObject.ItemTypeEnum.Thrown
                                                        }
Definition at line 54 of file Global.cs.
The documentation for this class was generated from the following file:
Global.cs