动态装备系统: ArmyArmory Class Reference
ArmyArmory Class Reference
Static Public Member Functions
static void AddItemToArmory (ItemObject item, int count=1)
static void AssignEquipment (Equipment equipment)
static void DebugClearEmptyItem ()
static void DebugRemovePlayerCraftedItems ()
static void Export ()
static void Import ()
static void RebuildArmory ()
static void ReturnEquipmentToArmoryFromAgents (IEnumerable< Agent > agents)
static void SellExcessEquipmentForThrowingWeapons ()
Static Public Attributes
static ItemRoster Armory = new()
Static Private Member Functions
static int SellExcessEquipment ()
Static Private Attributes
static ? ItemObject[] _cachedThrownWeapons
Detailed Description
Definition at line 24 of file ArmyArmory.cs.
Member Function Documentation
AddItemToArmory()
static void ArmyArmory.AddItemToArmory (ItemObject item, int count = 1) static
Definition at line 29 of file ArmyArmory.cs.
{
        if (!ItemBlackList.Test(item)) return;
        _ = Armory.AddToCounts(item, count);
    }
References ItemBlackList.Test().
Referenced by RecruitmentPatch.Prefix(), BuyMercenariesPatch.Prefix(), DynamicTroopMissionLogic.ReturnEquipmentFromAgents(), DynamicTroopMissionLogic.ReturnItemsToDestination(), and SellExcessEquipmentForThrowingWeapons().
AssignEquipment()
static void ArmyArmory.AssignEquipment (Equipment equipment) static
Definition at line 54 of file ArmyArmory.cs.
{
        foreach (var slot in Global.EquipmentSlots) {
            var element = equipment.GetEquipmentFromSlot(slot);
            // 使用模式匹配来检查条件，并反转if语句来减少嵌套
            if (element.IsEmpty || element.Item is null) continue;
            var itemToAssign =
                Armory.FirstOrDefaultQ(a => !a.IsEmpty                                                &&
                                            a.EquipmentElement.Item.StringId == element.Item.StringId &&
                                            a.Amount                         > 0);
            if (!itemToAssign.IsEmpty)
                _ = Armory.AddToCounts(itemToAssign.EquipmentElement, -1);
            else
                Global.Log($"Assigning Empty item {element.Item.StringId}", Colors.Red, Level.Warn);
        }
    }
Referenced by SpawnAgentPatch.AssignOrSpawnEquipment().
DebugClearEmptyItem()
static void ArmyArmory.DebugClearEmptyItem () static
Definition at line 139 of file ArmyArmory.cs.
{
        var toRemove = Armory
                       .WhereQ(kv => kv is not {
                                                   IsEmpty         : false,
                                                   EquipmentElement: { IsEmpty: false, Item: not null },
                                                   Amount          : > 0
                                               }                                                          ||
                                     kv.EquipmentElement.Item.ItemType == ItemObject.ItemTypeEnum.Invalid ||
                                     kv.EquipmentElement.Item.StringId == null                            ||
                                     kv.EquipmentElement.Item.StringId.IsEmpty())
                       .ToArrayQ();
        if (toRemove == null) return;
        foreach (var item in toRemove) Armory.Remove(item);
        Global.Debug($"Removed {toRemove.Length} empty entries from player's armory");
    }
DebugRemovePlayerCraftedItems()
static void ArmyArmory.DebugRemovePlayerCraftedItems () static
Definition at line 172 of file ArmyArmory.cs.
{
        var toRemove = Armory
                       .WhereQ(kv => kv is not {
                                                   IsEmpty         : false,
                                                   EquipmentElement: { IsEmpty: false, Item.IsCraftedByPlayer: true }
                                               })
                       .ToArrayQ();
        if (toRemove == null) return;
        foreach (var item in toRemove) Armory.Remove(item);
        Global.Debug($"Removed {toRemove.Length} player crafted entries from player's armory");
    }
Export()
static void ArmyArmory.Export () static
Definition at line 208 of file ArmyArmory.cs.
{
        try {
            Dictionary<string, int> dict = new();
            foreach (var rosterElement in Armory) {
                var stringId = rosterElement.EquipmentElement.Item?.StringId;
                var cnt      = rosterElement.Amount;
                if (stringId == null || cnt <= 0) continue;
                if (dict.ContainsKey(stringId)) { dict[stringId] += cnt; }
                else { dict.Add(stringId, cnt); }
            }
            // 使用 Newtonsoft.Json 的 JsonSerializer 进行序列化
            var json = JsonConvert.SerializeObject(dict, Formatting.Indented);
            // 写入到 armory.json 文件
            var filename = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "../../armory.json");
            File.WriteAllText(filename, json);
            Global.Debug($"Successfully export armory to {filename}");
        }
        catch (Exception e) { Global.Error(e.Message); }
    }
Import()
static void ArmyArmory.Import () static
Definition at line 186 of file ArmyArmory.cs.
{
        try {
            // 获取 armory.json 文件的完整路径
            var filePath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "../../armory.json");
            // 读取文件内容
            var json = File.ReadAllText(filePath);
            // 使用 Newtonsoft.Json 的 JsonSerializer 进行反序列化
            var dict = JsonConvert.DeserializeObject<Dictionary<string, int>>(json);
            Armory.Clear();
            foreach (var kpv in dict) {
                var item = MBObjectManager.Instance.GetObject<ItemObject>(kpv.Key);
                if (item != null) { _ = Armory.AddToCounts(item, kpv.Value); }
                else { Global.Warn($"cannot get object {kpv.Key}"); }
            }
            Global.Debug($"Successfully export armory from {filePath}");
        }
        catch (Exception e) { Global.Error(e.Message); }
    }
RebuildArmory()
static void ArmyArmory.RebuildArmory () static
Definition at line 157 of file ArmyArmory.cs.
{
        var toAdd = Armory
                    .WhereQ(kv => kv is {
                                            IsEmpty         : false,
                                            EquipmentElement: { IsEmpty: false, Item: not null },
                                            Amount          : > 0
                                        })
                    .ToArrayQ();
        Armory = new ItemRoster();
        if (toAdd == null) return;
        Armory.Add(toAdd);
        Global.Debug($"Armory has been rebuilt with {toAdd.Length} entries");
    }
Referenced by SellExcessEquipment().
ReturnEquipmentToArmoryFromAgents()
static void ArmyArmory.ReturnEquipmentToArmoryFromAgents (IEnumerable< Agent > agents) static
Definition at line 34 of file ArmyArmory.cs.
{
        Global.Log("ReturnEquipmentToArmoryFromAgents", Colors.Green, Level.Debug);
        var count = 0;
        foreach (var agent in agents)
            if (agent.IsValid()) {
                Global.Log($"Returning equipment of agent {agent.Character.StringId}", Colors.Green, Level.Debug);
                Global.ProcessAgentEquipment(agent,
                                             item => {
                                                 _ = Armory.AddToCounts(item, 1);
                                                 Global.Log($"equipment {item.StringId} returned",
                                                            Colors.Green,
                                                            Level.Debug);
                                                 count++;
                                             });
            }
        Global.Log($"{count} equipment reclaimed", Colors.Green, Level.Debug);
    }
SellExcessEquipment()
static int ArmyArmory.SellExcessEquipment () static private
Definition at line 96 of file ArmyArmory.cs.
{
        RebuildArmory();
        var excessValue = 0;
        var playerParty = MobileParty.MainParty;
        if (playerParty?.MemberRoster?.GetTroopRoster() == null) return 0;
        var memberCnt = playerParty.MemberRoster.GetTroopRoster()
                                   .WhereQ(element => element.Character is { IsHero: false })
                                   .SumQ(element => element.Number);
        foreach (var equipmentAndThreshold in EveryoneCampaignBehavior.EquipmentAndThresholds) {
            var armorTotalCount = Armory.WhereQ(kv => kv.EquipmentElement.Item?.ItemType == equipmentAndThreshold.Key)
                                        .SumQ(kv => kv.Amount);
            var surplusCount = armorTotalCount - equipmentAndThreshold.Value(memberCnt);
            if (surplusCount <= 0) continue;
            var surplusCountCpy = surplusCount;
            // 创建优先级队列
            ItemPriorityQueue armorQueue = new(new ArmorElementComparer());
            foreach (var kv in Armory.WhereQ(kv => kv.EquipmentElement.Item?.ItemType == equipmentAndThreshold.Key))
                armorQueue.Enqueue(kv.EquipmentElement, kv.EquipmentElement.ItemValue);
            // 移除多余的装备
            while (surplusCount > 0 && !armorQueue.IsEmpty) {
                var lowestArmor = armorQueue.Dequeue();
                var countToRemove = Math.Min(Armory.GetElementNumber(Armory.FindIndexOfElement(lowestArmor.Key)),
                                             surplusCount);
                //Global.Debug($"countToRemove={countToRemove}, lowestArmorNumber={Armory.GetItemNumber(lowestArmor.Key)}");
                _            =  Armory.AddToCounts(lowestArmor.Key, -countToRemove); // 减少数量
                surplusCount -= countToRemove;
                excessValue  += countToRemove * lowestArmor.Key.ItemValue;
                Global.Debug($"Sold {countToRemove}x{lowestArmor.Key.ItemValue} from player's armory");
            }
            Global.Debug($"Sold {surplusCountCpy - surplusCount}x{equipmentAndThreshold.Key} items from player's armory");
        }
        Global.Debug($"Sold {excessValue} denars worth of equipment from player's armory");
        return excessValue;
    }
References EveryoneCampaignBehavior.EquipmentAndThresholds, and RebuildArmory().
Referenced by SellExcessEquipmentForThrowingWeapons().
SellExcessEquipmentForThrowingWeapons()
static void ArmyArmory.SellExcessEquipmentForThrowingWeapons () static
Definition at line 73 of file ArmyArmory.cs.
{
        var value         = SellExcessEquipment();
        var originalValue = value;
        _cachedThrownWeapons ??= MBObjectManager.Instance.GetObjectTypeList<ItemObject>()
                                                ?.WhereQ(item => item.IsThrowingWeaponCanBeAcquired())
                                                .ToArrayQ();
        var cnt = 0;
        while (value > 0) {
            var item = _cachedThrownWeapons.GetRandomElement();
            if (item != null) {
                AddItemToArmory(item);
                value -= item.Value;
                cnt++;
            }
        }
        InformationManager.DisplayMessage(new InformationMessage(LocalizedTexts
                                                                     .GetSoldExcessEquipmentForThrowingWeapons(originalValue -
                                                                                                               value,
                                                                                                               cnt),
                                                                 Colors.Green));
    }
References _cachedThrownWeapons, AddItemToArmory(), and SellExcessEquipment().
Member Data Documentation
_cachedThrownWeapons
? ItemObject [] ArmyArmory._cachedThrownWeapons static private
Definition at line 27 of file ArmyArmory.cs.
Referenced by SellExcessEquipmentForThrowingWeapons().
Armory
ItemRoster ArmyArmory.Armory = new() static
Definition at line 25 of file ArmyArmory.cs.
Referenced by DynamicTroopMissionLogic.AfterStart(), ArmyArmoryBehavior.Load(), ArmyArmoryBehavior.OnNewGameCreated(), ArmyArmoryBehavior.Save(), and ArmyArmoryBehavior.SyncData().
The documentation for this class was generated from the following file:
ArmyArmory.cs