动态装备系统: MessageDisplayService Class Reference
MessageDisplayService Class Reference
Static Public Member Functions
static void EnqueueMessage (InformationMessage message)
static void StopService ()
static void Tick (float dt)
Static Private Attributes
static float _timeSinceLastMessage
static readonly ConcurrentQueue< InformationMessage > MessageQueue = new()
Detailed Description
Definition at line 4 of file MessageDisplayService.cs.
Member Function Documentation
EnqueueMessage()
static void MessageDisplayService.EnqueueMessage (InformationMessage message) static
Definition at line 9 of file MessageDisplayService.cs.
{
        MessageQueue.Enqueue(message);
    }
References MessageQueue.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.ApplyCapturedArmoryLoss(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.HandlePartyItems(), DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipmentForThrowingWeapons().
StopService()
static void MessageDisplayService.StopService () static
Definition at line 23 of file MessageDisplayService.cs.
{
        while (MessageQueue.TryDequeue(out _)) { }
        _timeSinceLastMessage = 0f;
    }
References _timeSinceLastMessage, and MessageQueue.
Referenced by DynamicTroopEquipmentReupload.SubModule.OnSubModuleUnloaded().
Tick()
static void MessageDisplayService.Tick (float dt) static
Definition at line 13 of file MessageDisplayService.cs.
{
        _timeSinceLastMessage += dt;
        if (_timeSinceLastMessage < 0.05f)
            return;
        _timeSinceLastMessage = 0f;
        if (MessageQueue.TryDequeue(out var message))
            InformationManager.DisplayMessage(message);
    }
References _timeSinceLastMessage, and MessageQueue.
Referenced by DynamicTroopEquipmentReupload.SubModule.OnApplicationTick().
Member Data Documentation
_timeSinceLastMessage
float MessageDisplayService._timeSinceLastMessage static private
Definition at line 7 of file MessageDisplayService.cs.
Referenced by StopService(), and Tick().
MessageQueue
readonly ConcurrentQueue<InformationMessage> MessageDisplayService.MessageQueue = new() static private
Definition at line 6 of file MessageDisplayService.cs.
Referenced by EnqueueMessage(), StopService(), and Tick().
The documentation for this class was generated from the following file:
MessageDisplayService.cs