动态装备系统: DynamicTroopEquipmentReupload.ArmyArmory Class Reference
DynamicTroopEquipmentReupload.ArmyArmory Class Reference
Static Public Member Functions
static void AddItemToArmory (ItemObject item, int count=1)
static void AssignEquipment (Equipment equipment)
static void DebugClearEmptyItem ()
static void DebugRemovePlayerCraftedItems ()
static void Export ()
static void Import ()
static void RebuildArmory ()
static void ResetForCampaign ()
static void ReturnEquipmentToArmoryFromAgents (IEnumerable< Agent > agents)
static int SanitizeInPlace (bool forceRebuild=false)
static void SellExcessEquipmentForThrowingWeapons ()
Static Public Attributes
static readonly ItemRoster Armory = new()
Static Package Functions
static ? ItemObject ResolveArmoryItem (string? itemId)
static bool TryNormalizeArmoryElement (EquipmentElement equipmentElement, out EquipmentElement normalizedElement)
static bool TryResolveArmoryItem (ItemObject? item, out ItemObject resolvedItem)
Static Private Member Functions
static ? ItemObject GetRandomItem (ItemObject[]? items)
static bool IsUsableArmoryItem (ItemObject? item)
static ? ItemModifier ResolveArmoryModifier (ItemModifier? itemModifier)
static int SellExcessEquipment ()
Static Private Attributes
static ? ItemObject[] _cachedArrows
static ? ItemObject[] _cachedBolts
static ? ItemObject[] _cachedThrownWeapons
Detailed Description
Definition at line 26 of file ArmyArmory.cs.
Member Function Documentation
AddItemToArmory()
static void DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory (ItemObject item, int count = 1) static
Definition at line 94 of file ArmyArmory.cs.
{
        if (count <= 0 || !TryResolveArmoryItem(item, out var resolvedItem) || !ItemBlackList.Test(resolvedItem))
            return;
        _ = Armory.AddToCounts(resolvedItem, count);
    }
References Armory, DynamicTroopEquipmentReupload.ItemBlackList.Test(), and TryResolveArmoryItem().
Referenced by DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.AddStartingEquipmentToPlayerArmory(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnEquipmentFromAgents(), ReturnEquipmentToArmoryFromAgents(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnItemsToDestination(), and SellExcessEquipmentForThrowingWeapons().
AssignEquipment()
static void DynamicTroopEquipmentReupload.ArmyArmory.AssignEquipment (Equipment equipment) static
Definition at line 181 of file ArmyArmory.cs.
{
        foreach (var slot in Global.EquipmentSlots) {
            if ((Mission.Current?.IsNavalBattle == true ||
                 Mission.Current?.IsNavalRaidBattle == true ||
                 Mission.Current?.HasMissionBehavior<HideoutMissionController>() == true ||
                 Mission.Current?.HasMissionBehavior<MissionSiegeEnginesLogic>() == true) &&
                (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness))
                continue;
            // 使用模式匹配来检查条件，并反转if语句来减少嵌套
            var element = equipment.GetEquipmentFromSlot(slot);
            if (!TryResolveArmoryItem(element.Item, out var itemToConsume))
                continue;
            var armoryElement = Armory.FirstOrDefaultQ(rosterElement =>
                rosterElement.Amount > 0 &&
                TryResolveArmoryItem(rosterElement.EquipmentElement.Item, out var armoryItem) &&
                armoryItem.StringId == itemToConsume.StringId);
            if (!armoryElement.IsEmpty)
                _ = Armory.AddToCounts(armoryElement.EquipmentElement, -1);
            else
                Global.Log($"Assigning Empty item {itemToConsume.StringId}", Colors.Red, Level.Warn);
        }
    }
References Armory, DynamicTroopEquipmentReupload.Global.EquipmentSlots, DynamicTroopEquipmentReupload.Global.Log(), and TryResolveArmoryItem().
Referenced by DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix().
DebugClearEmptyItem()
static void DynamicTroopEquipmentReupload.ArmyArmory.DebugClearEmptyItem () static
Definition at line 436 of file ArmyArmory.cs.
{
        var removedEntries = SanitizeInPlace();
        Global.Debug($"Removed {removedEntries} invalid entries from player's armory");
    }
References DynamicTroopEquipmentReupload.Global.Debug(), and SanitizeInPlace().
DebugRemovePlayerCraftedItems()
static void DynamicTroopEquipmentReupload.ArmyArmory.DebugRemovePlayerCraftedItems () static
Definition at line 446 of file ArmyArmory.cs.
{
        var toRemove = Armory
                       .WhereQ(kv => kv is {
                                               IsEmpty         : false,
                                               EquipmentElement: { IsEmpty: false, Item.IsCraftedByPlayer: true }
                                           })
                       .ToArrayQ();
        if (toRemove == null) return;
        foreach (var item in toRemove) Armory.Remove(item);
        Global.Debug($"Removed {toRemove.Length} player crafted entries from player's armory");
    }
References Armory, and DynamicTroopEquipmentReupload.Global.Debug().
Export()
static void DynamicTroopEquipmentReupload.ArmyArmory.Export () static
Definition at line 487 of file ArmyArmory.cs.
{
        try {
            SanitizeInPlace();
            Dictionary<string, int> dict = new();
            foreach (var rosterElement in Armory) {
                var stringId = rosterElement.EquipmentElement.Item?.StringId;
                var cnt      = rosterElement.Amount;
                if (stringId == null || cnt <= 0) continue;
                if (dict.ContainsKey(stringId)) { dict[stringId] += cnt; }
                else { dict.Add(stringId, cnt); }
            }
            // 使用 Newtonsoft.Json 的 JsonSerializer 进行序列化
            var json = JsonConvert.SerializeObject(dict, Formatting.Indented);
            // 写入到 armory.json 文件
            var filename = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "../../armory.json");
            File.WriteAllText(filename, json);
            Global.Debug($"Successfully export armory to {filename}");
        }
        catch (Exception e) { Global.Error(e.Message); }
    }
References Armory, DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Global.Error(), and SanitizeInPlace().
GetRandomItem()
static ? ItemObject DynamicTroopEquipmentReupload.ArmyArmory.GetRandomItem (ItemObject?[] items) static private
Definition at line 207 of file ArmyArmory.cs.
{
        return items is { Length: > 0 } ? items.GetRandomElement() : null;
    }
Referenced by SellExcessEquipmentForThrowingWeapons().
Import()
static void DynamicTroopEquipmentReupload.ArmyArmory.Import () static
Definition at line 460 of file ArmyArmory.cs.
{
        try {
            // 获取 armory.json 文件的完整路径
            var filePath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "../../armory.json");
            // 读取文件内容
            var json = File.ReadAllText(filePath);
            // 使用 Newtonsoft.Json 的 JsonSerializer 进行反序列化
            var dict = JsonConvert.DeserializeObject<Dictionary<string, int>>(json);
            if (dict == null) {
                Global.Warn("armory.json is empty or invalid");
                return;
            }
            Armory.Clear();
            foreach (var kpv in dict) {
                var item = ResolveArmoryItem(kpv.Key);
                if (item != null && kpv.Value > 0) { _ = Armory.AddToCounts(item, kpv.Value); }
                else { Global.Warn($"cannot get object {kpv.Key}"); }
            }
            Global.Debug($"Successfully imported armory from {filePath}");
        }
        catch (Exception e) { Global.Error(e.Message); }
    }
References Armory, DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.Global.Error(), ResolveArmoryItem(), and DynamicTroopEquipmentReupload.Global.Warn().
IsUsableArmoryItem()
static bool DynamicTroopEquipmentReupload.ArmyArmory.IsUsableArmoryItem (ItemObject? item) static private
Definition at line 86 of file ArmyArmory.cs.
{
        return item != null &&
               item.IsReady &&
               item.ItemType != ItemObject.ItemTypeEnum.Invalid &&
               !string.IsNullOrEmpty(item.StringId) &&
               !TextObject.IsNullOrEmpty(item.Name);
    }
Referenced by ResolveArmoryItem().
RebuildArmory()
static void DynamicTroopEquipmentReupload.ArmyArmory.RebuildArmory () static
Definition at line 441 of file ArmyArmory.cs.
{
        var removedEntries = SanitizeInPlace(forceRebuild: true);
        Global.Debug($"Armory rebuilt in place, removed {removedEntries} invalid entries");
    }
References DynamicTroopEquipmentReupload.Global.Debug(), and SanitizeInPlace().
ResetForCampaign()
static void DynamicTroopEquipmentReupload.ArmyArmory.ResetForCampaign () static
Definition at line 101 of file ArmyArmory.cs.
{
        Armory.Clear();
        _cachedThrownWeapons = null;
        _cachedArrows = null;
        _cachedBolts = null;
    }
References _cachedArrows, _cachedBolts, _cachedThrownWeapons, and Armory.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnNewGameCreated(), and DynamicTroopEquipmentReupload.ArmyArmoryBehavior.SyncData().
ResolveArmoryItem()
static ? ItemObject DynamicTroopEquipmentReupload.ArmyArmory.ResolveArmoryItem (string? itemId) static package
Definition at line 34 of file ArmyArmory.cs.
{
        if (string.IsNullOrEmpty(itemId))
            return null;
        var item = MBObjectManager.Instance.GetObject<ItemObject>(itemId) ??
                   ItemObject.GetCraftedItemObjectFromHashedCode(itemId);
        return IsUsableArmoryItem(item) ? item : null;
    }
References IsUsableArmoryItem().
Referenced by Import(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.RestoreReadyArmoryItems(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.RestoreReadyPartyArmories(), and TryResolveArmoryItem().
ResolveArmoryModifier()
static ? ItemModifier DynamicTroopEquipmentReupload.ArmyArmory.ResolveArmoryModifier (ItemModifier? itemModifier) static private
Definition at line 74 of file ArmyArmory.cs.
{
        if (itemModifier == null)
            return null;
        if (!itemModifier.IsReady ||
            string.IsNullOrEmpty(itemModifier.StringId) ||
            TextObject.IsNullOrEmpty(itemModifier.Name))
            return null;
        return MBObjectManager.Instance.GetObject<ItemModifier>(itemModifier.StringId);
    }
Referenced by TryNormalizeArmoryElement().
ReturnEquipmentToArmoryFromAgents()
static void DynamicTroopEquipmentReupload.ArmyArmory.ReturnEquipmentToArmoryFromAgents (IEnumerable< Agent > agents) static
Definition at line 161 of file ArmyArmory.cs.
{
        Global.Log("ReturnEquipmentToArmoryFromAgents", Colors.Green, Level.Debug);
        var count = 0;
        foreach (var agent in agents)
            if (agent.IsValid()) {
                Global.Log($"Returning equipment of agent {agent.Character.StringId}", Colors.Green, Level.Debug);
                Global.ProcessAgentEquipment(agent,
                                             item => {
                                                 AddItemToArmory(item);
                                                 Global.Log($"equipment {item.StringId} returned",
                                                            Colors.Green,
                                                            Level.Debug);
                                                 count++;
                                             });
            }
        Global.Log($"{count} equipment reclaimed", Colors.Green, Level.Debug);
    }
References AddItemToArmory(), DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.Global.ProcessAgentEquipment().
SanitizeInPlace()
static int DynamicTroopEquipmentReupload.ArmyArmory.SanitizeInPlace (bool forceRebuild = false) static
Definition at line 108 of file ArmyArmory.cs.
{
        var discardedEntryCount = 0;
        var requiresRebuild = forceRebuild;
        var normalizedEntries = new HashSet<(ItemObject Item, ItemModifier? Modifier)>();
        foreach (var rosterElement in Armory) {
            if (rosterElement.Amount <= 0 ||
                rosterElement.IsEmpty ||
                !TryNormalizeArmoryElement(rosterElement.EquipmentElement, out var normalizedElement)) {
                discardedEntryCount++;
                requiresRebuild = true;
                continue;
            }
            var equipmentElement = rosterElement.EquipmentElement;
            if (!ReferenceEquals(equipmentElement.Item, normalizedElement.Item) ||
                !ReferenceEquals(equipmentElement.ItemModifier, normalizedElement.ItemModifier) ||
                !ReferenceEquals(equipmentElement.CosmeticItem, normalizedElement.CosmeticItem) ||
                equipmentElement.IsQuestItem != normalizedElement.IsQuestItem ||
                !normalizedEntries.Add((normalizedElement.Item, normalizedElement.ItemModifier)))
                requiresRebuild = true;
        }
        if (!requiresRebuild)
            return 0;
        var sanitizedEntries = new Dictionary<(ItemObject Item, ItemModifier? Modifier, ItemObject? CosmeticItem, bool IsQuestItem), int>();
        foreach (var rosterElement in Armory) {
            if (rosterElement.Amount <= 0 ||
                rosterElement.IsEmpty ||
                !TryNormalizeArmoryElement(rosterElement.EquipmentElement, out var normalizedElement))
                continue;
            var key = (normalizedElement.Item,
                normalizedElement.ItemModifier,
                normalizedElement.CosmeticItem,
                normalizedElement.IsQuestItem);
            sanitizedEntries[key] = sanitizedEntries.TryGetValue(key, out var currentCount)
                ? currentCount + rosterElement.Amount
                : rosterElement.Amount;
        }
        Armory.Clear();
        foreach (var entry in sanitizedEntries) {
            var equipmentElement = new EquipmentElement(entry.Key.Item,
                entry.Key.Modifier,
                entry.Key.CosmeticItem,
                entry.Key.IsQuestItem);
            Armory.AddToCounts(equipmentElement, entry.Value);
        }
        return discardedEntryCount;
    }
References Armory, and TryNormalizeArmoryElement().
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.ApplyCapturedArmoryLoss(), DebugClearEmptyItem(), Export(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnDailyTick(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnGameLoaded(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnSessionLaunched(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OpenArmoryScreen(), RebuildArmory(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.SaveArmory(), SellExcessEquipment(), and DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.TryInitializeDistributors().
SellExcessEquipment()
static int DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipment () static private
Definition at line 393 of file ArmyArmory.cs.
{
        SanitizeInPlace();
        var excessValue = 0;
        var playerParty = MobileParty.MainParty;
        if (playerParty?.MemberRoster?.GetTroopRoster() == null) return 0;
        var memberCnt = playerParty.MemberRoster.GetTroopRoster()
                                   .WhereQ(element => element.Character is { IsHero: false })
                                   .SumQ(element => element.Number);
        foreach (var equipmentAndThreshold in EveryoneCampaignBehavior.EquipmentAndThresholds) {
            var armorTotalCount = Armory.WhereQ(kv => kv.EquipmentElement.Item?.ItemType == equipmentAndThreshold.Key)
                                        .SumQ(kv => kv.Amount);
            var surplusCount = armorTotalCount - equipmentAndThreshold.Value(memberCnt);
            if (surplusCount <= 0) continue;
            var surplusCountCpy = surplusCount;
            // 创建优先级队列
            ItemPriorityQueue armorQueue = new(new ArmorElementComparer());
            foreach (var kv in Armory.WhereQ(kv => kv.EquipmentElement.Item?.ItemType == equipmentAndThreshold.Key))
                armorQueue.Enqueue(kv.EquipmentElement, kv.EquipmentElement.ItemValue);
            // 移除多余的装备
            while (surplusCount > 0 && !armorQueue.IsEmpty) {
                var lowestArmor = armorQueue.Dequeue();
                var countToRemove = Math.Min(Armory.GetElementNumber(Armory.FindIndexOfElement(lowestArmor.Key)),
                                             surplusCount);
                //Global.Debug($"countToRemove={countToRemove}, lowestArmorNumber={Armory.GetItemNumber(lowestArmor.Key)}");
                _            =  Armory.AddToCounts(lowestArmor.Key, -countToRemove); // 减少数量
                surplusCount -= countToRemove;
                excessValue  += countToRemove * lowestArmor.Key.ItemValue;
                Global.Debug($"Sold {countToRemove}x{lowestArmor.Key.ItemValue} from player's armory");
            }
            Global.Debug($"Sold {surplusCountCpy - surplusCount}x{equipmentAndThreshold.Key} items from player's armory");
        }
        Global.Debug($"Sold {excessValue} denars worth of equipment from player's armory");
        return excessValue;
    }
References Armory, DynamicTroopEquipmentReupload.Global.Debug(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.EquipmentAndThresholds, and SanitizeInPlace().
Referenced by SellExcessEquipmentForThrowingWeapons().
SellExcessEquipmentForThrowingWeapons()
static void DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipmentForThrowingWeapons () static
Definition at line 211 of file ArmyArmory.cs.
{
        var soldValue = SellExcessEquipment();
        if (soldValue <= 0)
        {
            MessageDisplayService.EnqueueMessage(new InformationMessage(
                LocalizedTexts.GetSoldExcessEquipmentForThrowingWeapons(0, 0, 0),
                Colors.Green));
            return;
        }
        _cachedThrownWeapons ??= MBObjectManager.Instance
            .GetObjectTypeList<ItemObject>()
            ?.WhereQ(item => TryResolveArmoryItem(item, out _) && item.Value > 0 && item.IsThrowingWeaponCanBeAcquired())
            .ToArrayQ() ?? Array.Empty<ItemObject>();
        _cachedArrows ??= MBObjectManager.Instance
            .GetObjectTypeList<ItemObject>()
            ?.WhereQ(item => TryResolveArmoryItem(item, out _) && item.IsArrow() && item.Value > 0)
            .ToArrayQ() ?? Array.Empty<ItemObject>();
        _cachedBolts ??= MBObjectManager.Instance
            .GetObjectTypeList<ItemObject>()
            ?.WhereQ(item => TryResolveArmoryItem(item, out _) && item.IsBolt() && item.Value > 0)
            .ToArrayQ() ?? Array.Empty<ItemObject>();
        var playerParty = MobileParty.MainParty;
        var troopRoster = playerParty?.MemberRoster?.GetTroopRoster();
        if (troopRoster == null) return;
        // (cavalry + infantry) = X, (horse archer + archers) = Y, X+Y=100
        var infantryAndCavalryCount = 0;
        var archerAndHorseArcherCount = 0;
        // split
        var bowUserCount = 0;
        var crossbowUserCount = 0;
        // weighting for type of ranged ammo / throwing weapon
        var preferredThrowingWeights = new Dictionary<ItemObject, int>();
        var preferredArrowWeights = new Dictionary<ItemObject, int>();
        var preferredBoltWeights = new Dictionary<ItemObject, int>();
        foreach (var troop in troopRoster)
        {
            if (troop.Character is not { IsHero: false } character) continue;
            var troopCount = troop.Number;
            if (troopCount <= 0) continue;
            var isRanged = character.IsRanged;
            if (isRanged)
                archerAndHorseArcherCount += troopCount;
            else
                infantryAndCavalryCount += troopCount;
            var referenceEquipment = character.RandomBattleEquipment;
            var usesBow = false;
            var usesCrossbow = false;
            ItemObject? preferredThrowing = null;
            ItemObject? preferredArrows = null;
            ItemObject? preferredBolts = null;
            foreach (var slot in Assignment.WeaponSlots)
            {
                var equipmentElement = referenceEquipment.GetEquipmentFromSlot(slot);
                if (equipmentElement is not { IsEmpty: false, Item: { } item }) continue;
                if (!usesBow && item.IsBow())
                    usesBow = true;
                if (!usesCrossbow && item.IsCrossBow())
                    usesCrossbow = true;
                if (preferredThrowing == null && item.IsThrowingWeaponCanBeAcquired())
                    preferredThrowing = item;
                if (preferredArrows == null && item.IsArrow())
                    preferredArrows = item;
                if (preferredBolts == null && item.IsBolt())
                    preferredBolts = item;
            }
            if (isRanged)
            {
                if (usesCrossbow)
                {
                    crossbowUserCount += troopCount;
                    if (preferredBolts != null)
                        preferredBoltWeights[preferredBolts] = preferredBoltWeights.TryGetValue(preferredBolts, out var count)
                            ? count + troopCount
                            : troopCount;
                }
                else if (usesBow)
                {
                    bowUserCount += troopCount;
                    if (preferredArrows != null)
                        preferredArrowWeights[preferredArrows] = preferredArrowWeights.TryGetValue(preferredArrows, out var count)
                            ? count + troopCount
                            : troopCount;
                }
            }
            else if (preferredThrowing != null)
            {
                preferredThrowingWeights[preferredThrowing] = preferredThrowingWeights.TryGetValue(preferredThrowing, out var count)
                    ? count + troopCount
                    : troopCount;
            }
        }
        static ItemObject? GetWeightedRandomItem(Dictionary<ItemObject, int> weightByItem) {
            if (weightByItem.Count == 0) return null;
            var totalWeight = 0;
            foreach (var kv in weightByItem)
                totalWeight += kv.Value;
            if (totalWeight <= 0) return null;
            var roll = MBRandom.RandomInt(totalWeight);
            foreach (var kv in weightByItem)
            {
                roll -= kv.Value;
                if (roll < 0)
                    return kv.Key;
            }
            return null;
        }
        var totalTroopCount = infantryAndCavalryCount + archerAndHorseArcherCount;
        var throwingBudget = totalTroopCount > 0
            ? (int)Math.Round(soldValue * (double)infantryAndCavalryCount / totalTroopCount)
            : soldValue;
        var ammoBudget = soldValue - throwingBudget;
        var totalRangedWeaponUsers = bowUserCount + crossbowUserCount;
        var arrowBudget = totalRangedWeaponUsers > 0
            ? (int)Math.Round(ammoBudget * (double)bowUserCount / totalRangedWeaponUsers)
            : ammoBudget;
        var boltBudget = ammoBudget - arrowBudget;
        var throwingCount = 0;
        var ammoCount = 0;
        var remainingThrowingBudget = throwingBudget;
        while (remainingThrowingBudget > 0)
        {
            var item = GetWeightedRandomItem(preferredThrowingWeights) ?? GetRandomItem(_cachedThrownWeapons);
            if (item == null || item.Value <= 0) break;
            AddItemToArmory(item);
            remainingThrowingBudget -= item.Value;
            throwingCount++;
        }
        var remainingArrowBudget = arrowBudget;
        while (remainingArrowBudget > 0)
        {
            var item = GetWeightedRandomItem(preferredArrowWeights) ?? GetRandomItem(_cachedArrows);
            if (item == null || item.Value <= 0) break;
            AddItemToArmory(item);
            remainingArrowBudget -= item.Value;
            ammoCount++;
        }
        var remainingBoltBudget = boltBudget;
        while (remainingBoltBudget > 0)
        {
            var item = GetWeightedRandomItem(preferredBoltWeights) ?? GetRandomItem(_cachedBolts);
            if (item == null || item.Value <= 0) break;
            AddItemToArmory(item);
            remainingBoltBudget -= item.Value;
            ammoCount++;
        }
        MessageDisplayService.EnqueueMessage(new InformationMessage(
            LocalizedTexts.GetSoldExcessEquipmentForThrowingWeapons(soldValue, throwingCount, ammoCount),
            Colors.Green));
    }
References _cachedArrows, _cachedBolts, _cachedThrownWeapons, AddItemToArmory(), MessageDisplayService.EnqueueMessage(), GetRandomItem(), DynamicTroopEquipmentReupload.LocalizedTexts.GetSoldExcessEquipmentForThrowingWeapons(), SellExcessEquipment(), TryResolveArmoryItem(), and DynamicTroopEquipmentReupload.Assignment.WeaponSlots.
TryNormalizeArmoryElement()
static bool DynamicTroopEquipmentReupload.ArmyArmory.TryNormalizeArmoryElement (EquipmentElement equipmentElement, out EquipmentElement normalizedElement) static package
Definition at line 57 of file ArmyArmory.cs.
{
        normalizedElement = default;
        if (!TryResolveArmoryItem(equipmentElement.Item, out var resolvedItem))
            return false;
        var itemModifier = ResolveArmoryModifier(equipmentElement.ItemModifier);
        var cosmeticItem = TryResolveArmoryItem(equipmentElement.CosmeticItem, out var resolvedCosmeticItem)
            ? resolvedCosmeticItem
            : null;
        normalizedElement = new EquipmentElement(resolvedItem,
            itemModifier,
            cosmeticItem,
            equipmentElement.IsQuestItem);
        return true;
    }
References ResolveArmoryModifier(), and TryResolveArmoryItem().
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AddEquipmentToAssign(), DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.CreateSanitizedRoster(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.MeasureMainPartyArmoryReadiness(), and SanitizeInPlace().
TryResolveArmoryItem()
static bool DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem (ItemObject? item, out ItemObject resolvedItem) static package
Definition at line 44 of file ArmyArmory.cs.
{
        resolvedItem = null!;
        if (item == null || string.IsNullOrEmpty(item.StringId))
            return false;
        var canonicalItem = ResolveArmoryItem(item.StringId);
        if (canonicalItem == null)
            return false;
        resolvedItem = canonicalItem;
        return true;
    }
References ResolveArmoryItem().
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PartyEquipmentDistributor(), AddItemToArmory(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.AddItemToPartyArmory(), AssignEquipment(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.CreateSerializedPartyArmories(), DynamicTroopEquipmentReupload.Cache.GetItemsByTierAndCulture(), DynamicTroopEquipmentReupload.Cache.GetItemsByTypeTierAndCulture(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.InitializeItemListByType(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.MoveRosterToArmory(), DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.Prefix(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ReturnItem(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.SanitizePartyArmory(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.SaveArmory(), SellExcessEquipmentForThrowingWeapons(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Spawn(), DynamicTroopEquipmentReupload.ItemBlackList.Test(), DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.TransferCargoToTargetStash(), and TryNormalizeArmoryElement().
Member Data Documentation
_cachedArrows
? ItemObject [] DynamicTroopEquipmentReupload.ArmyArmory._cachedArrows static private
Definition at line 30 of file ArmyArmory.cs.
Referenced by ResetForCampaign(), and SellExcessEquipmentForThrowingWeapons().
_cachedBolts
? ItemObject [] DynamicTroopEquipmentReupload.ArmyArmory._cachedBolts static private
Definition at line 32 of file ArmyArmory.cs.
Referenced by ResetForCampaign(), and SellExcessEquipmentForThrowingWeapons().
_cachedThrownWeapons
? ItemObject [] DynamicTroopEquipmentReupload.ArmyArmory._cachedThrownWeapons static private
Definition at line 29 of file ArmyArmory.cs.
Referenced by ResetForCampaign(), and SellExcessEquipmentForThrowingWeapons().
Armory
readonly ItemRoster DynamicTroopEquipmentReupload.ArmyArmory.Armory = new() static
Definition at line 27 of file ArmyArmory.cs.
Referenced by AddItemToArmory(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.ApplyCapturedArmoryLoss(), AssignEquipment(), DebugRemovePlayerCraftedItems(), Export(), Import(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.MeasureMainPartyArmoryReadiness(), DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.OnRefresh(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OpenArmoryScreen(), DynamicTroopEquipmentReupload.Patches.InventoryLogic_TransferItem_CommandersGreedPatch.Prefix(), ResetForCampaign(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.RestoreReadyArmoryItems(), SanitizeInPlace(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.SaveArmory(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.ScrapArmyArmoryByCategory(), SellExcessEquipment(), and DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.TryInitializeDistributors().
The documentation for this class was generated from the following file:
CSharpSourceCode/ArmyArmory.cs