动态装备系统: CharacterObjectExtension Class Reference
CharacterObjectExtension Class Reference
Public Types
enum TroopType {
Militia , Bandit , None , Basic ,
Mercenary , Elite
}
Static Public Member Functions
static int EquipmentValue (this CharacterObject? character)
static TroopType GetTroopType (this CharacterObject? character)
static void Init ()
static int SkillValue (this CharacterObject? character)
Static Private Member Functions
static int CalculateEquipmentValue (this CharacterObject? character)
static int CalculateSkillValue (this CharacterObject? character)
static void Enqueue (CharacterObject? character, TroopType typ)
Static Private Attributes
static MBReadOnlyList< SkillObject > _cachedSkillValue = new()
static readonly Dictionary< CharacterObject, int > CachedCharacterEquipmentValue = new()
static readonly Dictionary< CharacterObject, int > CachedCharacterSkillValue = new()
static readonly Queue<(CharacterObject, TroopType)> TroopQueue = new()
static readonly Dictionary< CharacterObject, TroopType > TypeDict = new()
Detailed Description
Definition at line 11 of file CharacterObjectExtension.cs.
Member Enumeration Documentation
TroopType
enum CharacterObjectExtension.TroopType
Enumerator
Militia
Bandit
None
Basic
Mercenary
Elite
Definition at line 12 of file CharacterObjectExtension.cs.
{
        Militia,
        Bandit,
        None,
        Basic,
        Mercenary,
        Elite
    }
Member Function Documentation
CalculateEquipmentValue()
static int CharacterObjectExtension.CalculateEquipmentValue (this CharacterObject? character) static private
Definition at line 36 of file CharacterObjectExtension.cs.
{
        if (character == null) return 0;
        var                    totalValue = 0;
        IEnumerable<Equipment> equipments = character.BattleEquipments;
        if (equipments == null) return 0;
        var cnt = character.BattleEquipments.Count();
        foreach (var equipment in equipments) {
            foreach (var slot in Global.EquipmentSlots) {
                var element = equipment.GetEquipmentFromSlot(slot);
                if (element.IsEmpty || element.Item == null) continue;
                totalValue += equipment.GetEquipmentFromSlot(slot).ItemValue;
            }
        }
        return totalValue / cnt;
    }
Referenced by EquipmentValue().
CalculateSkillValue()
static int CharacterObjectExtension.CalculateSkillValue (this CharacterObject? character) static private
Definition at line 56 of file CharacterObjectExtension.cs.
{
        return character != null ? _cachedSkillValue.SumQ(character.GetSkillValue) : 0;
    }
References _cachedSkillValue.
Referenced by SkillValue().
Enqueue()
static void CharacterObjectExtension.Enqueue (CharacterObject? character, TroopType typ) static private
Definition at line 117 of file CharacterObjectExtension.cs.
{
        if (character == null) return;
        TroopQueue.Enqueue((character, typ));
    }
References TroopQueue.
Referenced by Init().
EquipmentValue()
static int CharacterObjectExtension.EquipmentValue (this CharacterObject? character) static
Definition at line 60 of file CharacterObjectExtension.cs.
{
        if (character == null) return 0;
        if (CachedCharacterEquipmentValue.TryGetValue(character, out var value)) return value;
        value = CalculateEquipmentValue(character);
        CachedCharacterEquipmentValue.Add(character, value);
        return value;
    }
References CachedCharacterEquipmentValue, and CalculateEquipmentValue().
GetTroopType()
static TroopType CharacterObjectExtension.GetTroopType (this CharacterObject? character) static
Definition at line 31 of file CharacterObjectExtension.cs.
{
        return character == null                            ? TroopType.None :
               TypeDict.TryGetValue(character, out var typ) ? typ : TroopType.None;
    }
References TypeDict.
Init()
static void CharacterObjectExtension.Init () static
Definition at line 80 of file CharacterObjectExtension.cs.
{
        var cultureList = MBObjectManager.Instance.GetObjectTypeList<CultureObject>();
        _cachedSkillValue = MBObjectManager.Instance.GetObjectTypeList<SkillObject>();
        foreach (var culture in cultureList) {
            Enqueue(culture?.EliteBasicTroop, TroopType.Elite);
            MBReadOnlyList<CharacterObject>? basicMercenaryTroops = culture?.BasicMercenaryTroops;
            if (basicMercenaryTroops != null)
                foreach (var troop in basicMercenaryTroops)
                    Enqueue(troop, TroopType.Mercenary);
            Enqueue(culture?.BasicTroop, TroopType.Basic);
            Enqueue(culture?.BanditChief,  TroopType.Bandit);
            Enqueue(culture?.BanditRaider, TroopType.Bandit);
            Enqueue(culture?.BanditBandit, TroopType.Bandit);
            Enqueue(culture?.BanditBoss,   TroopType.Bandit);
            Enqueue(culture?.MeleeMilitiaTroop,       TroopType.Militia);
            Enqueue(culture?.MeleeEliteMilitiaTroop,  TroopType.Militia);
            Enqueue(culture?.RangedEliteMilitiaTroop, TroopType.Militia);
            Enqueue(culture?.RangedMilitiaTroop,      TroopType.Militia);
            Enqueue(culture?.MilitiaArcher,           TroopType.Militia);
            Enqueue(culture?.MilitiaVeteranArcher,    TroopType.Militia);
            Enqueue(culture?.MilitiaSpearman,         TroopType.Militia);
            Enqueue(culture?.MilitiaVeteranSpearman,  TroopType.Militia);
        }
        while (!TroopQueue.IsEmpty()) {
            (var character, var typ) = TroopQueue.Dequeue();
            if (TypeDict.ContainsKey(character)) continue;
            TypeDict.Add(character, typ);
            foreach (var next in character.UpgradeTargets) Enqueue(next, typ);
        }
    }
References _cachedSkillValue, Enqueue(), TroopQueue, and TypeDict.
Referenced by EveryoneCampaignBehavior.OnGameLoaded().
SkillValue()
static int CharacterObjectExtension.SkillValue (this CharacterObject? character) static
Definition at line 70 of file CharacterObjectExtension.cs.
{
        if (character == null) return 0;
        if (CachedCharacterSkillValue.TryGetValue(character, out var value)) return value;
        value = CalculateSkillValue(character);
        CachedCharacterSkillValue.Add(character, value);
        return value;
    }
References CachedCharacterSkillValue, and CalculateSkillValue().
Member Data Documentation
_cachedSkillValue
MBReadOnlyList<SkillObject> CharacterObjectExtension._cachedSkillValue = new() static private
Definition at line 25 of file CharacterObjectExtension.cs.
Referenced by CalculateSkillValue(), and Init().
CachedCharacterEquipmentValue
readonly Dictionary<CharacterObject, int> CharacterObjectExtension.CachedCharacterEquipmentValue = new() static private
Definition at line 27 of file CharacterObjectExtension.cs.
Referenced by EquipmentValue().
CachedCharacterSkillValue
readonly Dictionary<CharacterObject, int> CharacterObjectExtension.CachedCharacterSkillValue = new() static private
Definition at line 29 of file CharacterObjectExtension.cs.
Referenced by SkillValue().
TroopQueue
readonly Queue<(CharacterObject, TroopType)> CharacterObjectExtension.TroopQueue = new() static private
Definition at line 23 of file CharacterObjectExtension.cs.
Referenced by Enqueue(), and Init().
TypeDict
readonly Dictionary<CharacterObject, TroopType> CharacterObjectExtension.TypeDict = new() static private
Definition at line 21 of file CharacterObjectExtension.cs.
Referenced by GetTroopType(), and Init().
The documentation for this class was generated from the following file:
Extensions/CharacterObjectExtension.cs