动态装备系统: DynamicTroopEquipmentReupload.PartyEquipmentDistributor Class Reference
DynamicTroopEquipmentReupload.PartyEquipmentDistributor Class Reference
Public Member Functions
PartyEquipmentDistributor (Mission mission, MobileParty party, Dictionary< ItemObject, int > objectToAssign)
PartyEquipmentDistributor (Mission mission, MobileParty party, IDictionary< EquipmentElement, int > equipmentToAssign)
PartyEquipmentDistributor (Mission mission, MobileParty party, ItemRoster itemRoster)
void ReturnItem (ItemObject? item, int count)
void RunAsync ()
void Spawn (Equipment equipment)
Public Attributes
readonly List< Assignment > Assignments = new()
Private Member Functions
void ApplyEmergencyLoadout ()
void AssignEquipmentType (ItemTypeEnum type)
void AssignExtraArrows ()
void AssignExtraBolts ()
void AssignExtraEquipment (EquipmentFilter equipmentFilter, AssignmentFilter assignmentFilter)
根据给定的装备筛选条件和分配筛选条件为角色分配额外装备。
void AssignExtraShield ()
void AssignExtraThrownWeapon ()
void AssignExtraTwoHandedWeaponOrPolearms ()
void AssignHorseAndHarness ()
delegate bool AssignmentFilter (Assignment assignment)
void AssignWeaponByItemEnumType (bool strict)
void AssignWeaponByItemEnumTypeBySlot (EquipmentIndex slot, Assignment assignment, bool mounted, bool strict)
void AssignWeaponByWeaponClass (bool strict)
void AssignWeaponByWeaponClassBySlot (EquipmentIndex slot, Assignment assignment, bool mounted, bool strict)
根据武器大类型和指定的装备槽位为角色分配武器。
void AssignWeaponIfAvailable (EquipmentIndex slot, Assignment assignment, EquipmentElement? availableWeapon)
void AssignWeaponToUnarmed ()
void ConsumeEquipmentToAssign (EquipmentElement equipmentElement)
void DoAssignAsync ()
delegate bool EquipmentFilter (KeyValuePair< EquipmentElement, int > equipment)
void GenerateHorseAndHarnessList ()
void GenerateHorseAndHarnessPairs (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, IList<(EquipmentElement Key, int Cnt)> saddles)
int GetMaxAllowedTier (ItemObject? referenceItem)
EquipmentElement? GetOneRandomMeleeWeapon (Assignment assignment)
bool IsWeaponSuitable (EquipmentElement equipment, ItemObject referenceWeapon, Assignment assignment, bool strict)
void MarkUnderEquippedAssignmentsIfEnabled ()
bool TryConsumeExactItem (ItemObject item, out EquipmentElement exactElement)
Static Private Member Functions
static void AddToDict (IDictionary< int, List<(EquipmentElement Key, int Cnt)> > dict, EquipmentElement element, int cnt)
static void AssignSaddlesToHorseAndHarnesses (IEnumerable< HorseAndHarness > horseAndHarnesses, IList<(EquipmentElement Key, int Cnt)> saddles)
static int CalculateEquipmentTierScoreWithoutMountEquipment (Equipment equipment)
static bool IsCultureCompatible (ItemObject item, BasicCultureObject? culture)
static void PopulateDictionaries (IEnumerable< KeyValuePair< EquipmentElement, int > > equipment, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, ICollection<(EquipmentElement Key, int Cnt)> saddles)
static void SortDict (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > dict, Comparison<(EquipmentElement Key, int Cnt)> comparer)
static void SortEquipmentDictionaries (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, Dictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, List<(EquipmentElement Key, int Cnt)> saddles)
Private Attributes
readonly ConcurrentDictionary< EquipmentElement, int > _equipmentToAssign
readonly List< HorseAndHarness > _horseAndHarnesses = new()
readonly? ItemRoster _itemRoster
readonly Mission _mission
readonly MobileParty _party
Static Private Attributes
const float CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER = 2f
const int MAX_TIER_ABOVE_DEFAULT = 2
const float UNDER_EQUIPPED_MORALE_PENALTY_CAP = 20f
const float UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER = 2f
Detailed Description
Definition at line 20 of file PartyEquipmentDistributor.cs.
Constructor & Destructor Documentation
PartyEquipmentDistributor() [1/3]
DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PartyEquipmentDistributor (Mission mission, MobileParty party, ItemRoster itemRoster)
Definition at line 39 of file PartyEquipmentDistributor.cs.
{
        _mission           = mission;
        _party             = party;
        _itemRoster        = itemRoster;
        _equipmentToAssign = new ConcurrentDictionary<EquipmentElement, int>(new EquipmentElementComparer());
    }
References _equipmentToAssign, _itemRoster, _mission, and _party.
PartyEquipmentDistributor() [2/3]
DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PartyEquipmentDistributor (Mission mission, MobileParty party, IDictionary< EquipmentElement, int > equipmentToAssign)
Definition at line 46 of file PartyEquipmentDistributor.cs.
{
        _mission           = mission;
        _party             = party;
        _itemRoster        = null;
        _equipmentToAssign = new ConcurrentDictionary<EquipmentElement, int>(equipmentToAssign, new EquipmentElementComparer());
    }
References _equipmentToAssign, _itemRoster, _mission, and _party.
PartyEquipmentDistributor() [3/3]
DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PartyEquipmentDistributor (Mission mission, MobileParty party, Dictionary< ItemObject, int > objectToAssign)
Definition at line 53 of file PartyEquipmentDistributor.cs.
{
        _mission           = mission;
        _party             = party;
        _itemRoster        = null;
        _equipmentToAssign = new ConcurrentDictionary<EquipmentElement, int>(new EquipmentElementComparer());
        foreach (var kv in objectToAssign) {
            if (kv.Key != null) {
                EquipmentElement element = new(kv.Key);
                if (_equipmentToAssign.TryGetValue(element, out var existingCount)) { _equipmentToAssign[element] = existingCount + kv.Value; }
                else { _                                                                                          = _equipmentToAssign.TryAdd(element, kv.Value); }
            }
        }
    }
References _equipmentToAssign, _itemRoster, _mission, and _party.
Member Function Documentation
AddToDict()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AddToDict (IDictionary< int, List<(EquipmentElement Key, int Cnt)> > dict, EquipmentElement element, int cnt) static private
Definition at line 138 of file PartyEquipmentDistributor.cs.
{
        var familyType = element.Item.HorseComponent?.Monster?.FamilyType ?? element.Item.ArmorComponent?.FamilyType ?? -1;
        if (!dict.TryGetValue(familyType, out var list)) {
            list             = new List<(EquipmentElement Key, int Cnt)>();
            dict[familyType] = list;
        }
        list.Add((element, cnt));
    }
Referenced by PopulateDictionaries().
ApplyEmergencyLoadout()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ApplyEmergencyLoadout () private
Definition at line 949 of file PartyEquipmentDistributor.cs.
{
        if (_mission.HasMissionBehavior<HideoutMissionController>())
            return;
        foreach (var assignment in Assignments) {
            // Armour slots
            foreach (var slot in Global.ArmourSlots) {
                if (assignment.GetEquipmentFromSlot(slot) is { IsEmpty: false, Item: not null })
                    continue;
                var reference   = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
                var desiredType = reference.Item?.ItemType ?? Helper.EquipmentIndexToItemEnumType(slot);
                if (!desiredType.HasValue)
                    continue;
                var emergencyCulture = _party.LeaderHero?.Culture ?? assignment.Character.Culture;
                var basicTroop       = emergencyCulture?.BasicTroop;
                if (basicTroop == null)
                    continue;
                var fallbackItem = basicTroop.RandomBattleEquipment.GetEquipmentFromSlot(slot).Item;
                if (fallbackItem == null)
                    continue;
                if (!ItemBlackList.Test(fallbackItem) || fallbackItem.IsCraftedByPlayer || !fallbackItem.IsSuitableForCharacter(assignment.Character))
                    continue;
                assignment.SetEquipment(slot, new EquipmentElement(fallbackItem));
                assignment.MarkSlotAsTemporary(slot, fallbackItem);
            }
            // Weapon slots (only if empty)
            foreach (var slot in Assignment.WeaponSlots) {
                if (assignment.GetEquipmentFromSlot(slot) is { IsEmpty: false, Item: not null })
                    continue;
                var reference   = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
                var desiredType = reference.Item?.ItemType;
                if (desiredType == null)
                    continue;
                var emergencyCulture = _party.LeaderHero?.Culture ?? assignment.Character.Culture;
                var basicTroop       = emergencyCulture?.BasicTroop;
                if (basicTroop == null)
                    continue;
                var fallbackItem = basicTroop.RandomBattleEquipment.GetEquipmentFromSlot(slot).Item;
                if (fallbackItem == null || !fallbackItem.HasWeaponComponent)
                    continue;
                if (!ItemBlackList.Test(fallbackItem) || fallbackItem.IsCraftedByPlayer || !fallbackItem.IsSuitableForCharacter(assignment.Character))
                    continue;
                assignment.SetEquipment(slot, new EquipmentElement(fallbackItem));
                assignment.MarkSlotAsTemporary(slot, fallbackItem);
            }
        }
    }
References _mission, _party, DynamicTroopEquipmentReupload.Global.ArmourSlots, Assignments, DynamicTroopEquipmentReupload.Helper.EquipmentIndexToItemEnumType(), DynamicTroopEquipmentReupload.ItemBlackList.Test(), and DynamicTroopEquipmentReupload.Assignment.WeaponSlots.
Referenced by DoAssignAsync().
AssignEquipmentType()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignEquipmentType (ItemTypeEnum type) private
Definition at line 445 of file PartyEquipmentDistributor.cs.
{
        var armours = _equipmentToAssign
            .Where(kv => kv.Key is { IsEmpty: false, Item: not null } &&
                         kv.Value > 0 &&
                         kv.Key.Item.ItemType == type)
            .Select(kv => new KeyValuePair<EquipmentElement, int>(kv.Key, kv.Value))
            .ToArray();
        var settings = ModSettings.Instance;
        var preferDefaultEquipmentThenClosest = settings?.PreferDefaultEquipmentThenClosest ?? true;
        var slotIndex = Global.GetEquipmentIndexByItemType(type);
        if (slotIndex == null) { return; }
        for (var assignmentIndex = 0; assignmentIndex < Assignments.Count; assignmentIndex++)
        {
            var assignment = Assignments[assignmentIndex];
            var referenceElement = assignment.ReferenceEquipment.GetEquipmentFromSlot(slotIndex.Value);
            var referenceItem = referenceElement.Item;
            // Loyal ON: first try exact vanilla equipment.
            if (preferDefaultEquipmentThenClosest && referenceItem != null)
            {
                for (var i = 0; i < armours.Length; i++)
                {
                    var candidate = armours[i];
                    if (candidate.Value <= 0) { continue; }
                    if (candidate.Key.Item != referenceItem) { continue; }
                    assignment.SetEquipment(slotIndex.Value, candidate.Key);
                    armours[i] = new KeyValuePair<EquipmentElement, int>(candidate.Key, candidate.Value - 1);
                    ConsumeEquipmentToAssign(candidate.Key);
                    break;
                }
            }
            if (!assignment.Equipment.GetEquipmentFromSlot(slotIndex.Value).IsEmpty) { continue; }
            var maxAllowedTier = GetMaxAllowedTier(referenceItem);
            var desiredCulture = assignment.Character.Culture;
            // Most-compatible selection (Effectiveness proximity), still capped by +2 tier.
            if (referenceItem != null)
            {
                var targetEffectiveness = referenceItem.Effectiveness;
                var bestCultureIndex = -1;
                var bestCultureDiff = float.MaxValue;
                var bestCultureEffectiveness = float.MinValue;
                var bestAnyIndex = -1;
                var bestAnyDiff = float.MaxValue;
                var bestAnyEffectiveness = float.MinValue;
                for (var i = 0; i < armours.Length; i++)
                {
                    var candidate = armours[i];
                    if (candidate.Value <= 0) { continue; }
                    var candidateItem = candidate.Key.Item;
                    if (candidateItem == null) { continue; }
                    if ((int)candidateItem.Tier > maxAllowedTier) { continue; }
                    var diff = Math.Abs(candidateItem.Effectiveness - targetEffectiveness);
                    var effectiveness = candidateItem.Effectiveness;
                    // ANY culture
                    if (diff < bestAnyDiff ||
                        diff == bestAnyDiff && effectiveness > bestAnyEffectiveness)
                    {
                        bestAnyIndex = i;
                        bestAnyDiff = diff;
                        bestAnyEffectiveness = effectiveness;
                    }
                    // CULTURE-compatible
                    if (!IsCultureCompatible(candidateItem, desiredCulture)) { continue; }
                    if (diff < bestCultureDiff ||
                        diff == bestCultureDiff && effectiveness > bestCultureEffectiveness)
                    {
                        bestCultureIndex = i;
                        bestCultureDiff = diff;
                        bestCultureEffectiveness = effectiveness;
                    }
                }
                var chosenIndex = bestAnyIndex;
                if (preferDefaultEquipmentThenClosest && bestCultureIndex >= 0)
                {
                    chosenIndex = bestCultureIndex;
                    if (bestAnyIndex >= 0)
                    {
                        // diff smaller = more compatible
                        var anyIsMoreThanTwiceAsCompatible = bestCultureDiff > (bestAnyDiff * CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER);
                        if (anyIsMoreThanTwiceAsCompatible)
{
                            chosenIndex = bestAnyIndex;
                        }
                    }
                }
                if (chosenIndex >= 0)
                {
                    var chosen = armours[chosenIndex];
                    assignment.SetEquipment(slotIndex.Value, chosen.Key);
                    armours[chosenIndex] = new KeyValuePair<EquipmentElement, int>(chosen.Key, chosen.Value - 1);
                    ConsumeEquipmentToAssign(chosen.Key);
                }
                continue;
            }
            // No reference item:
            {
                var bestCultureIndex = -1;
                var bestCultureEffectiveness = float.MinValue;
                var bestAnyIndex = -1;
                var bestAnyEffectiveness = float.MinValue;
                for (var i = 0; i < armours.Length; i++)
                {
                    var candidate = armours[i];
                    if (candidate.Value <= 0) { continue; }
                    var candidateItem = candidate.Key.Item;
                    if (candidateItem == null) { continue; }
                    if ((int)candidateItem.Tier > maxAllowedTier) { continue; }
                    var effectiveness = candidateItem.Effectiveness;
                    // ANY
                    if (effectiveness > bestAnyEffectiveness)
                    {
                        bestAnyIndex = i;
                        bestAnyEffectiveness = effectiveness;
                    }
                    // CULTURE-compatible
                    if (!IsCultureCompatible(candidateItem, desiredCulture)) { continue; }
                    if (effectiveness > bestCultureEffectiveness)
                    {
                        bestCultureIndex = i;
                        bestCultureEffectiveness = effectiveness;
                    }
                }
                var chosenIndex =
                    preferDefaultEquipmentThenClosest
                        ? (bestCultureIndex >= 0 ? bestCultureIndex : bestAnyIndex)
                        : bestAnyIndex;
                if (chosenIndex >= 0)
                {
                    var chosen = armours[chosenIndex];
                    assignment.SetEquipment(slotIndex.Value, chosen.Key);
                    armours[chosenIndex] = new KeyValuePair<EquipmentElement, int>(chosen.Key, chosen.Value - 1);
                    ConsumeEquipmentToAssign(chosen.Key);
                }
            }
        }
    }
References _equipmentToAssign, Assignments, ConsumeEquipmentToAssign(), CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER, DynamicTroopEquipmentReupload.Global.GetEquipmentIndexByItemType(), GetMaxAllowedTier(), IsCultureCompatible(), and DynamicTroopEquipmentReupload.ModSettings.PreferDefaultEquipmentThenClosest.
Referenced by DoAssignAsync().
AssignExtraArrows()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraArrows () private
Definition at line 360 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignExtraArrows for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(ArrowFilter, ArrowAssignmentFilter);
        return;
        static bool ArrowFilter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item: { } item } && item.IsArrow() && equipment.Value > 0;
        }
        static bool ArrowAssignmentFilter(Assignment assignment) {
            return assignment.IsArcher;
        }
    }
References AssignExtraEquipment(), DynamicTroopEquipmentReupload.Assignment.IsArcher, and DynamicTroopEquipmentReupload.Global.Log().
Referenced by DoAssignAsync().
AssignExtraBolts()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraBolts () private
Definition at line 375 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignExtraBolts for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(BoltFilter, BoltAssignmentFilter);
        return;
        static bool BoltFilter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item: { } item } && item.IsBolt() && equipment.Value > 0;
        }
        static bool BoltAssignmentFilter(Assignment assignment) {
            return assignment.IsCrossBowMan;
        }
    }
References AssignExtraEquipment(), DynamicTroopEquipmentReupload.Assignment.IsCrossBowMan, and DynamicTroopEquipmentReupload.Global.Log().
Referenced by DoAssignAsync().
AssignExtraEquipment()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraEquipment (EquipmentFilter equipmentFilter, AssignmentFilter assignmentFilter) private
根据给定的装备筛选条件和分配筛选条件为角色分配额外装备。
Parameters
equipmentFilter 装备筛选函数，用于决定哪些装备可以被分配。
assignmentFilter 分配筛选函数，用于决定哪些角色可以接收装备。
Definition at line 287 of file PartyEquipmentDistributor.cs.
{
        var candidates = new List<KeyValuePair<EquipmentElement, int>>();
        foreach (var kv in _equipmentToAssign) {
            if (kv.Key is { IsEmpty: false, Item: not null } &&
                kv.Value > 0                                 &&
                equipmentFilter(kv)) { candidates.Add(kv); }
        }
        if (candidates.Count == 0)
            return;
        candidates.Sort(static (a, b) => {
            var tierCompare = b.Key.Item.Tier.CompareTo(a.Key.Item.Tier);
            return tierCompare != 0 ? tierCompare : b.Key.Item.Value.CompareTo(a.Key.Item.Value);
        });
        var currentIndex = 0;
        foreach (var assignment in Assignments) {
            if (!assignmentFilter(assignment))
                continue;
            var slot = assignment.EmptyWeaponSlot;
            if (!slot.HasValue)
                continue;
            while (currentIndex < candidates.Count && candidates[currentIndex].Value <= 0)
                currentIndex++;
            if (currentIndex >= candidates.Count)
                return;
            var current = candidates[currentIndex];
            assignment.SetEquipment(slot.Value, current.Key);
            Global.Debug($"extra equipment {current.Key} assigned to {assignment.Character.StringId}#{assignment.Index} on slot {slot.Value} for {_party.Name}");
            candidates[currentIndex] = new KeyValuePair<EquipmentElement, int>(current.Key, current.Value - 1);
            ConsumeEquipmentToAssign(current.Key);
        }
    }
References _equipmentToAssign, AssignmentFilter(), Assignments, ConsumeEquipmentToAssign(), DynamicTroopEquipmentReupload.Global.Debug(), and EquipmentFilter().
Referenced by AssignExtraArrows(), AssignExtraBolts(), AssignExtraShield(), AssignExtraThrownWeapon(), and AssignExtraTwoHandedWeaponOrPolearms().
AssignExtraShield()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraShield () private
Definition at line 330 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignExtraShield for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(ShieldFilter, ShieldAssignmentFilter);
        return;
        static bool ShieldFilter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item.ItemType: ItemTypeEnum.Shield } && equipment.Value > 0;
        }
        static bool ShieldAssignmentFilter(Assignment assignment) {
            return assignment is { CanBeShielded: true, IsShielded: false };
        }
    }
References AssignExtraEquipment(), and DynamicTroopEquipmentReupload.Global.Log().
Referenced by DoAssignAsync().
AssignExtraThrownWeapon()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraThrownWeapon () private
Definition at line 345 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignExtraThrownWeapon for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(ThrownFilter, ThrownAssignmentFilter);
        return;
        static bool ThrownFilter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item: { } item } && item.IsThrowing() && equipment.Value > 0;
        }
        static bool ThrownAssignmentFilter(Assignment assignment) {
            return !assignment.HaveThrown;
        }
    }
References AssignExtraEquipment(), DynamicTroopEquipmentReupload.Assignment.HaveThrown, and DynamicTroopEquipmentReupload.Global.Log().
Referenced by DoAssignAsync().
AssignExtraTwoHandedWeaponOrPolearms()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraTwoHandedWeaponOrPolearms () private
Definition at line 390 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignExtraTwoHandedWeaponOrPolearms for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(Filter, AssignmentFilter);
        return;
        static bool Filter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item: { } item } && (item.IsTwoHanded() || item.IsPolearm()) && equipment.Value > 0;
        }
        static bool AssignmentFilter(Assignment assignment) {
            return !assignment.HaveTwoHandedWeaponOrPolearms;
        }
    }
References AssignExtraEquipment(), AssignmentFilter(), DynamicTroopEquipmentReupload.Assignment.HaveTwoHandedWeaponOrPolearms, and DynamicTroopEquipmentReupload.Global.Log().
Referenced by DoAssignAsync().
AssignHorseAndHarness()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignHorseAndHarness () private
Definition at line 250 of file PartyEquipmentDistributor.cs.
{
        Global.Debug($"Assigning Horse and Harness for {_party.Name}");
        var currentIndex = 0;
        foreach (var assignment in Assignments) {
            if (!assignment.IsMounted) { continue; }
            if (currentIndex >= _horseAndHarnesses.Count) { break; }
            var horseAndHarness = _horseAndHarnesses[currentIndex++];
            assignment.SetEquipment(EquipmentIndex.Horse, horseAndHarness.Horse);
            Global.Debug($"assign horse {horseAndHarness.Horse.Item.Name} to {assignment.Character.Name}#{assignment.Index} for {_party.Name}");
            if (!horseAndHarness.Harness.HasValue) { continue; }
            assignment.SetEquipment(EquipmentIndex.HorseHarness, horseAndHarness.Harness.Value);
            Global.Debug($"assign horse harness {horseAndHarness.Harness.Value.Item.Name} to {assignment.Character.Name}#{assignment.Index} for {_party.Name}");
        }
    }
References _horseAndHarnesses, Assignments, and DynamicTroopEquipmentReupload.Global.Debug().
Referenced by DoAssignAsync().
AssignmentFilter()
delegate bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignmentFilter (Assignment assignment) private
Referenced by AssignExtraEquipment(), and AssignExtraTwoHandedWeaponOrPolearms().
AssignSaddlesToHorseAndHarnesses()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignSaddlesToHorseAndHarnesses (IEnumerable< HorseAndHarness > horseAndHarnesses, IList<(EquipmentElement Key, int Cnt)> saddles) static private
Definition at line 194 of file PartyEquipmentDistributor.cs.
{
        var saddleIndex = 0;
        foreach (var hoh in horseAndHarnesses.WhereQ(h => h.Harness == null)) {
            if (saddleIndex >= saddles.Count) { break; }
            (var saddleItem, var saddleCnt) = saddles[saddleIndex];
            if (saddleCnt <= 0) { continue; }
            hoh.Harness          = saddleItem;
            saddles[saddleIndex] = (saddleItem, --saddleCnt);
            if (saddleCnt == 0) { saddleIndex++; }
        }
    }
Referenced by GenerateHorseAndHarnessPairs().
AssignWeaponByItemEnumType()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumType (bool strict) private
Definition at line 731 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignWeaponByItemEnumType strict={strict} for {_party.Name}", Colors.Green, Level.Debug);
        foreach (var assignment in Assignments) {
            AssignWeaponByItemEnumTypeBySlot(EquipmentIndex.Weapon0, assignment, assignment.IsMounted, strict);
            AssignWeaponByItemEnumTypeBySlot(EquipmentIndex.Weapon1, assignment, assignment.IsMounted, strict);
            AssignWeaponByItemEnumTypeBySlot(EquipmentIndex.Weapon2, assignment, assignment.IsMounted, strict);
            AssignWeaponByItemEnumTypeBySlot(EquipmentIndex.Weapon3, assignment, assignment.IsMounted, strict);
        }
    }
References Assignments, AssignWeaponByItemEnumTypeBySlot(), and DynamicTroopEquipmentReupload.Global.Log().
Referenced by DoAssignAsync().
AssignWeaponByItemEnumTypeBySlot()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumTypeBySlot (EquipmentIndex slot, Assignment assignment, bool mounted, bool strict) private
Definition at line 742 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignWeaponByItemEnumTypeBySlot slot={slot} character={assignment.Character.StringId}#{assignment.Index} mounted={mounted} strict={strict} for {_party.Name}", Colors.Green, Level.Debug);
        var settings = ModSettings.Instance;
        var preferVanillaThenClosest = settings?.PreferDefaultEquipmentThenClosest ?? true;
        var referenceWeapon = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
        var currentWeapon = assignment.GetEquipmentFromSlot(slot);
        if (currentWeapon is { IsEmpty: false, Item: not null } || referenceWeapon.IsEmpty || referenceWeapon.Item == null)
            return;
        var maxAllowedTier = GetMaxAllowedTier(referenceWeapon.Item);
        // Loyal ON: exact vanilla weapon first (if available)
        if (preferVanillaThenClosest &&
            (int)referenceWeapon.Item.Tier <= maxAllowedTier &&
            TryConsumeExactItem(referenceWeapon.Item, out var exactElement))
        {
            assignment.SetEquipment(slot, exactElement);
            Global.Log($"weapon (vanilla exact) {exactElement.Item.StringId} assigned to {assignment.Character.StringId}#{assignment.Index} for {_party.Name}", Colors.Green, Level.Debug);
            return;
        }
        var desiredCulture = assignment.Character.Culture;
        var targetEffectiveness = referenceWeapon.Item.Effectiveness;
        EquipmentElement? bestAnyWeapon = null;
        var bestAnyDiff = float.MaxValue;
        var bestAnyEffectiveness = float.MinValue;
        EquipmentElement? bestCultureWeapon = null;
        var bestCultureDiff = float.MaxValue;
        var bestCultureEffectiveness = float.MinValue;
        foreach (var kv in _equipmentToAssign)
        {
            if (kv.Value <= 0)
                continue;
            var element = kv.Key;
            if (element.IsEmpty || element.Item == null)
                continue;
            var item = element.Item;
            if ((int)item.Tier > maxAllowedTier)
                continue;
            if (!IsWeaponSuitable(element, referenceWeapon.Item, assignment, strict))
                continue;
            var diff = Math.Abs(item.Effectiveness - targetEffectiveness);
            var effectiveness = item.Effectiveness;
            // ANY culture
            if (diff < bestAnyDiff ||
                diff == bestAnyDiff && effectiveness > bestAnyEffectiveness)
            {
                bestAnyDiff = diff;
                bestAnyEffectiveness = effectiveness;
                bestAnyWeapon = element;
            }
            // CULTURE-compatible
            if (!IsCultureCompatible(item, desiredCulture))
                continue;
            if (diff < bestCultureDiff ||
                diff == bestCultureDiff && effectiveness > bestCultureEffectiveness)
            {
                bestCultureDiff = diff;
                bestCultureEffectiveness = effectiveness;
                bestCultureWeapon = element;
            }
        }
        // Loyal OFF must ignore culture.
        EquipmentElement? bestWeapon = bestAnyWeapon;
        if (preferVanillaThenClosest && bestCultureWeapon.HasValue)
        {
            bestWeapon = bestCultureWeapon;
            if (bestAnyWeapon.HasValue)
            {
                // diff smaller = more compatible
                var anyIsMoreThanTwiceAsCompatible = bestCultureDiff > (bestAnyDiff * CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER);
                if (anyIsMoreThanTwiceAsCompatible)
                {
                    bestWeapon = bestAnyWeapon;
                }
            }
        }
        AssignWeaponIfAvailable(slot, assignment, bestWeapon);
    }
References _equipmentToAssign, AssignWeaponIfAvailable(), DynamicTroopEquipmentReupload.Assignment.Character, CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER, DynamicTroopEquipmentReupload.Assignment.GetEquipmentFromSlot(), GetMaxAllowedTier(), IsCultureCompatible(), IsWeaponSuitable(), DynamicTroopEquipmentReupload.Global.Log(), DynamicTroopEquipmentReupload.ModSettings.PreferDefaultEquipmentThenClosest, DynamicTroopEquipmentReupload.Assignment.ReferenceEquipment, DynamicTroopEquipmentReupload.Assignment.SetEquipment(), and TryConsumeExactItem().
Referenced by AssignWeaponByItemEnumType().
AssignWeaponByWeaponClass()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClass (bool strict) private
Definition at line 616 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignWeaponByWeaponClass strict={strict} for {_party.Name}", Colors.Green, Level.Debug);
        foreach (var assignment in Assignments) {
            AssignWeaponByWeaponClassBySlot(EquipmentIndex.Weapon0, assignment, assignment.IsMounted, strict);
            AssignWeaponByWeaponClassBySlot(EquipmentIndex.Weapon1, assignment, assignment.IsMounted, strict);
            AssignWeaponByWeaponClassBySlot(EquipmentIndex.Weapon2, assignment, assignment.IsMounted, strict);
            AssignWeaponByWeaponClassBySlot(EquipmentIndex.Weapon3, assignment, assignment.IsMounted, strict);
        }
    }
References Assignments, AssignWeaponByWeaponClassBySlot(), and DynamicTroopEquipmentReupload.Global.Log().
Referenced by DoAssignAsync().
AssignWeaponByWeaponClassBySlot()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClassBySlot (EquipmentIndex slot, Assignment assignment, bool mounted, bool strict) private
根据武器大类型和指定的装备槽位为角色分配武器。
Parameters
slot 装备槽位，表示需要分配武器的具体位置。
assignment 包含角色和参考装备信息的分配对象。
mounted 指示角色是否骑乘状态，影响武器选择。
strict 是否启用严格模式。
Definition at line 633 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignWeaponByWeaponClassBySlot slot={slot} character={assignment.Character.StringId}#{assignment.Index} mounted={mounted} strict={strict} for {_party.Name}", Colors.Green, Level.Debug);
        var settings = ModSettings.Instance;
        var preferVanillaThenClosest = settings?.PreferDefaultEquipmentThenClosest ?? true;
        var referenceWeapon = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
        var currentWeapon = assignment.GetEquipmentFromSlot(slot);
        if (currentWeapon is { IsEmpty: false, Item: not null } || referenceWeapon.IsEmpty || referenceWeapon.Item == null)
            return;
        var maxAllowedTier = GetMaxAllowedTier(referenceWeapon.Item);
        // Loyal ON: exact vanilla weapon first (if available)
        if (preferVanillaThenClosest &&
            (int)referenceWeapon.Item.Tier <= maxAllowedTier &&
            TryConsumeExactItem(referenceWeapon.Item, out var exactElement))
        {
            assignment.SetEquipment(slot, exactElement);
            Global.Log($"weapon (vanilla exact) {exactElement.Item.StringId} assigned to {assignment.Character.StringId}#{assignment.Index} for {_party.Name}", Colors.Green, Level.Debug);
            return;
        }
        var desiredCulture = assignment.Character.Culture;
        var targetEffectiveness = referenceWeapon.Item.Effectiveness;
        EquipmentElement? bestAnyWeapon = null;
        var bestAnyDiff = float.MaxValue;
        var bestAnyEffectiveness = float.MinValue;
        EquipmentElement? bestCultureWeapon = null;
        var bestCultureDiff = float.MaxValue;
        var bestCultureEffectiveness = float.MinValue;
        foreach (var kv in _equipmentToAssign)
        {
            if (kv.Value <= 0)
                continue;
            var element = kv.Key;
            if (element.IsEmpty || element.Item == null)
                continue;
            var item = element.Item;
            if ((int)item.Tier > maxAllowedTier)
                continue;
            if (!IsWeaponSuitable(element, referenceWeapon.Item, assignment, strict))
                continue;
            var diff = Math.Abs(item.Effectiveness - targetEffectiveness);
            var effectiveness = item.Effectiveness;
            // ANY culture
            if (diff < bestAnyDiff ||
                diff == bestAnyDiff && effectiveness > bestAnyEffectiveness)
            {
                bestAnyDiff = diff;
                bestAnyEffectiveness = effectiveness;
                bestAnyWeapon = element;
            }
            // CULTURE-compatible
            if (!IsCultureCompatible(item, desiredCulture))
                continue;
            if (diff < bestCultureDiff ||
                diff == bestCultureDiff && effectiveness > bestCultureEffectiveness)
            {
                bestCultureDiff = diff;
                bestCultureEffectiveness = effectiveness;
                bestCultureWeapon = element;
            }
        }
        EquipmentElement? bestWeapon = bestAnyWeapon;
        if (preferVanillaThenClosest && bestCultureWeapon.HasValue)
        {
            bestWeapon = bestCultureWeapon;
            if (bestAnyWeapon.HasValue)
            {
                // diff smaller = more compatible
                var anyIsMoreThanTwiceAsCompatible = bestCultureDiff > (bestAnyDiff * CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER);
                if (anyIsMoreThanTwiceAsCompatible)
                {
                    bestWeapon = bestAnyWeapon;
                }
            }
        }
        AssignWeaponIfAvailable(slot, assignment, bestWeapon);
    }
References _equipmentToAssign, AssignWeaponIfAvailable(), DynamicTroopEquipmentReupload.Assignment.Character, CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER, DynamicTroopEquipmentReupload.Assignment.GetEquipmentFromSlot(), GetMaxAllowedTier(), IsCultureCompatible(), IsWeaponSuitable(), DynamicTroopEquipmentReupload.Global.Log(), DynamicTroopEquipmentReupload.ModSettings.PreferDefaultEquipmentThenClosest, DynamicTroopEquipmentReupload.Assignment.ReferenceEquipment, DynamicTroopEquipmentReupload.Assignment.SetEquipment(), and TryConsumeExactItem().
Referenced by AssignWeaponByWeaponClass().
AssignWeaponIfAvailable()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponIfAvailable (EquipmentIndex slot, Assignment assignment, EquipmentElement? availableWeapon) private
Definition at line 868 of file PartyEquipmentDistributor.cs.
{
        if (!availableWeapon.HasValue || availableWeapon.Value.IsEmpty || availableWeapon.Value.Item == null)
            return;
        Global.Log($"weapon {availableWeapon.Value.Item.StringId} assigned to {assignment.Character.StringId}#{assignment.Index} for {_party.Name}", Colors.Green, Level.Debug);
        assignment.SetEquipment(slot, availableWeapon.Value);
        ConsumeEquipmentToAssign(availableWeapon.Value);
    }
References ConsumeEquipmentToAssign(), DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.Assignment.SetEquipment().
Referenced by AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
AssignWeaponToUnarmed()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponToUnarmed () private
Definition at line 268 of file PartyEquipmentDistributor.cs.
{
        Global.Log($"AssignWeaponToUnarmed for {_party.Name}", Colors.Green, Level.Debug);
        var unarmedAssignments = Assignments.WhereQ(assignment => assignment.IsUnarmed).ToListQ();
        foreach (var assignment in unarmedAssignments) {
            Global.Warn($"Found unarmed unit Index {assignment.Index} for {_party.Name}");
            var weapon = GetOneRandomMeleeWeapon(assignment);
            if (weapon.HasValue) {
                assignment.SetEquipment(EquipmentIndex.Weapon0, weapon.Value);
                ConsumeEquipmentToAssign(weapon.Value);
            }
            else { Global.Warn($"Cannot find random melee weapon for {assignment.Index} for {_party.Name}"); }
        }
    }
References Assignments, ConsumeEquipmentToAssign(), GetOneRandomMeleeWeapon(), DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.Global.Warn().
Referenced by DoAssignAsync().
CalculateEquipmentTierScoreWithoutMountEquipment()
static int DynamicTroopEquipmentReupload.PartyEquipmentDistributor.CalculateEquipmentTierScoreWithoutMountEquipment (Equipment equipment) static private
Definition at line 1042 of file PartyEquipmentDistributor.cs.
{
        var score = 0;
        foreach (var slot in Global.EquipmentSlots) {
            if (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness) { continue; }
            var element = equipment.GetEquipmentFromSlot(slot);
            if (element is { IsEmpty: false, Item: not null }) { score += (int)element.Item.Tier; }
        }
        return score;
    }
References DynamicTroopEquipmentReupload.Global.EquipmentSlots.
Referenced by MarkUnderEquippedAssignmentsIfEnabled().
ConsumeEquipmentToAssign()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ConsumeEquipmentToAssign (EquipmentElement equipmentElement) private
Definition at line 96 of file PartyEquipmentDistributor.cs.
{
        _equipmentToAssign.AddOrUpdate(
            equipmentElement,
            0,
            (_, currentCount) => currentCount > 0 ? currentCount - 1 : 0);
    }
References _equipmentToAssign.
Referenced by AssignEquipmentType(), AssignExtraEquipment(), AssignWeaponIfAvailable(), AssignWeaponToUnarmed(), and TryConsumeExactItem().
DoAssignAsync()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.DoAssignAsync () private
Definition at line 208 of file PartyEquipmentDistributor.cs.
{
        var settings                          = ModSettings.Instance;
        var preferDefaultEquipmentThenClosest = settings?.PreferDefaultEquipmentThenClosest ?? true;
        GenerateHorseAndHarnessList();
        AssignEquipmentType(ItemTypeEnum.HeadArmor);
        AssignEquipmentType(ItemTypeEnum.BodyArmor);
        AssignEquipmentType(ItemTypeEnum.LegArmor);
        AssignEquipmentType(ItemTypeEnum.HandArmor);
        AssignEquipmentType(ItemTypeEnum.Cape);
        AssignHorseAndHarness();
        // strict
        AssignWeaponByWeaponClass(true);
        // non strict
        AssignWeaponByWeaponClass(false);
        AssignWeaponByItemEnumType(false);
        // random
        AssignWeaponToUnarmed();
        // Extra equipment
        if (settings?.AssignExtraEquipments ?? true) {
            AssignExtraShield();
            AssignExtraThrownWeapon();
            AssignExtraArrows();
            AssignExtraBolts();
            AssignExtraTwoHandedWeaponOrPolearms();
        }
        // Emergency loadout
        if (settings?.EnableEmergencyLoadout ?? true) { ApplyEmergencyLoadout(); }
        // Underequipped
        MarkUnderEquippedAssignmentsIfEnabled();
    }
References ApplyEmergencyLoadout(), AssignEquipmentType(), AssignExtraArrows(), AssignExtraBolts(), AssignExtraShield(), AssignExtraThrownWeapon(), AssignExtraTwoHandedWeaponOrPolearms(), AssignHorseAndHarness(), AssignWeaponByItemEnumType(), AssignWeaponByWeaponClass(), AssignWeaponToUnarmed(), GenerateHorseAndHarnessList(), MarkUnderEquippedAssignmentsIfEnabled(), and DynamicTroopEquipmentReupload.ModSettings.PreferDefaultEquipmentThenClosest.
Referenced by RunAsync().
EquipmentFilter()
delegate bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.EquipmentFilter (KeyValuePair< EquipmentElement, int > equipment) private
Referenced by AssignExtraEquipment().
GenerateHorseAndHarnessList()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GenerateHorseAndHarnessList () private
Definition at line 103 of file PartyEquipmentDistributor.cs.
{
        Dictionary<int, List<(EquipmentElement Key, int Cnt)>> horsesDict  = new();
        Dictionary<int, List<(EquipmentElement Key, int Cnt)>> harnessDict = new();
        List<(EquipmentElement Key, int Cnt)>                  saddles     = new();
        PopulateDictionaries(_equipmentToAssign, horsesDict, harnessDict, saddles);
        SortEquipmentDictionaries(horsesDict, harnessDict, saddles);
        GenerateHorseAndHarnessPairs(horsesDict, harnessDict, saddles);
    }
References _equipmentToAssign, GenerateHorseAndHarnessPairs(), PopulateDictionaries(), and SortEquipmentDictionaries().
Referenced by DoAssignAsync().
GenerateHorseAndHarnessPairs()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GenerateHorseAndHarnessPairs (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, IList<(EquipmentElement Key, int Cnt)> saddles) private
Definition at line 164 of file PartyEquipmentDistributor.cs.
{
        foreach (var kvp in horsesDict) {
            var familyType = kvp.Key;
            var horses     = kvp.Value.ToArrayQ();
            var harnesses  = harnessDict.TryGetValue(familyType, out var harnessesList) ? harnessesList.ToArrayQ() : Array.Empty<(EquipmentElement Key, int Cnt)>();
            int horseIndex = 0, harnessIndex = 0;
            while (horseIndex < horses.Length) {
                (var horseItem, var horseCnt) = horses[horseIndex];
                var harnessItem = harnessIndex < harnesses.Length ? harnesses[harnessIndex].Key : new EquipmentElement(null);
                var harnessCnt  = harnessIndex < harnesses.Length ? harnesses[harnessIndex].Cnt : 0;
                if (horseCnt > 0) {
                    HorseAndHarness hah = new(horseItem, harnessItem);
                    _horseAndHarnesses.Add(hah);
                    horses[horseIndex] = (horseItem, --horseCnt);
                    if (harnessCnt > 0) { harnesses[harnessIndex] = (harnessItem, --harnessCnt); }
                }
                if (horseCnt == 0) { horseIndex++; }
                if (harnessCnt == 0 && harnessIndex < harnesses.Length) { harnessIndex++; }
            }
        }
        AssignSaddlesToHorseAndHarnesses(_horseAndHarnesses, saddles);
        _horseAndHarnesses.Sort((x, y) => y.CompareTo(x));
    }
References _horseAndHarnesses, and AssignSaddlesToHorseAndHarnesses().
Referenced by GenerateHorseAndHarnessList().
GetMaxAllowedTier()
int DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GetMaxAllowedTier (ItemObject? referenceItem) private
Definition at line 924 of file PartyEquipmentDistributor.cs.
{
        if (referenceItem == null) {
            return 6; // max
        }
        return Math.Min(6, (int)referenceItem.Tier + MAX_TIER_ABOVE_DEFAULT);
    }
References MAX_TIER_ABOVE_DEFAULT.
Referenced by AssignEquipmentType(), AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
GetOneRandomMeleeWeapon()
EquipmentElement? DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GetOneRandomMeleeWeapon (Assignment assignment) private
Definition at line 405 of file PartyEquipmentDistributor.cs.
{
        var candidates = new List<EquipmentElement>();
        foreach (var kv in _equipmentToAssign) {
            var element = kv.Key;
            if (kv.Value <= 0 || element.IsEmpty || element.Item == null)
                continue;
            var item = element.Item;
            if (!item.HasWeaponComponent)
                continue;
            if (!item.IsSuitableForCharacter(assignment.Character))
                continue;
            if (item.IsThrowing())
                continue;
            if (!item.IsTwoHanded() && !item.IsOneHanded() && !item.IsPolearm())
                continue;
            var hasAssignedHorse =
                !assignment.GetEquipmentFromSlot(EquipmentIndex.Horse).IsEmpty &&
                assignment.GetEquipmentFromSlot(EquipmentIndex.Horse).Item != null;
            if (hasAssignedHorse && !item.IsSuitableForMount())
                continue;
            candidates.Add(element);
        }
        if (candidates.Count == 0)
            return null;
        var randomIndex = MBRandom.RandomInt(candidates.Count);
        var selected    = candidates[randomIndex];
        Global.Log($"(random) weapon {selected.Item.StringId} selected for {_party.Name}", Colors.Green, Level.Debug);
        return selected;
    }
References _equipmentToAssign, and DynamicTroopEquipmentReupload.Global.Log().
Referenced by AssignWeaponToUnarmed().
IsCultureCompatible()
static bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsCultureCompatible (ItemObject item, BasicCultureObject? culture) static private
Definition at line 931 of file PartyEquipmentDistributor.cs.
{
        return culture == null || item.Culture == null || item.Culture == culture;
    }
Referenced by AssignEquipmentType(), AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
IsWeaponSuitable()
bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsWeaponSuitable (EquipmentElement equipment, ItemObject referenceWeapon, Assignment assignment, bool strict) private
Definition at line 841 of file PartyEquipmentDistributor.cs.
{
        if (equipment.IsEmpty                                            ||
            equipment.Item == null                                       ||
            !equipment.Item.HasWeaponComponent                           ||
            _equipmentToAssign[equipment] <= 0                           ||
            !equipment.Item.IsSuitableForCharacter(assignment.Character) ||
            !Global.HaveSameWeaponClass(Global.GetWeaponClass(equipment.Item), Global.GetWeaponClass(referenceWeapon))) { return false; }
        var isSuitableForMount = equipment.Item.IsSuitableForMount();
        var isCouchable        = equipment.Item.IsCouchable();
        if (strict) {
            if (!Global.FullySameWeaponClass(equipment.Item, referenceWeapon)) { return false; }
            if (assignment.IsMounted) {
                // 严格模式下骑马：必须适合骑乘；如果是长杆武器，则必须可进行骑枪冲刺
                return isSuitableForMount && (!equipment.Item.IsPolearm() || isCouchable);
            }
            // 严格模式下非骑马：不可选择可进行骑枪冲刺的武器
            return !isCouchable;
        }
        // 非严格模式下：骑马的不能选择不适合骑乘的武器，非骑马的可以选择任意武器
        return !assignment.IsMounted || isSuitableForMount;
    }
References _equipmentToAssign, DynamicTroopEquipmentReupload.Assignment.Character, DynamicTroopEquipmentReupload.Global.FullySameWeaponClass(), DynamicTroopEquipmentReupload.Global.GetWeaponClass(), DynamicTroopEquipmentReupload.Global.HaveSameWeaponClass(), and DynamicTroopEquipmentReupload.Assignment.IsMounted.
Referenced by AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
MarkUnderEquippedAssignmentsIfEnabled()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.MarkUnderEquippedAssignmentsIfEnabled () private
Definition at line 1010 of file PartyEquipmentDistributor.cs.
{
        var settings = ModSettings.Instance;
        if (!(settings?.Underequipped ?? true)) {
            for (var i = 0; i < Assignments.Count; i++) {
                var assignment = Assignments[i];
                assignment.IsUnderEquipped            = false;
                assignment.UnderEquippedMoralePenalty = 0f;
            }
            return;
        }
        for (var i = 0; i < Assignments.Count; i++) {
            var assignment = Assignments[i];
            var referenceScore = CalculateEquipmentTierScoreWithoutMountEquipment(assignment.ReferenceEquipment);
            var assignedScore  = CalculateEquipmentTierScoreWithoutMountEquipment(assignment.Equipment);
            if (assignedScore >= referenceScore) {
                assignment.IsUnderEquipped            = false;
                assignment.UnderEquippedMoralePenalty = 0f;
                continue;
            }
            var missingTierTotal = referenceScore - assignedScore;
            var moralePenalty    = missingTierTotal * UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER;
            assignment.IsUnderEquipped            = true;
            assignment.UnderEquippedMoralePenalty = Math.Min(UNDER_EQUIPPED_MORALE_PENALTY_CAP, moralePenalty);
        }
    }
References Assignments, CalculateEquipmentTierScoreWithoutMountEquipment(), UNDER_EQUIPPED_MORALE_PENALTY_CAP, and UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER.
Referenced by DoAssignAsync().
PopulateDictionaries()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PopulateDictionaries (IEnumerable< KeyValuePair< EquipmentElement, int > > equipment, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, ICollection<(EquipmentElement Key, int Cnt)> saddles) static private
Definition at line 113 of file PartyEquipmentDistributor.cs.
{
        foreach (var kvp in equipment) {
            switch (kvp.Key.Item) {
                case { HasHorseComponent: true, ItemType: ItemTypeEnum.Horse }:
                    AddToDict(horsesDict, kvp.Key, kvp.Value);
                    break;
                case { HasArmorComponent: true, ItemType: ItemTypeEnum.HorseHarness }:
                    AddToDict(harnessDict, kvp.Key, kvp.Value);
                    break;
                case {
                         HasArmorComponent : false,
                         HasSaddleComponent: true,
                         ItemType          : ItemTypeEnum.HorseHarness
                     }:
                    saddles.Add((kvp.Key, kvp.Value));
                    break;
            }
        }
    }
References AddToDict().
Referenced by GenerateHorseAndHarnessList().
ReturnItem()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ReturnItem (ItemObject? item, int count)
Definition at line 906 of file PartyEquipmentDistributor.cs.
{
        if (item == null || count <= 0) {
            Global.Log("Invalid item or count for return.", Colors.Red, Level.Warn);
            return;
        }
        // 确保 PartyArmories 包含特定的 _party.Id
        if (!EveryoneCampaignBehavior.PartyArmories.TryGetValue(_party.Id, out var partyArmory)) {
            partyArmory                                       = new Dictionary<ItemObject, int>();
            EveryoneCampaignBehavior.PartyArmories[_party.Id] = partyArmory;
        }
        // 如果武器库中已经有这个物品，增加数量；否则，添加新的条目
        partyArmory[item] = partyArmory.TryGetValue(item, out var existingCount) ? existingCount + count : count;
        Global.Log($"Returned {count} of item {item.StringId} to party {_party.Name}.", Colors.Green, Level.Debug);
    }
References _party, DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.PartyArmories.
RunAsync()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.RunAsync ()
Definition at line 69 of file PartyEquipmentDistributor.cs.
{
        foreach (var troop in _party.MemberRoster.GetTroopRoster()) {
            for (var i = 0; i < troop.Number - troop.WoundedNumber; i++) {
                if (troop.Character is CharacterObject characterObject && !characterObject.IsHero) { Assignments.Add(new Assignment(characterObject)); }
            }
        }
        Assignments.Sort((x, y) => y.CompareTo(x));
        if (_itemRoster != null) {
            foreach (var kv in _itemRoster) {
                if (kv is not { IsEmpty: false, EquipmentElement.IsEmpty: false }) { continue; }
                // 尝试获取已存在的数量
                if (!_equipmentToAssign.TryGetValue(kv.EquipmentElement, out var existingAmount)) {
                    // 如果键不存在，添加新的键值对
                    _ = _equipmentToAssign.TryAdd(kv.EquipmentElement, kv.Amount);
                }
                else {
                    // 如果键已存在，更新数量
                    _equipmentToAssign[kv.EquipmentElement] = existingAmount + kv.Amount;
                }
            }
        }
        DoAssignAsync();
    }
References _equipmentToAssign, _itemRoster, _party, Assignments, and DoAssignAsync().
SortDict()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.SortDict (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > dict, Comparison<(EquipmentElement Key, int Cnt)> comparer) static private
Definition at line 160 of file PartyEquipmentDistributor.cs.
{
        foreach (var key in dict.Keys) { dict[key].Sort(comparer); }
    }
Referenced by SortEquipmentDictionaries().
SortEquipmentDictionaries()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.SortEquipmentDictionaries (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, Dictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, List<(EquipmentElement Key, int Cnt)> saddles) static private
Definition at line 148 of file PartyEquipmentDistributor.cs.
{
        SortDict(horsesDict,  CompareEquipment);
        SortDict(harnessDict, CompareEquipment);
        saddles.Sort(CompareEquipment);
        return;
        static int CompareEquipment((EquipmentElement Key, int Cnt) x, (EquipmentElement Key, int Cnt) y) {
            var tierCompare = y.Key.Item.Tier.CompareTo(x.Key.Item.Tier);
            return tierCompare != 0 ? tierCompare : y.Key.Item.Value.CompareTo(x.Key.Item.Value);
        }
    }
References SortDict().
Referenced by GenerateHorseAndHarnessList().
Spawn()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Spawn (Equipment equipment)
Definition at line 879 of file PartyEquipmentDistributor.cs.
{
        // 确保 PartyArmories 包含特定的 _party.Id
        if (!EveryoneCampaignBehavior.PartyArmories.TryGetValue(_party.Id, out var partyArmory)) {
            partyArmory                                       = new Dictionary<ItemObject, int>();
            EveryoneCampaignBehavior.PartyArmories[_party.Id] = partyArmory;
        }
        foreach (var slot in Global.EquipmentSlots) {
            if ((_mission.HasMissionBehavior<HideoutMissionController>() == true ||
                 _mission.HasMissionBehavior<MissionSiegeEnginesLogic>() == true) &&
                (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness))
                continue;
            var element = equipment.GetEquipmentFromSlot(slot);
            if (element is not { IsEmpty: false, Item: not null }) { continue; }
            if (partyArmory.TryGetValue(element.Item, out var itemCount) && itemCount > 0) {
                // 武器库中有足够的物品，分配一个并减少数量
                partyArmory[element.Item] = itemCount - 1;
                Global.Log($"Spawned item {element.Item.StringId}", Colors.Green, Level.Debug);
            }
            else {
                // 武器库中没有足够的物品或者该物品不存在
                Global.Log($"Insufficient or no items to spawn {element.Item.StringId}", Colors.Red, Level.Warn);
            }
        }
    }
References _mission, _party, DynamicTroopEquipmentReupload.Global.EquipmentSlots, DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.PartyArmories.
Referenced by DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix().
TryConsumeExactItem()
bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.TryConsumeExactItem (ItemObject item, out EquipmentElement exactElement) private
Definition at line 936 of file PartyEquipmentDistributor.cs.
{
        var stripped = new EquipmentElement(item);
        if (_equipmentToAssign.TryGetValue(stripped, out var cnt) && cnt > 0) {
            ConsumeEquipmentToAssign(stripped);
            exactElement = stripped;
            return true;
        }
        exactElement = default;
        return false;
    }
References _equipmentToAssign, and ConsumeEquipmentToAssign().
Referenced by AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
Member Data Documentation
_equipmentToAssign
readonly ConcurrentDictionary<EquipmentElement, int> DynamicTroopEquipmentReupload.PartyEquipmentDistributor._equipmentToAssign private
Definition at line 27 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), AssignEquipmentType(), AssignExtraEquipment(), AssignWeaponByItemEnumTypeBySlot(), AssignWeaponByWeaponClassBySlot(), ConsumeEquipmentToAssign(), GenerateHorseAndHarnessList(), GetOneRandomMeleeWeapon(), IsWeaponSuitable(), RunAsync(), and TryConsumeExactItem().
_horseAndHarnesses
readonly List<HorseAndHarness> DynamicTroopEquipmentReupload.PartyEquipmentDistributor._horseAndHarnesses = new() private
Definition at line 29 of file PartyEquipmentDistributor.cs.
Referenced by AssignHorseAndHarness(), and GenerateHorseAndHarnessPairs().
_itemRoster
readonly? ItemRoster DynamicTroopEquipmentReupload.PartyEquipmentDistributor._itemRoster private
Definition at line 31 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), and RunAsync().
_mission
readonly Mission DynamicTroopEquipmentReupload.PartyEquipmentDistributor._mission private
Definition at line 33 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), ApplyEmergencyLoadout(), and Spawn().
_party
readonly MobileParty DynamicTroopEquipmentReupload.PartyEquipmentDistributor._party private
Definition at line 35 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), ApplyEmergencyLoadout(), ReturnItem(), RunAsync(), and Spawn().
Assignments
readonly List<Assignment> DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Assignments = new()
Definition at line 37 of file PartyEquipmentDistributor.cs.
Referenced by ApplyEmergencyLoadout(), AssignEquipmentType(), AssignExtraEquipment(), AssignHorseAndHarness(), AssignWeaponByItemEnumType(), AssignWeaponByWeaponClass(), AssignWeaponToUnarmed(), MarkUnderEquippedAssignmentsIfEnabled(), and RunAsync().
CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER
const float DynamicTroopEquipmentReupload.PartyEquipmentDistributor.CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER = 2f static private
Definition at line 22 of file PartyEquipmentDistributor.cs.
Referenced by AssignEquipmentType(), AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
MAX_TIER_ABOVE_DEFAULT
const int DynamicTroopEquipmentReupload.PartyEquipmentDistributor.MAX_TIER_ABOVE_DEFAULT = 2 static private
Definition at line 21 of file PartyEquipmentDistributor.cs.
Referenced by GetMaxAllowedTier().
UNDER_EQUIPPED_MORALE_PENALTY_CAP
const float DynamicTroopEquipmentReupload.PartyEquipmentDistributor.UNDER_EQUIPPED_MORALE_PENALTY_CAP = 20f static private
Definition at line 26 of file PartyEquipmentDistributor.cs.
Referenced by MarkUnderEquippedAssignmentsIfEnabled().
UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER
const float DynamicTroopEquipmentReupload.PartyEquipmentDistributor.UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER = 2f static private
Definition at line 24 of file PartyEquipmentDistributor.cs.
Referenced by MarkUnderEquippedAssignmentsIfEnabled().
The documentation for this class was generated from the following file:
PartyEquipmentDistributor.cs