动态装备系统: DynamicTroopEquipmentReupload.ArmyArmoryBehavior Class Reference
DynamicTroopEquipmentReupload.ArmyArmoryBehavior Class Reference
Classes
class Data
Public Member Functions
override void RegisterEvents ()
override void SyncData (IDataStore dataStore)
Private Member Functions
void AddArmyArmorySubmenu (CampaignGameStarter starter)
void AddTownMenuOptions (CampaignGameStarter starter)
void OnDailyTick ()
void OnGameLoaded (CampaignGameStarter starter)
void OnHeroPrisonerTaken (PartyBase capturerParty, Hero prisonerHero)
void OnNewGameCreated (CampaignGameStarter starter)
void OnSessionLaunched (CampaignGameStarter starter)
void RestoreReadyArmoryItems ()
void SaveArmory ()
Static Private Member Functions
static void ApplyCapturedArmoryLoss ()
static void ScrapArmyArmoryByCategory (int targetCountPerCategory)
Private Attributes
Data _data = new()
readonly Dictionary< string, int > _unresolvedArmoryItemCounts = new()
Detailed Description
Definition at line 19 of file ArmyArmoryBehavior.cs.
Member Function Documentation
AddArmyArmorySubmenu()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu (CampaignGameStarter starter) private
Definition at line 271 of file ArmyArmoryBehavior.cs.
{
        // 创建子菜单
        starter.AddGameMenu("army_armory_submenu", LocalizedTexts.ArmoryManageOption.ToString(), args => { });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "view_armory",
                                  LocalizedTexts.ArmorViewOption.ToString(),
                                  args => true,
                                  args => {
                                      RestoreReadyArmoryItems();
                                      ArmyArmory.SanitizeInPlace();
                                      InventoryScreenHelper.OpenScreenAsStash(ArmyArmory.Armory);
                                  });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "sell_for_throwing",
                                  LocalizedTexts.SellForThrowing.ToString(),
                                  args => true,
                                  args => { ArmyArmory.SellExcessEquipmentForThrowingWeapons(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_clear_invalid_items",
                                  LocalizedTexts.DebugClearInvalidItems.ToString(),
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.DebugClearEmptyItem(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_remove_player_crafted_items",
                                  LocalizedTexts.DebugRemovePlayerCraftedItems.ToString(),
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.DebugRemovePlayerCraftedItems(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_rebuild_armory",
                                  LocalizedTexts.DebugRebuildArmory.ToString(),
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.RebuildArmory(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_export_armory",
                                  LocalizedTexts.DebugExportArmory.ToString(),
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.Export(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_import_armory",
                                  LocalizedTexts.DebugImportArmory.ToString(),
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.Import(); });
        // 返回上一级菜单的选项
        starter.AddGameMenuOption("army_armory_submenu",
                                  "return_to_town",
                                  LocalizedTexts.ReturnToTown.ToString(),
                                  args => true,
                                  args => { GameMenu.SwitchToMenu("town"); },
                                  true);
    }
References DynamicTroopEquipmentReupload.LocalizedTexts.ArmorViewOption, DynamicTroopEquipmentReupload.LocalizedTexts.ArmoryManageOption, DynamicTroopEquipmentReupload.LocalizedTexts.DebugClearInvalidItems, DynamicTroopEquipmentReupload.LocalizedTexts.DebugExportArmory, DynamicTroopEquipmentReupload.LocalizedTexts.DebugImportArmory, DynamicTroopEquipmentReupload.ModSettings.DebugMode, DynamicTroopEquipmentReupload.LocalizedTexts.DebugRebuildArmory, DynamicTroopEquipmentReupload.LocalizedTexts.DebugRemovePlayerCraftedItems, DynamicTroopEquipmentReupload.LocalizedTexts.ReturnToTown, and DynamicTroopEquipmentReupload.LocalizedTexts.SellForThrowing.
Referenced by AddTownMenuOptions().
AddTownMenuOptions()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddTownMenuOptions (CampaignGameStarter starter) private
Definition at line 257 of file ArmyArmoryBehavior.cs.
{
        AddArmyArmorySubmenu(starter);
        starter.AddGameMenuOption("town",
                                  "army_armory_manage",
                                  LocalizedTexts.ArmoryManageOption.ToString(),
                                  args => true,
                                  args => {
                                      // 打开子菜单
                                      GameMenu.SwitchToMenu("army_armory_submenu");
                                  },
                                  false,
                                  4);
    }
References AddArmyArmorySubmenu(), and DynamicTroopEquipmentReupload.LocalizedTexts.ArmoryManageOption.
Referenced by OnSessionLaunched().
ApplyCapturedArmoryLoss()
static void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.ApplyCapturedArmoryLoss () static private
Definition at line 105 of file ArmyArmoryBehavior.cs.
{
        ArmyArmory.SanitizeInPlace();
        const int LOSS_NUMERATOR = 4;
        const int LOSS_DENOMINATOR = 5;
        var removals = new List<(EquipmentElement Equipment, int RemoveCount)>();
        var removedItemCount = 0;
        long removedValue = 0;
        var enumerator = ArmyArmory.Armory.GetEnumerator();
        while (enumerator.MoveNext())
        {
            var element = enumerator.Current;
            if (element is not { IsEmpty: false, EquipmentElement: { IsEmpty: false, Item: not null }, Amount: > 0 })
                continue;
            var amount = element.Amount;
            // exact 80% with integer math + randomized remainder (vanilla-like)
            var weightedAmount = (long)amount * LOSS_NUMERATOR;
            var baseLoss = (int)(weightedAmount / LOSS_DENOMINATOR);
            var remainder = (int)(weightedAmount % LOSS_DENOMINATOR);
            var extraLoss = remainder > 0 && MBRandom.RandomInt(LOSS_DENOMINATOR) < remainder ? 1 : 0;
            var removeCount = Math.Min(amount, baseLoss + extraLoss);
            if (removeCount <= 0)
                continue;
            removals.Add((element.EquipmentElement, removeCount));
        }
        enumerator.Dispose();
        for (var i = 0; i < removals.Count; i++)
        {
            (var equipment, var removeCount) = removals[i];
            ArmyArmory.Armory.AddToCounts(equipment, -removeCount);
            removedItemCount += removeCount;
            removedValue += (long)equipment.ItemValue * removeCount;
        }
        if (removedItemCount > 0)
        {
            MessageDisplayService.EnqueueMessage(new InformationMessage(
                $"You were captured and lost {removedItemCount} items from the Army Armory (value: {removedValue}).",
                Colors.Red));
        }
    }
References DynamicTroopEquipmentReupload.ArmyArmory.Armory, MessageDisplayService.EnqueueMessage(), and DynamicTroopEquipmentReupload.ArmyArmory.SanitizeInPlace().
Referenced by OnHeroPrisonerTaken().
OnDailyTick()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnDailyTick () private
Definition at line 70 of file ArmyArmoryBehavior.cs.
{
        RestoreReadyArmoryItems();
        ArmyArmory.SanitizeInPlace();
        var settings = ModSettings.Instance;
        if (settings == null)
            return;
        // Only if Commander's Greed is OFF.
        if (settings.CommandersGreed)
            return;
        var currentDayNumber = (int)CampaignTime.Now.ToDays;
        // Run every 3 days.
        if (_data.LastScrapDayNumber >= 0 && currentDayNumber - _data.LastScrapDayNumber < 3)
            return;
        _data.LastScrapDayNumber = currentDayNumber;
        var cap                    = settings.ScrapCapPerCategory;
        var targetCountPerCategory = cap - 1;
        if (targetCountPerCategory <= 0)
            return;
        ScrapArmyArmoryByCategory(targetCountPerCategory);
    }
References _data, RestoreReadyArmoryItems(), DynamicTroopEquipmentReupload.ArmyArmory.SanitizeInPlace(), and ScrapArmyArmoryByCategory().
Referenced by RegisterEvents().
OnGameLoaded()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnGameLoaded (CampaignGameStarter starter) private
Definition at line 65 of file ArmyArmoryBehavior.cs.
{
        RestoreReadyArmoryItems();
        ArmyArmory.SanitizeInPlace();
    }
References RestoreReadyArmoryItems(), and DynamicTroopEquipmentReupload.ArmyArmory.SanitizeInPlace().
Referenced by RegisterEvents().
OnHeroPrisonerTaken()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnHeroPrisonerTaken (PartyBase capturerParty, Hero prisonerHero) private
Definition at line 98 of file ArmyArmoryBehavior.cs.
{
        if (prisonerHero != Hero.MainHero)
            return;
        ApplyCapturedArmoryLoss();
    }
References ApplyCapturedArmoryLoss().
Referenced by RegisterEvents().
OnNewGameCreated()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnNewGameCreated (CampaignGameStarter starter) private
Definition at line 59 of file ArmyArmoryBehavior.cs.
{
        Global.Debug("OnNewGameCreated() called");
        _unresolvedArmoryItemCounts.Clear();
        ArmyArmory.ResetForCampaign();
    }
References _unresolvedArmoryItemCounts, DynamicTroopEquipmentReupload.Global.Debug(), and DynamicTroopEquipmentReupload.ArmyArmory.ResetForCampaign().
Referenced by RegisterEvents().
OnSessionLaunched()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnSessionLaunched (CampaignGameStarter starter) private
Definition at line 251 of file ArmyArmoryBehavior.cs.
{
        RestoreReadyArmoryItems();
        ArmyArmory.SanitizeInPlace();
        AddTownMenuOptions(starter);
    }
References AddTownMenuOptions(), RestoreReadyArmoryItems(), and DynamicTroopEquipmentReupload.ArmyArmory.SanitizeInPlace().
Referenced by RegisterEvents().
RegisterEvents()
override void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.RegisterEvents ()
Definition at line 50 of file ArmyArmoryBehavior.cs.
{
        CampaignEvents.OnSessionLaunchedEvent.AddNonSerializedListener(this, OnSessionLaunched);
        CampaignEvents.OnNewGameCreatedEvent.AddNonSerializedListener(this, OnNewGameCreated);
        CampaignEvents.OnGameLoadedEvent.AddNonSerializedListener(this, OnGameLoaded);
        CampaignEvents.DailyTickEvent.AddNonSerializedListener(this, OnDailyTick);
        CampaignEvents.HeroPrisonerTaken.AddNonSerializedListener(this, OnHeroPrisonerTaken);
    }
References OnDailyTick(), OnGameLoaded(), OnHeroPrisonerTaken(), OnNewGameCreated(), and OnSessionLaunched().
RestoreReadyArmoryItems()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.RestoreReadyArmoryItems () private
Definition at line 178 of file ArmyArmoryBehavior.cs.
{
        if (_unresolvedArmoryItemCounts.Count == 0)
            return;
        foreach (var pendingItem in new Dictionary<string, int>(_unresolvedArmoryItemCounts)) {
            var item = ArmyArmory.ResolveArmoryItem(pendingItem.Key);
            if (item == null)
                continue;
            ArmyArmory.Armory.AddToCounts(item, pendingItem.Value);
            _unresolvedArmoryItemCounts.Remove(pendingItem.Key);
        }
    }
References _unresolvedArmoryItemCounts, DynamicTroopEquipmentReupload.ArmyArmory.Armory, and DynamicTroopEquipmentReupload.ArmyArmory.ResolveArmoryItem().
Referenced by OnDailyTick(), OnGameLoaded(), and OnSessionLaunched().
SaveArmory()
void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.SaveArmory () private
Definition at line 159 of file ArmyArmoryBehavior.cs.
{
        ArmyArmory.SanitizeInPlace();
        _data.Armory ??= new Dictionary<string, int>();
        _data.Armory.Clear();
        foreach (var unresolvedItem in _unresolvedArmoryItemCounts)
            _data.Armory[unresolvedItem.Key] = unresolvedItem.Value;
        foreach (var rosterElement in ArmyArmory.Armory) {
            if (rosterElement.Amount <= 0 ||
                !ArmyArmory.TryResolveArmoryItem(rosterElement.EquipmentElement.Item, out var item))
                continue;
            _data.Armory[item.StringId] = _data.Armory.TryGetValue(item.StringId, out var currentCount)
                ? currentCount + rosterElement.Amount
                : rosterElement.Amount;
        }
    }
References _data, _unresolvedArmoryItemCounts, DynamicTroopEquipmentReupload.ArmyArmory.Armory, DynamicTroopEquipmentReupload.ArmyArmory.SanitizeInPlace(), and DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem().
Referenced by SyncData().
ScrapArmyArmoryByCategory()
static void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.ScrapArmyArmoryByCategory (int targetCountPerCategory) static private
Definition at line 192 of file ArmyArmoryBehavior.cs.
{
        var itemsByType = new Dictionary<ItemObject.ItemTypeEnum, List<(EquipmentElement Equipment, int Amount)>>();
        var enumerator = ArmyArmory.Armory.GetEnumerator();
        while (enumerator.MoveNext()) {
            var element = enumerator.Current;
            if (element is not { IsEmpty: false, EquipmentElement: { IsEmpty: false, Item: not null }, Amount: > 0 })
                continue;
            var equipmentElement = element.EquipmentElement;
            var itemType         = equipmentElement.Item.ItemType;
            if (!itemsByType.TryGetValue(itemType, out var list)) {
                list = new List<(EquipmentElement Equipment, int Amount)>();
                itemsByType.Add(itemType, list);
            }
            list.Add((equipmentElement, element.Amount));
        }
        enumerator.Dispose();
        foreach (var kvp in itemsByType) {
            var entries = kvp.Value;
            var totalCount = 0;
            for (var i = 0; i < entries.Count; i++)
                totalCount += entries[i].Amount;
            if (totalCount <= targetCountPerCategory)
                continue;
            var removeNeeded = totalCount - targetCountPerCategory;
            // lowest value first
            entries.Sort((a, b) => {
                var valueCompare = a.Equipment.ItemValue.CompareTo(b.Equipment.ItemValue);
                if (valueCompare != 0)
                    return valueCompare;
                var itemCompare = string.CompareOrdinal(a.Equipment.Item.StringId, b.Equipment.Item.StringId);
                return itemCompare != 0
                           ? itemCompare
                           : string.CompareOrdinal(a.Equipment.ItemModifier?.StringId, b.Equipment.ItemModifier?.StringId);
            });
            for (var i = 0; i < entries.Count && removeNeeded > 0; i++) {
                (var equipment, var amount) = entries[i];
                var removeCount = Math.Min(amount, removeNeeded);
                ArmyArmory.Armory.AddToCounts(equipment, -removeCount);
                removeNeeded -= removeCount;
            }
        }
    }
References DynamicTroopEquipmentReupload.ArmyArmory.Armory.
Referenced by OnDailyTick().
SyncData()
override void DynamicTroopEquipmentReupload.ArmyArmoryBehavior.SyncData (IDataStore dataStore)
Definition at line 23 of file ArmyArmoryBehavior.cs.
{
        if (dataStore.IsSaving) {
            SaveArmory();
            var tempData = _data;
            if (dataStore.SyncDataAsJson("DynamicTroopArmyArmory", ref tempData) && tempData != null)
                _data = tempData;
            else
                Global.Error("null data on save");
        }
        else if (dataStore.IsLoading) {
            ArmyArmory.ResetForCampaign();
            _unresolvedArmoryItemCounts.Clear();
            var tempData = new Data();
            if (dataStore.SyncDataAsJson("DynamicTroopArmyArmory", ref tempData) && tempData != null) {
                _data = tempData;
                _data.Armory ??= new Dictionary<string, int>();
                foreach (var entry in _data.Armory) {
                    if (!string.IsNullOrEmpty(entry.Key) && entry.Value > 0)
                        _unresolvedArmoryItemCounts[entry.Key] = entry.Value;
                }
            }
            else
                Global.Error("null data on load");
        }
    }
References _data, _unresolvedArmoryItemCounts, DynamicTroopEquipmentReupload.Global.Error(), DynamicTroopEquipmentReupload.ArmyArmory.ResetForCampaign(), and SaveArmory().
Member Data Documentation
_data
Data DynamicTroopEquipmentReupload.ArmyArmoryBehavior._data = new() private
Definition at line 21 of file ArmyArmoryBehavior.cs.
Referenced by OnDailyTick(), SaveArmory(), and SyncData().
_unresolvedArmoryItemCounts
readonly Dictionary<string, int> DynamicTroopEquipmentReupload.ArmyArmoryBehavior._unresolvedArmoryItemCounts = new() private
Definition at line 20 of file ArmyArmoryBehavior.cs.
Referenced by OnNewGameCreated(), RestoreReadyArmoryItems(), SaveArmory(), and SyncData().
The documentation for this class was generated from the following file:
ArmyArmoryBehavior.cs