动态装备系统: ArmyArmoryBehavior Class Reference
ArmyArmoryBehavior Class Reference
Classes
class Data
Public Member Functions
override void RegisterEvents ()
override void SyncData (IDataStore dataStore)
Private Member Functions
void AddArmyArmorySubmenu (CampaignGameStarter starter)
void AddTownMenuOptions (CampaignGameStarter starter)
void Load (Data tempData)
void OnNewGameCreated (CampaignGameStarter starter)
void OnSessionLaunched (CampaignGameStarter starter)
void Save ()
Private Attributes
Data _data = new()
Detailed Description
Definition at line 17 of file ArmyArmoryBehavior.cs.
Member Function Documentation
AddArmyArmorySubmenu()
void ArmyArmoryBehavior.AddArmyArmorySubmenu (CampaignGameStarter starter) private
Definition at line 103 of file ArmyArmoryBehavior.cs.
{
        // 创建子菜单
        starter.AddGameMenu("army_armory_submenu", LocalizedTexts.ArmoryManageOption.ToString(), args => { });
        // 在子菜单中添加选项
        starter.AddGameMenuOption("army_armory_submenu",
                                  "view_armory",
                                  LocalizedTexts.ArmorViewOption.ToString(),
                                  args => true,
                                  args => { InventoryManager.OpenScreenAsStash(ArmyArmory.Armory); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "sell_for_throwing",
                                  LocalizedTexts.SellForThrowing.ToString(),
                                  args => true,
                                  args => { ArmyArmory.SellExcessEquipmentForThrowingWeapons(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_clear_invalid_items",
                                  "DEBUG: Clear invalid items",
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.DebugClearEmptyItem(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_remove_player_crafted_items",
                                  "DEBUG: Remove player crafted items",
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.DebugRemovePlayerCraftedItems(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_rebuild_armory",
                                  "DEBUG: Rebuild player armory",
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.RebuildArmory(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_export_armory",
                                  "DEBUG: Export player armory",
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.Export(); });
        starter.AddGameMenuOption("army_armory_submenu",
                                  "debug_import_armory",
                                  "DEBUG: Import player armory",
                                  args => ModSettings.Instance?.DebugMode ?? false,
                                  args => { ArmyArmory.Import(); });
        // 返回上一级菜单的选项
        starter.AddGameMenuOption("army_armory_submenu",
                                  "return_to_town",
                                  LocalizedTexts.ReturnToTown.ToString(),
                                  args => true,
                                  args => { GameMenu.SwitchToMenu("town"); },
                                  true);
    }
References LocalizedTexts.ArmorViewOption, LocalizedTexts.ArmoryManageOption, ModSettings.DebugMode, LocalizedTexts.ReturnToTown, and LocalizedTexts.SellForThrowing.
AddTownMenuOptions()
void ArmyArmoryBehavior.AddTownMenuOptions (CampaignGameStarter starter) private
Definition at line 89 of file ArmyArmoryBehavior.cs.
{
        AddArmyArmorySubmenu(starter);
        starter.AddGameMenuOption("town",
                                  "army_armory_manage",
                                  LocalizedTexts.ArmoryManageOption.ToString(),
                                  args => true,
                                  args => {
                                      // 打开子菜单
                                      GameMenu.SwitchToMenu("army_armory_submenu");
                                  },
                                  false,
                                  4);
    }
References LocalizedTexts.ArmoryManageOption.
Load()
void ArmyArmoryBehavior.Load (Data tempData) private
Definition at line 74 of file ArmyArmoryBehavior.cs.
{
        foreach (var item in tempData.Armory) {
            var equipment = MBObjectManager.Instance.GetObject<ItemObject>(item.Key) ??
                            ItemObject.GetCraftedItemObjectFromHashedCode(item.Key);
            if (equipment != null && item.Value > 0)
                _ = ArmyArmory.Armory.AddToCounts(equipment, item.Value);
            else
                Global.Warn($"cannot get object {item.Key}");
        }
        Global.Debug($"loaded {tempData.Armory.Count} entries for player");
    }
References ArmyArmory.Armory.
Referenced by SyncData().
OnNewGameCreated()
void ArmyArmoryBehavior.OnNewGameCreated (CampaignGameStarter starter) private
Definition at line 56 of file ArmyArmoryBehavior.cs.
{
        Global.Debug("OnNewGameCreated() called");
        ArmyArmory.Armory.Clear();
    }
References ArmyArmory.Armory.
Referenced by RegisterEvents().
OnSessionLaunched()
void ArmyArmoryBehavior.OnSessionLaunched (CampaignGameStarter starter) private
Definition at line 87 of file ArmyArmoryBehavior.cs.
{ AddTownMenuOptions(starter); }
Referenced by RegisterEvents().
RegisterEvents()
override void ArmyArmoryBehavior.RegisterEvents ()
Definition at line 51 of file ArmyArmoryBehavior.cs.
{
        CampaignEvents.OnSessionLaunchedEvent.AddNonSerializedListener(this, OnSessionLaunched);
        CampaignEvents.OnNewGameCreatedEvent.AddNonSerializedListener(this, OnNewGameCreated);
    }
References OnNewGameCreated(), and OnSessionLaunched().
Save()
void ArmyArmoryBehavior.Save () private
Definition at line 61 of file ArmyArmoryBehavior.cs.
{
        var i = ArmyArmory.Armory.GetEnumerator();
        while (i.MoveNext())
            if (i.Current is { IsEmpty: false, EquipmentElement: { IsEmpty: false, Item: not null }, Amount: > 0 }) {
                if (!_data.Armory.ContainsKey(i.Current.EquipmentElement.Item.StringId))
                    _data.Armory.Add(i.Current.EquipmentElement.Item.StringId, i.Current.Amount);
                else
                    _data.Armory[i.Current.EquipmentElement.Item.StringId] += i.Current.Amount;
            }
        i.Dispose();
    }
References ArmyArmory.Armory.
Referenced by SyncData().
SyncData()
override void ArmyArmoryBehavior.SyncData (IDataStore dataStore)
Definition at line 20 of file ArmyArmoryBehavior.cs.
{
        //InformationManager.DisplayMessage(new InformationMessage("Sync Data called", Colors.Green));
        if (dataStore.IsSaving) {
            _data.Armory.Clear();
            Save();
            var tempData = _data;
            _ = dataStore.SyncDataAsJson("DynamicTroopArmyArmory", ref tempData);
            if (tempData != null) {
                _data = tempData;
                _data.Armory.Clear();
            }
            else { Global.Error("null data on save"); }
        }
        else if (dataStore.IsLoading) {
            _data.Armory.Clear();
            ArmyArmory.Armory.Clear();
            var tempData = _data;
            _ = dataStore.SyncDataAsJson("DynamicTroopArmyArmory", ref tempData);
            if (tempData != null) {
                Load(tempData);
                _data = tempData;
                _data.Armory.Clear();
            }
            else { Global.Error("null data on load"); }
        }
    }
References _data, ArmyArmory.Armory, ArmyArmoryBehavior.Data.Armory, Load(), and Save().
Member Data Documentation
_data
Data ArmyArmoryBehavior._data = new() private
Definition at line 18 of file ArmyArmoryBehavior.cs.
Referenced by SyncData().
The documentation for this class was generated from the following file:
ArmyArmoryBehavior.cs