动态装备系统: DynamicTroopEquipmentReupload.DynamicTroopMissionLogic Class Reference
DynamicTroopEquipmentReupload.DynamicTroopMissionLogic Class Reference
Public Member Functions
override void AfterStart ()
override void EarlyStart ()
override void OnAgentRemoved (Agent affectedAgent, Agent affectorAgent, AgentState agentState, KillingBlow blow)
当士兵在战斗中被移除（如被杀或被击晕）时触发的处理。
override void OnBattleEnded ()
override void OnBehaviorInitialize ()
override void OnCreated ()
override InquiryData OnEndMissionRequest (out bool canLeave)
override void OnMissionResultReady (MissionResult missionResult)
override void OnRetreatMission ()
override void OnSurrenderMission ()
void RegisterSpawnedAgentAssignment (Agent agent, Assignment assignment)
override void ShowBattleResults ()
void TryInitializeDistributors ()
Public Attributes
readonly Dictionary< MBGUID, PartyEquipmentDistributor > Distributors = new()
readonly Dictionary< MBGUID, BattleSideEnum > PartyBattleSides = new()
Protected Member Functions
override void OnEndMission ()
Private Member Functions
void HandlePartyItems (MBGUID partyId, bool isPlayerParty, bool isVictorious, bool isDefeated)
处理部队战后的物品管理。
void OnMissionEnded (MissionResult? missionResult)
void ProcessAgentEquipmentRespectingTemporarySlots (Agent agent, Action< ItemObject > processEquipmentItem)
void ReturnEquipmentFromAgents (MBGUID partyId, IEnumerable< Agent > agents)
从参与战斗的士兵那里回收装备。
void ReturnItemsToDestination (MBGUID partyId, ConcurrentDictionary< ItemObject, int > items, bool isPlayerParty)
将物品返回到指定部队。
Static Private Member Functions
static void ProcessAssignmentEquipmentFallback (Assignment assignment, Action< ItemObject > processEquipmentItem)
Private Attributes
bool _areDistributorsInitialized
readonly Dictionary< Agent, Assignment > _assignmentByAgent = new()
bool _isMissionEnded
readonly ConcurrentDictionary< MBGUID, PartyBattleRecord > _partyBattleRecords = new()
readonly HashSet< Agent > _processedAgents = new()
readonly Random _random = new()
Detailed Description
Definition at line 17 of file DynamicTroopMissionLogic.cs.
Member Function Documentation
AfterStart()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.AfterStart ()
Definition at line 87 of file DynamicTroopMissionLogic.cs.
{
        base.AfterStart();
        Global.Log("AfterStart", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log().
EarlyStart()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.EarlyStart ()
Definition at line 81 of file DynamicTroopMissionLogic.cs.
{
        base.EarlyStart();
        Global.Log("EarlyStart", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.Global.Log().
HandlePartyItems()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.HandlePartyItems (MBGUID partyId, bool isPlayerParty, bool isVictorious, bool isDefeated) private
处理部队战后的物品管理。
Parameters
partyId 部队的唯一标识符。
isPlayerParty 是否为玩家的部队。
isVictorious 部队是否胜利。
isDefeated 部队是否被击败。
Definition at line 316 of file DynamicTroopMissionLogic.cs.
{
        // 检查是否存在对应的battleRecord
        if (!_partyBattleRecords.TryGetValue(partyId, out var battleRecord)) {
            Global.Warn($"No battle record found for party {partyId}");
            return;
        }
        if (isVictorious) {
            ReturnItemsToDestination(partyId, battleRecord.ItemsToRecover, isPlayerParty);
            ReturnItemsToDestination(partyId, battleRecord.LootedItems,    isPlayerParty);
            if (isPlayerParty) {
                MessageDisplayService.EnqueueMessage(new InformationMessage(LocalizedTexts.GetLootAddedMessage(battleRecord.LootedItemsCount),                   Colors.Green));
                MessageDisplayService.EnqueueMessage(new InformationMessage(LocalizedTexts.GetItemsRecoveredFromFallenMessage(battleRecord.ItemsToRecoverCount), Colors.Green));
            }
        }
        else if (!isDefeated) { ReturnItemsToDestination(partyId, battleRecord.ItemsToRecover, isPlayerParty); }
        // 被击败的一方不获取任何物品
    }
References _partyBattleRecords, MessageDisplayService.EnqueueMessage(), DynamicTroopEquipmentReupload.LocalizedTexts.GetItemsRecoveredFromFallenMessage(), DynamicTroopEquipmentReupload.LocalizedTexts.GetLootAddedMessage(), ReturnItemsToDestination(), and DynamicTroopEquipmentReupload.Global.Warn().
Referenced by OnMissionEnded().
OnAgentRemoved()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnAgentRemoved (Agent affectedAgent, Agent affectorAgent, AgentState agentState, KillingBlow blow)
当士兵在战斗中被移除（如被杀或被击晕）时触发的处理。
Parameters
affectedAgent 被移除的士兵。
affectorAgent 造成移除的士兵。
agentState 被移除的士兵的状态（如被杀、失去意识等）。
blow 造成移除的攻击详情。
Definition at line 100 of file DynamicTroopMissionLogic.cs.
{
        if (Mission is not { PlayerTeam.IsValid: true }) {
            base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
            return;
        }
        if (!affectedAgent.IsValid() || affectedAgent.Character is not { IsHero: false }) {
            base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
            return;
        }
        if (_processedAgents.Contains(affectedAgent)) {
            base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
            return;
        }
        // potential loot for the opposing side.
        if (agentState is AgentState.Killed or AgentState.Unconscious) {
            _ = _processedAgents.Add(affectedAgent);
            var affectedPartyId = Global.GetAgentParty(affectedAgent.Origin)?.Id;
            if (!affectedPartyId.HasValue) {
                base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
                return;
            }
            if (!_partyBattleRecords.ContainsKey(affectedPartyId.Value))
                _partyBattleRecords.TryAdd(affectedPartyId.Value, new PartyBattleRecord());
            var affectedBattleRecord = _partyBattleRecords[affectedPartyId.Value];
            PartyBattleRecord? affectorBattleRecord = null;
            var                affectorPartyId      = affectorAgent.IsValid() ? Global.GetAgentParty(affectorAgent.Origin)?.Id : null;
            if (affectorPartyId.HasValue) {
                if (!_partyBattleRecords.ContainsKey(affectorPartyId.Value))
                    _partyBattleRecords.TryAdd(affectorPartyId.Value, new PartyBattleRecord());
                affectorBattleRecord = _partyBattleRecords[affectorPartyId.Value];
            }
            var hitBodyPart = blow.VictimBodyPart;
            var armors      = affectedAgent.GetAgentArmors();
            var hitArmor    = ArmorSelector.GetRandomArmorByBodyPart(armors, hitBodyPart);
            // Extra armor break: ONLY for enemy casualties, tierbased.
            // This is an addition to the existing hitArmor destruction logic.
            ItemObject? extraBrokenArmor = null;
            var isEnemyCasualty = false;
            if (PartyBattleSides.TryGetValue(affectedPartyId.Value, out var affectedSide))
            {
                isEnemyCasualty = affectedSide != Mission.PlayerTeam.Side;
            }
            if (isEnemyCasualty)
            {
                var troopTier = 0;
                if (affectedAgent.Character is CharacterObject characterObject)
                    troopTier = characterObject.Tier;
                var extraBreakChance = troopTier switch {
                    3 => 0.25f,
                    4 => 0.35f,
                    5 => 0.45f,
                    _ => troopTier >= 6 ? 0.60f : 0f
                };
                if (extraBreakChance > 0f && _random.NextFloat() <= extraBreakChance)
                {
                    // Pick an additional armor piece to destroy (excluding hitArmor)
                    var candidates = new List<ItemObject>();
                    foreach (var armor in armors)
                    {
                        if (armor == null)
                            continue;
                        if (hitArmor != null && armor.StringId == hitArmor.StringId)
                            continue;
                        if (armor.ItemType == ItemObject.ItemTypeEnum.HorseHarness)
                            continue;
                        candidates.Add(armor);
                    }
                    if (candidates.Count > 0)
                        extraBrokenArmor = candidates[_random.Next(candidates.Count)];
                }
            }
            ProcessAgentEquipmentRespectingTemporarySlots(
                affectedAgent,
                item => {
                    if (item == null || !ItemBlackList.Test(item))
                        return;
                    if (hitArmor != null && item.StringId == hitArmor.StringId)
                        return;
                    if (extraBrokenArmor != null && item.StringId == extraBrokenArmor.StringId)
                        return;
                    var dropRate = SubModule.Settings?.DropRate ?? 1f;
                    affectedBattleRecord.AddItemToRecover(item);
                    if (affectorBattleRecord != null && _random.NextFloat() <= dropRate) {
                        affectorBattleRecord.AddLootedItem(item);
                        Global.Log($"{item.StringId} looted", Colors.Green, Level.Debug);
                    }
                });
        }
        //Routed (alive, removed mid-battle), make sure their equipment is still returned to their own armory
        else if (!_isMissionEnded && agentState is AgentState.Routed or AgentState.Deleted) {
            _ = _processedAgents.Add(affectedAgent);
            var affectedPartyId = Global.GetAgentParty(affectedAgent.Origin)?.Id;
            if (!affectedPartyId.HasValue) {
                base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
                return;
            }
            if (!_partyBattleRecords.ContainsKey(affectedPartyId.Value))
                _partyBattleRecords.TryAdd(affectedPartyId.Value, new PartyBattleRecord());
            var affectedBattleRecord = _partyBattleRecords[affectedPartyId.Value];
            ProcessAgentEquipmentRespectingTemporarySlots(affectedAgent, item => { affectedBattleRecord.AddItemToRecover(item); });
            Global.Log(
                $"[DTES] Killed/Unconscious processed for {affectedAgent.Character?.Name} | party={affectedPartyId.Value} | recordRecoverNow={affectedBattleRecord.ItemsToRecoverCount}",
                Colors.Green,
                Level.Debug);
        }
        base.OnAgentRemoved(affectedAgent, affectorAgent, agentState, blow);
    }
References _isMissionEnded, _partyBattleRecords, _processedAgents, _random, DynamicTroopEquipmentReupload.PartyBattleRecord.AddLootedItem(), DynamicTroopEquipmentReupload.ModSettings.DropRate, DynamicTroopEquipmentReupload.Global.GetAgentParty(), DynamicTroopEquipmentReupload.ArmorSelector.GetRandomArmorByBodyPart(), DynamicTroopEquipmentReupload.Global.Log(), PartyBattleSides, ProcessAgentEquipmentRespectingTemporarySlots(), DynamicTroopEquipmentReupload.SubModule.Settings, and DynamicTroopEquipmentReupload.ItemBlackList.Test().
OnBattleEnded()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnBattleEnded ()
Definition at line 270 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnBattleEnded() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.OnBattleEnded();
    }
References DynamicTroopEquipmentReupload.Global.Log(), and OnMissionEnded().
OnBehaviorInitialize()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnBehaviorInitialize ()
Definition at line 36 of file DynamicTroopMissionLogic.cs.
{
        base.OnBehaviorInitialize();
        Global.Log("OnBehaviorInitialize", Colors.Green, Level.Debug);
        _processedAgents.Clear();
        _partyBattleRecords.Clear();
        Distributors.Clear();
        PartyBattleSides.Clear();
        _assignmentByAgent.Clear();
        _isMissionEnded = false;
        _areDistributorsInitialized = false;
        TryInitializeDistributors();
    }
References _areDistributorsInitialized, _assignmentByAgent, _isMissionEnded, _partyBattleRecords, _processedAgents, Distributors, DynamicTroopEquipmentReupload.Global.Log(), PartyBattleSides, and TryInitializeDistributors().
OnCreated()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnCreated ()
Definition at line 32 of file DynamicTroopMissionLogic.cs.
{
        base.OnCreated();
    }
OnEndMission()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnEndMission () protected
Definition at line 438 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnEndMission() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.OnEndMission();
    }
References DynamicTroopEquipmentReupload.Global.Log(), and OnMissionEnded().
OnEndMissionRequest()
override InquiryData DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnEndMissionRequest (out bool canLeave)
Definition at line 258 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnEndMissionRequest() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        return base.OnEndMissionRequest(out canLeave);
    }
References DynamicTroopEquipmentReupload.Global.Log(), and OnMissionEnded().
OnMissionEnded()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnMissionEnded (MissionResult? missionResult) private
Definition at line 276 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnMissionEnded() called", Colors.Green, Level.Debug);
        if (_isMissionEnded) return;
        _isMissionEnded = true;
        var playerVictory    = missionResult?.PlayerVictory  ?? false;
        var playerDefeat     = missionResult?.PlayerDefeated ?? false;
        var unresolvedBattle = missionResult == null || !missionResult.BattleResolved;
        // 确定玩家方
        var playerPartyId = Campaign.Current.MainParty.Id;
        foreach (var kvPartyBattleSides in PartyBattleSides) {
            var isPlayerParty = kvPartyBattleSides.Key == playerPartyId;
            var isVictorious  = !unresolvedBattle && (playerVictory && kvPartyBattleSides.Value == Mission.PlayerTeam.Side || playerDefeat  && kvPartyBattleSides.Value != Mission.PlayerTeam.Side);
            var isDefeated    = !unresolvedBattle && (playerDefeat  && kvPartyBattleSides.Value == Mission.PlayerTeam.Side || playerVictory && kvPartyBattleSides.Value != Mission.PlayerTeam.Side);
            HandlePartyItems(kvPartyBattleSides.Key, isPlayerParty, isVictorious, isDefeated);
        }
        // 回收场上士兵的装备
        foreach (var kvPartyBattleSides in PartyBattleSides) {
            IEnumerable<Agent> partyAgents = Mission.Agents.WhereQ(agent =>
                                                                       agent.IsValid()                   &&
                                                                       agent.IsActive()                  &&
                                                                       !agent.IsHero                     &&
                                                                       !_processedAgents.Contains(agent) &&
                                                                       Global.GetAgentParty(agent.Origin)?.Id == kvPartyBattleSides.Key);
            ReturnEquipmentFromAgents(kvPartyBattleSides.Key, partyAgents);
        }
    }
References _isMissionEnded, _processedAgents, DynamicTroopEquipmentReupload.Global.GetAgentParty(), HandlePartyItems(), DynamicTroopEquipmentReupload.Global.Log(), PartyBattleSides, and ReturnEquipmentFromAgents().
Referenced by OnBattleEnded(), OnEndMission(), OnEndMissionRequest(), OnMissionResultReady(), OnRetreatMission(), OnSurrenderMission(), and ShowBattleResults().
OnMissionResultReady()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnMissionResultReady (MissionResult missionResult)
Definition at line 252 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnMissionResultReady() called", Colors.Green, Level.Debug);
        OnMissionEnded(missionResult);
        base.OnMissionResultReady(missionResult);
    }
References DynamicTroopEquipmentReupload.Global.Log(), and OnMissionEnded().
OnRetreatMission()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnRetreatMission ()
Definition at line 240 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnRetreatMission() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.OnRetreatMission();
    }
References DynamicTroopEquipmentReupload.Global.Log(), and OnMissionEnded().
OnSurrenderMission()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnSurrenderMission ()
Definition at line 246 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("OnSurrenderMission() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.OnSurrenderMission();
    }
References DynamicTroopEquipmentReupload.Global.Log(), and OnMissionEnded().
ProcessAgentEquipmentRespectingTemporarySlots()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ProcessAgentEquipmentRespectingTemporarySlots (Agent agent, Action< ItemObject > processEquipmentItem) private
Definition at line 394 of file DynamicTroopMissionLogic.cs.
{
        if (_assignmentByAgent.TryGetValue(agent, out var assignment)) {
            var processedItemCount = 0;
            Global.ProcessAgentEquipment(
                agent,
                item => {
                    processedItemCount++;
                    processEquipmentItem(item);
                },
                (slot, missionWeapon, spawnElement) => !assignment.IsTemporarySlot(slot, spawnElement.Item));
            if (processedItemCount == 0) {
                Global.Log($"[DTES] Agent equipment returned 0 items. Fallback to Assignment. Agent={agent.Character?.Name}", Colors.Yellow, Level.Debug);
                ProcessAssignmentEquipmentFallback(assignment, processEquipmentItem);
            }
            return;
        }
        Global.ProcessAgentEquipment(agent, processEquipmentItem);
    }
References _assignmentByAgent, DynamicTroopEquipmentReupload.Global.Log(), DynamicTroopEquipmentReupload.Global.ProcessAgentEquipment(), and ProcessAssignmentEquipmentFallback().
Referenced by OnAgentRemoved(), and ReturnEquipmentFromAgents().
ProcessAssignmentEquipmentFallback()
static void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ProcessAssignmentEquipmentFallback (Assignment assignment, Action< ItemObject > processEquipmentItem) static private
Definition at line 417 of file DynamicTroopMissionLogic.cs.
{
        foreach (var slot in Global.EquipmentSlots) {
            var element = assignment.Equipment[slot];
            if (element.IsEmpty || element.Item is null)
                continue;
            if (element.Item.IsBannerItem || element.Item.ItemType == ItemObject.ItemTypeEnum.Banner)
                continue;
            if (assignment.IsTemporarySlot(slot, element.Item))
                continue;
            if (element.Item.ItemType is ItemObject.ItemTypeEnum.Arrows
                                         or ItemObject.ItemTypeEnum.Bolts
                                         or ItemObject.ItemTypeEnum.Thrown) { continue; }
            processEquipmentItem(element.Item);
        }
    }
References DynamicTroopEquipmentReupload.Global.EquipmentSlots.
Referenced by ProcessAgentEquipmentRespectingTemporarySlots().
RegisterSpawnedAgentAssignment()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.RegisterSpawnedAgentAssignment (Agent agent, Assignment assignment)
Definition at line 389 of file DynamicTroopMissionLogic.cs.
{
        _assignmentByAgent[agent] = assignment;
    }
References _assignmentByAgent.
Referenced by DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix().
ReturnEquipmentFromAgents()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnEquipmentFromAgents (MBGUID partyId, IEnumerable< Agent > agents) private
从参与战斗的士兵那里回收装备。
Parameters
partyId 部队的唯一标识符。
agents 参与战斗的士兵集合。
Definition at line 367 of file DynamicTroopMissionLogic.cs.
{
        var isPlayerParty  = partyId == Campaign.Current.MainParty.Id;
        var totalItemCount = 0;
        foreach (var agent in agents)
            ProcessAgentEquipmentRespectingTemporarySlots(agent,
                                                          item => {
                                                              if (item is null || !ItemBlackList.Test(item)) return;
                                                              totalItemCount++;
                                                              if (isPlayerParty)
                                                                  ArmyArmory.AddItemToArmory(item);
                                                              else if (Distributors.TryGetValue(partyId, out var distributor))
                                                                  distributor.ReturnItem(item, 1);
                                                          });
        if (totalItemCount <= 0) return;
        var partyType = isPlayerParty ? "Player party" : "Party";
        Global.Log($"{partyType} {partyId} reclaimed {totalItemCount} items from agents", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory(), Distributors, DynamicTroopEquipmentReupload.Global.Log(), ProcessAgentEquipmentRespectingTemporarySlots(), and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by OnMissionEnded().
ReturnItemsToDestination()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnItemsToDestination (MBGUID partyId, ConcurrentDictionary< ItemObject, int > items, bool isPlayerParty) private
将物品返回到指定部队。
Parameters
partyId 部队的唯一标识符。
items 要返回的物品及其数量。
isPlayerParty 是否为玩家的部队。
Definition at line 342 of file DynamicTroopMissionLogic.cs.
{
        var totalItemCount = 0; // 用于累计物品总数
        foreach (var item in items) {
            if (item.Key == null || item.Value <= 0 || !ItemBlackList.Test(item.Key)) continue;
            totalItemCount += item.Value;
            if (isPlayerParty)
                ArmyArmory.AddItemToArmory(item.Key, item.Value);
            else if (Distributors.TryGetValue(partyId, out var distributor))
                distributor.ReturnItem(item.Key, item.Value);
        }
        if (totalItemCount <= 0) return;
        var partyType = isPlayerParty ? "Player party" : "Party";
        Global.Log($"{partyType} {partyId} processed a total of {totalItemCount} items", Colors.Green, Level.Debug);
    }
References DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory(), Distributors, DynamicTroopEquipmentReupload.Global.Log(), and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by HandlePartyItems().
ShowBattleResults()
override void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ShowBattleResults ()
Definition at line 264 of file DynamicTroopMissionLogic.cs.
{
        Global.Log("ShowBattleResults() called", Colors.Green, Level.Debug);
        OnMissionEnded(null);
        base.ShowBattleResults();
    }
References DynamicTroopEquipmentReupload.Global.Log(), and OnMissionEnded().
TryInitializeDistributors()
void DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.TryInitializeDistributors ()
Definition at line 52 of file DynamicTroopMissionLogic.cs.
{
        if (_areDistributorsInitialized || _isMissionEnded) { return; }
        if (MapEvent.PlayerMapEvent == null || MapEvent.PlayerMapEvent.IsRaid) { return; }
        var mainParty            = Campaign.Current.MainParty;
        var mainPartyDistributor = new PartyEquipmentDistributor(Mission, mainParty, ArmyArmory.Armory);
        mainPartyDistributor.RunAsync();
        Distributors[mainParty.Id] = mainPartyDistributor;
        PartyBattleSides[mainParty.Id] = PartyBase.MainParty.Side;
        foreach (var partyBase in MapEvent.PlayerMapEvent.InvolvedParties) {
            var party = partyBase.MobileParty;
            if (party == null || !party.IsValid() || party == Campaign.Current.MainParty || party.LeaderHero == null) { continue; }
            if (!EveryoneCampaignBehavior.PartyArmories.TryGetValue(party.Id, out var partyArmory)) { continue; }
            var distributor = new PartyEquipmentDistributor(Mission, party, partyArmory);
            distributor.RunAsync();
            Distributors[party.Id] = distributor;
            PartyBattleSides[party.Id] = partyBase.Side;
        }
        _areDistributorsInitialized = true;
    }
References _areDistributorsInitialized, _isMissionEnded, DynamicTroopEquipmentReupload.ArmyArmory.Armory, Distributors, DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.PartyArmories, and PartyBattleSides.
Referenced by OnBehaviorInitialize().
Member Data Documentation
_areDistributorsInitialized
bool DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._areDistributorsInitialized private
Definition at line 28 of file DynamicTroopMissionLogic.cs.
Referenced by OnBehaviorInitialize(), and TryInitializeDistributors().
_assignmentByAgent
readonly Dictionary<Agent, Assignment> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._assignmentByAgent = new() private
Definition at line 18 of file DynamicTroopMissionLogic.cs.
Referenced by OnBehaviorInitialize(), ProcessAgentEquipmentRespectingTemporarySlots(), and RegisterSpawnedAgentAssignment().
_isMissionEnded
bool DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._isMissionEnded private
Definition at line 30 of file DynamicTroopMissionLogic.cs.
Referenced by OnAgentRemoved(), OnBehaviorInitialize(), OnMissionEnded(), and TryInitializeDistributors().
_partyBattleRecords
readonly ConcurrentDictionary<MBGUID, PartyBattleRecord> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._partyBattleRecords = new() private
Definition at line 19 of file DynamicTroopMissionLogic.cs.
Referenced by HandlePartyItems(), OnAgentRemoved(), and OnBehaviorInitialize().
_processedAgents
readonly HashSet<Agent> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._processedAgents = new() private
Definition at line 21 of file DynamicTroopMissionLogic.cs.
Referenced by OnAgentRemoved(), OnBehaviorInitialize(), and OnMissionEnded().
_random
readonly Random DynamicTroopEquipmentReupload.DynamicTroopMissionLogic._random = new() private
Definition at line 23 of file DynamicTroopMissionLogic.cs.
Referenced by OnAgentRemoved().
Distributors
readonly Dictionary<MBGUID, PartyEquipmentDistributor> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.Distributors = new()
Definition at line 25 of file DynamicTroopMissionLogic.cs.
Referenced by OnBehaviorInitialize(), ReturnEquipmentFromAgents(), ReturnItemsToDestination(), and TryInitializeDistributors().
PartyBattleSides
readonly Dictionary<MBGUID, BattleSideEnum> DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.PartyBattleSides = new()
Definition at line 27 of file DynamicTroopMissionLogic.cs.
Referenced by OnAgentRemoved(), OnBehaviorInitialize(), OnMissionEnded(), and TryInitializeDistributors().
The documentation for this class was generated from the following file:
DynamicTroopMissionLogic.cs