动态装备系统: DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin Class Reference
DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin Class Reference sealed
Public Member Functions
MapArmoryReadinessMixin (MapBarVM mapBar)
void ExecuteOpenArmyArmory ()
override void OnRefresh ()
Properties
float ArmoryReadinessFillHeight [get, private set]
HintViewModel ArmoryReadinessHint [get, private set]
bool IsArmoryReadinessVisible [get, private set]
Private Member Functions
bool MainPartyTroopCompositionChanged (MobileParty mainParty)
Static Private Member Functions
static bool CanOpenArmory (MapBarVM mapBar, MobileParty? mainParty)
Private Attributes
float _armoryReadinessFillHeight
HintViewModel _armoryReadinessHint
bool _hasReadinessContextSnapshot
bool _isArmoryReadinessVisible
int _lastArmoryVersion = -1
bool _lastMainPartyAtSea
readonly Dictionary< CharacterObject, int > _lastMainPartyTroopCounts = new()
int _lastMemberRosterVersion = -1
bool _lastPreferDefaultEquipmentThenClosest
MobileParty? _trackedMainParty
Static Private Attributes
const float INDICATOR_HEIGHT = 152f
Detailed Description
Definition at line 18 of file MapArmoryReadiness.cs.
Constructor & Destructor Documentation
MapArmoryReadinessMixin()
DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.MapArmoryReadinessMixin (MapBarVM mapBar)
Definition at line 32 of file MapArmoryReadiness.cs.
                                                    : base(mapBar) {
        _armoryReadinessHint = new HintViewModel();
    }
References _armoryReadinessHint.
Member Function Documentation
CanOpenArmory()
static bool DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.CanOpenArmory (MapBarVM mapBar, MobileParty? mainParty) static private
Definition at line 111 of file MapArmoryReadiness.cs.
{
        return Campaign.Current != null &&
               mainParty != null &&
               Hero.MainHero is { IsPrisoner: false } &&
               mapBar.IsEnabled &&
               mapBar.MapTimeControl is { IsInMap: true, IsCenterPanelEnabled: true } &&
               !mainParty.IsTransitionInProgress &&
               mainParty.MapEvent == null &&
               PlayerEncounter.Current == null;
    }
Referenced by ExecuteOpenArmyArmory(), and OnRefresh().
ExecuteOpenArmyArmory()
void DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.ExecuteOpenArmyArmory ()
Definition at line 123 of file MapArmoryReadiness.cs.
{
        var mapBar = ViewModel;
        var mainParty = Campaign.Current != null ? MobileParty.MainParty : null;
        if (mapBar != null && CanOpenArmory(mapBar, mainParty))
            ArmyArmoryBehavior.OpenArmoryScreen();
    }
References CanOpenArmory(), and DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OpenArmoryScreen().
MainPartyTroopCompositionChanged()
bool DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.MainPartyTroopCompositionChanged (MobileParty mainParty) private
Definition at line 83 of file MapArmoryReadiness.cs.
{
        var currentTroopCounts = new Dictionary<CharacterObject, int>();
        foreach (var rosterElement in mainParty.MemberRoster.GetTroopRoster()) {
            if (rosterElement.Character is CharacterObject { IsHero: false } character && rosterElement.Number > 0)
                currentTroopCounts[character] = rosterElement.Number;
        }
        if (currentTroopCounts.Count == _lastMainPartyTroopCounts.Count) {
            var compositionChanged = false;
            foreach (var troopCount in currentTroopCounts) {
                if (!_lastMainPartyTroopCounts.TryGetValue(troopCount.Key, out var previousCount) || previousCount != troopCount.Value) {
                    compositionChanged = true;
                    break;
                }
            }
            if (!compositionChanged)
                return false;
        }
        _lastMainPartyTroopCounts.Clear();
        foreach (var troopCount in currentTroopCounts)
            _lastMainPartyTroopCounts.Add(troopCount.Key, troopCount.Value);
        return true;
    }
References _lastMainPartyTroopCounts.
Referenced by OnRefresh().
OnRefresh()
override void DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.OnRefresh ()
Definition at line 36 of file MapArmoryReadiness.cs.
{
        var mapBar = ViewModel;
        var mainParty = Campaign.Current != null ? MobileParty.MainParty : null;
        var canOpenArmory = mapBar != null && CanOpenArmory(mapBar, mainParty);
        IsArmoryReadinessVisible = canOpenArmory;
        if (!canOpenArmory || mainParty == null)
            return;
        if (!ReferenceEquals(_trackedMainParty, mainParty)) {
            _trackedMainParty = mainParty;
            _lastArmoryVersion = -1;
            _lastMemberRosterVersion = -1;
            _hasReadinessContextSnapshot = false;
            _lastMainPartyTroopCounts.Clear();
        }
        var armoryVersion = ArmyArmory.Armory.VersionNo;
        var memberRosterVersion = mainParty.MemberRoster.VersionNo;
        var preferDefaultEquipmentThenClosest = ModSettings.Instance?.PreferDefaultEquipmentThenClosest ?? true;
        var mainPartyAtSea = mainParty.IsCurrentlyAtSea;
        var readinessContextChanged = !_hasReadinessContextSnapshot ||
            _lastPreferDefaultEquipmentThenClosest != preferDefaultEquipmentThenClosest ||
            _lastMainPartyAtSea != mainPartyAtSea;
        var troopCompositionChanged = false;
        if (_lastMemberRosterVersion != memberRosterVersion) {
            _lastMemberRosterVersion = memberRosterVersion;
            troopCompositionChanged = MainPartyTroopCompositionChanged(mainParty);
        }
        if (_lastArmoryVersion == armoryVersion && !troopCompositionChanged && !readinessContextChanged)
            return;
        _lastArmoryVersion = armoryVersion;
        _hasReadinessContextSnapshot = true;
        _lastPreferDefaultEquipmentThenClosest = preferDefaultEquipmentThenClosest;
        _lastMainPartyAtSea = mainPartyAtSea;
        var readiness = PartyEquipmentDistributor.MeasureMainPartyArmoryReadiness(!mainPartyAtSea);
        ArmoryReadinessFillHeight = INDICATOR_HEIGHT * readiness.FillRatio;
        var hintText = new TextObject("{=armory_readiness_hint}Army Armory readiness: {PERCENT}% ({FILLED}/{EXPECTED} required equipment slots filled)");
        hintText.SetTextVariable("PERCENT", readiness.Percentage);
        hintText.SetTextVariable("FILLED", readiness.EquippedSlots);
        hintText.SetTextVariable("EXPECTED", readiness.ExpectedSlots);
    }
References _hasReadinessContextSnapshot, _lastArmoryVersion, _lastMainPartyAtSea, _lastMainPartyTroopCounts, _lastMemberRosterVersion, _lastPreferDefaultEquipmentThenClosest, _trackedMainParty, DynamicTroopEquipmentReupload.ArmyArmory.Armory, ArmoryReadinessFillHeight, CanOpenArmory(), INDICATOR_HEIGHT, IsArmoryReadinessVisible, MainPartyTroopCompositionChanged(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.MeasureMainPartyArmoryReadiness(), and DynamicTroopEquipmentReupload.ModSettings.PreferDefaultEquipmentThenClosest.
Member Data Documentation
_armoryReadinessFillHeight
float DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._armoryReadinessFillHeight private
Definition at line 29 of file MapArmoryReadiness.cs.
_armoryReadinessHint
HintViewModel DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._armoryReadinessHint private
Definition at line 30 of file MapArmoryReadiness.cs.
Referenced by MapArmoryReadinessMixin().
_hasReadinessContextSnapshot
bool DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._hasReadinessContextSnapshot private
Definition at line 25 of file MapArmoryReadiness.cs.
Referenced by OnRefresh().
_isArmoryReadinessVisible
bool DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._isArmoryReadinessVisible private
Definition at line 28 of file MapArmoryReadiness.cs.
_lastArmoryVersion
int DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._lastArmoryVersion = -1 private
Definition at line 23 of file MapArmoryReadiness.cs.
Referenced by OnRefresh().
_lastMainPartyAtSea
bool DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._lastMainPartyAtSea private
Definition at line 27 of file MapArmoryReadiness.cs.
Referenced by OnRefresh().
_lastMainPartyTroopCounts
readonly Dictionary<CharacterObject, int> DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._lastMainPartyTroopCounts = new() private
Definition at line 21 of file MapArmoryReadiness.cs.
Referenced by MainPartyTroopCompositionChanged(), and OnRefresh().
_lastMemberRosterVersion
int DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._lastMemberRosterVersion = -1 private
Definition at line 24 of file MapArmoryReadiness.cs.
Referenced by OnRefresh().
_lastPreferDefaultEquipmentThenClosest
bool DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._lastPreferDefaultEquipmentThenClosest private
Definition at line 26 of file MapArmoryReadiness.cs.
Referenced by OnRefresh().
_trackedMainParty
MobileParty? DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin._trackedMainParty private
Definition at line 22 of file MapArmoryReadiness.cs.
Referenced by OnRefresh().
INDICATOR_HEIGHT
const float DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.INDICATOR_HEIGHT = 152f static private
Definition at line 19 of file MapArmoryReadiness.cs.
Referenced by OnRefresh().
Property Documentation
ArmoryReadinessFillHeight
float DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.ArmoryReadinessFillHeight get private set
Definition at line 143 of file MapArmoryReadiness.cs.
{
        get => _armoryReadinessFillHeight;
        private set {
            if (_armoryReadinessFillHeight.Equals(value))
                return;
            _armoryReadinessFillHeight = value;
            OnPropertyChangedWithValue(value);
        }
    }
Referenced by OnRefresh().
ArmoryReadinessHint
HintViewModel DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.ArmoryReadinessHint get private set
Definition at line 155 of file MapArmoryReadiness.cs.
{
        get => _armoryReadinessHint;
        private set {
            if (ReferenceEquals(_armoryReadinessHint, value))
                return;
            _armoryReadinessHint = value;
            OnPropertyChangedWithValue(value);
        }
    }
IsArmoryReadinessVisible
bool DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.IsArmoryReadinessVisible get private set
Definition at line 131 of file MapArmoryReadiness.cs.
{
        get => _isArmoryReadinessVisible;
        private set {
            if (_isArmoryReadinessVisible == value)
                return;
            _isArmoryReadinessVisible = value;
            OnPropertyChangedWithValue(value);
        }
    }
Referenced by OnRefresh().
The documentation for this class was generated from the following file:
GUIExtensions/MapArmoryReadiness.cs