动态装备系统: Armories Class Reference
Armories Class Reference
Public Member Functions
bool AddParty (MobileParty party)
Armory? GetParty (MobileParty party)
void Load (Dictionary< uint, Dictionary<(uint, uint), int > > data)
Armory? RemoveParty (MobileParty party)
Private Attributes
readonly ConcurrentDictionary< MobileParty, Armory > _armories = new()
Detailed Description
Definition at line 11 of file Armories.cs.
Member Function Documentation
AddParty()
bool Armories.AddParty (MobileParty party)
Definition at line 14 of file Armories.cs.
{
        try { return _armories.TryAdd(party, new Armory(party)); }
        catch (Exception e) {
            Global.Error(e.Message);
            return false;
        }
    }
References _armories.
GetParty()
Armory? Armories.GetParty (MobileParty party)
Definition at line 30 of file Armories.cs.
{
        try { return _armories.TryGetValue(party, out var armory) ? armory : null; }
        catch (Exception e) {
            Global.Error(e.Message);
            return null;
        }
    }
References _armories.
Load()
void Armories.Load (Dictionary< uint, Dictionary<(uint, uint), int > > data)
Definition at line 38 of file Armories.cs.
{
        //var partyObj = MBObjectManager.Instance.GetObject()
        _armories.Clear();
        var party = Campaign.Current.MobileParties.First(party => party.Id.InternalValue == 1);
        throw new NotImplementedException();
    }
References _armories.
RemoveParty()
Armory? Armories.RemoveParty (MobileParty party)
Definition at line 22 of file Armories.cs.
{
        try { return _armories.TryRemove(party, out var armory) ? armory : null; }
        catch (Exception e) {
            Global.Error(e.Message);
            return null;
        }
    }
References _armories.
Member Data Documentation
_armories
readonly ConcurrentDictionary<MobileParty, Armory> Armories._armories = new() private
Definition at line 12 of file Armories.cs.
Referenced by AddParty(), GetParty(), Load(), and RemoveParty().
The documentation for this class was generated from the following file:
Armories.cs