动态装备系统: DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch Class Reference
DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch Class Reference
Static Private Member Functions
static ItemRoster CreateSanitizedRoster (ItemRoster sourceRoster)
static void Prefix (PartyBase winnerParty, ItemRoster gainedLoots)
static void ReplaceRosterContents (ItemRoster targetRoster, ItemRoster sourceRoster)
Static Private Attributes
static readonly Random _random = new()
Detailed Description
Definition at line 15 of file ItemRosterForPlayerLootSharePatch.cs.
Member Function Documentation
CreateSanitizedRoster()
static ItemRoster DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.CreateSanitizedRoster (ItemRoster sourceRoster) static private
Definition at line 80 of file ItemRosterForPlayerLootSharePatch.cs.
{
        var sanitizedRoster = new ItemRoster();
        foreach (var rosterElement in sourceRoster) {
            if (rosterElement.Amount <= 0 ||
                !ArmyArmory.TryNormalizeArmoryElement(rosterElement.EquipmentElement, out var equipmentElement))
                continue;
            sanitizedRoster.AddToCounts(equipmentElement, rosterElement.Amount);
        }
        return sanitizedRoster;
    }
References DynamicTroopEquipmentReupload.ArmyArmory.TryNormalizeArmoryElement().
Referenced by Prefix().
Prefix()
static void DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.Prefix (PartyBase winnerParty, ItemRoster gainedLoots) static private
Definition at line 18 of file ItemRosterForPlayerLootSharePatch.cs.
{
        if ((ModSettings.Instance?.UseVanillaLootingSystem ?? false) || winnerParty != PartyBase.MainParty)
            return;
        var playerEncounter = PlayerEncounter.Current;
        var mapEvent = MapEvent.PlayerMapEvent;
        if (mapEvent == null ||
            mapEvent.WinningSide != mapEvent.PlayerSide ||
            playerEncounter?.IsNavalEncounterFinishedWithDisengage == true ||
            playerEncounter?.ForceHideoutSendTroops == true)
            return;
        var sanitizedVanillaLoot = CreateSanitizedRoster(gainedLoots);
        var dynamicTroopLoot = new ItemRoster();
        var playerContribution = mapEvent.GetPlayerBattleContributionRate();
        if (float.IsNaN(playerContribution) || float.IsInfinity(playerContribution))
            playerContribution = 0f;
        playerContribution = MBMath.ClampFloat(
            playerContribution * (ModSettings.Instance?.DropRate ?? 1f),
            0f,
            1f);
        foreach (var defeatedParty in mapEvent.PartiesOnSide(mapEvent.DefeatedSide)) {
            var defeatedMobileParty = defeatedParty.Party.MobileParty;
            if (defeatedMobileParty == null)
                continue;
            var defeatedArmory = EveryoneCampaignBehavior.SanitizePartyArmory(defeatedMobileParty.Id);
            if (defeatedArmory == null)
                continue;
            foreach (var entry in defeatedArmory) {
                if (entry.Value <= 0 ||
                    !ArmyArmory.TryResolveArmoryItem(entry.Key, out var item) ||
                    !ItemBlackList.Test(item))
                    continue;
                var expectedCount = entry.Value * playerContribution;
                var lootCount = (int)expectedCount;
                if (_random.NextDouble() < expectedCount - lootCount)
                    lootCount++;
                lootCount = Math.Min(lootCount, entry.Value);
                if (lootCount > 0)
                    dynamicTroopLoot.AddToCounts(item, lootCount);
            }
        }
        if (dynamicTroopLoot.IsEmpty()) {
            ReplaceRosterContents(gainedLoots, sanitizedVanillaLoot);
            return;
        }
        foreach (var rosterElement in sanitizedVanillaLoot) {
            var item = rosterElement.EquipmentElement.Item;
            if (item.IsTradeGood || item.IsBannerItem || item.ItemType == ItemObject.ItemTypeEnum.Animal)
                dynamicTroopLoot.AddToCounts(rosterElement.EquipmentElement, rosterElement.Amount);
        }
        ReplaceRosterContents(gainedLoots, dynamicTroopLoot);
    }
References _random, CreateSanitizedRoster(), DynamicTroopEquipmentReupload.ModSettings.DropRate, ReplaceRosterContents(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.SanitizePartyArmory(), DynamicTroopEquipmentReupload.ItemBlackList.Test(), DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem(), and DynamicTroopEquipmentReupload.ModSettings.UseVanillaLootingSystem.
ReplaceRosterContents()
static void DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.ReplaceRosterContents (ItemRoster targetRoster, ItemRoster sourceRoster) static private
Definition at line 93 of file ItemRosterForPlayerLootSharePatch.cs.
{
        targetRoster.Clear();
        foreach (var rosterElement in sourceRoster)
            targetRoster.AddToCounts(rosterElement.EquipmentElement, rosterElement.Amount);
    }
Referenced by Prefix().
Member Data Documentation
_random
readonly Random DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch._random = new() static private
Definition at line 16 of file ItemRosterForPlayerLootSharePatch.cs.
Referenced by Prefix().
The documentation for this class was generated from the following file:
CSharpSourceCode/Patches/ItemRosterForPlayerLootSharePatch.cs