动态装备系统: DynamicTroopEquipmentReupload.PartyBattleRecord Class Reference
DynamicTroopEquipmentReupload.PartyBattleRecord Class Reference
Public Member Functions
void AddItemToRecover (ItemObject item)
void AddItemToRecover (ItemObject item, int count)
void AddLootedItem (ItemObject item)
void AddLootedItem (ItemObject item, int count)
Public Attributes
readonly ConcurrentDictionary< ItemObject, int > ItemsToRecover = new()
readonly ConcurrentDictionary< ItemObject, int > LootedItems = new()
Properties
int ItemsToRecoverCount [get]
int LootedItemsCount [get]
Static Private Member Functions
static void AddItemToDictionary (IDictionary< ItemObject, int > dictionary, ItemObject? item, int count)
Detailed Description
Definition at line 8 of file PartyBattleRecord.cs.
Member Function Documentation
AddItemToDictionary()
static void DynamicTroopEquipmentReupload.PartyBattleRecord.AddItemToDictionary (IDictionary< ItemObject, int > dictionary, ItemObject? item, int count) static private
Definition at line 27 of file PartyBattleRecord.cs.
{
        if (item == null || !ItemBlackList.Test(item)) return;
        dictionary[item] = dictionary.TryGetValue(item, out var existingCount) ? existingCount + count : count;
    }
References DynamicTroopEquipmentReupload.ItemBlackList.Test().
Referenced by AddItemToRecover(), AddItemToRecover(), AddLootedItem(), and AddLootedItem().
AddItemToRecover() [1/2]
void DynamicTroopEquipmentReupload.PartyBattleRecord.AddItemToRecover (ItemObject item)
Definition at line 17 of file PartyBattleRecord.cs.
{
        AddItemToDictionary(ItemsToRecover, item, 1);
    }
References AddItemToDictionary(), and ItemsToRecover.
AddItemToRecover() [2/2]
void DynamicTroopEquipmentReupload.PartyBattleRecord.AddItemToRecover (ItemObject item, int count)
Definition at line 21 of file PartyBattleRecord.cs.
{ AddItemToDictionary(ItemsToRecover, item, count); }
References AddItemToDictionary(), and ItemsToRecover.
AddLootedItem() [1/2]
void DynamicTroopEquipmentReupload.PartyBattleRecord.AddLootedItem (ItemObject item)
Definition at line 23 of file PartyBattleRecord.cs.
{ AddItemToDictionary(LootedItems, item, 1); }
References AddItemToDictionary(), and LootedItems.
Referenced by DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnAgentRemoved().
AddLootedItem() [2/2]
void DynamicTroopEquipmentReupload.PartyBattleRecord.AddLootedItem (ItemObject item, int count)
Definition at line 25 of file PartyBattleRecord.cs.
{ AddItemToDictionary(LootedItems, item, count); }
References AddItemToDictionary(), and LootedItems.
Member Data Documentation
ItemsToRecover
readonly ConcurrentDictionary<ItemObject, int> DynamicTroopEquipmentReupload.PartyBattleRecord.ItemsToRecover = new()
Definition at line 9 of file PartyBattleRecord.cs.
Referenced by AddItemToRecover(), and AddItemToRecover().
LootedItems
readonly ConcurrentDictionary<ItemObject, int> DynamicTroopEquipmentReupload.PartyBattleRecord.LootedItems = new()
Definition at line 11 of file PartyBattleRecord.cs.
Referenced by AddLootedItem(), and AddLootedItem().
Property Documentation
ItemsToRecoverCount
int DynamicTroopEquipmentReupload.PartyBattleRecord.ItemsToRecoverCount get
Definition at line 13 of file PartyBattleRecord.cs.
LootedItemsCount
int DynamicTroopEquipmentReupload.PartyBattleRecord.LootedItemsCount get
Definition at line 15 of file PartyBattleRecord.cs.
The documentation for this class was generated from the following file:
PartyBattleRecord.cs