动态装备系统: ItemBlackListTest Class Reference
ItemBlackListTest Class Reference
Classes
class BlackList
Utility class for managing item blacklist for dynamic troops.
Public Member Functions
void Test1 ()
Static Public Member Functions
static bool TestName (string name)
static bool TestStringId (string stringId)
Static Private Member Functions
static void LoadBlackList (string filePath)
Loads the blacklist from a JSON file and populates the internal blacklists.
Static Private Attributes
static readonly HashSet< string > NamePatterns = new()
Contains the patterns used for filtering item names.
static readonly HashSet< string > Names = new()
Represents a collection of string names used for blacklisting items.
static readonly HashSet< string > StringIdPatterns = new()
The set of string ID patterns used for blacklisting items.
static readonly HashSet< string > StringIds = new()
Represents a collection of string IDs used for blacklisting items.
Detailed Description
Definition at line 10 of file ItemBlackListTest.cs.
Member Function Documentation
LoadBlackList()
static void ItemBlackListTest.LoadBlackList (string filePath) static private
Loads the blacklist from a JSON file and populates the internal blacklists.
Parameters
filePath The path to the JSON file containing the blacklist.
Definition at line 67 of file ItemBlackListTest.cs.
{
        var content = File.ReadAllText(filePath);
        //Global.Debug($"read black list file: {content}");
        var blackList = JsonConvert.DeserializeObject<BlackList>(content);
        if (blackList != null) {
            StringIds.UnionWith(blackList.string_id              ?? Enumerable.Empty<string>());
            Names.UnionWith(blackList.name                       ?? Enumerable.Empty<string>());
            StringIdPatterns.UnionWith(blackList.string_id_regex ?? Enumerable.Empty<string>());
            NamePatterns.UnionWith(blackList.name_regex          ?? Enumerable.Empty<string>());
            //foreach (var id in StringIds) { Global.Debug($"string id {id} added to blacklist"); }
            //foreach (var name in Names) { Global.Debug($"name {name} added to blacklist"); }
            //foreach (var pattern in StringIdPatterns) { Global.Debug($"string id regex pattern {pattern} added to blacklist"); }
            //foreach (var pattern in NamePatterns) { Global.Debug($"name regex pattern {pattern} added to blacklist"); }
        }
    }
References NamePatterns, Names, StringIdPatterns, and StringIds.
Referenced by Test1().
Test1()
void ItemBlackListTest.Test1 ()
Definition at line 44 of file ItemBlackListTest.cs.
{
        LoadBlackList(AppDomain.CurrentDomain.BaseDirectory + "../../../../_Module/blacklist-example.json");
        Assert.False(TestStringId("crown"));
        Assert.False(TestStringId("dp_anything"));
        Assert.False(TestName("女士裙"));
        Assert.True(TestStringId("女士裙"));
        Assert.False(TestName("Golden Crown"));
    }
References LoadBlackList(), TestName(), and TestStringId().
TestName()
static bool ItemBlackListTest.TestName (string name) static
Definition at line 58 of file ItemBlackListTest.cs.
{
        return !Names.Contains(name) &&
               !NamePatterns.Any(pattern => Regex.IsMatch(name, pattern));
    }
References NamePatterns, and Names.
Referenced by Test1().
TestStringId()
static bool ItemBlackListTest.TestStringId (string stringId) static
Definition at line 53 of file ItemBlackListTest.cs.
{
        return !StringIds.Contains(stringId) &&
               !StringIdPatterns.Any(pattern => Regex.IsMatch(stringId, pattern));
    }
References StringIdPatterns, and StringIds.
Referenced by Test1().
Member Data Documentation
NamePatterns
readonly HashSet<string> ItemBlackListTest.NamePatterns = new() static private
Contains the patterns used for filtering item names.
This set is populated by reading and parsing a blacklist file.
Definition at line 41 of file ItemBlackListTest.cs.
Referenced by LoadBlackList(), and TestName().
Names
readonly HashSet<string> ItemBlackListTest.Names = new() static private
Represents a collection of string names used for blacklisting items.
This set is populated by reading and parsing a blacklist file.
Definition at line 25 of file ItemBlackListTest.cs.
Referenced by LoadBlackList(), and TestName().
StringIdPatterns
readonly HashSet<string> ItemBlackListTest.StringIdPatterns = new() static private
The set of string ID patterns used for blacklisting items.
This set is populated by reading and parsing a blacklist file.
Definition at line 33 of file ItemBlackListTest.cs.
Referenced by LoadBlackList(), and TestStringId().
StringIds
readonly HashSet<string> ItemBlackListTest.StringIds = new() static private
Represents a collection of string IDs used for blacklisting items.
This set is populated by reading and parsing a blacklist file.
Definition at line 17 of file ItemBlackListTest.cs.
Referenced by LoadBlackList(), and TestStringId().
The documentation for this class was generated from the following file:
Bannerlord.DynamicTroop.Test/ItemBlackListTest.cs