动态装备系统: DynamicTroopEquipmentReupload.Global Class Reference
DynamicTroopEquipmentReupload.Global Class Reference
Static Public Member Functions
static void BeginTroopPoolStashSession ()
static int CountCharacterEquipmentItemTypes (CharacterObject? character, ItemObject.ItemTypeEnum? itemType)
static List< ItemObject > CreateRandomCraftedItemsByItemType (ItemObject.ItemTypeEnum? type, BasicCultureObject? culture, int num=0)
static void Debug (string message)
static void EndTroopPoolStashSession ()
static void Error (string message)
static void Fatal (string message)
static bool FullySameWeaponClass (ItemObject weapon1, ItemObject weapon2)
static ? MobileParty GetAgentParty (IAgentOriginBase? origin)
static ? EquipmentIndex GetEquipmentIndexByItemType (ItemObject.ItemTypeEnum type)
static List< WeaponClass > GetWeaponClass (ItemObject item)
static bool HaveSameWeaponClass (List< WeaponClass > list1, List< WeaponClass > list2)
static void Info (string message)
static void InitializeCraftingTemplatesByItemType ()
static bool IsInPlayerParty (IAgentOriginBase agentOrigin)
static void Log (string message, Color color, Level level, int skipFrames=1)
static void ProcessAgentEquipment (Agent agent, Action< ItemObject > processEquipmentItem)
static void ProcessAgentEquipment (Agent agent, Action< ItemObject > processEquipmentItem, Func< EquipmentIndex, MissionWeapon, EquipmentElement, bool >? shouldProcessSlot)
static void Warn (string message)
Static Public Attributes
static readonly EquipmentIndex[] ArmourAndHorsesSlots
static EquipmentIndex[] ArmourSlots
static readonly EquipmentIndex[] EquipmentSlots
static WeaponClass[] InvalidWeaponClasses
static ItemObject.ItemTypeEnum[] ItemTypes
Properties
static bool IsTroopPoolStashSessionActive [get, private set]
Static Private Member Functions
static bool IsAmmoAndEmpty (MissionWeapon? mw)
static bool IsPartyInPlayerCommand (PartyBase? party)
Static Private Attributes
static readonly Dictionary< ItemObject.ItemTypeEnum, CraftingTemplate[]> CraftingTemplatesByItemType = new()
Detailed Description
Definition at line 21 of file Global.cs.
Member Function Documentation
BeginTroopPoolStashSession()
static void DynamicTroopEquipmentReupload.Global.BeginTroopPoolStashSession () static
Definition at line 84 of file Global.cs.
{
        IsTroopPoolStashSessionActive = true;
    }
References IsTroopPoolStashSessionActive.
CountCharacterEquipmentItemTypes()
static int DynamicTroopEquipmentReupload.Global.CountCharacterEquipmentItemTypes (CharacterObject? character, ItemObject.ItemTypeEnum? itemType) static
Definition at line 280 of file Global.cs.
{
        return character == null || itemType == null || character.BattleEquipments == null ? 0 : character.BattleEquipments.MaxQ(equipment => Assignment.WeaponSlots.CountQ(slot => equipment.GetEquipmentFromSlot(slot).Item?.ItemType == itemType));
    }
References DynamicTroopEquipmentReupload.Assignment.WeaponSlots.
CreateRandomCraftedItemsByItemType()
static List< ItemObject > DynamicTroopEquipmentReupload.Global.CreateRandomCraftedItemsByItemType (ItemObject.ItemTypeEnum? type, BasicCultureObject? culture, int num = 0) static
Definition at line 284 of file Global.cs.
{
        List<ItemObject> items  = new();
        Random           random = new();
        if (type == null || culture == null) return items;
        var templates = CraftingTemplatesByItemType[type.Value];
        for (var i = 0; i < num; i++) {
            var        randomElement = templates[random.Next() % templates.Length];
            TextObject textObject    = new("{=uZhHh7pm}Crafted {CURR_TEMPLATE_NAME}");
            _ = textObject.SetTextVariable("CURR_TEMPLATE_NAME", randomElement.TemplateName);
            Crafting crafting = new(randomElement, culture, textObject);
            crafting.Init();
            crafting.Randomize();
            var hashedCode = crafting.CurrentWeaponDesign.HashedCode;
            crafting.GetCurrentCraftedItemObject().StringId = hashedCode;
            var itemObject = MBObjectManager.Instance.GetObject<ItemObject>(hashedCode);
            if (itemObject == null) {
                itemObject = MBObjectManager.Instance.RegisterObject(crafting.GetCurrentCraftedItemObject());
                items.Add(itemObject);
            }
        }
        return items;
    }
References CraftingTemplatesByItemType.
Debug()
static void DynamicTroopEquipmentReupload.Global.Debug (string message) static
Definition at line 155 of file Global.cs.
{ Log(message, Colors.Green, Level.Debug, 2); }
References Log().
Referenced by DynamicTroopEquipmentReupload.ItemBlackList.ItemBlackList(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.AllocateRandomEquipmentToPartyArmory(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraEquipment(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignHorseAndHarness(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.DailyTickParty(), DynamicTroopEquipmentReupload.ArmyArmory.DebugClearEmptyItem(), DynamicTroopEquipmentReupload.ArmyArmory.DebugRemovePlayerCraftedItems(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.DistributeLootRandomly(), DynamicTroopEquipmentReupload.ArmyArmory.Export(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.GarbageCollectEquipments(), DynamicTroopEquipmentReupload.ArmyArmory.Import(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.Load(), DynamicTroopEquipmentReupload.ItemBlackList.LoadBlackList(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.MoveRosterToArmory(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnGameLoaded(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.OnNewGameCreated(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnNewGameCreated(), DynamicTroopEquipmentReupload.Patches.ItemRosterForPlayerLootSharePatch.Postfix(), DynamicTroopEquipmentReupload.Patches.BuyMercenariesPatch.Prefix(), DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.Prefix(), DynamicTroopEquipmentReupload.ArmyArmory.RebuildArmory(), DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipment(), and DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.SyncData().
EndTroopPoolStashSession()
static void DynamicTroopEquipmentReupload.Global.EndTroopPoolStashSession () static
Definition at line 88 of file Global.cs.
{
        IsTroopPoolStashSessionActive = false;
    }
References IsTroopPoolStashSessionActive.
Error()
static void DynamicTroopEquipmentReupload.Global.Error (string message) static
Definition at line 161 of file Global.cs.
{ Log(message, Colors.Red, Level.Error, 2); }
References Log().
Referenced by DynamicTroopEquipmentReupload.ItemBlackList.ItemBlackList(), DynamicTroopEquipmentReupload.ItemBlackList.EnsureBlackListExists(), DynamicTroopEquipmentReupload.ArmyArmory.Export(), DynamicTroopEquipmentReupload.ArmyArmory.Import(), DynamicTroopEquipmentReupload.ItemBlackList.LoadBlackList(), DynamicTroopEquipmentReupload.ArmyArmoryBehavior.SyncData(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.SyncData(), and DynamicTroopEquipmentReupload.ItemBlackList.Test().
Fatal()
static void DynamicTroopEquipmentReupload.Global.Fatal (string message) static
Definition at line 163 of file Global.cs.
{ Log(message, Colors.Magenta, Level.Fatal, 2); }
References Log().
FullySameWeaponClass()
static bool DynamicTroopEquipmentReupload.Global.FullySameWeaponClass (ItemObject weapon1, ItemObject weapon2) static
Definition at line 185 of file Global.cs.
{
        //var list1 = GetWeaponClass(weapon1);
        //var list2 = GetWeaponClass(weapon2);
        //if (list1.Count != list2.Count) return false;
        if (weapon1.Weapons == null || weapon2.Weapons == null || weapon1.Weapons.IsEmpty() || weapon2.Weapons.IsEmpty() || weapon1.Weapons.Count != weapon2.Weapons.Count)
            return false;
        weapon1.Weapons.Sort((x, y) => x.WeaponClass - y.WeaponClass);
        weapon2.Weapons.Sort((x, y) => x.WeaponClass - y.WeaponClass);
        return !Enumerable
                .Range(0, weapon1.Weapons.Count)
                .AnyQ(i => weapon1.Weapons[i].WeaponClass != weapon2.Weapons[i].WeaponClass || weapon1.Weapons[i].SwingDamageType != weapon2.Weapons[i].SwingDamageType || weapon1.Weapons[i].ThrustDamageType != weapon2.Weapons[i].ThrustDamageType);
    }
Referenced by DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.EquipmentElementComparer.Equals(), and DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsWeaponSuitable().
GetAgentParty()
static ? MobileParty DynamicTroopEquipmentReupload.Global.GetAgentParty (IAgentOriginBase? origin) static
Definition at line 265 of file Global.cs.
{
        return origin switch {
                   null                                        => null,
                   PartyAgentOrigin partyAgentOrigin           => partyAgentOrigin.Party?.MobileParty,
                   PartyGroupAgentOrigin partyGroupAgentOrigin => partyGroupAgentOrigin.Party?.MobileParty,
                   SimpleAgentOrigin simpleAgentOrigin         => simpleAgentOrigin.Party?.MobileParty,
                   _                                           => null
               };
    }
Referenced by DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnAgentRemoved(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnMissionEnded(), and DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Prefix().
GetEquipmentIndexByItemType()
static ? EquipmentIndex DynamicTroopEquipmentReupload.Global.GetEquipmentIndexByItemType (ItemObject.ItemTypeEnum type) static
Definition at line 105 of file Global.cs.
{
        return type switch {
                   ItemObject.ItemTypeEnum.HeadArmor => EquipmentIndex.Head,
                   ItemObject.ItemTypeEnum.BodyArmor => EquipmentIndex.Body,
                   ItemObject.ItemTypeEnum.LegArmor  => EquipmentIndex.Leg,
                   ItemObject.ItemTypeEnum.HandArmor => EquipmentIndex.Gloves,
                   ItemObject.ItemTypeEnum.Cape      => EquipmentIndex.Cape,
                   _                                 => null
               };
    }
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignEquipmentType().
GetWeaponClass()
static List< WeaponClass > DynamicTroopEquipmentReupload.Global.GetWeaponClass (ItemObject item) static
Definition at line 117 of file Global.cs.
{
        return item is { HasWeaponComponent: true } ? item.WeaponComponent.Weapons.SelectQ(weapon => weapon.WeaponClass).Distinct().OrderByQ(weaponClass => weaponClass).ToListQ() : new List<WeaponClass>();
    }
Referenced by DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.EquipmentElementComparer.GetHashCode(), and DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsWeaponSuitable().
HaveSameWeaponClass()
static bool DynamicTroopEquipmentReupload.Global.HaveSameWeaponClass (List< WeaponClass > list1, List< WeaponClass > list2) static
Definition at line 165 of file Global.cs.
{
        if (list1.IsEmpty() || list2.IsEmpty()) { return false; }
        static bool IsThrown(WeaponClass wc) {
            return wc is WeaponClass.ThrowingKnife or WeaponClass.ThrowingAxe or WeaponClass.Stone or WeaponClass.Javelin;
        }
        var thrown1 = list1.WhereQ(IsThrown).ToArrayQ();
        var thrown2 = list2.WhereQ(IsThrown).ToArrayQ();
        if (!thrown1.IsEmpty() || !thrown2.IsEmpty()) {
            var lhs = !thrown1.IsEmpty() ? thrown1 : list1.ToArrayQ();
            var rhs = !thrown2.IsEmpty() ? thrown2 : list2.ToArrayQ();
            return lhs.AnyQ(wc => rhs.Contains(wc));
        }
        return list1.AnyQ(wc => list2.Contains(wc));
    }
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsWeaponSuitable().
Info()
static void DynamicTroopEquipmentReupload.Global.Info (string message) static
Definition at line 157 of file Global.cs.
{ Log(message, Colors.Blue, Level.Info, 2); }
References Log().
InitializeCraftingTemplatesByItemType()
static void DynamicTroopEquipmentReupload.Global.InitializeCraftingTemplatesByItemType () static
Definition at line 92 of file Global.cs.
{
        ItemObject.ItemTypeEnum[] itemTypes = {
                                                  ItemObject.ItemTypeEnum.OneHandedWeapon,
                                                  ItemObject.ItemTypeEnum.TwoHandedWeapon,
                                                  ItemObject.ItemTypeEnum.Polearm
                                              };
        foreach (var itemType in itemTypes) {
            CraftingTemplate[] templates = CraftingTemplate.All.WhereQ(template => template.ItemType == itemType).ToArrayQ();
            CraftingTemplatesByItemType[itemType] = templates;
        }
    }
References CraftingTemplatesByItemType.
IsAmmoAndEmpty()
static bool DynamicTroopEquipmentReupload.Global.IsAmmoAndEmpty (MissionWeapon? mw) static private
Definition at line 248 of file Global.cs.
{
        return mw is { IsEmpty: false, Item.HasWeaponComponent: true, Amount: 0 } && (mw.Value.IsAnyAmmo() || mw.Value.Item.IsThrowing());
    }
Referenced by ProcessAgentEquipment().
IsInPlayerParty()
static bool DynamicTroopEquipmentReupload.Global.IsInPlayerParty (IAgentOriginBase agentOrigin) static
Definition at line 252 of file Global.cs.
{
        var party = agentOrigin switch {
                        PartyAgentOrigin partyAgentOrigin           => partyAgentOrigin.Party,
                        PartyGroupAgentOrigin partyGroupAgentOrigin => partyGroupAgentOrigin.Party,
                        SimpleAgentOrigin simpleAgentOrigin         => simpleAgentOrigin.Party,
                        _                                           => null
                    };
        if (agentOrigin.IsUnderPlayersCommand) { return true; }
        return party != null && IsPartyInPlayerCommand(party);
    }
References IsPartyInPlayerCommand().
IsPartyInPlayerCommand()
static bool DynamicTroopEquipmentReupload.Global.IsPartyInPlayerCommand (PartyBase? party) static private
Definition at line 275 of file Global.cs.
{
        var mainParty = Campaign.Current?.MainParty;
        return party?.MobileParty != null && mainParty != null && party.MobileParty == mainParty;
    }
Referenced by IsInPlayerParty().
Log()
static void DynamicTroopEquipmentReupload.Global.Log (string message, Color color, Level level, int skipFrames = 1) static
Definition at line 121 of file Global.cs.
{
        if (SubModule.Settings is { DebugMode: true } &&
            (SubModule.Settings.MinimumLogLevel == Level.All || level >= SubModule.Settings.MinimumLogLevel)) {
            MessageDisplayService.EnqueueMessage(new InformationMessage(message, color));
            // 使用 log4net 记录日志
            StackFrame frame  = new(skipFrames, true); // 创建 StackFrame 对象，参数 1 表示上一个栈帧
            var        method = frame.GetMethod();     // 获取方法信息
            // 获取文件名而不是完整路径
            var fileName = Path.GetFileName(frame.GetFileName());
            var lineNumber = frame.GetFileLineNumber(); // 获取行号
            // 构造日志消息
            var logMessage = $"[{method.DeclaringType?.FullName}.{method.Name}] [{fileName}:{lineNumber}] {message}";
            // 获取 log4net 日志实例
            //LogManager.GetLogger(method.DeclaringType);
            var log = LogManager.GetLogger("dtes");
            // 根据指定的日志级别记录日志
            if (level == Level.Debug)
                log.Debug(logMessage);
            else if (level == Level.Info)
                log.Info(logMessage);
            else if (level == Level.Warn)
                log.Warn(logMessage);
            else if (level == Level.Error)
                log.Error(logMessage);
            else if (level == Level.Fatal) log.Fatal(logMessage);
        }
    }
References MessageDisplayService.EnqueueMessage(), DynamicTroopEquipmentReupload.ModSettings.MinimumLogLevel, and DynamicTroopEquipmentReupload.SubModule.Settings.
Referenced by DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.AfterStart(), DynamicTroopEquipmentReupload.ArmyArmory.AssignEquipment(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraArrows(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraBolts(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraShield(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraThrownWeapon(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraTwoHandedWeaponOrPolearms(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumType(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumTypeBySlot(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClass(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClassBySlot(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponIfAvailable(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponToUnarmed(), Debug(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.EarlyStart(), Error(), Fatal(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GetOneRandomMeleeWeapon(), Info(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.LogParties(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnAgentRemoved(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnBattleEnded(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnBehaviorInitialize(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnEndMission(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnEndMissionRequest(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMapEventEnded(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnMissionEnded(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnMissionResultReady(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMobilePartyCreated(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnMobilePartyDestroyed(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnRetreatMission(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnSurrenderMission(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnTroopRecruited(), DynamicTroopEquipmentReupload.Patches.BuyMercenariesPatch.Prefix(), DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.Prefix(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ProcessAgentEquipmentRespectingTemporarySlots(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnEquipmentFromAgents(), DynamicTroopEquipmentReupload.ArmyArmory.ReturnEquipmentToArmoryFromAgents(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ReturnItem(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ReturnItemsToDestination(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ShowBattleResults(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Spawn(), and Warn().
ProcessAgentEquipment() [1/2]
static void DynamicTroopEquipmentReupload.Global.ProcessAgentEquipment (Agent agent, Action< ItemObject > processEquipmentItem) static
Definition at line 199 of file Global.cs.
{
        ProcessAgentEquipment(agent, processEquipmentItem, null);
    }
References ProcessAgentEquipment().
Referenced by ProcessAgentEquipment(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ProcessAgentEquipmentRespectingTemporarySlots(), and DynamicTroopEquipmentReupload.ArmyArmory.ReturnEquipmentToArmoryFromAgents().
ProcessAgentEquipment() [2/2]
static void DynamicTroopEquipmentReupload.Global.ProcessAgentEquipment (Agent agent, Action< ItemObject > processEquipmentItem, Func< EquipmentIndex, MissionWeapon, EquipmentElement, bool >? shouldProcessSlot) static
Definition at line 203 of file Global.cs.
{
        var missionEquipment = agent.Equipment;
        var spawnEquipment   = agent.SpawnEquipment;
        foreach (var slot in EquipmentSlots) {
            var spawnElement = spawnEquipment[slot];
            if (spawnElement.IsEmpty || spawnElement.Item is null)
                continue;
            var isWeaponSlot =
                slot == EquipmentIndex.Weapon0 ||
                slot == EquipmentIndex.Weapon1 ||
                slot == EquipmentIndex.Weapon2 ||
                slot == EquipmentIndex.Weapon3;
            var missionWeapon = default(MissionWeapon);
            if (isWeaponSlot) { missionWeapon = missionEquipment[slot]; }
            if (spawnElement.Item.ItemType == ItemObject.ItemTypeEnum.Banner || spawnElement.Item.IsBannerItem)
                continue;
            if (isWeaponSlot) {
                var isAmmoOrThrown =
                    spawnElement.Item.ItemType == ItemObject.ItemTypeEnum.Arrows ||
                    spawnElement.Item.ItemType == ItemObject.ItemTypeEnum.Bolts  ||
                    spawnElement.Item.ItemType == ItemObject.ItemTypeEnum.Thrown;
                if (isAmmoOrThrown && (missionWeapon.IsEmpty || IsAmmoAndEmpty(missionWeapon)))
                    continue;
                if (spawnElement.Item.ItemType == ItemObject.ItemTypeEnum.Shield && !missionWeapon.IsEmpty && missionWeapon.HitPoints <= 0)
                    continue;
            }
            if (shouldProcessSlot != null && !shouldProcessSlot(slot, missionWeapon, spawnElement))
                continue;
            processEquipmentItem(spawnElement.Item);
        }
    }
References EquipmentSlots, and IsAmmoAndEmpty().
Warn()
static void DynamicTroopEquipmentReupload.Global.Warn (string message) static
Definition at line 159 of file Global.cs.
{ Log(message, Colors.Yellow, Level.Warn, 2); }
References Log().
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponToUnarmed(), DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.ConvertToGuidDict(), DynamicTroopEquipmentReupload.ItemBlackList.EnsureBlackListExists(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.HandlePartyItems(), DynamicTroopEquipmentReupload.ArmyArmory.Import(), and DynamicTroopEquipmentReupload.ArmyArmoryBehavior.Load().
Member Data Documentation
ArmourAndHorsesSlots
readonly EquipmentIndex [] DynamicTroopEquipmentReupload.Global.ArmourAndHorsesSlots static
Initial value:
= {
                                                                       EquipmentIndex.Head,
                                                                       EquipmentIndex.Body,
                                                                       EquipmentIndex.Leg,
                                                                       EquipmentIndex.Gloves,
                                                                       EquipmentIndex.Cape,
                                                                       EquipmentIndex.Horse,
                                                                       EquipmentIndex.HorseHarness
                                                                   }
Definition at line 36 of file Global.cs.
{
                                                                       EquipmentIndex.Head,
                                                                       EquipmentIndex.Body,
                                                                       EquipmentIndex.Leg,
                                                                       EquipmentIndex.Gloves,
                                                                       EquipmentIndex.Cape,
                                                                       EquipmentIndex.Horse,
                                                                       EquipmentIndex.HorseHarness
                                                                   };
Referenced by DynamicTroopEquipmentReupload.Extensions.AgentExtension.GetAgentArmors().
ArmourSlots
EquipmentIndex [] DynamicTroopEquipmentReupload.Global.ArmourSlots static
Initial value:
= {
                                                     EquipmentIndex.Head,
                                                     EquipmentIndex.Body,
                                                     EquipmentIndex.Leg,
                                                     EquipmentIndex.Gloves,
                                                     EquipmentIndex.Cape
                                                 }
Definition at line 46 of file Global.cs.
{
                                                     EquipmentIndex.Head,
                                                     EquipmentIndex.Body,
                                                     EquipmentIndex.Leg,
                                                     EquipmentIndex.Gloves,
                                                     EquipmentIndex.Cape
                                                 };
Referenced by DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ApplyEmergencyLoadout(), DynamicTroopEquipmentReupload.Assignment.FillEmptySlots(), and DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRecruitEquipments().
CraftingTemplatesByItemType
readonly Dictionary<ItemObject.ItemTypeEnum, CraftingTemplate[]> DynamicTroopEquipmentReupload.Global.CraftingTemplatesByItemType = new() static private
Definition at line 80 of file Global.cs.
Referenced by CreateRandomCraftedItemsByItemType(), and InitializeCraftingTemplatesByItemType().
EquipmentSlots
readonly EquipmentIndex [] DynamicTroopEquipmentReupload.Global.EquipmentSlots static
Initial value:
= {
                                                                 EquipmentIndex.Weapon0,
                                                                 EquipmentIndex.Weapon1,
                                                                 EquipmentIndex.Weapon2,
                                                                 EquipmentIndex.Weapon3,
                                                                 EquipmentIndex.Head,
                                                                 EquipmentIndex.Body,
                                                                 EquipmentIndex.Leg,
                                                                 EquipmentIndex.Gloves,
                                                                 EquipmentIndex.Cape,
                                                                 EquipmentIndex.Horse,
                                                                 EquipmentIndex.HorseHarness
                                                             }
Definition at line 22 of file Global.cs.
{
                                                                 EquipmentIndex.Weapon0,
                                                                 EquipmentIndex.Weapon1,
                                                                 EquipmentIndex.Weapon2,
                                                                 EquipmentIndex.Weapon3,
                                                                 EquipmentIndex.Head,
                                                                 EquipmentIndex.Body,
                                                                 EquipmentIndex.Leg,
                                                                 EquipmentIndex.Gloves,
                                                                 EquipmentIndex.Cape,
                                                                 EquipmentIndex.Horse,
                                                                 EquipmentIndex.HorseHarness
                                                             };
Referenced by DynamicTroopEquipmentReupload.ArmyArmory.AssignEquipment(), DynamicTroopEquipmentReupload.PartyEquipmentDistributor.CalculateEquipmentTierScoreWithoutMountEquipment(), DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.CalculateEquipmentValue(), DynamicTroopEquipmentReupload.Assignment.CreateEmptyEquipment(), DynamicTroopEquipmentReupload.Assignment.FillEmptySlots(), DynamicTroopEquipmentReupload.Extensions.MobilePartyExtension.GetRandomEquipmentsFromTroop(), DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRandomizedRecruitEquipments(), ProcessAgentEquipment(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.ProcessAssignmentEquipmentFallback(), and DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Spawn().
InvalidWeaponClasses
WeaponClass [] DynamicTroopEquipmentReupload.Global.InvalidWeaponClasses static
Initial value:
= {
                                                           WeaponClass.Undefined,
                                                           WeaponClass.Boulder,
                                                           WeaponClass.Banner,
                                                           WeaponClass.Stone
                                                       }
Definition at line 73 of file Global.cs.
{
                                                           WeaponClass.Undefined,
                                                           WeaponClass.Boulder,
                                                           WeaponClass.Banner,
                                                           WeaponClass.Stone
                                                       };
Referenced by DynamicTroopEquipmentReupload.Cache.GetItemsByTierAndCulture(), and DynamicTroopEquipmentReupload.Cache.GetItemsByTypeTierAndCulture().
ItemTypes
ItemObject.ItemTypeEnum [] DynamicTroopEquipmentReupload.Global.ItemTypes static
Initial value:
= {
                                                            ItemObject.ItemTypeEnum.BodyArmor,
                                                            ItemObject.ItemTypeEnum.LegArmor,
                                                            ItemObject.ItemTypeEnum.HeadArmor,
                                                            ItemObject.ItemTypeEnum.HandArmor,
                                                            ItemObject.ItemTypeEnum.Cape,
                                                            ItemObject.ItemTypeEnum.Horse,
                                                            ItemObject.ItemTypeEnum.HorseHarness,
                                                            ItemObject.ItemTypeEnum.Bow,
                                                            ItemObject.ItemTypeEnum.Crossbow,
                                                            ItemObject.ItemTypeEnum.Shield,
                                                            ItemObject.ItemTypeEnum.OneHandedWeapon,
                                                            ItemObject.ItemTypeEnum.TwoHandedWeapon,
                                                            ItemObject.ItemTypeEnum.Polearm,
                                                            ItemObject.ItemTypeEnum.Arrows,
                                                            ItemObject.ItemTypeEnum.Bolts,
                                                            ItemObject.ItemTypeEnum.Thrown
                                                        }
Definition at line 54 of file Global.cs.
{
                                                            ItemObject.ItemTypeEnum.BodyArmor,
                                                            ItemObject.ItemTypeEnum.LegArmor,
                                                            ItemObject.ItemTypeEnum.HeadArmor,
                                                            ItemObject.ItemTypeEnum.HandArmor,
                                                            ItemObject.ItemTypeEnum.Cape,
                                                            ItemObject.ItemTypeEnum.Horse,
                                                            ItemObject.ItemTypeEnum.HorseHarness,
                                                            ItemObject.ItemTypeEnum.Bow,
                                                            ItemObject.ItemTypeEnum.Crossbow,
                                                            ItemObject.ItemTypeEnum.Shield,
                                                            ItemObject.ItemTypeEnum.OneHandedWeapon,
                                                            ItemObject.ItemTypeEnum.TwoHandedWeapon,
                                                            ItemObject.ItemTypeEnum.Polearm,
                                                            ItemObject.ItemTypeEnum.Arrows,
                                                            ItemObject.ItemTypeEnum.Bolts,
                                                            ItemObject.ItemTypeEnum.Thrown
                                                        };
Referenced by DynamicTroopEquipmentReupload.Cache.GetItemsByTierAndCulture(), and DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.InitializeItemListByType().
Property Documentation
IsTroopPoolStashSessionActive
bool DynamicTroopEquipmentReupload.Global.IsTroopPoolStashSessionActive static get private set
Definition at line 82 of file Global.cs.
{ get; private set; }
Referenced by BeginTroopPoolStashSession(), and EndTroopPoolStashSession().
The documentation for this class was generated from the following file:
Global.cs