动态装备系统: Cache Class Reference
Cache Class Reference
Static Public Member Functions
static ? ItemObject[] GetItemsByTierAndCulture (int tier, CultureObject? culture)
根据物品类型、层级和文化获取物品数组。
static ? ItemObject[] GetItemsByTypeTierAndCulture (ItemObject.ItemTypeEnum itemType, int tier, CultureObject? culture)
Static Private Attributes
static readonly Dictionary<(int, CultureObject?), ItemObject[]> CachedItems = new()
static readonly Dictionary<(ItemObject.ItemTypeEnum, int, CultureObject?), ItemObject[]> CachedItemsByType
Detailed Description
Definition at line 14 of file Cache.cs.
Member Function Documentation
GetItemsByTierAndCulture()
static ? ItemObject[] Cache.GetItemsByTierAndCulture (int tier, CultureObject? culture) static
根据物品类型、层级和文化获取物品数组。
Parameters
itemType 物品的类型。
tier 物品的层级。
culture 物品的文化属性。如果为null，则不限制文化。
Returns
符合条件的物品数组。如果没有符合条件的物品，返回null。
Definition at line 27 of file Cache.cs.
{
        var key = (tier, culture);
        if (!CachedItems.TryGetValue(key, out var items)) {
            // If not cached, generate and cache the list
            items = MBObjectManager.Instance.GetObjectTypeList<ItemObject>()
                                   .WhereQ(item => item           != null   &&
                                                   (int)item.Tier <= tier   &&
                                                   ItemBlackList.Test(item) &&
                                                   (item.ItemType == ItemObject.ItemTypeEnum.Horse        ||
                                                    item.ItemType == ItemObject.ItemTypeEnum.HorseHarness ||
                                                    (ModSettings.Instance?.RemoveCivilianEquipmentsInRandom ?? false
                                                         ? !item.IsCivilian
                                                         : !item.ItemFlags.HasAnyFlag(ItemFlags.NotUsableByMale))) &&
                                                   Global.ItemTypes.ContainsQ(item.ItemType)                       &&
                                                   !item.IsCraftedByPlayer                                         &&
                                                   (!item.HasWeaponComponent ||
                                                    !Global.InvalidWeaponClasses.ContainsQ(item.PrimaryWeapon
                                                                                               .WeaponClass)) &&
                                                   (item.Culture == null || item.Culture == culture))
                                   .ToArrayQ();
            CachedItems[key] = items;
        }
        return items;
    }
References CachedItems, ModSettings.RemoveCivilianEquipmentsInRandom, and ItemBlackList.Test().
Referenced by TownExtension.GetRandomEquipments(), and MobilePartyExtension.GetRandomEquipmentsFromClan().
GetItemsByTypeTierAndCulture()
static ? ItemObject[] Cache.GetItemsByTypeTierAndCulture (ItemObject.ItemTypeEnum itemType, int tier, CultureObject? culture) static
Definition at line 55 of file Cache.cs.
{
        if (tier < 0) return null;
        var key = (itemType, tier, culture);
        if (!CachedItemsByType.TryGetValue(key, out var items)) {
            // If not cached, generate and cache the list
            items = EveryoneCampaignBehavior.ItemListByType[itemType]
                                            .WhereQ(item => item           != null   &&
                                                            (int)item.Tier == tier   &&
                                                            ItemBlackList.Test(item) &&
                                                            !item.IsCraftedByPlayer  &&
                                                            (item.ItemType == ItemObject.ItemTypeEnum.Horse        ||
                                                             item.ItemType == ItemObject.ItemTypeEnum.HorseHarness ||
                                                             (ModSettings.Instance?.RemoveCivilianEquipmentsInRandom ??
                                                              false
                                                                  ? !item.IsCivilian
                                                                  : !item.ItemFlags
                                                                         .HasAnyFlag(ItemFlags.NotUsableByMale))) &&
                                                            (!item.HasWeaponComponent ||
                                                             !Global.InvalidWeaponClasses.ContainsQ(item.PrimaryWeapon
                                                                                                        .WeaponClass)) &&
                                                            (item.Culture == null || item.Culture == culture))
                                            .ToArrayQ();
            if (items == null || items.Length == 0) items = GetItemsByTypeTierAndCulture(itemType, tier - 1, culture);
            if (items == null) return null;
            CachedItemsByType[key] = items;
        }
        return items;
    }
References CachedItemsByType, GetItemsByTypeTierAndCulture(), EveryoneCampaignBehavior.ItemListByType, ModSettings.RemoveCivilianEquipmentsInRandom, and ItemBlackList.Test().
Referenced by Assignment.FillEmptySlots(), GetItemsByTypeTierAndCulture(), and RecruitmentPatch.GetRecruitEquipments().
Member Data Documentation
CachedItems
readonly Dictionary<(int, CultureObject?), ItemObject[]> Cache.CachedItems = new() static private
Definition at line 18 of file Cache.cs.
Referenced by GetItemsByTierAndCulture().
CachedItemsByType
readonly Dictionary<(ItemObject.ItemTypeEnum, int, CultureObject?), ItemObject[]> Cache.CachedItemsByType static private
Initial value:
=
        new()
Definition at line 15 of file Cache.cs.
Referenced by GetItemsByTypeTierAndCulture().
The documentation for this class was generated from the following file:
Cache.cs