动态装备系统: DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension Class Reference
DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension Class Reference
Public Types
enum TroopType {
Militia , Bandit , None , Basic ,
Mercenary , Elite
}
Static Public Member Functions
static int EquipmentValue (this CharacterObject? character)
static TroopType GetTroopType (this CharacterObject? character)
static void Init ()
static int SkillValue (this CharacterObject? character)
Static Private Member Functions
static int CalculateEquipmentValue (this CharacterObject? character)
static int CalculateSkillValue (this CharacterObject? character)
static void Enqueue (CharacterObject? character, TroopType typ)
Static Private Attributes
static MBReadOnlyList< SkillObject > _cachedSkillValue = new()
static readonly ConcurrentDictionary< CharacterObject, int > CachedCharacterEquipmentValue = new()
static readonly ConcurrentDictionary< CharacterObject, int > CachedCharacterSkillValue = new()
static readonly ConcurrentQueue<(CharacterObject character, TroopType troopType)> TroopQueue = new()
static readonly ConcurrentDictionary< CharacterObject, TroopType > TypeDict = new()
Detailed Description
Definition at line 12 of file CharacterObjectExtension.cs.
Member Enumeration Documentation
TroopType
enum DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.TroopType
Enumerator
Militia
Bandit
None
Basic
Mercenary
Elite
Definition at line 13 of file CharacterObjectExtension.cs.
{
        Militia,
        Bandit,
        None,
        Basic,
        Mercenary,
        Elite
    }
Member Function Documentation
CalculateEquipmentValue()
static int DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.CalculateEquipmentValue (this CharacterObject? character) static private
Definition at line 37 of file CharacterObjectExtension.cs.
{
        if (character == null) return 0;
        var                    totalValue = 0;
        IEnumerable<Equipment> equipments = character.BattleEquipments;
        if (equipments == null) return 0;
        var cnt = character.BattleEquipments.Count();
        foreach (var equipment in equipments) {
            foreach (var slot in Global.EquipmentSlots) {
                var element = equipment.GetEquipmentFromSlot(slot);
                if (element.IsEmpty || element.Item == null) continue;
                totalValue += equipment.GetEquipmentFromSlot(slot).ItemValue;
            }
        }
        return totalValue / cnt;
    }
References DynamicTroopEquipmentReupload.Global.EquipmentSlots.
CalculateSkillValue()
static int DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.CalculateSkillValue (this CharacterObject? character) static private
Definition at line 57 of file CharacterObjectExtension.cs.
{
        return character != null ? _cachedSkillValue.SumQ(character.GetSkillValue) : 0;
    }
References _cachedSkillValue.
Enqueue()
static void DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.Enqueue (CharacterObject? character, TroopType typ) static private
Definition at line 118 of file CharacterObjectExtension.cs.
{
        if (character == null) return;
        TroopQueue.Enqueue((character, typ));
    }
References TroopQueue.
Referenced by Init().
EquipmentValue()
static int DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.EquipmentValue (this CharacterObject? character) static
Definition at line 61 of file CharacterObjectExtension.cs.
{
        if (character == null) return 0;
        if (CachedCharacterEquipmentValue.TryGetValue(character, out var value)) return value;
        value = character.CalculateEquipmentValue();
        CachedCharacterEquipmentValue.TryAdd(character, value);
        return value;
    }
References CachedCharacterEquipmentValue.
GetTroopType()
static TroopType DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.GetTroopType (this CharacterObject? character) static
Definition at line 32 of file CharacterObjectExtension.cs.
{
        return character == null                            ? TroopType.None :
               TypeDict.TryGetValue(character, out var typ) ? typ : TroopType.None;
    }
References None, and TypeDict.
Init()
static void DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.Init () static
Definition at line 81 of file CharacterObjectExtension.cs.
{
        var cultureList = MBObjectManager.Instance.GetObjectTypeList<CultureObject>();
        _cachedSkillValue = MBObjectManager.Instance.GetObjectTypeList<SkillObject>();
        foreach (var culture in cultureList) {
            Enqueue(culture?.EliteBasicTroop, TroopType.Elite);
            MBReadOnlyList<CharacterObject>? basicMercenaryTroops = culture?.BasicMercenaryTroops;
            if (basicMercenaryTroops != null)
                foreach (var troop in basicMercenaryTroops)
                    Enqueue(troop, TroopType.Mercenary);
            Enqueue(culture?.BasicTroop, TroopType.Basic);
            Enqueue(culture?.BanditChief,  TroopType.Bandit);
            Enqueue(culture?.BanditRaider, TroopType.Bandit);
            Enqueue(culture?.BanditBandit, TroopType.Bandit);
            Enqueue(culture?.BanditBoss,   TroopType.Bandit);
            Enqueue(culture?.MeleeMilitiaTroop,       TroopType.Militia);
            Enqueue(culture?.MeleeEliteMilitiaTroop,  TroopType.Militia);
            Enqueue(culture?.RangedEliteMilitiaTroop, TroopType.Militia);
            Enqueue(culture?.RangedMilitiaTroop,      TroopType.Militia);
            Enqueue(culture?.MilitiaVeteranArcher,    TroopType.Militia);
        }
        while (TroopQueue.TryDequeue(out var entry)) {
            var character = entry.character;
            var typ       = entry.troopType;
            if (!TypeDict.TryAdd(character, typ))
                continue;
            foreach (var next in character.UpgradeTargets)
                Enqueue(next, typ);
        }
    }
References _cachedSkillValue, Enqueue(), TroopQueue, and TypeDict.
Referenced by DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnGameLoaded(), and DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnNewGameCreated().
SkillValue()
static int DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.SkillValue (this CharacterObject? character) static
Definition at line 71 of file CharacterObjectExtension.cs.
{
        if (character == null) return 0;
        if (CachedCharacterSkillValue.TryGetValue(character, out var value)) return value;
        value = character.CalculateSkillValue();
        CachedCharacterSkillValue.TryAdd(character, value);
        return value;
    }
References CachedCharacterSkillValue.
Member Data Documentation
_cachedSkillValue
MBReadOnlyList<SkillObject> DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension._cachedSkillValue = new() static private
Definition at line 26 of file CharacterObjectExtension.cs.
Referenced by CalculateSkillValue(), and Init().
CachedCharacterEquipmentValue
readonly ConcurrentDictionary<CharacterObject, int> DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.CachedCharacterEquipmentValue = new() static private
Definition at line 28 of file CharacterObjectExtension.cs.
Referenced by EquipmentValue().
CachedCharacterSkillValue
readonly ConcurrentDictionary<CharacterObject, int> DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.CachedCharacterSkillValue = new() static private
Definition at line 30 of file CharacterObjectExtension.cs.
Referenced by SkillValue().
TroopQueue
readonly ConcurrentQueue<(CharacterObject character, TroopType troopType)> DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.TroopQueue = new() static private
Definition at line 24 of file CharacterObjectExtension.cs.
Referenced by Enqueue(), and Init().
TypeDict
readonly ConcurrentDictionary<CharacterObject, TroopType> DynamicTroopEquipmentReupload.Extensions.CharacterObjectExtension.TypeDict = new() static private
Definition at line 22 of file CharacterObjectExtension.cs.
Referenced by GetTroopType(), and Init().
The documentation for this class was generated from the following file:
Extensions/CharacterObjectExtension.cs