动态装备系统: WeightedRandomSelector Class Reference
WeightedRandomSelector Class Reference
Static Public Member Functions
static ItemObject SelectItem (List< ItemObject > items, float targetValue)
根据目标值和物品效能的正态分布概率，从物品列表中随机选择一个物品。
Static Private Member Functions
static int BinarySearchClosest (List< float > sortedValues, double value)
二分查找最接近给定值的元素索引。
Static Private Attributes
static readonly Random _random = new()
Detailed Description
Definition at line 10 of file WeightedRandomSelector.cs.
Member Function Documentation
BinarySearchClosest()
static int WeightedRandomSelector.BinarySearchClosest (List< float > sortedValues, double value) static private
二分查找最接近给定值的元素索引。
Parameters
sortedValues 已排序的列表。
value 要查找的值。
Returns
最接近给定值的元素索引。
Definition at line 53 of file WeightedRandomSelector.cs.
{
        int left = 0, right = sortedValues.Count - 1;
        while (left < right) {
            var mid      = (left + right) / 2;
            var midValue = sortedValues[mid];
            if (midValue      < value) { left  = mid; }
            else if (midValue > value) { right = mid; }
            else { return mid; }
            if (left == right - 1) { break; }
        }
        return Math.Abs(sortedValues[left] - value) < Math.Abs(sortedValues[right] - value) ? left : right;
    }
Referenced by SelectItem().
SelectItem()
static ItemObject WeightedRandomSelector.SelectItem (List< ItemObject > items, float targetValue) static
根据目标值和物品效能的正态分布概率，从物品列表中随机选择一个物品。
Parameters
items 物品列表，每个物品都有一个效能值。
targetValue 目标效能值，用于确定正态分布的中心。
Returns
根据正态分布随机选中的物品。
Definition at line 19 of file WeightedRandomSelector.cs.
{
        if (items == null || !items.Any()) { throw new ArgumentException("Items list cannot be null or empty."); }
        // 将物品根据Effectiveness分组并排序
        var groupedItems = items.GroupBy(item => item.Effectiveness).ToDictionary(group => group.Key, group => group.ToList());
        var distinctEffectiveness = groupedItems.Keys.OrderBy(eff => eff).ToList();
        // 计算所有物品效能值的标准差
        var standardDeviation = distinctEffectiveness.StandardDeviation();
        if (standardDeviation == 0) {
            // 如果所有物品的效能值相同，则随机返回一个物品
            return items[_random.Next(items.Count)];
        }
        // 生成一个目标效能值附近的正态分布随机值
        var distribution = new Normal(targetValue, standardDeviation);
        var randomValue  = distribution.Sample();
        // 通过二分查找找到最接近随机值的效能值
        var index = BinarySearchClosest(distinctEffectiveness, randomValue);
        // 获取对应的所有物品，并从中随机选择一个返回
        var effectiveItems = groupedItems[distinctEffectiveness[index]];
        return effectiveItems[_random.Next(effectiveItems.Count)];
    }
References _random, and BinarySearchClosest().
Referenced by Assignment.FillEmptySlots(), and RecruitmentPatch.GetRecruitEquipments().
Member Data Documentation
_random
readonly Random WeightedRandomSelector._random = new() static private
Definition at line 11 of file WeightedRandomSelector.cs.
Referenced by SelectItem().
The documentation for this class was generated from the following file:
WeightedRandomSelector.cs