动态装备系统: DynamicTroopEquipmentReupload.SubModule Class Reference
DynamicTroopEquipmentReupload.SubModule Class Reference
Public Member Functions
override void BeginGameStart (Game game)
override void OnCampaignStart (Game game, object starterObject)
override void OnGameInitializationFinished (Game game)
override void OnGameLoaded (Game game, object initializerObject)
override void OnMissionBehaviorInitialize (Mission mission)
override void OnNewGameCreated (Game game, object initializerObject)
Static Public Attributes
static ? ModSettings Settings
Protected Member Functions
override void OnApplicationTick (float dt)
override void OnBeforeInitialModuleScreenSetAsRoot ()
override void OnGameStart (Game game, IGameStarter gameStarterObject)
override void OnSubModuleLoad ()
override void OnSubModuleUnloaded ()
Private Member Functions
void AddBehaviors (CampaignGameStarter? gameStarterObject)
Private Attributes
UIExtender? _uiExtender
Detailed Description
Definition at line 17 of file SubModule.cs.
Member Function Documentation
AddBehaviors()
void DynamicTroopEquipmentReupload.SubModule.AddBehaviors (CampaignGameStarter? gameStarterObject) private
Definition at line 101 of file SubModule.cs.
{
        gameStarterObject?.AddBehavior(new ArmyArmoryBehavior());
        gameStarterObject?.AddBehavior(new EveryoneCampaignBehavior());
        gameStarterObject?.AddBehavior(new CutTheirSupplyBehavior());
    }
Referenced by OnGameStart().
BeginGameStart()
override void DynamicTroopEquipmentReupload.SubModule.BeginGameStart (Game game)
Definition at line 79 of file SubModule.cs.
{
        base.BeginGameStart(game);
        /*if (game.GameType is Campaign)
            CampaignEvents.OnMissionStartedEvent.AddNonSerializedListener(this,
                                                                          m => {
                                                                              if (m is Mission instance)
                                                                                  instance
                                                                                      .AddMissionBehavior(new
                                                                                          MyMissionBehavior());
                                                                          });
        CampaignEvents.OnMissionEndedEvent.AddNonSerializedListener(this,
                                                                m => {
                                                                });*/
    }
OnApplicationTick()
override void DynamicTroopEquipmentReupload.SubModule.OnApplicationTick (float dt) protected
Definition at line 57 of file SubModule.cs.
{
        base.OnApplicationTick(dt);
        MessageDisplayService.Tick(dt);
    }
References MessageDisplayService.Tick().
OnBeforeInitialModuleScreenSetAsRoot()
override void DynamicTroopEquipmentReupload.SubModule.OnBeforeInitialModuleScreenSetAsRoot () protected
Definition at line 62 of file SubModule.cs.
{
        base.OnBeforeInitialModuleScreenSetAsRoot();
        Settings = ModSettings.Instance;
    }
References Settings.
OnCampaignStart()
override void DynamicTroopEquipmentReupload.SubModule.OnCampaignStart (Game game, object starterObject)
Definition at line 77 of file SubModule.cs.
{ base.OnCampaignStart(game, starterObject); }
OnGameInitializationFinished()
override void DynamicTroopEquipmentReupload.SubModule.OnGameInitializationFinished (Game game)
Definition at line 94 of file SubModule.cs.
{ base.OnGameInitializationFinished(game); }
OnGameLoaded()
override void DynamicTroopEquipmentReupload.SubModule.OnGameLoaded (Game game, object initializerObject)
Definition at line 67 of file SubModule.cs.
{
        base.OnGameLoaded(game, initializerObject);
    }
OnGameStart()
override void DynamicTroopEquipmentReupload.SubModule.OnGameStart (Game game, IGameStarter gameStarterObject) protected
Definition at line 96 of file SubModule.cs.
{
        base.OnGameStart(game, gameStarterObject);
        if (game.GameType is Campaign) AddBehaviors(gameStarterObject as CampaignGameStarter);
    }
References AddBehaviors().
OnMissionBehaviorInitialize()
override void DynamicTroopEquipmentReupload.SubModule.OnMissionBehaviorInitialize (Mission mission)
Definition at line 107 of file SubModule.cs.
{
        if (mission.HasMissionBehavior<DynamicTroopMissionLogic>()) {
            base.OnMissionBehaviorInitialize(mission);
            return;
        }
        if (mission.DoesMissionRequireCivilianEquipment) {
            base.OnMissionBehaviorInitialize(mission);
            return;
        }
        if (mission.HasMissionBehavior<TournamentBehavior>() ||
            mission.HasMissionBehavior<TournamentFightMissionController>() ||
            mission.HasMissionBehavior<TournamentArcheryMissionController>() ||
            mission.HasMissionBehavior<TournamentJoustingMissionController>() ||
            mission.HasMissionBehavior<TownHorseRaceMissionController>() ||
            mission.HasMissionBehavior<CustomBattleAgentLogic>())
        {
            base.OnMissionBehaviorInitialize(mission);
            return;
        }
        mission.AddMissionBehavior(new DynamicTroopMissionLogic());
        base.OnMissionBehaviorInitialize(mission);
    }
OnNewGameCreated()
override void DynamicTroopEquipmentReupload.SubModule.OnNewGameCreated (Game game, object initializerObject)
Definition at line 71 of file SubModule.cs.
{
        base.OnNewGameCreated(game, initializerObject);
        //Campaign.Current.CampaignBehaviorManager.AddBehavior(new ArmyArmoryBehavior());
    }
OnSubModuleLoad()
override void DynamicTroopEquipmentReupload.SubModule.OnSubModuleLoad () protected
Definition at line 22 of file SubModule.cs.
{
        base.OnSubModuleLoad();
        var assembly = Assembly.GetExecutingAssembly();
        _uiExtender = UIExtender.Create("DynamicTroopEquipmentReupload");
        _uiExtender.Register(assembly);
        _uiExtender.Enable();
        var harmony = new Harmony("com.bannerlord.mod.dynamic_troop");
        harmony.PatchAll(assembly);
        // 获取 Mod 目录的路径
        var modDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
        // 构建 log4net 配置文件的完整路径
        var logConfigPath = Path.Combine(modDirectory, "log4net.config");
        // 设置日志文件的路径
        GlobalContext.Properties["LogDir"] = modDirectory;
        // 初始化 log4net
        var loggerRepository = LogManager.CreateRepository(Assembly.GetEntryAssembly(), typeof(Hierarchy));
        _ = XmlConfigurator.Configure(loggerRepository, new FileInfo(logConfigPath));
        var fileAppender = loggerRepository.GetAppenders().OfType<FileAppender>().FirstOrDefault();
        if (fileAppender != null) {
            fileAppender.File = Path.Combine(modDirectory, "log.txt");
            fileAppender.ActivateOptions(); // 应用新的配置
        }
    }
References _uiExtender.
OnSubModuleUnloaded()
override void DynamicTroopEquipmentReupload.SubModule.OnSubModuleUnloaded () protected
Definition at line 51 of file SubModule.cs.
{
        _uiExtender?.Deregister();
        _uiExtender = null;
        MessageDisplayService.StopService();
        base.OnSubModuleUnloaded();
    }
References _uiExtender, and MessageDisplayService.StopService().
Member Data Documentation
_uiExtender
UIExtender? DynamicTroopEquipmentReupload.SubModule._uiExtender private
Definition at line 20 of file SubModule.cs.
Referenced by OnSubModuleLoad(), and OnSubModuleUnloaded().
Settings
? ModSettings DynamicTroopEquipmentReupload.SubModule.Settings static
Definition at line 18 of file SubModule.cs.
Referenced by DynamicTroopEquipmentReupload.Global.Log(), DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnAgentRemoved(), and OnBeforeInitialModuleScreenSetAsRoot().
The documentation for this class was generated from the following file:
SubModule.cs