动态装备系统: DynamicTroopEquipmentReupload.WeightedRandomSelector Class Reference
DynamicTroopEquipmentReupload.WeightedRandomSelector Class Reference
提供基于权重的随机选择功能，用于从一组物品中根据特定规则选择单个物品。
Static Public Member Functions
static ItemObject SelectItem (List< ItemObject > items, float targetValue)
根据目标值和物品效能的正态分布概率，从物品列表中随机选择一个物品。
Static Private Member Functions
static ItemObject WeightedRandomChoose (List< ItemObject > items, List< float > weights)
根据给定的权重列表，从物品列表中随机选择一个物品。
Static Private Attributes
static readonly Random _random = new()
Detailed Description
提供基于权重的随机选择功能，用于从一组物品中根据特定规则选择单个物品。
Definition at line 13 of file WeightedRandomSelector.cs.
Member Function Documentation
SelectItem()
static ItemObject DynamicTroopEquipmentReupload.WeightedRandomSelector.SelectItem (List< ItemObject > items, float targetValue) static
根据目标值和物品效能的正态分布概率，从物品列表中随机选择一个物品。
Parameters
items 物品列表，每个物品都有一个效能值。
targetValue 目标效能值，用于确定正态分布的中心。
Returns
根据加权概率选中的物品。
Definition at line 22 of file WeightedRandomSelector.cs.
{
        if (items == null || items.Count == 0)
            throw new ArgumentException("items cannot be null or empty", nameof(items));
        if (items.Count == 1)
            return items[0];
        var effectiveness     = items.Select(item => (double)item.Effectiveness).ToArray();
        var standardDeviation = effectiveness.StandardDeviation();
        // Uniform fallback
        if (double.IsNaN(standardDeviation) || standardDeviation <= 0.0001)
            return items[_random.Next(items.Count)];
        var mean = (double)targetValue;
        // Normal.PDF(mean, stddev, x)
        var weights = items.Select(item => (float)Normal.PDF(mean, standardDeviation, item.Effectiveness)).ToList();
        var totalWeight = weights.Sum();
        if (totalWeight <= 0 || float.IsNaN(totalWeight) || float.IsInfinity(totalWeight))
            return items[_random.Next(items.Count)];
        var normalizedWeights = weights.Select(weight => weight / totalWeight).ToList();
        return WeightedRandomChoose(items, normalizedWeights);
    }
References _random, and WeightedRandomChoose().
Referenced by DynamicTroopEquipmentReupload.Assignment.FillEmptySlots(), and DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRecruitEquipments().
WeightedRandomChoose()
static ItemObject DynamicTroopEquipmentReupload.WeightedRandomSelector.WeightedRandomChoose (List< ItemObject > items, List< float > weights) static private
根据给定的权重列表，从物品列表中随机选择一个物品。
Parameters
items 物品列表。
weights 与物品列表对应的权重列表，表示每个物品被选中的相对概率。
Returns
根据权重随机选中的物品。
Definition at line 55 of file WeightedRandomSelector.cs.
{
        List<float> cumulativeWeights = new();
        float       total             = 0;
        foreach (var weight in weights) {
            total += weight;
            cumulativeWeights.Add(total);
        }
        var randomNumber = (float)_random.NextDouble() * total;
        for (var i = 0; i < items.Count; i++) {
            if (randomNumber < cumulativeWeights[i]) { return items[i]; }
        }
        return items.Last();
    }
References _random.
Referenced by SelectItem().
Member Data Documentation
_random
readonly Random DynamicTroopEquipmentReupload.WeightedRandomSelector._random = new() static private
Definition at line 14 of file WeightedRandomSelector.cs.
Referenced by SelectItem(), and WeightedRandomChoose().
The documentation for this class was generated from the following file:
WeightedRandomSelector.cs