动态装备系统: DynamicTroopEquipmentReupload.PartyEquipmentDistributor Class Reference
DynamicTroopEquipmentReupload.PartyEquipmentDistributor Class Reference
Classes
struct ArmoryReadiness
Public Member Functions
PartyEquipmentDistributor (Mission mission, MobileParty party, Dictionary< ItemObject, int > objectToAssign)
PartyEquipmentDistributor (Mission mission, MobileParty party, IDictionary< EquipmentElement, int > equipmentToAssign)
PartyEquipmentDistributor (Mission mission, MobileParty party, ItemRoster itemRoster)
void ReturnItem (ItemObject? item, int count)
void RunAsync ()
void Spawn (Equipment equipment)
Public Attributes
readonly List< Assignment > Assignments = new()
Static Package Functions
static ArmoryReadiness MeasureMainPartyArmoryReadiness (bool canUseMountEquipment)
Private Member Functions
PartyEquipmentDistributor (MobileParty party, ItemRoster armorySnapshot, bool canUseMountEquipment)
void AddEquipmentToAssign (EquipmentElement equipmentElement, int count)
void ApplyEmergencyLoadout ()
void AssignEquipmentType (ItemTypeEnum type)
void AssignExtraArrows ()
void AssignExtraBolts ()
void AssignExtraEquipment (EquipmentFilter equipmentFilter, AssignmentFilter assignmentFilter)
根据给定的装备筛选条件和分配筛选条件为角色分配额外装备。
void AssignExtraShield ()
void AssignExtraThrownWeapon ()
void AssignExtraTwoHandedWeaponOrPolearms ()
void AssignHorseAndHarness ()
delegate bool AssignmentFilter (Assignment assignment)
void AssignWeaponByItemEnumType (bool strict)
void AssignWeaponByItemEnumTypeBySlot (EquipmentIndex slot, Assignment assignment, bool mounted, bool strict)
void AssignWeaponByWeaponClass (bool strict)
void AssignWeaponByWeaponClassBySlot (EquipmentIndex slot, Assignment assignment, bool mounted, bool strict)
根据武器大类型和指定的装备槽位为角色分配武器。
void AssignWeaponIfAvailable (EquipmentIndex slot, Assignment assignment, EquipmentElement? availableWeapon)
void AssignWeaponToUnarmed (bool useRandomSelection)
void ConsumeEquipmentToAssign (EquipmentElement equipmentElement)
void DoAssignAsync (bool assignExtraEquipment=true, bool applyEmergencyLoadout=true, bool markUnderEquipped=true, bool useRandomUnarmedFallback=true)
delegate bool EquipmentFilter (KeyValuePair< EquipmentElement, int > equipment)
void GenerateHorseAndHarnessList ()
void GenerateHorseAndHarnessPairs (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, IList<(EquipmentElement Key, int Cnt)> saddles)
int GetMaxAllowedTier (ItemObject? referenceItem)
EquipmentElement? GetMeleeWeaponForUnarmedTroop (Assignment assignment, bool useRandomSelection)
bool IsWeaponSuitable (EquipmentElement equipment, ItemObject referenceWeapon, Assignment assignment, bool strict)
void MarkUnderEquippedAssignmentsIfEnabled ()
bool TryConsumeExactItem (ItemObject item, out EquipmentElement exactElement)
void WriteDistributionLog (string message, Color color, Level level)
Static Private Member Functions
static void AddToDict (IDictionary< int, List<(EquipmentElement Key, int Cnt)> > dict, EquipmentElement element, int cnt)
static void AssignSaddlesToHorseAndHarnesses (IEnumerable< HorseAndHarness > horseAndHarnesses, IList<(EquipmentElement Key, int Cnt)> saddles)
static int CalculateEquipmentTierScoreWithoutMountEquipment (Equipment equipment)
static bool IsCultureCompatible (ItemObject item, BasicCultureObject? culture)
static void PopulateDictionaries (IEnumerable< KeyValuePair< EquipmentElement, int > > equipment, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, ICollection<(EquipmentElement Key, int Cnt)> saddles)
static void SortDict (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > dict, Comparison<(EquipmentElement Key, int Cnt)> comparer)
static void SortEquipmentDictionaries (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, Dictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, List<(EquipmentElement Key, int Cnt)> saddles)
Private Attributes
readonly ConcurrentDictionary< EquipmentElement, int > _equipmentToAssign
readonly List< HorseAndHarness > _horseAndHarnesses = new()
readonly bool _isReadinessPreview
readonly? ItemRoster _itemRoster
readonly? Mission _mission
readonly bool _missionAllowsMountEquipment
readonly MobileParty _party
Static Private Attributes
const float CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER = 2f
const int MAX_TIER_ABOVE_DEFAULT = 2
const float UNDER_EQUIPPED_MORALE_PENALTY_CAP = 20f
const float UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER = 2f
Detailed Description
Definition at line 20 of file PartyEquipmentDistributor.cs.
Constructor & Destructor Documentation
PartyEquipmentDistributor() [1/4]
DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PartyEquipmentDistributor (Mission mission, MobileParty party, ItemRoster itemRoster)
Definition at line 43 of file PartyEquipmentDistributor.cs.
{
        _mission                      = mission;
        _missionAllowsMountEquipment = !mission.IsNavalBattle && !mission.IsNavalRaidBattle;
        _isReadinessPreview           = false;
        _party                        = party;
        _itemRoster                   = itemRoster;
        _equipmentToAssign = new ConcurrentDictionary<EquipmentElement, int>(new EquipmentElementComparer());
    }
References _equipmentToAssign, _isReadinessPreview, _itemRoster, _mission, _missionAllowsMountEquipment, and _party.
Referenced by MeasureMainPartyArmoryReadiness().
PartyEquipmentDistributor() [2/4]
DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PartyEquipmentDistributor (Mission mission, MobileParty party, IDictionary< EquipmentElement, int > equipmentToAssign)
Definition at line 52 of file PartyEquipmentDistributor.cs.
{
        _mission                      = mission;
        _missionAllowsMountEquipment = !mission.IsNavalBattle && !mission.IsNavalRaidBattle;
        _isReadinessPreview           = false;
        _party                        = party;
        _itemRoster                   = null;
        _equipmentToAssign = new ConcurrentDictionary<EquipmentElement, int>(new EquipmentElementComparer());
        foreach (var entry in equipmentToAssign)
            AddEquipmentToAssign(entry.Key, entry.Value);
    }
References _equipmentToAssign, _isReadinessPreview, _itemRoster, _mission, _missionAllowsMountEquipment, _party, and AddEquipmentToAssign().
PartyEquipmentDistributor() [3/4]
DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PartyEquipmentDistributor (Mission mission, MobileParty party, Dictionary< ItemObject, int > objectToAssign)
Definition at line 64 of file PartyEquipmentDistributor.cs.
{
        _mission                      = mission;
        _missionAllowsMountEquipment = !mission.IsNavalBattle && !mission.IsNavalRaidBattle;
        _isReadinessPreview           = false;
        _party                        = party;
        _itemRoster                   = null;
        _equipmentToAssign = new ConcurrentDictionary<EquipmentElement, int>(new EquipmentElementComparer());
        foreach (var entry in objectToAssign) {
            if (ArmyArmory.TryResolveArmoryItem(entry.Key, out var item))
                AddEquipmentToAssign(new EquipmentElement(item), entry.Value);
        }
    }
References _equipmentToAssign, _isReadinessPreview, _itemRoster, _mission, _missionAllowsMountEquipment, _party, AddEquipmentToAssign(), and DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem().
PartyEquipmentDistributor() [4/4]
DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PartyEquipmentDistributor (MobileParty party, ItemRoster armorySnapshot, bool canUseMountEquipment) private
Definition at line 78 of file PartyEquipmentDistributor.cs.
{
        _mission                      = null;
        _missionAllowsMountEquipment = canUseMountEquipment;
        _isReadinessPreview           = true;
        _party                        = party;
        _itemRoster                   = armorySnapshot;
        _equipmentToAssign = new ConcurrentDictionary<EquipmentElement, int>(new EquipmentElementComparer());
    }
References _equipmentToAssign, _isReadinessPreview, _itemRoster, _mission, _missionAllowsMountEquipment, and _party.
Member Function Documentation
AddEquipmentToAssign()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AddEquipmentToAssign (EquipmentElement equipmentElement, int count) private
Definition at line 290 of file PartyEquipmentDistributor.cs.
{
        if (count <= 0 ||
            !ArmyArmory.TryNormalizeArmoryElement(equipmentElement, out var normalizedElement) ||
            !ItemBlackList.Test(normalizedElement.Item))
            return;
        _equipmentToAssign.AddOrUpdate(normalizedElement, count, (_, currentCount) => currentCount + count);
    }
References _equipmentToAssign, DynamicTroopEquipmentReupload.ItemBlackList.Test(), and DynamicTroopEquipmentReupload.ArmyArmory.TryNormalizeArmoryElement().
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), and RunAsync().
AddToDict()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AddToDict (IDictionary< int, List<(EquipmentElement Key, int Cnt)> > dict, EquipmentElement element, int cnt) static private
Definition at line 341 of file PartyEquipmentDistributor.cs.
{
        var familyType = element.Item.HorseComponent?.Monster?.FamilyType ?? element.Item.ArmorComponent?.FamilyType ?? -1;
        if (!dict.TryGetValue(familyType, out var list)) {
            list             = new List<(EquipmentElement Key, int Cnt)>();
            dict[familyType] = list;
        }
        list.Add((element, cnt));
    }
Referenced by PopulateDictionaries().
ApplyEmergencyLoadout()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ApplyEmergencyLoadout () private
Definition at line 1164 of file PartyEquipmentDistributor.cs.
{
        if (_mission?.HasMissionBehavior<HideoutMissionController>() == true)
            return;
        foreach (var assignment in Assignments) {
            // Armour slots
            foreach (var slot in Global.ArmourSlots) {
                if (assignment.GetEquipmentFromSlot(slot) is { IsEmpty: false, Item: not null })
                    continue;
                var reference   = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
                var desiredType = reference.Item?.ItemType ?? Helper.EquipmentIndexToItemEnumType(slot);
                if (!desiredType.HasValue)
                    continue;
                var emergencyCulture = _party.LeaderHero?.Culture ?? assignment.Character.Culture;
                var basicTroop       = emergencyCulture?.BasicTroop;
                if (basicTroop == null)
                    continue;
                var fallbackItem = basicTroop.RandomBattleEquipment.GetEquipmentFromSlot(slot).Item;
                if (fallbackItem == null)
                    continue;
                if (!ItemBlackList.Test(fallbackItem) || fallbackItem.IsCraftedByPlayer || !fallbackItem.IsSuitableForCharacter(assignment.Character))
                    continue;
                assignment.SetEquipment(slot, new EquipmentElement(fallbackItem));
                assignment.MarkSlotAsTemporary(slot, fallbackItem);
            }
            // Weapon slots (only if empty)
            foreach (var slot in Assignment.WeaponSlots) {
                if (assignment.GetEquipmentFromSlot(slot) is { IsEmpty: false, Item: not null })
                    continue;
                var reference   = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
                var desiredType = reference.Item?.ItemType;
                if (desiredType == null)
                    continue;
                var emergencyCulture = _party.LeaderHero?.Culture ?? assignment.Character.Culture;
                var basicTroop       = emergencyCulture?.BasicTroop;
                if (basicTroop == null)
                    continue;
                var fallbackItem = basicTroop.RandomBattleEquipment.GetEquipmentFromSlot(slot).Item;
                if (fallbackItem == null || !fallbackItem.HasWeaponComponent)
                    continue;
                if (!ItemBlackList.Test(fallbackItem) || fallbackItem.IsCraftedByPlayer || !fallbackItem.IsSuitableForCharacter(assignment.Character))
                    continue;
                assignment.SetEquipment(slot, new EquipmentElement(fallbackItem));
                assignment.MarkSlotAsTemporary(slot, fallbackItem);
            }
        }
    }
References _mission, _party, DynamicTroopEquipmentReupload.Global.ArmourSlots, Assignments, DynamicTroopEquipmentReupload.Helper.EquipmentIndexToItemEnumType(), DynamicTroopEquipmentReupload.ItemBlackList.Test(), and DynamicTroopEquipmentReupload.Assignment.WeaponSlots.
Referenced by DoAssignAsync().
AssignEquipmentType()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignEquipmentType (ItemTypeEnum type) private
Definition at line 664 of file PartyEquipmentDistributor.cs.
{
        var armours = _equipmentToAssign
            .Where(kv => kv.Key is { IsEmpty: false, Item: not null } &&
                         kv.Value > 0 &&
                         kv.Key.Item.ItemType == type)
            .Select(kv => new KeyValuePair<EquipmentElement, int>(kv.Key, kv.Value))
            .ToArray();
        var settings = ModSettings.Instance;
        var preferDefaultEquipmentThenClosest = settings?.PreferDefaultEquipmentThenClosest ?? true;
        var slotIndex = Global.GetEquipmentIndexByItemType(type);
        if (slotIndex == null) { return; }
        for (var assignmentIndex = 0; assignmentIndex < Assignments.Count; assignmentIndex++)
        {
            var assignment = Assignments[assignmentIndex];
            var referenceElement = assignment.ReferenceEquipment.GetEquipmentFromSlot(slotIndex.Value);
            var referenceItem = referenceElement.Item;
            // Loyal ON: first try exact vanilla equipment.
            if (preferDefaultEquipmentThenClosest && referenceItem != null)
            {
                for (var i = 0; i < armours.Length; i++)
                {
                    var candidate = armours[i];
                    if (candidate.Value <= 0) { continue; }
                    if (candidate.Key.Item != referenceItem) { continue; }
                    assignment.SetEquipment(slotIndex.Value, candidate.Key);
                    armours[i] = new KeyValuePair<EquipmentElement, int>(candidate.Key, candidate.Value - 1);
                    ConsumeEquipmentToAssign(candidate.Key);
                    break;
                }
            }
            if (!assignment.Equipment.GetEquipmentFromSlot(slotIndex.Value).IsEmpty) { continue; }
            var maxAllowedTier = GetMaxAllowedTier(referenceItem);
            var desiredCulture = assignment.Character.Culture;
            // Most-compatible selection (Effectiveness proximity), still capped by +2 tier.
            if (referenceItem != null)
            {
                var targetEffectiveness = referenceItem.Effectiveness;
                var bestCultureIndex = -1;
                var bestCultureDiff = float.MaxValue;
                var bestCultureEffectiveness = float.MinValue;
                var bestAnyIndex = -1;
                var bestAnyDiff = float.MaxValue;
                var bestAnyEffectiveness = float.MinValue;
                for (var i = 0; i < armours.Length; i++)
                {
                    var candidate = armours[i];
                    if (candidate.Value <= 0) { continue; }
                    var candidateItem = candidate.Key.Item;
                    if (candidateItem == null) { continue; }
                    if ((int)candidateItem.Tier > maxAllowedTier) { continue; }
                    var diff = Math.Abs(candidateItem.Effectiveness - targetEffectiveness);
                    var effectiveness = candidateItem.Effectiveness;
                    // ANY culture
                    if (diff < bestAnyDiff ||
                        diff == bestAnyDiff && effectiveness > bestAnyEffectiveness)
                    {
                        bestAnyIndex = i;
                        bestAnyDiff = diff;
                        bestAnyEffectiveness = effectiveness;
                    }
                    // CULTURE-compatible
                    if (!IsCultureCompatible(candidateItem, desiredCulture)) { continue; }
                    if (diff < bestCultureDiff ||
                        diff == bestCultureDiff && effectiveness > bestCultureEffectiveness)
                    {
                        bestCultureIndex = i;
                        bestCultureDiff = diff;
                        bestCultureEffectiveness = effectiveness;
                    }
                }
                var chosenIndex = bestAnyIndex;
                if (preferDefaultEquipmentThenClosest && bestCultureIndex >= 0)
                {
                    chosenIndex = bestCultureIndex;
                    if (bestAnyIndex >= 0)
                    {
                        // diff smaller = more compatible
                        var anyIsMoreThanTwiceAsCompatible = bestCultureDiff > (bestAnyDiff * CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER);
                        if (anyIsMoreThanTwiceAsCompatible)
{
                            chosenIndex = bestAnyIndex;
                        }
                    }
                }
                if (chosenIndex >= 0)
                {
                    var chosen = armours[chosenIndex];
                    assignment.SetEquipment(slotIndex.Value, chosen.Key);
                    armours[chosenIndex] = new KeyValuePair<EquipmentElement, int>(chosen.Key, chosen.Value - 1);
                    ConsumeEquipmentToAssign(chosen.Key);
                }
                continue;
            }
            // No reference item:
            {
                var bestCultureIndex = -1;
                var bestCultureEffectiveness = float.MinValue;
                var bestAnyIndex = -1;
                var bestAnyEffectiveness = float.MinValue;
                for (var i = 0; i < armours.Length; i++)
                {
                    var candidate = armours[i];
                    if (candidate.Value <= 0) { continue; }
                    var candidateItem = candidate.Key.Item;
                    if (candidateItem == null) { continue; }
                    if ((int)candidateItem.Tier > maxAllowedTier) { continue; }
                    var effectiveness = candidateItem.Effectiveness;
                    // ANY
                    if (effectiveness > bestAnyEffectiveness)
                    {
                        bestAnyIndex = i;
                        bestAnyEffectiveness = effectiveness;
                    }
                    // CULTURE-compatible
                    if (!IsCultureCompatible(candidateItem, desiredCulture)) { continue; }
                    if (effectiveness > bestCultureEffectiveness)
                    {
                        bestCultureIndex = i;
                        bestCultureEffectiveness = effectiveness;
                    }
                }
                var chosenIndex =
                    preferDefaultEquipmentThenClosest
                        ? (bestCultureIndex >= 0 ? bestCultureIndex : bestAnyIndex)
                        : bestAnyIndex;
                if (chosenIndex >= 0)
                {
                    var chosen = armours[chosenIndex];
                    assignment.SetEquipment(slotIndex.Value, chosen.Key);
                    armours[chosenIndex] = new KeyValuePair<EquipmentElement, int>(chosen.Key, chosen.Value - 1);
                    ConsumeEquipmentToAssign(chosen.Key);
                }
            }
        }
    }
References _equipmentToAssign, Assignments, ConsumeEquipmentToAssign(), CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER, DynamicTroopEquipmentReupload.Global.GetEquipmentIndexByItemType(), GetMaxAllowedTier(), IsCultureCompatible(), and DynamicTroopEquipmentReupload.ModSettings.PreferDefaultEquipmentThenClosest.
Referenced by DoAssignAsync().
AssignExtraArrows()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraArrows () private
Definition at line 568 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignExtraArrows for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(ArrowFilter, ArrowAssignmentFilter);
        return;
        static bool ArrowFilter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item: { } item } && item.IsArrow() && equipment.Value > 0;
        }
        static bool ArrowAssignmentFilter(Assignment assignment) {
            return assignment.IsArcher;
        }
    }
References AssignExtraEquipment(), DynamicTroopEquipmentReupload.Assignment.IsArcher, and WriteDistributionLog().
Referenced by DoAssignAsync().
AssignExtraBolts()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraBolts () private
Definition at line 583 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignExtraBolts for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(BoltFilter, BoltAssignmentFilter);
        return;
        static bool BoltFilter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item: { } item } && item.IsBolt() && equipment.Value > 0;
        }
        static bool BoltAssignmentFilter(Assignment assignment) {
            return assignment.IsCrossBowMan;
        }
    }
References AssignExtraEquipment(), DynamicTroopEquipmentReupload.Assignment.IsCrossBowMan, and WriteDistributionLog().
Referenced by DoAssignAsync().
AssignExtraEquipment()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraEquipment (EquipmentFilter equipmentFilter, AssignmentFilter assignmentFilter) private
根据给定的装备筛选条件和分配筛选条件为角色分配额外装备。
Parameters
equipmentFilter 装备筛选函数，用于决定哪些装备可以被分配。
assignmentFilter 分配筛选函数，用于决定哪些角色可以接收装备。
Definition at line 495 of file PartyEquipmentDistributor.cs.
{
        var candidates = new List<KeyValuePair<EquipmentElement, int>>();
        foreach (var kv in _equipmentToAssign) {
            if (kv.Key is { IsEmpty: false, Item: not null } &&
                kv.Value > 0                                 &&
                equipmentFilter(kv)) { candidates.Add(kv); }
        }
        if (candidates.Count == 0)
            return;
        candidates.Sort(static (a, b) => {
            var tierCompare = b.Key.Item.Tier.CompareTo(a.Key.Item.Tier);
            return tierCompare != 0 ? tierCompare : b.Key.Item.Value.CompareTo(a.Key.Item.Value);
        });
        var currentIndex = 0;
        foreach (var assignment in Assignments) {
            if (!assignmentFilter(assignment))
                continue;
            var slot = assignment.EmptyWeaponSlot;
            if (!slot.HasValue)
                continue;
            while (currentIndex < candidates.Count && candidates[currentIndex].Value <= 0)
                currentIndex++;
            if (currentIndex >= candidates.Count)
                return;
            var current = candidates[currentIndex];
            assignment.SetEquipment(slot.Value, current.Key);
            WriteDistributionLog($"extra equipment {current.Key} assigned to {assignment.Character.StringId}#{assignment.Index} on slot {slot.Value} for {_party.Name}", Colors.Green, Level.Debug);
            candidates[currentIndex] = new KeyValuePair<EquipmentElement, int>(current.Key, current.Value - 1);
            ConsumeEquipmentToAssign(current.Key);
        }
    }
References _equipmentToAssign, AssignmentFilter(), Assignments, ConsumeEquipmentToAssign(), EquipmentFilter(), and WriteDistributionLog().
Referenced by AssignExtraArrows(), AssignExtraBolts(), AssignExtraShield(), AssignExtraThrownWeapon(), and AssignExtraTwoHandedWeaponOrPolearms().
AssignExtraShield()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraShield () private
Definition at line 538 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignExtraShield for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(ShieldFilter, ShieldAssignmentFilter);
        return;
        static bool ShieldFilter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item.ItemType: ItemTypeEnum.Shield } && equipment.Value > 0;
        }
        static bool ShieldAssignmentFilter(Assignment assignment) {
            return assignment is { CanBeShielded: true, IsShielded: false };
        }
    }
References AssignExtraEquipment(), and WriteDistributionLog().
Referenced by DoAssignAsync().
AssignExtraThrownWeapon()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraThrownWeapon () private
Definition at line 553 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignExtraThrownWeapon for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(ThrownFilter, ThrownAssignmentFilter);
        return;
        static bool ThrownFilter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item: { } item } && item.IsThrowing() && equipment.Value > 0;
        }
        static bool ThrownAssignmentFilter(Assignment assignment) {
            return !assignment.HaveThrown;
        }
    }
References AssignExtraEquipment(), DynamicTroopEquipmentReupload.Assignment.HaveThrown, and WriteDistributionLog().
Referenced by DoAssignAsync().
AssignExtraTwoHandedWeaponOrPolearms()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignExtraTwoHandedWeaponOrPolearms () private
Definition at line 598 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignExtraTwoHandedWeaponOrPolearms for {_party.Name}", Colors.Green, Level.Debug);
        AssignExtraEquipment(Filter, AssignmentFilter);
        return;
        static bool Filter(KeyValuePair<EquipmentElement, int> equipment) {
            return equipment.Key is { IsEmpty: false, Item: { } item } && (item.IsTwoHanded() || item.IsPolearm()) && equipment.Value > 0;
        }
        static bool AssignmentFilter(Assignment assignment) {
            return !assignment.HaveTwoHandedWeaponOrPolearms;
        }
    }
References AssignExtraEquipment(), AssignmentFilter(), DynamicTroopEquipmentReupload.Assignment.HaveTwoHandedWeaponOrPolearms, and WriteDistributionLog().
Referenced by DoAssignAsync().
AssignHorseAndHarness()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignHorseAndHarness () private
Definition at line 458 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"Assigning Horse and Harness for {_party.Name}", Colors.Green, Level.Debug);
        var currentIndex = 0;
        foreach (var assignment in Assignments) {
            if (!assignment.IsMounted) { continue; }
            if (currentIndex >= _horseAndHarnesses.Count) { break; }
            var horseAndHarness = _horseAndHarnesses[currentIndex++];
            assignment.SetEquipment(EquipmentIndex.Horse, horseAndHarness.Horse);
            WriteDistributionLog($"assign horse {horseAndHarness.Horse.Item.Name} to {assignment.Character.Name}#{assignment.Index} for {_party.Name}", Colors.Green, Level.Debug);
            if (!horseAndHarness.Harness.HasValue) { continue; }
            assignment.SetEquipment(EquipmentIndex.HorseHarness, horseAndHarness.Harness.Value);
            WriteDistributionLog($"assign horse harness {horseAndHarness.Harness.Value.Item.Name} to {assignment.Character.Name}#{assignment.Index} for {_party.Name}", Colors.Green, Level.Debug);
        }
    }
References _horseAndHarnesses, Assignments, and WriteDistributionLog().
Referenced by DoAssignAsync().
AssignmentFilter()
delegate bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignmentFilter (Assignment assignment) private
Referenced by AssignExtraEquipment(), and AssignExtraTwoHandedWeaponOrPolearms().
AssignSaddlesToHorseAndHarnesses()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignSaddlesToHorseAndHarnesses (IEnumerable< HorseAndHarness > horseAndHarnesses, IList<(EquipmentElement Key, int Cnt)> saddles) static private
Definition at line 397 of file PartyEquipmentDistributor.cs.
{
        var saddleIndex = 0;
        foreach (var hoh in horseAndHarnesses.WhereQ(h => h.Harness == null)) {
            if (saddleIndex >= saddles.Count) { break; }
            (var saddleItem, var saddleCnt) = saddles[saddleIndex];
            if (saddleCnt <= 0) { continue; }
            hoh.Harness          = saddleItem;
            saddles[saddleIndex] = (saddleItem, --saddleCnt);
            if (saddleCnt == 0) { saddleIndex++; }
        }
    }
Referenced by GenerateHorseAndHarnessPairs().
AssignWeaponByItemEnumType()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumType (bool strict) private
Definition at line 950 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignWeaponByItemEnumType strict={strict} for {_party.Name}", Colors.Green, Level.Debug);
        foreach (var assignment in Assignments) {
            AssignWeaponByItemEnumTypeBySlot(EquipmentIndex.Weapon0, assignment, assignment.IsMounted, strict);
            AssignWeaponByItemEnumTypeBySlot(EquipmentIndex.Weapon1, assignment, assignment.IsMounted, strict);
            AssignWeaponByItemEnumTypeBySlot(EquipmentIndex.Weapon2, assignment, assignment.IsMounted, strict);
            AssignWeaponByItemEnumTypeBySlot(EquipmentIndex.Weapon3, assignment, assignment.IsMounted, strict);
        }
    }
References Assignments, AssignWeaponByItemEnumTypeBySlot(), and WriteDistributionLog().
Referenced by DoAssignAsync().
AssignWeaponByItemEnumTypeBySlot()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByItemEnumTypeBySlot (EquipmentIndex slot, Assignment assignment, bool mounted, bool strict) private
Definition at line 961 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignWeaponByItemEnumTypeBySlot slot={slot} character={assignment.Character.StringId}#{assignment.Index} mounted={mounted} strict={strict} for {_party.Name}", Colors.Green, Level.Debug);
        var settings = ModSettings.Instance;
        var preferVanillaThenClosest = settings?.PreferDefaultEquipmentThenClosest ?? true;
        var referenceWeapon = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
        var currentWeapon = assignment.GetEquipmentFromSlot(slot);
        if (currentWeapon is { IsEmpty: false, Item: not null } || referenceWeapon.IsEmpty || referenceWeapon.Item == null)
            return;
        var maxAllowedTier = GetMaxAllowedTier(referenceWeapon.Item);
        // Loyal ON: exact vanilla weapon first (if available)
        if (preferVanillaThenClosest &&
            (int)referenceWeapon.Item.Tier <= maxAllowedTier &&
            TryConsumeExactItem(referenceWeapon.Item, out var exactElement))
        {
            assignment.SetEquipment(slot, exactElement);
            WriteDistributionLog($"weapon (vanilla exact) {exactElement.Item.StringId} assigned to {assignment.Character.StringId}#{assignment.Index} for {_party.Name}", Colors.Green, Level.Debug);
            return;
        }
        var desiredCulture = assignment.Character.Culture;
        var targetEffectiveness = referenceWeapon.Item.Effectiveness;
        EquipmentElement? bestAnyWeapon = null;
        var bestAnyDiff = float.MaxValue;
        var bestAnyEffectiveness = float.MinValue;
        EquipmentElement? bestCultureWeapon = null;
        var bestCultureDiff = float.MaxValue;
        var bestCultureEffectiveness = float.MinValue;
        foreach (var kv in _equipmentToAssign)
        {
            if (kv.Value <= 0)
                continue;
            var element = kv.Key;
            if (element.IsEmpty || element.Item == null)
                continue;
            var item = element.Item;
            if ((int)item.Tier > maxAllowedTier)
                continue;
            if (!IsWeaponSuitable(element, referenceWeapon.Item, assignment, strict))
                continue;
            var diff = Math.Abs(item.Effectiveness - targetEffectiveness);
            var effectiveness = item.Effectiveness;
            // ANY culture
            if (diff < bestAnyDiff ||
                diff == bestAnyDiff && effectiveness > bestAnyEffectiveness)
            {
                bestAnyDiff = diff;
                bestAnyEffectiveness = effectiveness;
                bestAnyWeapon = element;
            }
            // CULTURE-compatible
            if (!IsCultureCompatible(item, desiredCulture))
                continue;
            if (diff < bestCultureDiff ||
                diff == bestCultureDiff && effectiveness > bestCultureEffectiveness)
            {
                bestCultureDiff = diff;
                bestCultureEffectiveness = effectiveness;
                bestCultureWeapon = element;
            }
        }
        // Loyal OFF must ignore culture.
        EquipmentElement? bestWeapon = bestAnyWeapon;
        if (preferVanillaThenClosest && bestCultureWeapon.HasValue)
        {
            bestWeapon = bestCultureWeapon;
            if (bestAnyWeapon.HasValue)
            {
                // diff smaller = more compatible
                var anyIsMoreThanTwiceAsCompatible = bestCultureDiff > (bestAnyDiff * CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER);
                if (anyIsMoreThanTwiceAsCompatible)
                {
                    bestWeapon = bestAnyWeapon;
                }
            }
        }
        AssignWeaponIfAvailable(slot, assignment, bestWeapon);
    }
References _equipmentToAssign, AssignWeaponIfAvailable(), DynamicTroopEquipmentReupload.Assignment.Character, CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER, DynamicTroopEquipmentReupload.Assignment.GetEquipmentFromSlot(), GetMaxAllowedTier(), IsCultureCompatible(), IsWeaponSuitable(), DynamicTroopEquipmentReupload.ModSettings.PreferDefaultEquipmentThenClosest, DynamicTroopEquipmentReupload.Assignment.ReferenceEquipment, DynamicTroopEquipmentReupload.Assignment.SetEquipment(), TryConsumeExactItem(), and WriteDistributionLog().
Referenced by AssignWeaponByItemEnumType().
AssignWeaponByWeaponClass()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClass (bool strict) private
Definition at line 835 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignWeaponByWeaponClass strict={strict} for {_party.Name}", Colors.Green, Level.Debug);
        foreach (var assignment in Assignments) {
            AssignWeaponByWeaponClassBySlot(EquipmentIndex.Weapon0, assignment, assignment.IsMounted, strict);
            AssignWeaponByWeaponClassBySlot(EquipmentIndex.Weapon1, assignment, assignment.IsMounted, strict);
            AssignWeaponByWeaponClassBySlot(EquipmentIndex.Weapon2, assignment, assignment.IsMounted, strict);
            AssignWeaponByWeaponClassBySlot(EquipmentIndex.Weapon3, assignment, assignment.IsMounted, strict);
        }
    }
References Assignments, AssignWeaponByWeaponClassBySlot(), and WriteDistributionLog().
Referenced by DoAssignAsync().
AssignWeaponByWeaponClassBySlot()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponByWeaponClassBySlot (EquipmentIndex slot, Assignment assignment, bool mounted, bool strict) private
根据武器大类型和指定的装备槽位为角色分配武器。
Parameters
slot 装备槽位，表示需要分配武器的具体位置。
assignment 包含角色和参考装备信息的分配对象。
mounted 指示角色是否骑乘状态，影响武器选择。
strict 是否启用严格模式。
Definition at line 852 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignWeaponByWeaponClassBySlot slot={slot} character={assignment.Character.StringId}#{assignment.Index} mounted={mounted} strict={strict} for {_party.Name}", Colors.Green, Level.Debug);
        var settings = ModSettings.Instance;
        var preferVanillaThenClosest = settings?.PreferDefaultEquipmentThenClosest ?? true;
        var referenceWeapon = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
        var currentWeapon = assignment.GetEquipmentFromSlot(slot);
        if (currentWeapon is { IsEmpty: false, Item: not null } || referenceWeapon.IsEmpty || referenceWeapon.Item == null)
            return;
        var maxAllowedTier = GetMaxAllowedTier(referenceWeapon.Item);
        // Loyal ON: exact vanilla weapon first (if available)
        if (preferVanillaThenClosest &&
            (int)referenceWeapon.Item.Tier <= maxAllowedTier &&
            TryConsumeExactItem(referenceWeapon.Item, out var exactElement))
        {
            assignment.SetEquipment(slot, exactElement);
            WriteDistributionLog($"weapon (vanilla exact) {exactElement.Item.StringId} assigned to {assignment.Character.StringId}#{assignment.Index} for {_party.Name}", Colors.Green, Level.Debug);
            return;
        }
        var desiredCulture = assignment.Character.Culture;
        var targetEffectiveness = referenceWeapon.Item.Effectiveness;
        EquipmentElement? bestAnyWeapon = null;
        var bestAnyDiff = float.MaxValue;
        var bestAnyEffectiveness = float.MinValue;
        EquipmentElement? bestCultureWeapon = null;
        var bestCultureDiff = float.MaxValue;
        var bestCultureEffectiveness = float.MinValue;
        foreach (var kv in _equipmentToAssign)
        {
            if (kv.Value <= 0)
                continue;
            var element = kv.Key;
            if (element.IsEmpty || element.Item == null)
                continue;
            var item = element.Item;
            if ((int)item.Tier > maxAllowedTier)
                continue;
            if (!IsWeaponSuitable(element, referenceWeapon.Item, assignment, strict))
                continue;
            var diff = Math.Abs(item.Effectiveness - targetEffectiveness);
            var effectiveness = item.Effectiveness;
            // ANY culture
            if (diff < bestAnyDiff ||
                diff == bestAnyDiff && effectiveness > bestAnyEffectiveness)
            {
                bestAnyDiff = diff;
                bestAnyEffectiveness = effectiveness;
                bestAnyWeapon = element;
            }
            // CULTURE-compatible
            if (!IsCultureCompatible(item, desiredCulture))
                continue;
            if (diff < bestCultureDiff ||
                diff == bestCultureDiff && effectiveness > bestCultureEffectiveness)
            {
                bestCultureDiff = diff;
                bestCultureEffectiveness = effectiveness;
                bestCultureWeapon = element;
            }
        }
        EquipmentElement? bestWeapon = bestAnyWeapon;
        if (preferVanillaThenClosest && bestCultureWeapon.HasValue)
        {
            bestWeapon = bestCultureWeapon;
            if (bestAnyWeapon.HasValue)
            {
                // diff smaller = more compatible
                var anyIsMoreThanTwiceAsCompatible = bestCultureDiff > (bestAnyDiff * CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER);
                if (anyIsMoreThanTwiceAsCompatible)
                {
                    bestWeapon = bestAnyWeapon;
                }
            }
        }
        AssignWeaponIfAvailable(slot, assignment, bestWeapon);
    }
References _equipmentToAssign, AssignWeaponIfAvailable(), DynamicTroopEquipmentReupload.Assignment.Character, CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER, DynamicTroopEquipmentReupload.Assignment.GetEquipmentFromSlot(), GetMaxAllowedTier(), IsCultureCompatible(), IsWeaponSuitable(), DynamicTroopEquipmentReupload.ModSettings.PreferDefaultEquipmentThenClosest, DynamicTroopEquipmentReupload.Assignment.ReferenceEquipment, DynamicTroopEquipmentReupload.Assignment.SetEquipment(), TryConsumeExactItem(), and WriteDistributionLog().
Referenced by AssignWeaponByWeaponClass().
AssignWeaponIfAvailable()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponIfAvailable (EquipmentIndex slot, Assignment assignment, EquipmentElement? availableWeapon) private
Definition at line 1087 of file PartyEquipmentDistributor.cs.
{
        if (!availableWeapon.HasValue || availableWeapon.Value.IsEmpty || availableWeapon.Value.Item == null)
            return;
        WriteDistributionLog($"weapon {availableWeapon.Value.Item.StringId} assigned to {assignment.Character.StringId}#{assignment.Index} for {_party.Name}", Colors.Green, Level.Debug);
        assignment.SetEquipment(slot, availableWeapon.Value);
        ConsumeEquipmentToAssign(availableWeapon.Value);
    }
References ConsumeEquipmentToAssign(), DynamicTroopEquipmentReupload.Assignment.SetEquipment(), and WriteDistributionLog().
Referenced by AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
AssignWeaponToUnarmed()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.AssignWeaponToUnarmed (bool useRandomSelection) private
Definition at line 476 of file PartyEquipmentDistributor.cs.
{
        WriteDistributionLog($"AssignWeaponToUnarmed for {_party.Name}", Colors.Green, Level.Debug);
        var unarmedAssignments = Assignments.WhereQ(assignment => assignment.IsUnarmed).ToListQ();
        foreach (var assignment in unarmedAssignments) {
            WriteDistributionLog($"Found unarmed unit Index {assignment.Index} for {_party.Name}", Colors.Yellow, Level.Warn);
            var weapon = GetMeleeWeaponForUnarmedTroop(assignment, useRandomSelection);
            if (weapon.HasValue) {
                assignment.SetEquipment(EquipmentIndex.Weapon0, weapon.Value);
                ConsumeEquipmentToAssign(weapon.Value);
            }
            else { WriteDistributionLog($"Cannot find random melee weapon for {assignment.Index} for {_party.Name}", Colors.Yellow, Level.Warn); }
        }
    }
References Assignments, ConsumeEquipmentToAssign(), GetMeleeWeaponForUnarmedTroop(), and WriteDistributionLog().
Referenced by DoAssignAsync().
CalculateEquipmentTierScoreWithoutMountEquipment()
static int DynamicTroopEquipmentReupload.PartyEquipmentDistributor.CalculateEquipmentTierScoreWithoutMountEquipment (Equipment equipment) static private
Definition at line 1257 of file PartyEquipmentDistributor.cs.
{
        var score = 0;
        foreach (var slot in Global.EquipmentSlots) {
            if (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness) { continue; }
            var element = equipment.GetEquipmentFromSlot(slot);
            if (element is { IsEmpty: false, Item: not null }) { score += (int)element.Item.Tier; }
        }
        return score;
    }
References DynamicTroopEquipmentReupload.Global.EquipmentSlots.
Referenced by MarkUnderEquippedAssignmentsIfEnabled().
ConsumeEquipmentToAssign()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ConsumeEquipmentToAssign (EquipmentElement equipmentElement) private
Definition at line 299 of file PartyEquipmentDistributor.cs.
{
        _equipmentToAssign.AddOrUpdate(
            equipmentElement,
            0,
            (_, currentCount) => currentCount > 0 ? currentCount - 1 : 0);
    }
References _equipmentToAssign.
Referenced by AssignEquipmentType(), AssignExtraEquipment(), AssignWeaponIfAvailable(), AssignWeaponToUnarmed(), and TryConsumeExactItem().
DoAssignAsync()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.DoAssignAsync (bool assignExtraEquipment = true, bool applyEmergencyLoadout = true, bool markUnderEquipped = true, bool useRandomUnarmedFallback = true) private
Definition at line 411 of file PartyEquipmentDistributor.cs.
{
        var settings = ModSettings.Instance;
        if (_missionAllowsMountEquipment)
            GenerateHorseAndHarnessList();
        AssignEquipmentType(ItemTypeEnum.HeadArmor);
        AssignEquipmentType(ItemTypeEnum.BodyArmor);
        AssignEquipmentType(ItemTypeEnum.LegArmor);
        AssignEquipmentType(ItemTypeEnum.HandArmor);
        AssignEquipmentType(ItemTypeEnum.Cape);
        if (_missionAllowsMountEquipment)
            AssignHorseAndHarness();
        // strict
        AssignWeaponByWeaponClass(true);
        // non strict
        AssignWeaponByWeaponClass(false);
        AssignWeaponByItemEnumType(false);
        // random
        AssignWeaponToUnarmed(useRandomUnarmedFallback);
        // Extra equipment
        if (assignExtraEquipment && (settings?.AssignExtraEquipments ?? true)) {
            AssignExtraShield();
            AssignExtraThrownWeapon();
            AssignExtraArrows();
            AssignExtraBolts();
            AssignExtraTwoHandedWeaponOrPolearms();
        }
        // Emergency loadout
        if (applyEmergencyLoadout && (settings?.EnableEmergencyLoadout ?? true))
            ApplyEmergencyLoadout();
        // Underequipped
        if (markUnderEquipped)
            MarkUnderEquippedAssignmentsIfEnabled();
    }
References _missionAllowsMountEquipment, ApplyEmergencyLoadout(), AssignEquipmentType(), AssignExtraArrows(), AssignExtraBolts(), AssignExtraShield(), AssignExtraThrownWeapon(), AssignExtraTwoHandedWeaponOrPolearms(), AssignHorseAndHarness(), AssignWeaponByItemEnumType(), AssignWeaponByWeaponClass(), AssignWeaponToUnarmed(), GenerateHorseAndHarnessList(), and MarkUnderEquippedAssignmentsIfEnabled().
Referenced by RunAsync().
EquipmentFilter()
delegate bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.EquipmentFilter (KeyValuePair< EquipmentElement, int > equipment) private
Referenced by AssignExtraEquipment().
GenerateHorseAndHarnessList()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GenerateHorseAndHarnessList () private
Definition at line 306 of file PartyEquipmentDistributor.cs.
{
        Dictionary<int, List<(EquipmentElement Key, int Cnt)>> horsesDict  = new();
        Dictionary<int, List<(EquipmentElement Key, int Cnt)>> harnessDict = new();
        List<(EquipmentElement Key, int Cnt)>                  saddles     = new();
        PopulateDictionaries(_equipmentToAssign, horsesDict, harnessDict, saddles);
        SortEquipmentDictionaries(horsesDict, harnessDict, saddles);
        GenerateHorseAndHarnessPairs(horsesDict, harnessDict, saddles);
    }
References _equipmentToAssign, GenerateHorseAndHarnessPairs(), PopulateDictionaries(), and SortEquipmentDictionaries().
Referenced by DoAssignAsync().
GenerateHorseAndHarnessPairs()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GenerateHorseAndHarnessPairs (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, IList<(EquipmentElement Key, int Cnt)> saddles) private
Definition at line 367 of file PartyEquipmentDistributor.cs.
{
        foreach (var kvp in horsesDict) {
            var familyType = kvp.Key;
            var horses     = kvp.Value.ToArrayQ();
            var harnesses  = harnessDict.TryGetValue(familyType, out var harnessesList) ? harnessesList.ToArrayQ() : Array.Empty<(EquipmentElement Key, int Cnt)>();
            int horseIndex = 0, harnessIndex = 0;
            while (horseIndex < horses.Length) {
                (var horseItem, var horseCnt) = horses[horseIndex];
                var harnessItem = harnessIndex < harnesses.Length ? harnesses[harnessIndex].Key : new EquipmentElement(null);
                var harnessCnt  = harnessIndex < harnesses.Length ? harnesses[harnessIndex].Cnt : 0;
                if (horseCnt > 0) {
                    HorseAndHarness hah = new(horseItem, harnessItem);
                    _horseAndHarnesses.Add(hah);
                    horses[horseIndex] = (horseItem, --horseCnt);
                    if (harnessCnt > 0) { harnesses[harnessIndex] = (harnessItem, --harnessCnt); }
                }
                if (horseCnt == 0) { horseIndex++; }
                if (harnessCnt == 0 && harnessIndex < harnesses.Length) { harnessIndex++; }
            }
        }
        AssignSaddlesToHorseAndHarnesses(_horseAndHarnesses, saddles);
        _horseAndHarnesses.Sort((x, y) => y.CompareTo(x));
    }
References _horseAndHarnesses, and AssignSaddlesToHorseAndHarnesses().
Referenced by GenerateHorseAndHarnessList().
GetMaxAllowedTier()
int DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GetMaxAllowedTier (ItemObject? referenceItem) private
Definition at line 1139 of file PartyEquipmentDistributor.cs.
{
        if (referenceItem == null) {
            return 6; // max
        }
        return Math.Min(6, (int)referenceItem.Tier + MAX_TIER_ABOVE_DEFAULT);
    }
References MAX_TIER_ABOVE_DEFAULT.
Referenced by AssignEquipmentType(), AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
GetMeleeWeaponForUnarmedTroop()
EquipmentElement? DynamicTroopEquipmentReupload.PartyEquipmentDistributor.GetMeleeWeaponForUnarmedTroop (Assignment assignment, bool useRandomSelection) private
Definition at line 613 of file PartyEquipmentDistributor.cs.
{
        var candidates = new List<EquipmentElement>();
        foreach (var kv in _equipmentToAssign) {
            var element = kv.Key;
            if (kv.Value <= 0 || element.IsEmpty || element.Item == null)
                continue;
            var item = element.Item;
            if (!item.HasWeaponComponent)
                continue;
            if (!item.IsSuitableForCharacter(assignment.Character))
                continue;
            if (item.IsThrowing())
                continue;
            if (!item.IsTwoHanded() && !item.IsOneHanded() && !item.IsPolearm())
                continue;
            var hasAssignedHorse =
                !assignment.GetEquipmentFromSlot(EquipmentIndex.Horse).IsEmpty &&
                assignment.GetEquipmentFromSlot(EquipmentIndex.Horse).Item != null;
            if (hasAssignedHorse && !item.IsSuitableForMount())
                continue;
            candidates.Add(element);
        }
        if (candidates.Count == 0)
            return null;
        EquipmentElement selected;
        if (useRandomSelection) {
            selected = candidates[MBRandom.RandomInt(candidates.Count)];
        }
        else {
            candidates.Sort((x, y) => {
                var tierComparison = x.Item.Tier.CompareTo(y.Item.Tier);
                return tierComparison != 0
                    ? tierComparison
                    : string.CompareOrdinal(x.Item.StringId, y.Item.StringId);
            });
            selected = candidates[0];
        }
        WriteDistributionLog($"(random) weapon {selected.Item.StringId} selected for {_party.Name}", Colors.Green, Level.Debug);
        return selected;
    }
References _equipmentToAssign, and WriteDistributionLog().
Referenced by AssignWeaponToUnarmed().
IsCultureCompatible()
static bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsCultureCompatible (ItemObject item, BasicCultureObject? culture) static private
Definition at line 1146 of file PartyEquipmentDistributor.cs.
{
        return culture == null || item.Culture == null || item.Culture == culture;
    }
Referenced by AssignEquipmentType(), AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
IsWeaponSuitable()
bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.IsWeaponSuitable (EquipmentElement equipment, ItemObject referenceWeapon, Assignment assignment, bool strict) private
Definition at line 1060 of file PartyEquipmentDistributor.cs.
{
        if (equipment.IsEmpty                                            ||
            equipment.Item == null                                       ||
            !equipment.Item.HasWeaponComponent                           ||
            _equipmentToAssign[equipment] <= 0                           ||
            !equipment.Item.IsSuitableForCharacter(assignment.Character) ||
            !Global.HaveSameWeaponClass(Global.GetWeaponClass(equipment.Item), Global.GetWeaponClass(referenceWeapon))) { return false; }
        var isSuitableForMount = equipment.Item.IsSuitableForMount();
        var isCouchable        = equipment.Item.IsCouchable();
        if (strict) {
            if (!Global.FullySameWeaponClass(equipment.Item, referenceWeapon)) { return false; }
            if (assignment.IsMounted) {
                // 严格模式下骑马：必须适合骑乘；如果是长杆武器，则必须可进行骑枪冲刺
                return isSuitableForMount && (!equipment.Item.IsPolearm() || isCouchable);
            }
            // 严格模式下非骑马：不可选择可进行骑枪冲刺的武器
            return !isCouchable;
        }
        // 非严格模式下：骑马的不能选择不适合骑乘的武器，非骑马的可以选择任意武器
        return !assignment.IsMounted || isSuitableForMount;
    }
References _equipmentToAssign, DynamicTroopEquipmentReupload.Assignment.Character, DynamicTroopEquipmentReupload.Global.FullySameWeaponClass(), DynamicTroopEquipmentReupload.Global.GetWeaponClass(), DynamicTroopEquipmentReupload.Global.HaveSameWeaponClass(), and DynamicTroopEquipmentReupload.Assignment.IsMounted.
Referenced by AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
MarkUnderEquippedAssignmentsIfEnabled()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.MarkUnderEquippedAssignmentsIfEnabled () private
Definition at line 1225 of file PartyEquipmentDistributor.cs.
{
        var settings = ModSettings.Instance;
        if (!(settings?.Underequipped ?? true)) {
            for (var i = 0; i < Assignments.Count; i++) {
                var assignment = Assignments[i];
                assignment.IsUnderEquipped            = false;
                assignment.UnderEquippedMoralePenalty = 0f;
            }
            return;
        }
        for (var i = 0; i < Assignments.Count; i++) {
            var assignment = Assignments[i];
            var referenceScore = CalculateEquipmentTierScoreWithoutMountEquipment(assignment.ReferenceEquipment);
            var assignedScore  = CalculateEquipmentTierScoreWithoutMountEquipment(assignment.Equipment);
            if (assignedScore >= referenceScore) {
                assignment.IsUnderEquipped            = false;
                assignment.UnderEquippedMoralePenalty = 0f;
                continue;
            }
            var missingTierTotal = referenceScore - assignedScore;
            var moralePenalty    = missingTierTotal * UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER;
            assignment.IsUnderEquipped            = true;
            assignment.UnderEquippedMoralePenalty = Math.Min(UNDER_EQUIPPED_MORALE_PENALTY_CAP, moralePenalty);
        }
    }
References Assignments, CalculateEquipmentTierScoreWithoutMountEquipment(), UNDER_EQUIPPED_MORALE_PENALTY_CAP, and UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER.
Referenced by DoAssignAsync().
MeasureMainPartyArmoryReadiness()
static ArmoryReadiness DynamicTroopEquipmentReupload.PartyEquipmentDistributor.MeasureMainPartyArmoryReadiness (bool canUseMountEquipment) static package
Definition at line 103 of file PartyEquipmentDistributor.cs.
{
        var mainParty = MobileParty.MainParty;
        if (mainParty == null)
            return new ArmoryReadiness(0, 0);
        // refreshed campaign map before armory transactions have been finalized
        var armorySnapshot = new ItemRoster();
        foreach (var rosterElement in ArmyArmory.Armory)
        {
            if (rosterElement.Amount > 0 &&
                ArmyArmory.TryNormalizeArmoryElement(rosterElement.EquipmentElement, out var equipmentElement))
                armorySnapshot.AddToCounts(equipmentElement, rosterElement.Amount);
        }
        var armoryPreview = new PartyEquipmentDistributor(mainParty, armorySnapshot, canUseMountEquipment);
        foreach (var troop in mainParty.MemberRoster.GetTroopRoster())
        {
            if (troop.Character is not CharacterObject character || character.IsHero || troop.Number <= 0)
                continue;
            var battleEquipments = character.BattleEquipments
                .Where(equipment => equipment.IsBattle && !equipment.IsEmpty())
                .ToArray();
            if (battleEquipments.Length == 0)
                continue;
            for (var troopIndex = 0; troopIndex < troop.Number; troopIndex++)
            {
                var authoredEquipment = battleEquipments[troopIndex % battleEquipments.Length];
                armoryPreview.Assignments.Add(new Assignment(character, authoredEquipment, canUseMountEquipment));
            }
        }
        armoryPreview.Assignments.Sort((x, y) => y.CompareTo(x));
        foreach (var rosterElement in armoryPreview._itemRoster!)
            armoryPreview.AddEquipmentToAssign(rosterElement.EquipmentElement, rosterElement.Amount);
        armoryPreview.DoAssignAsync(
            assignExtraEquipment: false,
            applyEmergencyLoadout: false,
            markUnderEquipped: false,
            useRandomUnarmedFallback: false);
        var equippedSlots = 0;
        var expectedSlots = 0;
        foreach (var assignment in armoryPreview.Assignments)
        {
            var expectsMeleeWeapon = false;
            var expectsShield = false;
            var hasAssignedMeleeWeapon = false;
            var hasAssignedShield = false;
            var assignedMeleeCanUseShield = false;
            foreach (var slot in Global.EquipmentSlots)
            {
                if (!canUseMountEquipment &&
                    (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness))
                    continue;
                var isWeaponSlot =
                    slot == EquipmentIndex.Weapon0 ||
                    slot == EquipmentIndex.Weapon1 ||
                    slot == EquipmentIndex.Weapon2 ||
                    slot == EquipmentIndex.Weapon3;
                if (!isWeaponSlot)
                {
                    var expectedEquipment = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
                    if (expectedEquipment.IsEmpty || expectedEquipment.Item == null)
                        continue;
                    expectedSlots++;
                    var assignedEquipment = assignment.GetEquipmentFromSlot(slot);
                    if (!assignedEquipment.IsEmpty && assignedEquipment.Item != null)
                        equippedSlots++;
                    continue;
                }
                var expectedWeapon = assignment.ReferenceEquipment.GetEquipmentFromSlot(slot);
                if (!expectedWeapon.IsEmpty && expectedWeapon.Item != null)
                {
                    var expectedItem = expectedWeapon.Item;
                    if (expectedItem.ItemType == ItemTypeEnum.Shield)
                    {
                        expectsShield = true;
                    }
                    else if (!expectedItem.IsThrowing() &&
                             (expectedItem.IsOneHanded() ||
                              expectedItem.IsTwoHanded() ||
                              expectedItem.IsPolearm()))
                    {
                        expectsMeleeWeapon = true;
                    }
                    else
                    {
                        expectedSlots++;
                        var assignedWeapon = assignment.GetEquipmentFromSlot(slot);
                        var assignedWeaponItem = assignedWeapon.Item;
                        if (!assignedWeapon.IsEmpty && assignedWeaponItem != null)
{
                            var matchesExpectedWeapon =
                                expectedItem.IsBow() && assignedWeaponItem.IsBow() ||
                                expectedItem.IsCrossBow() && assignedWeaponItem.IsCrossBow() ||
                                expectedItem.IsArrow() && assignedWeaponItem.IsArrow() ||
                                expectedItem.IsBolt() && assignedWeaponItem.IsBolt() ||
                                expectedItem.IsThrowing() && assignedWeaponItem.IsThrowing() ||
                                expectedItem.ItemType == assignedWeaponItem.ItemType;
                            if (matchesExpectedWeapon)
                                equippedSlots++;
                        }
                    }
                }
                var assignedWeaponElement = assignment.GetEquipmentFromSlot(slot);
                if (assignedWeaponElement.IsEmpty || assignedWeaponElement.Item == null)
                    continue;
                var assignedItem = assignedWeaponElement.Item;
                if (assignedItem.ItemType == ItemTypeEnum.Shield)
                {
                    hasAssignedShield = true;
                }
                else if (!assignedItem.IsThrowing() &&
                         (assignedItem.IsOneHanded() ||
                          assignedItem.IsTwoHanded() ||
                          assignedItem.IsPolearm()))
                {
                    hasAssignedMeleeWeapon = true;
                    if (assignedItem.IsOneHanded() && !assignedItem.CantUseWithShields())
                        assignedMeleeCanUseShield = true;
                }
            }
            if (expectsMeleeWeapon)
            {
                expectedSlots++;
                if (hasAssignedMeleeWeapon)
                    equippedSlots++;
            }
            // a two handed replacement makes the templates shield irrelevant
            if (expectsShield && (!hasAssignedMeleeWeapon || assignedMeleeCanUseShield))
            {
                expectedSlots++;
                if (hasAssignedShield)
                    equippedSlots++;
            }
        }
        return new ArmoryReadiness(equippedSlots, expectedSlots);
    }
References PartyEquipmentDistributor(), DynamicTroopEquipmentReupload.ArmyArmory.Armory, DynamicTroopEquipmentReupload.Global.EquipmentSlots, and DynamicTroopEquipmentReupload.ArmyArmory.TryNormalizeArmoryElement().
Referenced by DynamicTroopEquipmentReupload.GUIExtensions.MapArmoryReadinessMixin.OnRefresh().
PopulateDictionaries()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.PopulateDictionaries (IEnumerable< KeyValuePair< EquipmentElement, int > > equipment, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, IDictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, ICollection<(EquipmentElement Key, int Cnt)> saddles) static private
Definition at line 316 of file PartyEquipmentDistributor.cs.
{
        foreach (var kvp in equipment) {
            switch (kvp.Key.Item) {
                case { HasHorseComponent: true, ItemType: ItemTypeEnum.Horse }:
                    AddToDict(horsesDict, kvp.Key, kvp.Value);
                    break;
                case { HasArmorComponent: true, ItemType: ItemTypeEnum.HorseHarness }:
                    AddToDict(harnessDict, kvp.Key, kvp.Value);
                    break;
                case {
                         HasArmorComponent : false,
                         HasSaddleComponent: true,
                         ItemType          : ItemTypeEnum.HorseHarness
                     }:
                    saddles.Add((kvp.Key, kvp.Value));
                    break;
            }
        }
    }
References AddToDict().
Referenced by GenerateHorseAndHarnessList().
ReturnItem()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.ReturnItem (ItemObject? item, int count)
Definition at line 1129 of file PartyEquipmentDistributor.cs.
{
        if (!ArmyArmory.TryResolveArmoryItem(item, out var resolvedItem) || count <= 0) {
            WriteDistributionLog("Invalid item or count for return.", Colors.Red, Level.Warn);
            return;
        }
        EveryoneCampaignBehavior.AddItemToPartyArmory(_party.Id, resolvedItem, count);
        WriteDistributionLog($"Returned {count} of item {resolvedItem.StringId} to party {_party.Name}.", Colors.Green, Level.Debug);
    }
References _party, DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.AddItemToPartyArmory(), DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem(), and WriteDistributionLog().
RunAsync()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.RunAsync ()
Definition at line 269 of file PartyEquipmentDistributor.cs.
{
        foreach (var troop in _party.MemberRoster.GetTroopRoster()) {
            for (var i = 0; i < troop.Number - troop.WoundedNumber; i++) {
                if (troop.Character is CharacterObject characterObject && !characterObject.IsHero) { Assignments.Add(new Assignment(characterObject, _missionAllowsMountEquipment)); }
            }
        }
        Assignments.Sort((x, y) => y.CompareTo(x));
        if (_itemRoster != null) {
            foreach (var rosterElement in _itemRoster)
                AddEquipmentToAssign(rosterElement.EquipmentElement, rosterElement.Amount);
        }
        DoAssignAsync();
    }
References _itemRoster, _missionAllowsMountEquipment, _party, AddEquipmentToAssign(), Assignments, and DoAssignAsync().
SortDict()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.SortDict (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > dict, Comparison<(EquipmentElement Key, int Cnt)> comparer) static private
Definition at line 363 of file PartyEquipmentDistributor.cs.
{
        foreach (var key in dict.Keys) { dict[key].Sort(comparer); }
    }
Referenced by SortEquipmentDictionaries().
SortEquipmentDictionaries()
static void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.SortEquipmentDictionaries (Dictionary< int, List<(EquipmentElement Key, int Cnt)> > horsesDict, Dictionary< int, List<(EquipmentElement Key, int Cnt)> > harnessDict, List<(EquipmentElement Key, int Cnt)> saddles) static private
Definition at line 351 of file PartyEquipmentDistributor.cs.
{
        SortDict(horsesDict,  CompareEquipment);
        SortDict(harnessDict, CompareEquipment);
        saddles.Sort(CompareEquipment);
        return;
        static int CompareEquipment((EquipmentElement Key, int Cnt) x, (EquipmentElement Key, int Cnt) y) {
            var tierCompare = y.Key.Item.Tier.CompareTo(x.Key.Item.Tier);
            return tierCompare != 0 ? tierCompare : y.Key.Item.Value.CompareTo(x.Key.Item.Value);
        }
    }
References SortDict().
Referenced by GenerateHorseAndHarnessList().
Spawn()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Spawn (Equipment equipment)
Definition at line 1098 of file PartyEquipmentDistributor.cs.
{
        // 确保 PartyArmories 包含特定的 _party.Id
        if (!EveryoneCampaignBehavior.PartyArmories.TryGetValue(_party.Id, out var partyArmory)) {
            partyArmory                                       = new Dictionary<ItemObject, int>();
            EveryoneCampaignBehavior.PartyArmories[_party.Id] = partyArmory;
        }
        foreach (var slot in Global.EquipmentSlots) {
            if ((!_missionAllowsMountEquipment ||
                 _mission?.HasMissionBehavior<HideoutMissionController>() == true ||
                 _mission?.HasMissionBehavior<MissionSiegeEnginesLogic>() == true) &&
                (slot == EquipmentIndex.Horse || slot == EquipmentIndex.HorseHarness))
                continue;
            var element = equipment.GetEquipmentFromSlot(slot);
            if (!ArmyArmory.TryResolveArmoryItem(element.Item, out var item)) { continue; }
            if (partyArmory.TryGetValue(item, out var itemCount) && itemCount > 0) {
                if (itemCount == 1)
                    partyArmory.Remove(item);
                else
                    partyArmory[item] = itemCount - 1;
                WriteDistributionLog($"Spawned item {item.StringId}", Colors.Green, Level.Debug);
            }
            else {
                // 武器库中没有足够的物品或者该物品不存在
                WriteDistributionLog($"Insufficient or no items to spawn {item.StringId}", Colors.Red, Level.Warn);
            }
        }
    }
References _mission, _missionAllowsMountEquipment, _party, DynamicTroopEquipmentReupload.Global.EquipmentSlots, DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.PartyArmories, DynamicTroopEquipmentReupload.ArmyArmory.TryResolveArmoryItem(), and WriteDistributionLog().
Referenced by DynamicTroopEquipmentReupload.Patches.SpawnAgentPatch.Postfix().
TryConsumeExactItem()
bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor.TryConsumeExactItem (ItemObject item, out EquipmentElement exactElement) private
Definition at line 1151 of file PartyEquipmentDistributor.cs.
{
        var stripped = new EquipmentElement(item);
        if (_equipmentToAssign.TryGetValue(stripped, out var cnt) && cnt > 0) {
            ConsumeEquipmentToAssign(stripped);
            exactElement = stripped;
            return true;
        }
        exactElement = default;
        return false;
    }
References _equipmentToAssign, and ConsumeEquipmentToAssign().
Referenced by AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
WriteDistributionLog()
void DynamicTroopEquipmentReupload.PartyEquipmentDistributor.WriteDistributionLog (string message, Color color, Level level) private
Definition at line 285 of file PartyEquipmentDistributor.cs.
{
        if (!_isReadinessPreview)
            Global.Log(message, color, level, 2);
    }
References _isReadinessPreview, and DynamicTroopEquipmentReupload.Global.Log().
Referenced by AssignExtraArrows(), AssignExtraBolts(), AssignExtraEquipment(), AssignExtraShield(), AssignExtraThrownWeapon(), AssignExtraTwoHandedWeaponOrPolearms(), AssignHorseAndHarness(), AssignWeaponByItemEnumType(), AssignWeaponByItemEnumTypeBySlot(), AssignWeaponByWeaponClass(), AssignWeaponByWeaponClassBySlot(), AssignWeaponIfAvailable(), AssignWeaponToUnarmed(), GetMeleeWeaponForUnarmedTroop(), ReturnItem(), and Spawn().
Member Data Documentation
_equipmentToAssign
readonly ConcurrentDictionary<EquipmentElement, int> DynamicTroopEquipmentReupload.PartyEquipmentDistributor._equipmentToAssign private
Definition at line 27 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), AddEquipmentToAssign(), AssignEquipmentType(), AssignExtraEquipment(), AssignWeaponByItemEnumTypeBySlot(), AssignWeaponByWeaponClassBySlot(), ConsumeEquipmentToAssign(), GenerateHorseAndHarnessList(), GetMeleeWeaponForUnarmedTroop(), IsWeaponSuitable(), and TryConsumeExactItem().
_horseAndHarnesses
readonly List<HorseAndHarness> DynamicTroopEquipmentReupload.PartyEquipmentDistributor._horseAndHarnesses = new() private
Definition at line 29 of file PartyEquipmentDistributor.cs.
Referenced by AssignHorseAndHarness(), and GenerateHorseAndHarnessPairs().
_isReadinessPreview
readonly bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor._isReadinessPreview private
Definition at line 37 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), and WriteDistributionLog().
_itemRoster
readonly? ItemRoster DynamicTroopEquipmentReupload.PartyEquipmentDistributor._itemRoster private
Definition at line 31 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), and RunAsync().
_mission
readonly? Mission DynamicTroopEquipmentReupload.PartyEquipmentDistributor._mission private
Definition at line 33 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), ApplyEmergencyLoadout(), and Spawn().
_missionAllowsMountEquipment
readonly bool DynamicTroopEquipmentReupload.PartyEquipmentDistributor._missionAllowsMountEquipment private
Definition at line 35 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), DoAssignAsync(), RunAsync(), and Spawn().
_party
readonly MobileParty DynamicTroopEquipmentReupload.PartyEquipmentDistributor._party private
Definition at line 39 of file PartyEquipmentDistributor.cs.
Referenced by PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), PartyEquipmentDistributor(), ApplyEmergencyLoadout(), ReturnItem(), RunAsync(), and Spawn().
Assignments
readonly List<Assignment> DynamicTroopEquipmentReupload.PartyEquipmentDistributor.Assignments = new()
Definition at line 41 of file PartyEquipmentDistributor.cs.
Referenced by ApplyEmergencyLoadout(), AssignEquipmentType(), AssignExtraEquipment(), AssignHorseAndHarness(), AssignWeaponByItemEnumType(), AssignWeaponByWeaponClass(), AssignWeaponToUnarmed(), MarkUnderEquippedAssignmentsIfEnabled(), and RunAsync().
CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER
const float DynamicTroopEquipmentReupload.PartyEquipmentDistributor.CULTURE_OVERRIDE_COMPATIBILITY_MULTIPLIER = 2f static private
Definition at line 22 of file PartyEquipmentDistributor.cs.
Referenced by AssignEquipmentType(), AssignWeaponByItemEnumTypeBySlot(), and AssignWeaponByWeaponClassBySlot().
MAX_TIER_ABOVE_DEFAULT
const int DynamicTroopEquipmentReupload.PartyEquipmentDistributor.MAX_TIER_ABOVE_DEFAULT = 2 static private
Definition at line 21 of file PartyEquipmentDistributor.cs.
Referenced by GetMaxAllowedTier().
UNDER_EQUIPPED_MORALE_PENALTY_CAP
const float DynamicTroopEquipmentReupload.PartyEquipmentDistributor.UNDER_EQUIPPED_MORALE_PENALTY_CAP = 20f static private
Definition at line 26 of file PartyEquipmentDistributor.cs.
Referenced by MarkUnderEquippedAssignmentsIfEnabled().
UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER
const float DynamicTroopEquipmentReupload.PartyEquipmentDistributor.UNDER_EQUIPPED_MORALE_PENALTY_PER_MISSING_TIER = 2f static private
Definition at line 24 of file PartyEquipmentDistributor.cs.
Referenced by MarkUnderEquippedAssignmentsIfEnabled().
The documentation for this class was generated from the following file:
PartyEquipmentDistributor.cs