动态装备系统: Assignment Class Reference
Assignment Class Reference
Public Member Functions
Assignment (CharacterObject character)
int CompareTo (object? obj)
void FillEmptySlots ()
EquipmentElement GetEquipmentFromSlot (EquipmentIndex slot)
void SetEquipment (EquipmentIndex slot, EquipmentElement equipment)
Public Attributes
readonly Equipment Equipment
Static Public Attributes
static readonly EquipmentIndex[] WeaponSlots
Properties
bool CanBeShielded [get]
CharacterObject Character [get]
EquipmentIndex? EmptyWeaponSlot [get]
bool HaveThrown [get]
bool HaveTwoHandedWeaponOrPolearms [get]
int Index [get]
bool IsArcher [get]
bool IsAssigned [getset]
bool IsCrossBowMan [get]
bool IsMounted [get]
bool IsShielded [get]
bool IsUnarmed [get]
Equipment ReferenceEquipment [get]
Static Private Member Functions
static Equipment CreateEmptyEquipment ()
Private Attributes
readonly ReaderWriterLockSlim _eqLock = new()
bool _isAssigned
readonly ReaderWriterLockSlim _lock = new()
Static Private Attributes
static int _counter
Detailed Description
Definition at line 12 of file Assignment.cs.
Constructor & Destructor Documentation
Assignment()
Assignment.Assignment (CharacterObject character)
Definition at line 28 of file Assignment.cs.
{
        _lock.EnterWriteLock();
        try { Index = Interlocked.Increment(ref _counter); }
        finally { _lock.ExitWriteLock(); }
        Character          = character;
        Equipment          = CreateEmptyEquipment();
        ReferenceEquipment = character.RandomBattleEquipment.Clone();
    }
References _counter, _lock, Character, CreateEmptyEquipment(), Equipment, Index, and ReferenceEquipment.
Member Function Documentation
CompareTo()
int Assignment.CompareTo (object? obj)
Definition at line 114 of file Assignment.cs.
{
        if (obj == null) return 1;
        if (obj is not Assignment other) throw new ArgumentException("Object is not an Assignment");
        var tierComparison = Character.Tier.CompareTo(other.Character.Tier);
        if (tierComparison != 0) return tierComparison;
        // TroopType 比较，小的放在前面
        var thisTroopType       = Character.GetTroopType();
        var otherTroopType      = other.Character.GetTroopType();
        var troopTypeComparison = thisTroopType.CompareTo(otherTroopType);
        if (troopTypeComparison != 0) return troopTypeComparison;
        // 按 IsRanged 比较，IsRanged 排在 !IsRanged 前面
        if (!Character.IsRanged && other.Character.IsRanged) return 1;
        if (Character.IsRanged && !other.Character.IsRanged) return -1;
        // 按 IsMounted 比较，!IsMounted 排在 IsMounted 前面
        if (Character.IsMounted && !other.Character.IsMounted) return 1;
        if (!Character.IsMounted && other.Character.IsMounted) return -1;
        var skillValueComparison = Character.SkillValue().CompareTo(other.Character.SkillValue());
        if (skillValueComparison != 0) return skillValueComparison;
        var equipmentValueComparison = Character.EquipmentValue().CompareTo(other.Character.EquipmentValue());
        if (equipmentValueComparison != 0) return equipmentValueComparison;
        var levelComparison = Character.Level.CompareTo(other.Character.Level);
        if (levelComparison != 0) return levelComparison;
        return 0; // 如果所有条件都相等，则认为两者相等
    }
References Character.
CreateEmptyEquipment()
static Equipment Assignment.CreateEmptyEquipment () static private
Definition at line 162 of file Assignment.cs.
{
        Equipment emptyEquipment = new();
        foreach (var slot in Global.EquipmentSlots)
            emptyEquipment.AddEquipmentToSlotWithoutAgent(slot, new EquipmentElement());
        return emptyEquipment;
    }
References Equipment.
Referenced by Assignment().
FillEmptySlots()
void Assignment.FillEmptySlots ()
Definition at line 170 of file Assignment.cs.
{
        foreach (var slot in Global.ArmourSlots) {
            var referenceEquipment = ReferenceEquipment.GetEquipmentFromSlot(slot);
            if (GetEquipmentFromSlot(slot) is not { IsEmpty: false, Item: not null }) {
                var itemType = Helper.EquipmentIndexToItemEnumType(slot);
                if (!itemType.HasValue) continue;
                ItemObject? item;
                if (referenceEquipment is { IsEmpty: false, Item: not null }) {
                    List<ItemObject> itemList         = new() { referenceEquipment.Item };
                    var              itemsByCharacter = Cache.GetItemsByTypeTierAndCulture(itemType.Value, Character.Tier, Character.Culture);
                    if (itemsByCharacter != null) itemList.AddRange(itemsByCharacter);
                    if (referenceEquipment.Item.Culture is CultureObject cultureObject) {
                        var itemsByReference = Cache.GetItemsByTypeTierAndCulture(itemType.Value, (int)referenceEquipment.Item.Tier, cultureObject);
                        if (itemsByReference != null) itemList.AddRange(itemsByReference);
                    }
                    item = WeightedRandomSelector.SelectItem(itemList, referenceEquipment.Item.Effectiveness);
                }
                else {
                    item = Cache.GetItemsByTypeTierAndCulture(itemType.Value, Character.Tier, Character.Culture)?.GetRandomElement();
                    if (item == null) continue;
                }
                SetEquipment(slot, new EquipmentElement(item));
            }
        }
        foreach (var slot in Global.EquipmentSlots)
            if (GetEquipmentFromSlot(slot) is not { IsEmpty: false, Item: not null })
                SetEquipment(slot, ReferenceEquipment.GetEquipmentFromSlot(slot));
    }
References Character, Helper.EquipmentIndexToItemEnumType(), GetEquipmentFromSlot(), Cache.GetItemsByTypeTierAndCulture(), ReferenceEquipment, WeightedRandomSelector.SelectItem(), and SetEquipment().
Referenced by SpawnAgentPatch.Prefix().
GetEquipmentFromSlot()
EquipmentElement Assignment.GetEquipmentFromSlot (EquipmentIndex slot)
Definition at line 150 of file Assignment.cs.
{
        _eqLock.EnterReadLock();
        try { return Equipment.GetEquipmentFromSlot(slot); }
        finally { _eqLock.ExitReadLock(); }
    }
References _eqLock, and Equipment.
Referenced by PartyEquipmentDistributor.AssignWeaponByItemEnumTypeBySlot(), PartyEquipmentDistributor.AssignWeaponByWeaponClassBySlot(), and FillEmptySlots().
SetEquipment()
void Assignment.SetEquipment (EquipmentIndex slot, EquipmentElement equipment)
Definition at line 156 of file Assignment.cs.
{
        _eqLock.EnterWriteLock();
        try { Equipment.AddEquipmentToSlotWithoutAgent(slot, equipment); }
        finally { _eqLock.ExitWriteLock(); }
    }
References _eqLock, and Equipment.
Referenced by PartyEquipmentDistributor.AssignWeaponIfAvailable(), and FillEmptySlots().
Member Data Documentation
_counter
int Assignment._counter static private
Definition at line 20 of file Assignment.cs.
Referenced by Assignment().
_eqLock
readonly ReaderWriterLockSlim Assignment._eqLock = new() private
Definition at line 21 of file Assignment.cs.
Referenced by GetEquipmentFromSlot(), and SetEquipment().
_isAssigned
bool Assignment._isAssigned private
Definition at line 26 of file Assignment.cs.
_lock
readonly ReaderWriterLockSlim Assignment._lock = new() private
Definition at line 22 of file Assignment.cs.
Referenced by Assignment().
Equipment
readonly Equipment Assignment.Equipment
Definition at line 24 of file Assignment.cs.
Referenced by Assignment(), SpawnAgentPatch.AssignOrSpawnEquipment(), CreateEmptyEquipment(), GetEquipmentFromSlot(), SpawnAgentPatch.Prefix(), and SetEquipment().
WeaponSlots
readonly EquipmentIndex [] Assignment.WeaponSlots static
Initial value:
= {
                                                              EquipmentIndex.Weapon0,
                                                              EquipmentIndex.Weapon1,
                                                              EquipmentIndex.Weapon2,
                                                              EquipmentIndex.Weapon3
                                                          }
Definition at line 13 of file Assignment.cs.
Referenced by Global.CountCharacterEquipmentItemTypes(), RecruitmentPatch.GetRecruitEquipments(), and Global.ProcessAgentEquipment().
Property Documentation
CanBeShielded
bool Assignment.CanBeShielded get
Definition at line 66 of file Assignment.cs.
Character
CharacterObject Assignment.Character get
Definition at line 56 of file Assignment.cs.
{ get; }
Referenced by Assignment(), CompareTo(), FillEmptySlots(), PartyEquipmentDistributor.IsWeaponSuitable(), and PartyEquipmentDistributor.IsWeaponSuitableByType().
EmptyWeaponSlot
EquipmentIndex? Assignment.EmptyWeaponSlot get
Definition at line 87 of file Assignment.cs.
    {
        get
        {
            foreach (var slot in WeaponSlots)
                if (GetEquipmentFromSlot(slot).IsEmpty || GetEquipmentFromSlot(slot).Item == null)
                    return slot;
            return null;
        }
    }
HaveThrown
bool Assignment.HaveThrown get
Definition at line 81 of file Assignment.cs.
Referenced by PartyEquipmentDistributor.AssignExtraThrownWeapon().
HaveTwoHandedWeaponOrPolearms
bool Assignment.HaveTwoHandedWeaponOrPolearms get
Definition at line 84 of file Assignment.cs.
Referenced by PartyEquipmentDistributor.AssignExtraTwoHandedWeaponOrPolearms().
Index
int Assignment.Index get
Definition at line 38 of file Assignment.cs.
{ get; }
Referenced by Assignment().
IsArcher
bool Assignment.IsArcher get
Definition at line 75 of file Assignment.cs.
Referenced by PartyEquipmentDistributor.AssignExtraArrows().
IsAssigned
bool Assignment.IsAssigned get set
Definition at line 40 of file Assignment.cs.
    {
        get
        {
            _lock.EnterReadLock();
            try { return _isAssigned; }
            finally { _lock.ExitReadLock(); }
        }
        set
        {
            _lock.EnterWriteLock();
            try { _isAssigned = value; }
            finally { _lock.ExitWriteLock(); }
        }
    }
IsCrossBowMan
bool Assignment.IsCrossBowMan get
Definition at line 78 of file Assignment.cs.
Referenced by PartyEquipmentDistributor.AssignExtraBolts().
IsMounted
bool Assignment.IsMounted get
Definition at line 99 of file Assignment.cs.
    {
        get
        {
            var horse = ReferenceEquipment.GetEquipmentFromSlot(EquipmentIndex.Horse);
            return horse is { IsEmpty: false, Item: not null };
        }
    }
Referenced by PartyEquipmentDistributor.IsWeaponSuitable(), and PartyEquipmentDistributor.IsWeaponSuitableByType().
IsShielded
bool Assignment.IsShielded get
Definition at line 60 of file Assignment.cs.
IsUnarmed
bool Assignment.IsUnarmed get
Definition at line 108 of file Assignment.cs.
ReferenceEquipment
Equipment Assignment.ReferenceEquipment get
Definition at line 58 of file Assignment.cs.
{ get; }
Referenced by Assignment(), PartyEquipmentDistributor.AssignWeaponByItemEnumTypeBySlot(), PartyEquipmentDistributor.AssignWeaponByWeaponClassBySlot(), and FillEmptySlots().
The documentation for this class was generated from the following file:
Assignment.cs