动态装备系统: DynamicTroopEquipmentReupload.ArmorSelector Class Reference
DynamicTroopEquipmentReupload.ArmorSelector Class Reference
Static Public Member Functions
static ? ItemObject GetRandomArmorByBodyPart (List< ItemObject > armors, BoneBodyPartType? bodyPart)
Static Private Member Functions
static ? ItemObject SelectArmorBasedOnWeight ((ItemObject Armor, int Weight)[] weightedArmors)
Static Private Attributes
static readonly Random Random = new()
Detailed Description
Definition at line 9 of file ArmorSelector.cs.
Member Function Documentation
GetRandomArmorByBodyPart()
static ? ItemObject DynamicTroopEquipmentReupload.ArmorSelector.GetRandomArmorByBodyPart (List< ItemObject > armors, BoneBodyPartType? bodyPart) static
Definition at line 12 of file ArmorSelector.cs.
{
        if (!bodyPart.HasValue) return null;
        var weightedArmors = armors.WhereQ(armor => armor.HasArmorComponent)
                                   .SelectQ(armor => new { Armor = armor, armor.ArmorComponent })
                                   .WhereQ(ac => ac.ArmorComponent != null)
                                   .SelectQ(ac => new {
                                                          ac.Armor,
                                                          Weight =
                                                              Helper.GetArmorValueForBodyPart(ac.ArmorComponent,
                                                                                              bodyPart.Value)
                                                      })
                                   .WhereQ(aw => aw.Weight > 0)
                                   .ToArrayQ();
        return SelectArmorBasedOnWeight(weightedArmors.SelectQ(aw => (aw.Armor, aw.Weight)).ToArrayQ());
    }
References DynamicTroopEquipmentReupload.Helper.GetArmorValueForBodyPart(), and SelectArmorBasedOnWeight().
Referenced by DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.OnAgentRemoved().
SelectArmorBasedOnWeight()
static ? ItemObject DynamicTroopEquipmentReupload.ArmorSelector.SelectArmorBasedOnWeight ((ItemObject Armor, int Weight)[] weightedArmors) static private
Definition at line 30 of file ArmorSelector.cs.
{
        if (weightedArmors == null || weightedArmors.Length == 0)
            return null;
        var totalWeight = weightedArmors.SumQ(a => a.Weight);
        if (totalWeight <= 0)
            return weightedArmors[Random.Next(weightedArmors.Length)].Armor;
        var choice = Random.Next(totalWeight);
        var sum    = 0;
        foreach ((var armor, var weight) in weightedArmors) {
            sum += weight;
            if (choice < sum) return armor;
        }
        return null;
    }
References Random.
Referenced by GetRandomArmorByBodyPart().
Member Data Documentation
Random
readonly Random DynamicTroopEquipmentReupload.ArmorSelector.Random = new() static private
Definition at line 10 of file ArmorSelector.cs.
Referenced by SelectArmorBasedOnWeight().
The documentation for this class was generated from the following file:
ArmorSelector.cs