动态装备系统: DynamicTroopEquipmentReupload.LocalizedTexts Class Reference
DynamicTroopEquipmentReupload.LocalizedTexts Class Reference
Static Public Member Functions
static string GetItemsRecoveredFromFallenMessage (int count)
static string GetLootAddedMessage (int count)
static string GetSoldExcessEquipmentForThrowingWeapons (int value, int throwingCount, int ammoCount)
Static Public Attributes
static readonly TextObject ArmorViewOption = new("{=armory_view_option}View Army Armory")
static readonly TextObject ArmoryManageOption = new("{=armory_manage_option}Manage Armory")
static readonly TextObject DebugClearInvalidItems = new("{=debug_clear_invalid_items}DEBUG: Clear invalid items")
static readonly TextObject DebugExportArmory = new("{=debug_export_armory}DEBUG: Export player armory")
static readonly TextObject DebugImportArmory = new("{=debug_import_armory}DEBUG: Import player armory")
static readonly TextObject DebugRebuildArmory = new("{=debug_rebuild_armory}DEBUG: Rebuild player armory")
static readonly TextObject DebugRemovePlayerCraftedItems = new("{=debug_remove_player_crafted_items}DEBUG: Remove player crafted items")
static readonly TextObject ModName = new("{=mod_name}Dynamic Troop Equipment System")
static readonly TextObject ReinforcementCaravan = new("{=reinforcement_caravan}Reinforcement Caravan")
static readonly TextObject ReinforcementCaravanTradeDisabled = new("{=reinforcement_caravan_trade_disabled}These caravans do not trade.")
static readonly TextObject ReturnToTown = new("{=return_to_town}Return to Town Menu")
static readonly TextObject SellForThrowing
static readonly TextObject SettingEasy = new("{=setting_easy}Easy")
static readonly TextObject SettingHard = new("{=setting_hard}Hard")
static readonly TextObject SettingNormal = new("{=setting_normal}Normal")
static readonly TextObject SettingVeryHard = new("{=setting_very_hard}Very Hard")
Static Private Attributes
static readonly TextObject ItemsRecoveredFromFallenMessage
static readonly TextObject LootAddedMessage
static readonly TextObject SoldExcessEquipmentForThrowingWeapons
Detailed Description
Definition at line 5 of file LocalizedTexts.cs.
Member Function Documentation
GetItemsRecoveredFromFallenMessage()
static string DynamicTroopEquipmentReupload.LocalizedTexts.GetItemsRecoveredFromFallenMessage (int count) static
Definition at line 60 of file LocalizedTexts.cs.
{
        _ = ItemsRecoveredFromFallenMessage.SetTextVariable("ITEM_COUNT", count);
        return ItemsRecoveredFromFallenMessage.ToString();
    }
References ItemsRecoveredFromFallenMessage.
Referenced by DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.HandlePartyItems().
GetLootAddedMessage()
static string DynamicTroopEquipmentReupload.LocalizedTexts.GetLootAddedMessage (int count) static
Definition at line 55 of file LocalizedTexts.cs.
{
        _ = LootAddedMessage.SetTextVariable("ITEM_COUNT", count);
        return LootAddedMessage.ToString();
    }
References LootAddedMessage.
Referenced by DynamicTroopEquipmentReupload.DynamicTroopMissionLogic.HandlePartyItems().
GetSoldExcessEquipmentForThrowingWeapons()
static string DynamicTroopEquipmentReupload.LocalizedTexts.GetSoldExcessEquipmentForThrowingWeapons (int value, int throwingCount, int ammoCount) static
Definition at line 48 of file LocalizedTexts.cs.
{
        _ = SoldExcessEquipmentForThrowingWeapons.SetTextVariable("VALUE", value);
        _ = SoldExcessEquipmentForThrowingWeapons.SetTextVariable("THROWING_COUNT", throwingCount);
        _ = SoldExcessEquipmentForThrowingWeapons.SetTextVariable("AMMO_COUNT", ammoCount);
        return SoldExcessEquipmentForThrowingWeapons.ToString();
    }
References SoldExcessEquipmentForThrowingWeapons.
Referenced by DynamicTroopEquipmentReupload.ArmyArmory.SellExcessEquipmentForThrowingWeapons().
Member Data Documentation
ArmorViewOption
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.ArmorViewOption = new("{=armory_view_option}View Army Armory") static
Definition at line 16 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu().
ArmoryManageOption
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.ArmoryManageOption = new("{=armory_manage_option}Manage Armory") static
Definition at line 18 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu(), and DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddTownMenuOptions().
DebugClearInvalidItems
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.DebugClearInvalidItems = new("{=debug_clear_invalid_items}DEBUG: Clear invalid items") static
Definition at line 34 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu().
DebugExportArmory
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.DebugExportArmory = new("{=debug_export_armory}DEBUG: Export player armory") static
Definition at line 40 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu().
DebugImportArmory
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.DebugImportArmory = new("{=debug_import_armory}DEBUG: Import player armory") static
Definition at line 42 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu().
DebugRebuildArmory
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.DebugRebuildArmory = new("{=debug_rebuild_armory}DEBUG: Rebuild player armory") static
Definition at line 38 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu().
DebugRemovePlayerCraftedItems
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.DebugRemovePlayerCraftedItems = new("{=debug_remove_player_crafted_items}DEBUG: Remove player crafted items") static
Definition at line 36 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu().
ItemsRecoveredFromFallenMessage
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.ItemsRecoveredFromFallenMessage static private
Initial value:
=
        new("{=items_recover_from_fallen_message}recover {ITEM_COUNT} from your fallen soldiers")
Definition at line 29 of file LocalizedTexts.cs.
Referenced by GetItemsRecoveredFromFallenMessage().
LootAddedMessage
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.LootAddedMessage static private
Initial value:
=
        new("{=loot_added_message}looted {ITEM_COUNT} items from enemy")
Definition at line 26 of file LocalizedTexts.cs.
Referenced by GetLootAddedMessage().
ModName
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.ModName = new("{=mod_name}Dynamic Troop Equipment System") static
Definition at line 14 of file LocalizedTexts.cs.
ReinforcementCaravan
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.ReinforcementCaravan = new("{=reinforcement_caravan}Reinforcement Caravan") static
Definition at line 44 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.SpawnReinforcementCaravan().
ReinforcementCaravanTradeDisabled
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.ReinforcementCaravanTradeDisabled = new("{=reinforcement_caravan_trade_disabled}These caravans do not trade.") static
Definition at line 46 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.CutTheirSupplyBehavior.ReinforcementCaravanBuyProductsDisabledOnClickableCondition(), and DynamicTroopEquipmentReupload.ReinforcementCaravanConversationPatches.ReinforcementTradeLineOnClickableCondition().
ReturnToTown
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.ReturnToTown = new("{=return_to_town}Return to Town Menu") static
Definition at line 32 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu().
SellForThrowing
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.SellForThrowing static
Initial value:
=
        new("{=sell_for_throwing}Trade Excess Equipment for Throwing Weapons and Arrows")
Definition at line 20 of file LocalizedTexts.cs.
Referenced by DynamicTroopEquipmentReupload.ArmyArmoryBehavior.AddArmyArmorySubmenu().
SettingEasy
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.SettingEasy = new("{=setting_easy}Easy") static
Definition at line 6 of file LocalizedTexts.cs.
SettingHard
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.SettingHard = new("{=setting_hard}Hard") static
Definition at line 10 of file LocalizedTexts.cs.
SettingNormal
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.SettingNormal = new("{=setting_normal}Normal") static
Definition at line 8 of file LocalizedTexts.cs.
SettingVeryHard
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.SettingVeryHard = new("{=setting_very_hard}Very Hard") static
Definition at line 12 of file LocalizedTexts.cs.
SoldExcessEquipmentForThrowingWeapons
readonly TextObject DynamicTroopEquipmentReupload.LocalizedTexts.SoldExcessEquipmentForThrowingWeapons static private
Initial value:
=
        new("{=sell_for_throwing_text}Sold excess equipment worth {VALUE} and obtained {THROWING_COUNT} throwing weapons and {AMMO_COUNT} ammunition")
Definition at line 23 of file LocalizedTexts.cs.
Referenced by GetSoldExcessEquipmentForThrowingWeapons().
The documentation for this class was generated from the following file:
LocalizedTexts.cs