动态装备系统: LocalizedTexts Class Reference
LocalizedTexts Class Reference
Static Public Member Functions
static string GetItemsRecoveredFromFallenMessage (int count)
static string GetLootAddedMessage (int count)
static string GetSoldExcessEquipmentForThrowingWeapons (int value, int count)
Static Public Attributes
static readonly TextObject ArmorViewOption = new("{=armory_view_option}View Army Armory")
static readonly TextObject ArmoryManageOption = new("{=armory_manage_option}Manage Armory")
static readonly TextObject ModName = new("{=mod_name}Dynamic Troop Equipment System")
static readonly TextObject ReturnToTown = new("{=return_to_town}Return to Town Menu")
static readonly TextObject SellForThrowing
static readonly TextObject SettingEasy = new("{=setting_easy}Easy")
static readonly TextObject SettingHard = new("{=setting_hard}Hard")
static readonly TextObject SettingNormal = new("{=setting_normal}Normal")
static readonly TextObject SettingVeryHard = new("{=setting_very_hard}Very Hard")
Static Private Attributes
static readonly TextObject ItemsRecoveredFromFallenMessage
static readonly TextObject LootAddedMessage
static readonly TextObject SoldExcessEquipmentForThrowingWeapons
Detailed Description
Definition at line 5 of file LocalizedTexts.cs.
Member Function Documentation
GetItemsRecoveredFromFallenMessage()
static string LocalizedTexts.GetItemsRecoveredFromFallenMessage (int count) static
Definition at line 45 of file LocalizedTexts.cs.
{
        _ = ItemsRecoveredFromFallenMessage.SetTextVariable("ITEM_COUNT", count);
        return ItemsRecoveredFromFallenMessage.ToString();
    }
References ItemsRecoveredFromFallenMessage.
GetLootAddedMessage()
static string LocalizedTexts.GetLootAddedMessage (int count) static
Definition at line 40 of file LocalizedTexts.cs.
{
        _ = LootAddedMessage.SetTextVariable("ITEM_COUNT", count);
        return LootAddedMessage.ToString();
    }
References LootAddedMessage.
Referenced by DynamicTroopMissionLogic.HandlePartyItems().
GetSoldExcessEquipmentForThrowingWeapons()
static string LocalizedTexts.GetSoldExcessEquipmentForThrowingWeapons (int value, int count) static
Definition at line 34 of file LocalizedTexts.cs.
{
        _ = SoldExcessEquipmentForThrowingWeapons.SetTextVariable("VALUE", value);
        _ = SoldExcessEquipmentForThrowingWeapons.SetTextVariable("COUNT", count);
        return SoldExcessEquipmentForThrowingWeapons.ToString();
    }
References SoldExcessEquipmentForThrowingWeapons.
Member Data Documentation
ArmorViewOption
readonly TextObject LocalizedTexts.ArmorViewOption = new("{=armory_view_option}View Army Armory") static
Definition at line 16 of file LocalizedTexts.cs.
Referenced by ArmyArmoryBehavior.AddArmyArmorySubmenu().
ArmoryManageOption
readonly TextObject LocalizedTexts.ArmoryManageOption = new("{=armory_manage_option}Manage Armory") static
Definition at line 18 of file LocalizedTexts.cs.
Referenced by ArmyArmoryBehavior.AddArmyArmorySubmenu(), and ArmyArmoryBehavior.AddTownMenuOptions().
ItemsRecoveredFromFallenMessage
readonly TextObject LocalizedTexts.ItemsRecoveredFromFallenMessage static private
Initial value:
=
        new("{=items_recover_from_fallen_message}recover {ITEM_COUNT} from your fallen soldiers")
Definition at line 29 of file LocalizedTexts.cs.
Referenced by GetItemsRecoveredFromFallenMessage().
LootAddedMessage
readonly TextObject LocalizedTexts.LootAddedMessage static private
Initial value:
=
        new("{=loot_added_message}looted {ITEM_COUNT} items from enemy")
Definition at line 26 of file LocalizedTexts.cs.
Referenced by GetLootAddedMessage().
ModName
readonly TextObject LocalizedTexts.ModName = new("{=mod_name}Dynamic Troop Equipment System") static
Definition at line 14 of file LocalizedTexts.cs.
ReturnToTown
readonly TextObject LocalizedTexts.ReturnToTown = new("{=return_to_town}Return to Town Menu") static
Definition at line 32 of file LocalizedTexts.cs.
Referenced by ArmyArmoryBehavior.AddArmyArmorySubmenu().
SellForThrowing
readonly TextObject LocalizedTexts.SellForThrowing static
Initial value:
=
        new("{=sell_for_throwing}Trade Excess Equipment for Throwing Weapons")
Definition at line 20 of file LocalizedTexts.cs.
Referenced by ArmyArmoryBehavior.AddArmyArmorySubmenu().
SettingEasy
readonly TextObject LocalizedTexts.SettingEasy = new("{=setting_easy}Easy") static
Definition at line 6 of file LocalizedTexts.cs.
SettingHard
readonly TextObject LocalizedTexts.SettingHard = new("{=setting_hard}Hard") static
Definition at line 10 of file LocalizedTexts.cs.
SettingNormal
readonly TextObject LocalizedTexts.SettingNormal = new("{=setting_normal}Normal") static
Definition at line 8 of file LocalizedTexts.cs.
SettingVeryHard
readonly TextObject LocalizedTexts.SettingVeryHard = new("{=setting_very_hard}Very Hard") static
Definition at line 12 of file LocalizedTexts.cs.
SoldExcessEquipmentForThrowingWeapons
readonly TextObject LocalizedTexts.SoldExcessEquipmentForThrowingWeapons static private
Initial value:
=
        new("{=sell_for_throwing_text}Sold excess equipment worth {VALUE} and obtained {COUNT} throwing weapons")
Definition at line 23 of file LocalizedTexts.cs.
Referenced by GetSoldExcessEquipmentForThrowingWeapons().
The documentation for this class was generated from the following file:
LocalizedTexts.cs