动态装备系统: DynamicTroopEquipmentReupload.Patches.RecruitmentPatch Class Reference
DynamicTroopEquipmentReupload.Patches.RecruitmentPatch Class Reference
Classes
class EquipmentElementComparer
Static Public Member Functions
static List< EquipmentElement > GetRandomizedRecruitEquipments (CharacterObject? character)
static List< EquipmentElement > GetRecruitEquipments (CharacterObject? character)
Static Package Functions
static void AddStartingEquipmentToPlayerArmory (CharacterObject character, int troopCount)
Static Private Member Functions
static void Postfix (Dictionary< CharacterObject, int > __state)
static void Prefix (RecruitmentVM __instance, out Dictionary< CharacterObject, int > __state)
Detailed Description
Definition at line 14 of file RecruitmentPatch.cs.
Member Function Documentation
AddStartingEquipmentToPlayerArmory()
static void DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.AddStartingEquipmentToPlayerArmory (CharacterObject character, int troopCount) static package
Definition at line 33 of file RecruitmentPatch.cs.
{
        if (troopCount <= 0)
            return;
        Global.Log($"recruiting {troopCount}x{character.Name}", Colors.Green, Level.Debug);
        var equipments = GetRecruitEquipments(character);
        Global.Debug($"{equipments.Count * troopCount} starting equipments added");
        foreach (var equipment in equipments) {
            if (equipment is { IsEmpty: false, Item: not null })
                ArmyArmory.AddItemToArmory(equipment.Item, troopCount);
        }
    }
References DynamicTroopEquipmentReupload.ArmyArmory.AddItemToArmory(), DynamicTroopEquipmentReupload.Global.Debug(), GetRecruitEquipments(), and DynamicTroopEquipmentReupload.Global.Log().
Referenced by Postfix(), DynamicTroopEquipmentReupload.Patches.TavernMercenaryEquipmentPatch.Postfix(), and DynamicTroopEquipmentReupload.Patches.TownMenuMercenaryEquipmentPatch.Postfix().
GetRandomizedRecruitEquipments()
static List< EquipmentElement > DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRandomizedRecruitEquipments (CharacterObject? character) static
Definition at line 106 of file RecruitmentPatch.cs.
{
        List<EquipmentElement> list = new();
        if (character?.BattleEquipments?.IsEmpty() ?? true) return list;
        foreach (var equipment in character.BattleEquipments) {
            if (equipment.IsEmpty())
                continue;
            foreach (var slot in Global.EquipmentSlots) {
                var item = equipment.GetEquipmentFromSlot(slot);
                if (item is { IsEmpty: false, Item: not null }) list.Add(item);
            }
        }
        return list;
    }
References DynamicTroopEquipmentReupload.Global.EquipmentSlots.
GetRecruitEquipments()
static List< EquipmentElement > DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.GetRecruitEquipments (CharacterObject? character) static
Definition at line 46 of file RecruitmentPatch.cs.
{
        if (character?.BattleEquipments?.IsEmpty() ?? true) return new List<EquipmentElement>();
        var armorAndHorse = character.RandomBattleEquipment;
        List<EquipmentElement> equipmentElements = new();
        List<EquipmentElement> weaponList = new();
        HashSet<EquipmentElement> weaponSet = new(new EquipmentElementComparer());
        foreach (var slot in Global.ArmourSlots) {
            var equipmentElement = armorAndHorse.GetEquipmentFromSlot(slot);
            if (equipmentElement is { IsEmpty: false, Item: not null }) {
                if (ModSettings.Instance?.RandomizeStartingEquipment ?? false) {
                    List<ItemObject> items  = new();
                    ItemObject[]?    items1 = { };
                    if (equipmentElement.Item.Culture is CultureObject cultureObject)
                        items1 = Cache.GetItemsByTypeTierAndCulture(equipmentElement.Item.ItemType,
                                                                    (int)equipmentElement.Item.Tier,
                                                                    cultureObject);
                    var items2 =
                        Cache.GetItemsByTypeTierAndCulture(equipmentElement.Item.ItemType,
                                                           character.Tier,
                                                           character.Culture);
                    if (items1 != null) items.AddRange(items1);
                    if (items2 != null) items.AddRange(items2);
                    items.Add(equipmentElement.Item);
                    items = items.Distinct().ToList();
                    equipmentElements.Add(new EquipmentElement(WeightedRandomSelector.SelectItem(items,
                                                                     equipmentElement.Item.Effectiveness)));
                }
                else { equipmentElements.Add(equipmentElement); }
            }
        }
        foreach (var slot in new[] { EquipmentIndex.Horse, EquipmentIndex.HorseHarness }) {
            var equipmentElement = armorAndHorse.GetEquipmentFromSlot(slot);
            if (equipmentElement is { IsEmpty: false, Item: not null }) equipmentElements.Add(equipmentElement);
        }
        foreach (var equipment in character.BattleEquipments) {
            if (equipment.IsEmpty())
                continue;
            foreach (var slot in Assignment.WeaponSlots) {
                var item = equipment.GetEquipmentFromSlot(slot);
                if (item is not { IsEmpty: false, Item: not null } || !item.Item.HasWeaponComponent) continue;
                if (item.Item.IsConsumable())
                    equipmentElements.Add(item);
                else
                    weaponList.Add(item);
            }
        }
        weaponList.Shuffle();
        foreach (var weapon in weaponList.Except(weaponSet))
            _ = weaponSet.Add(weapon);
        equipmentElements.AddRange(weaponSet);
        return equipmentElements;
    }
References DynamicTroopEquipmentReupload.Global.ArmourSlots, DynamicTroopEquipmentReupload.Cache.GetItemsByTypeTierAndCulture(), DynamicTroopEquipmentReupload.ModSettings.RandomizeStartingEquipment, DynamicTroopEquipmentReupload.WeightedRandomSelector.SelectItem(), and DynamicTroopEquipmentReupload.Assignment.WeaponSlots.
Referenced by AddStartingEquipmentToPlayerArmory(), DynamicTroopEquipmentReupload.Extensions.MobilePartyExtension.GetItems(), and DynamicTroopEquipmentReupload.EveryoneCampaignBehavior.OnTroopRecruited().
Postfix()
static void DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.Postfix (Dictionary< CharacterObject, int > __state) static private
Definition at line 25 of file RecruitmentPatch.cs.
{
        foreach (var rosterEntry in __state) {
            var recruitedCount = Campaign.Current.MainParty.MemberRoster.GetTroopCount(rosterEntry.Key) - rosterEntry.Value;
            if (recruitedCount > 0)
                AddStartingEquipmentToPlayerArmory(rosterEntry.Key, recruitedCount);
        }
    }
References AddStartingEquipmentToPlayerArmory().
Prefix()
static void DynamicTroopEquipmentReupload.Patches.RecruitmentPatch.Prefix (RecruitmentVM __instance, out Dictionary< CharacterObject, int > __state) static private
Definition at line 15 of file RecruitmentPatch.cs.
{
        __state = __instance.TroopsInCart
            .Where(troop => !troop.IsTroopEmpty && troop.Character != null)
            .Select(troop => troop.Character!)
            .Distinct()
            .ToDictionary(
                character => character,
                character => Campaign.Current.MainParty.MemberRoster.GetTroopCount(character));
    }
The documentation for this class was generated from the following file:
Patches/RecruitmentPatch.cs